/*
 * Auto-generated by tools/ghidra_unmanaged_homes.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists so every raw Ghidra function mapped to an unmanaged live owner
 * still has a concrete .c home for iteration/reference work.
 *
 * Live owner: dolphin/MSL_C/PPCEABI/bare/H/direct_io.c
 * Text span: 0x8028F054-0x8028F380
 * Imported Ghidra functions: 2
 * Verbatim-safe functions: 1
 * Auto-stubbed functions: 1
 */
/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: dolphin/MSL_C/PPCEABI/bare/H/direct_io.c
 * Text span: 0x8028F054-0x8028F380
 * Imported Ghidra functions: 2
 * Verbatim-safe functions: 1
 * Auto-stubbed functions: 1
 */

#include "ghidra_import.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_80003494();
extern int FUN_8028ef5c();
extern undefined4 FUN_8028f020();
extern int FUN_8028f578();
extern void* FUN_8028f9d4();
extern undefined4 FUN_8028fdd8();
extern int FUN_80292020();

/* Local declarations keep imported functions visible within the TU. */
uint FUN_8028f054();
void FUN_8028f360(uint param_1,uint param_2,int param_3,undefined4 *param_4);

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8028F054
 * EN v1.0 Size: 780b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
uint FUN_8028f054()
{
    return 0;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8028F360
 * EN v1.0 Size: 32b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8028f360(uint param_1,uint param_2,int param_3,undefined4 *param_4)
{
  FUN_8028f054(param_1,param_2,param_3,param_4);
  return;
}
