/*
 * Auto-generated by tools/ghidra_unmanaged_homes.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists so every raw Ghidra function mapped to an unmanaged live owner
 * still has a concrete .c home for iteration/reference work.
 *
 * Live owner: dolphin/MSL_C/PPCEABI/bare/H/e_sqrt.c
 * Text span: 0x80292F04-0x8029312C
 * Imported Ghidra functions: 1
 * Verbatim-safe functions: 1
 * Auto-stubbed functions: 0
 */
/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: dolphin/MSL_C/PPCEABI/bare/H/e_sqrt.c
 * Text span: 0x80292F04-0x8029312C
 * Imported Ghidra functions: 1
 * Verbatim-safe functions: 1
 * Auto-stubbed functions: 0
 */

#include "ghidra_import.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_802867ac();
extern undefined4 FUN_802867f8();

/* Local declarations keep imported functions visible within the TU. */
void FUN_80292f04(void);

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80292F04
 * EN v1.0 Size: 552b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80292f04(void)
{
  FUN_802867ac();
  FUN_802867f8();
  return;
}
