/*
 * Auto-generated by tools/ghidra_unmanaged_homes.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists so every raw Ghidra function mapped to an unmanaged live owner
 * still has a concrete .c home for iteration/reference work.
 *
 * Live owner: dolphin/MSL_C/PPCEABI/bare/H/mem.c
 * Text span: 0x8028F988-0x8028FAF8
 * Imported Ghidra functions: 4
 * Verbatim-safe functions: 4
 * Auto-stubbed functions: 0
 */
/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: dolphin/MSL_C/PPCEABI/bare/H/mem.c
 * Text span: 0x8028F988-0x8028FAF8
 * Imported Ghidra functions: 4
 * Verbatim-safe functions: 4
 * Auto-stubbed functions: 0
 */

#include "ghidra_import.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_8028faf8();
extern undefined4 FUN_8028fba8();
extern undefined4 FUN_8028fc6c();
extern undefined4 FUN_8028fd18();
extern int countLeadingZeros();

/* Local declarations keep imported functions visible within the TU. */
undefined4 FUN_8028f988(int param_1,int param_2,int param_3);
char * FUN_8028f9d4(int param_1,char param_2,int param_3);
char * FUN_8028fa00(int param_1,char param_2,int param_3);
uint FUN_8028fa2c(uint param_1,uint param_2,uint param_3);

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8028F988
 * EN v1.0 Size: 76b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
undefined4 FUN_8028f988(int param_1,int param_2,int param_3)
{
  int iVar1;
  byte *pbVar2;
  byte *pbVar3;
  
  pbVar2 = (byte *)(param_1 + -1);
  pbVar3 = (byte *)(param_2 + -1);
  iVar1 = param_3 + 1;
  do {
    iVar1 = iVar1 + -1;
    if (iVar1 == 0) {
      return 0;
    }
    pbVar2 = pbVar2 + 1;
    pbVar3 = pbVar3 + 1;
  } while (*pbVar2 == *pbVar3);
  if (*pbVar3 <= *pbVar2) {
    return 1;
  }
  return 0xffffffff;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8028F9D4
 * EN v1.0 Size: 44b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
char * FUN_8028f9d4(int param_1,char param_2,int param_3)
{
  char *pcVar1;
  int iVar2;
  
  pcVar1 = (char *)(param_1 + param_3);
  iVar2 = param_3 + 1;
  do {
    iVar2 = iVar2 + -1;
    if (iVar2 == 0) {
      return (char *)0x0;
    }
    pcVar1 = pcVar1 + -1;
  } while (*pcVar1 != param_2);
  return pcVar1;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8028FA00
 * EN v1.0 Size: 44b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
char * FUN_8028fa00(int param_1,char param_2,int param_3)
{
  char *pcVar1;
  int iVar2;
  
  pcVar1 = (char *)(param_1 + -1);
  iVar2 = param_3 + 1;
  do {
    iVar2 = iVar2 + -1;
    if (iVar2 == 0) {
      return (char *)0x0;
    }
    pcVar1 = pcVar1 + 1;
  } while (*pcVar1 != param_2);
  return pcVar1;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8028FA2C
 * EN v1.0 Size: 204b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
uint FUN_8028fa2c(uint param_1,uint param_2,uint param_3)
{
  int iVar1;
  undefined *puVar2;
  undefined *puVar3;
  
  iVar1 = countLeadingZeros(param_1 ^ param_2);
  iVar1 = param_1 << iVar1;
  if (param_3 < 0x20) {
    if (iVar1 < 0) {
      puVar2 = (undefined *)(param_2 + param_3);
      puVar3 = (undefined *)(param_1 + param_3);
      iVar1 = param_3 + 1;
      while (iVar1 = iVar1 + -1, iVar1 != 0) {
        puVar2 = puVar2 + -1;
        puVar3 = puVar3 + -1;
        *puVar3 = *puVar2;
      }
    }
    else {
      puVar2 = (undefined *)(param_2 - 1);
      puVar3 = (undefined *)(param_1 - 1);
      iVar1 = param_3 + 1;
      while (iVar1 = iVar1 + -1, iVar1 != 0) {
        puVar2 = puVar2 + 1;
        puVar3 = puVar3 + 1;
        *puVar3 = *puVar2;
      }
    }
  }
  else if (((param_1 ^ param_2) & 3) == 0) {
    if (iVar1 < 0) {
      FUN_8028fc6c(param_1,param_2,param_3);
    }
    else {
      FUN_8028fd18(param_1,param_2,param_3);
    }
  }
  else if (iVar1 < 0) {
    FUN_8028faf8(param_1,param_2,param_3);
  }
  else {
    FUN_8028fba8(param_1,param_2,param_3);
  }
  return param_1;
}
