/*
 * Auto-generated by tools/ghidra_unmanaged_homes.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists so every raw Ghidra function mapped to an unmanaged live owner
 * still has a concrete .c home for iteration/reference work.
 *
 * Live owner: dolphin/MSL_C/PPCEABI/bare/H/s_floor.c
 * Text span: 0x802947F8-0x80294964
 * Imported Ghidra functions: 1
 * Verbatim-safe functions: 1
 * Auto-stubbed functions: 0
 */
/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: dolphin/MSL_C/PPCEABI/bare/H/s_floor.c
 * Text span: 0x802947F8-0x80294964
 * Imported Ghidra functions: 1
 * Verbatim-safe functions: 1
 * Auto-stubbed functions: 0
 */

#include "ghidra_import.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_802867b4();
extern undefined4 FUN_80286800();
extern undefined4 FUN_8029349c();

/* Local declarations keep imported functions visible within the TU. */
void FUN_802947f8(void);

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x802947F8
 * EN v1.0 Size: 364b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_802947f8(void)
{
  FUN_802867b4();
  FUN_8029349c();
  FUN_80286800();
  return;
}
