/*
 * Auto-generated by tools/orig/object_def_packets.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists as a retail-backed per-object packet for exploratory split work.
 *
 * Object def: 0x0060 sharpclawGr
 * Output path: src/main/unknown/objects/obj_0060_sharpclawgr.c
 * Retail placements: 63
 * Root romlists: 8
 * Object-def size: 0x3C0
 * Root placement widths: 14w x63
 * DLL ID: 0x00C9
 * Class ID: 0x001C
 * Suggested outer boundary: shared DLL family
 * Reference class name: baddie
 * Reference DLL name: Baddie
 * Remap aliases: 0x0011
 *
 * Related packet paths:
 * - class: src/main/unknown/classes/class_001C_baddie.c
 * - family: src/main/unknown/dll_00C9_baddie.c
 *
 * Width samples:
 * - 14w (0x38 bytes): capeclaw.romlist.zlb, dfshrine.romlist.zlb, fortress.romlist.zlb, hollow.romlist.zlb
 *
 * Inline object-def evidence:
 * - inline fields: pModelList, pSeq, pEvent, pHits, pWeaponDa, hitboxes, aButtonInteraction
 * - model IDs: 0x00000017
 * - sequence IDs: 0x007C 0x0096 0x0097 0x04EB 0x0185 0x00F3 0x00F4 0x04ED
 * - help texts: 0x0120 0xFFFF 0xFFFF 0xFFFF
 *
 * Same-class objects (58 defs / 413 placements):
 * - 0x0060 sharpclawGr: placements=63, dll=0x00C9, widths=14w x63
 * - 0x005F sharpclawSn: placements=42, dll=0x00C9, widths=14w x42
 * - 0x003A WB: placements=39, dll=0x00C9, widths=14w x39
 * - 0x0036 snowworm_ba: placements=30, dll=0x00C9, widths=14w x30
 * - 0x0037 Whirlpool: placements=22, dll=0x00C9, widths=14w x22
 * - 0x0034 MutatedEba: placements=21, dll=0x00C9, widths=14w x21
 * - 0x0031 HagabonMK2: placements=18, dll=0x00C9, widths=14w x18
 * - 0x02D5 SC_babyligh: placements=18, dll=0x01B5, widths=14w x18
 * - 0x0039 PinPon: placements=17, dll=0x00C9, widths=14w x17
 * - 0x0030 Firebat: placements=16, dll=0x00C9, widths=14w x16
 * - 0x0026 Kaldachom: placements=13, dll=0x00D5, widths=14w x13
 * - 0x002E GCRobotPatr: placements=13, dll=0x00C9, widths=14w x13
 * - ... 46 more class siblings omitted
 *
 * Same-DLL objects (29 defs / 350 placements):
 * - 0x0060 sharpclawGr: placements=63, class=0x001C, widths=14w x63
 * - 0x005F sharpclawSn: placements=42, class=0x001C, widths=14w x42
 * - 0x003A WB: placements=39, class=0x001C, widths=14w x39
 * - 0x0036 snowworm_ba: placements=30, class=0x001C, widths=14w x30
 * - 0x0037 Whirlpool: placements=22, class=0x001C, widths=14w x22
 * - 0x0034 MutatedEba: placements=21, class=0x001C, widths=14w x21
 * - 0x0031 HagabonMK2: placements=18, class=0x001C, widths=14w x18
 * - 0x0039 PinPon: placements=17, class=0x001C, widths=14w x17
 * - 0x0030 Firebat: placements=16, class=0x001C, widths=14w x16
 * - 0x002E GCRobotPatr: placements=13, class=0x001C, widths=14w x13
 * - 0x0041 FireCrawler: placements=12, class=0x001C, widths=14w x12
 * - 0x0035 snowworm: placements=11, class=0x001C, widths=14w x11
 * - ... 17 more DLL siblings omitted
 *
 * Reference-only DLL hints:
 * - objparams size: 0x36
 * - Various enemies
 *
 * EN descriptor slot map:
 * - descriptor=0x8031E880 lbl_8031E880 (slots=10, mask=1101111111)
 * - slot 00: 0x8014E638 fn_8014E638 ref=Enemyinitialise
 * - slot 01: 0x8014E604 fn_8014E604 ref=Enemyrelease
 * - slot 03: 0x8014DE78 fn_8014DE78 ref=Enemyinit
 * - slot 04: 0x8014D984 fn_8014D984 ref=update
 * - slot 05: 0x8014D8C4 fn_8014D8C4 ref=EnemyhitDetect
 * - slot 06: 0x8014D730 fn_8014D730 ref=Enemyrender
 * - slot 07: 0x8014D5F8 fn_8014D5F8 ref=Enemyfree
 * - slot 08: 0x8014D5F0 fn_8014D5F0 stub=const 331
 * - slot 09: 0x8014D5E8 fn_8014D5E8 stub=const 880 ref=EnemygetExtraSize (stub)
 */

#if 0
/*
 * Retail-backed packet constants. Promote only after EN code inspection.
 */
enum obj_0060_sharpclawGr_packet_info {
    SHARPCLAWGR_DEF_ID = 0x0060,
    SHARPCLAWGR_DLL_ID = 0x00C9,
    SHARPCLAWGR_CLASS_ID = 0x001C,
    SHARPCLAWGR_OBJECT_DEF_BYTES = 0x3C0,
    SHARPCLAWGR_PLACEMENT_BYTES_MIN = 0x38,
    SHARPCLAWGR_PLACEMENT_BYTES_MAX = 0x38,
};
#endif
