/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/MMP/mmp_levelcontrol.c
 * Text span: 0x80194688-0x801950D8
 * Imported Ghidra functions: 10
 * Verbatim-safe functions: 5
 * Auto-stubbed functions: 5
 */

#include "ghidra_import.h"
#include "main/dll/MMP/mmp_levelcontrol.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_8000bb38();
extern uint FUN_80020078();
extern undefined4 FUN_800201ac();
extern undefined4 FUN_80021b8c();
extern uint FUN_80022264();
extern int FUN_8002ba84();
extern int FUN_80036f50();
extern undefined4 FUN_8003709c();
extern undefined4 FUN_800372f8();
extern undefined4 FUN_8003b9ec();
extern undefined4 FUN_80041110();
extern int FUN_8005b068();
extern int FUN_8005b478();
extern uint FUN_800607f4();
extern undefined4 FUN_80060858();
extern undefined4 FUN_80060868();
extern int FUN_80060878();
extern undefined4 FUN_80194338();
extern undefined8 FUN_80286830();
extern undefined8 FUN_80286838();
extern undefined4 FUN_8028687c();
extern undefined4 FUN_80286884();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4* DAT_803dd708;
extern f64 DOUBLE_803e4c88;
extern f32 FLOAT_803e4c68;
extern f32 FLOAT_803e4c6c;
extern f32 FLOAT_803e4c70;
extern f32 FLOAT_803e4c74;
extern f32 FLOAT_803e4c78;
extern f32 FLOAT_803e4c7c;
extern f32 FLOAT_803e4c80;
extern f32 FLOAT_803e4c94;
extern f32 FLOAT_803e4c98;

/* Local declarations keep imported functions visible within the TU. */
void FUN_80194688(int param_1,int param_2);
void FUN_801947d4(int param_1);
void FUN_801948a4(int param_1,int param_2);
void FUN_801949b8(void);
void FUN_80194c20(int param_1);
void FUN_80194c5c(int param_1);
void FUN_80194c8c(uint param_1);
void FUN_80194db8(undefined2 *param_1,int param_2);
double FUN_80194e3c(int param_1,byte param_2);
void FUN_80194ee0(undefined4 param_1,undefined4 param_2,int param_3);

/* Auto-stubbed for compileability: pointer-heavy local typing needs manual cleanup. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_80194688(int param_1,int param_2)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: pointer-heavy local typing needs manual cleanup. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801947d4(int param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: pointer-heavy local typing needs manual cleanup. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801948a4(int param_1,int param_2)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: function-pointer stores need manual cleanup. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801949b8(void)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

// Function: FUN_80194c20
// Entry: 80194c20
// Size: 60 bytes

void FUN_80194c20(int param_1)

{
  FUN_8003709c(param_1,0x23);
  FUN_8003709c(param_1,0x31);
  return;
}

// Function: FUN_80194c5c
// Entry: 80194c5c
// Size: 48 bytes

void FUN_80194c5c(int param_1)

{
  char in_r8;
  
  if (in_r8 != '\0') {
    FUN_8003b9ec(param_1);
  }
  return;
}

/* Auto-stubbed for compileability: function-pointer stores need manual cleanup. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_80194c8c(uint param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

// Function: FUN_80194db8
// Entry: 80194db8
// Size: 132 bytes

void FUN_80194db8(undefined2 *param_1,int param_2)

{
  uint uVar1;
  undefined4 *puVar2;
  
  puVar2 = *(undefined4 **)(param_1 + 0x5c);
  *param_1 = *(undefined2 *)(param_2 + 0x24);
  FUN_800372f8((int)param_1,0x23);
  FUN_800372f8((int)param_1,0x31);
  uVar1 = FUN_80020078((int)*(short *)(param_2 + 0x18));
  if (uVar1 != 0) {
    *(byte *)(puVar2 + 1) = *(byte *)(puVar2 + 1) & 0x7f | 0x80;
    *puVar2 = 3000;
  }
  return;
}

// Function: FUN_80194e3c
// Entry: 80194e3c
// Size: 164 bytes

double FUN_80194e3c(int param_1,byte param_2)

{
  int iVar1;
  
  if ((param_1 == 0) || (iVar1 = *(int *)(param_1 + 0xb8), iVar1 == 0)) {
    return (double)FLOAT_803e4c98;
  }
  if (param_2 == 4) {
    return (double)*(float *)(iVar1 + 0x44);
  }
  if (param_2 < 4) {
    if (param_2 == 2) {
      return (double)*(float *)(iVar1 + 0x40);
    }
    if (1 < param_2) {
      return (double)(*(float *)(param_1 + 0x10) + *(float *)(iVar1 + 0x44));
    }
    if (param_2 != 0) {
      return (double)(*(float *)(param_1 + 0xc) + *(float *)(iVar1 + 0x40));
    }
  }
  else {
    if (param_2 == 6) {
      return (double)*(float *)(iVar1 + 0x48);
    }
    if (param_2 < 6) {
      return (double)(*(float *)(param_1 + 0x14) + *(float *)(iVar1 + 0x48));
    }
  }
  return (double)FLOAT_803e4c98;
}

// Function: FUN_80194ee0
// Entry: 80194ee0
// Size: 504 bytes

void FUN_80194ee0(undefined4 param_1,undefined4 param_2,int param_3)

{
  ushort uVar1;
  ushort *puVar2;
  uint uVar3;
  int iVar4;
  undefined2 *puVar5;
  int iVar6;
  int iVar7;
  int iVar8;
  int iVar9;
  undefined8 uVar10;
  
  uVar10 = FUN_80286830();
  iVar4 = (int)uVar10;
  iVar8 = 0;
  iVar7 = 0;
  for (iVar6 = 0; iVar6 < (int)(uint)*(ushort *)(param_3 + 0x9a); iVar6 = iVar6 + 1) {
    puVar2 = (ushort *)FUN_80060868(param_3,iVar6);
    uVar3 = FUN_800607f4((int)puVar2);
    if ((int)*(char *)((int)((ulonglong)uVar10 >> 0x20) + 0x28) == uVar3) {
      *(ushort *)(*(int *)(iVar4 + 0x10) + iVar8) = puVar2[3];
      *(ushort *)(*(int *)(iVar4 + 0x14) + iVar8) = puVar2[4];
      iVar8 = iVar8 + 2;
      uVar1 = puVar2[10];
      iVar9 = iVar7;
      for (uVar3 = (uint)*puVar2; (int)uVar3 < (int)(uint)uVar1; uVar3 = uVar3 + 1) {
        puVar2 = (ushort *)FUN_80060858(param_3,uVar3);
        puVar5 = (undefined2 *)(*(int *)(param_3 + 0x58) + (uint)*puVar2 * 6);
        *(undefined2 *)(*(int *)(iVar4 + 0xc) + iVar9) = *puVar5;
        *(undefined2 *)(*(int *)(iVar4 + 0xc) + iVar9 + 2) = puVar5[1];
        *(undefined2 *)(*(int *)(iVar4 + 0xc) + iVar9 + 4) = puVar5[2];
        puVar5 = (undefined2 *)(*(int *)(param_3 + 0x58) + (uint)puVar2[1] * 6);
        *(undefined2 *)(*(int *)(iVar4 + 0xc) + iVar9 + 6) = *puVar5;
        *(undefined2 *)(*(int *)(iVar4 + 0xc) + iVar9 + 8) = puVar5[1];
        *(undefined2 *)(*(int *)(iVar4 + 0xc) + iVar9 + 10) = puVar5[2];
        puVar5 = (undefined2 *)(*(int *)(param_3 + 0x58) + (uint)puVar2[2] * 6);
        *(undefined2 *)(*(int *)(iVar4 + 0xc) + iVar9 + 0xc) = *puVar5;
        *(undefined2 *)(*(int *)(iVar4 + 0xc) + iVar9 + 0xe) = puVar5[1];
        *(undefined2 *)(*(int *)(iVar4 + 0xc) + iVar9 + 0x10) = puVar5[2];
        iVar9 = iVar9 + 0x12;
        iVar7 = iVar7 + 0x12;
      }
    }
  }
  iVar6 = 0;
  for (iVar7 = 0; iVar7 < (int)(uint)*(byte *)(param_3 + 0xa1); iVar7 = iVar7 + 1) {
    iVar8 = FUN_80060878(param_3,iVar7);
    *(undefined2 *)(*(int *)(iVar4 + 0x28) + iVar6) = *(undefined2 *)(iVar8 + 6);
    *(undefined2 *)(*(int *)(iVar4 + 0x2c) + iVar6) = *(undefined2 *)(iVar8 + 0xc);
    *(undefined2 *)(*(int *)(iVar4 + 0x30) + iVar6) = *(undefined2 *)(iVar8 + 8);
    *(undefined2 *)(*(int *)(iVar4 + 0x34) + iVar6) = *(undefined2 *)(iVar8 + 0xe);
    *(undefined2 *)(*(int *)(iVar4 + 0x38) + iVar6) = *(undefined2 *)(iVar8 + 10);
    *(undefined2 *)(*(int *)(iVar4 + 0x3c) + iVar6) = *(undefined2 *)(iVar8 + 0x10);
    iVar6 = iVar6 + 2;
  }
  FUN_8028687c();
  return;
}
