/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/SP/SPdrape.c
 * Text span: 0x801D8DE8-0x801D90F0
 * Imported Ghidra functions: 1
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 1
 */

#include "ghidra_import.h"
#include "main/dll/SP/SPdrape.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern uint FUN_80020078();
extern undefined4 FUN_800201ac();
extern int FUN_8002bac4();
extern int FUN_8002e1ac();
extern uint FUN_800d7d78();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4* DAT_803dd6cc;
extern undefined4* DAT_803dd6d4;
extern undefined4* DAT_803dd72c;

/* Local declarations keep imported functions visible within the TU. */
void FUN_801d8de8(undefined4 param_1,uint *param_2);

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801d8de8(undefined4 param_1,uint *param_2)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}
