/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/LGT/LGTcontrollight.c
 * Text span: 0x801F4C60-0x801F4EF0
 * Imported Ghidra functions: 1
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 1
 */

#include "ghidra_import.h"
#include "main/dll/LGT/LGTcontrollight.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_800201ac();
extern undefined4 FUN_800372f8();
extern undefined4 FUN_80043604();
extern undefined4 FUN_80043658();
extern int FUN_8004832c();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4* DAT_803dd72c;
extern f32 FLOAT_803e6b28;

/* Local declarations keep imported functions visible within the TU. */
void FUN_801f4c60(int param_1);

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801f4c60(int param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}
