/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/unknown/autos/placeholder_80279AF0.c
 * Text span: 0x80279AF0-0x80279D30
 * Imported Ghidra functions: 4
 * Verbatim-safe functions: 1
 * Auto-stubbed functions: 3
 */

#include "ghidra_import.h"
#include "main/unknown/autos/placeholder_80279AF0.h"

/* Raw global references kept as loose externs for later cleanup. */
extern byte DAT_803cb7f0;
extern undefined4 DAT_803cb7f1;
extern undefined4 DAT_803cb7f2;
extern undefined4 DAT_803cb8f0;
extern undefined4 DAT_803cb9f0;
extern undefined4 DAT_803cb9f2;
extern undefined4 DAT_803def70;
extern int* DAT_803def74;
extern int* DAT_803def78;
extern undefined4 DAT_803def7c;

/* Local declarations keep imported functions visible within the TU. */
undefined4 FUN_80279af0(int param_1);
uint FUN_80279b04(int param_1,int param_2);
undefined4 FUN_80279c00(uint param_1);
void FUN_80279c50(int param_1);

// Function: FUN_80279af0
// Entry: 80279af0
// Size: 20 bytes

undefined4 FUN_80279af0(int param_1)

{
  *(undefined4 *)(param_1 + 0xfc) = *(undefined4 *)(param_1 + 0xf8);
  return *(undefined4 *)(*(int *)(param_1 + 0xf8) + 8);
}

/* Auto-stubbed for compileability: typed global pointer comparisons need manual cleanup, conflicting local pointer bases for shared globals: DAT_803def74. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

uint FUN_80279b04(int param_1,int param_2)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0;
}

/* Auto-stubbed for compileability: conflicting local pointer bases for shared globals: DAT_803def74. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

undefined4 FUN_80279c00(uint param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0;
}

/* Auto-stubbed for compileability: address-of global symbols need manual typing. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_80279c50(int param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}
