/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/unknown/autos/placeholder_8027A710.c
 * Text span: 0x8027A710-0x8027A940
 * Imported Ghidra functions: 3
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 3
 */

#include "ghidra_import.h"
#include "main/unknown/autos/placeholder_8027A710.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_80273f50();
extern void* FUN_80279768();
extern undefined4 FUN_8027979c();
extern undefined4 FUN_8027a2fc();
extern bool FUN_802839b8();
extern undefined4 FUN_80283ba0();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4 DAT_803deeb8;
extern undefined4 DAT_803deee8;

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8027A710
 * EN v1.0 Size: 128b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8027a710(int param_1)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8027A790
 * EN v1.0 Size: 160b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8027a790(int param_1)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8027A830
 * EN v1.0 Size: 272b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
undefined4 FUN_8027a830(uint param_1)
{
    return 0;
}
