/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/unknown/autos/placeholder_80293A9C.c
 * Text span: 0x80293A9C-0x80293BC4
 * Imported Ghidra functions: 1
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 1
 */

#include "ghidra_import.h"
#include "main/unknown/autos/placeholder_80293A9C.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern int FUN_802867b4();
extern undefined4 FUN_80286800();
extern undefined4 FUN_80292568();

/* Local declarations keep imported functions visible within the TU. */
void FUN_80293a9c(void);

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_80293a9c(void)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}
