/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/unknown/autos/placeholder_8027C728.c
 * Text span: 0x8027C728-0x8027CAF4
 * Imported Ghidra functions: 3
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 3
 */

#include "ghidra_import.h"
#include "main/unknown/autos/placeholder_8027C728.h"

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4 DAT_803cce90;

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8027C728
 * EN v1.0 Size: 32b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8027c728(uint param_1)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8027C748
 * EN v1.0 Size: 244b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
undefined4
FUN_8027c748(undefined2 *param_1,undefined2 *param_2,short *param_3,short param_4,int param_5,
            ushort param_6)
{
    return 0;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8027C83C
 * EN v1.0 Size: 696b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8027c83c(int param_1,int *param_2)
{
}
