/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/unknown/autos/placeholder_8028373C.c
 * Text span: 0x8028373C-0x80283744
 * Imported Ghidra functions: 1
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 1
 */

#include "ghidra_import.h"
#include "main/unknown/autos/placeholder_8028373C.h"

/* Local declarations keep imported functions visible within the TU. */
uint FUN_8028373c(uint param_1);

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

uint FUN_8028373c(uint param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0;
}
