/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/unknown/autos/placeholder_802857B0.c
 * Text span: 0x802857B0-0x80285B64
 * Imported Ghidra functions: 1
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 1
 */

#include "ghidra_import.h"
#include "main/unknown/autos/placeholder_802857B0.h"

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4 DAT_803e85b8;
extern undefined4 DAT_803e85bc;
extern undefined4 DAT_803e85c0;

/* Local declarations keep imported functions visible within the TU. */
void FUN_802857b0(uint *param_1,int param_2);

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_802857b0(uint *param_1,int param_2)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}
