/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/unknown/autos/placeholder_8002F604.c
 * Text span: 0x8002F604-0x80030780
 * Imported Ghidra functions: 7
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 7
 */

#include "ghidra_import.h"
#include "main/unknown/autos/placeholder_8002F604.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_80024f40();
extern undefined4 FUN_8002c7a0();
extern undefined4 FUN_8003586c();
extern undefined4 FUN_8007d858();
extern undefined8 FUN_80286840();
extern undefined4 FUN_8028688c();

/* Raw global references kept as loose externs for later cleanup. */
extern f64 DOUBLE_803df568;
extern f64 DOUBLE_803df580;
extern f32 FLOAT_803df560;
extern f32 FLOAT_803df570;
extern f32 FLOAT_803df574;
extern f32 FLOAT_803df578;
extern f32 FLOAT_803df588;
extern f32 FLOAT_803df58c;

/* Local declarations keep imported functions visible within the TU. */
undefined2 FUN_8002f604(int param_1);
void FUN_8002f624(int param_1,int param_2,short param_3,undefined2 param_4);
void FUN_8002f66c(int param_1,uint param_2);
undefined4 FUN_8002f6cc(double param_1,int param_2,float *param_3);
void FUN_8002fb40(undefined8 param_1,double param_2);
undefined4 FUN_800303fc(double param_1,int param_2);
void FUN_8003042c(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 undefined4 param_9,undefined4 param_10,uint param_11,undefined4 param_12,
                 undefined4 param_13,undefined4 param_14,undefined4 param_15,undefined4 param_16);

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

undefined2 FUN_8002f604(int param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0;
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_8002f624(int param_1,int param_2,short param_3,undefined2 param_4)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_8002f66c(int param_1,uint param_2)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

undefined4 FUN_8002f6cc(double param_1,int param_2,float *param_3)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0;
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_8002fb40(undefined8 param_1,double param_2)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

undefined4 FUN_800303fc(double param_1,int param_2)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0;
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_8003042c(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 undefined4 param_9,undefined4 param_10,uint param_11,undefined4 param_12,
                 undefined4 param_13,undefined4 param_14,undefined4 param_15,undefined4 param_16)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}
