/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/unknown/autos/placeholder_80284698.c
 * Text span: 0x80284698-0x80284704
 * Imported Ghidra functions: 5
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 5
 */

#include "ghidra_import.h"
#include "main/unknown/autos/placeholder_80284698.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern uint countLeadingZeros();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4 DAT_803defb4;
extern undefined4 DAT_803defc4;
extern undefined4 DAT_803deff4;
extern undefined4 DAT_803deff8;

/* Local declarations keep imported functions visible within the TU. */
void FUN_80284698(void);
void FUN_8028469c(undefined4 *param_1);
void FUN_802846b0(void);
undefined4 FUN_802846bc(int param_1);
uint FUN_802846e4(int param_1);

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_80284698(void)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_8028469c(undefined4 *param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_802846b0(void)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

undefined4 FUN_802846bc(int param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0;
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

uint FUN_802846e4(int param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0;
}
