/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/unknown/autos/placeholder_80283E4C.c
 * Text span: 0x80283E4C-0x80283FA0
 * Imported Ghidra functions: 5
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 5
 */

#include "ghidra_import.h"
#include "main/unknown/autos/placeholder_80283E4C.h"

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4 DAT_803dd280;
extern undefined4 DAT_803dd288;
extern undefined4 DAT_803defc4;
extern undefined4 DAT_803deff0;

/* Local declarations keep imported functions visible within the TU. */
void FUN_80283e4c(int param_1);
void FUN_80283e74(int param_1,ushort param_2);
void FUN_80283eec(int param_1,uint param_2);
void FUN_80283f18(int param_1,uint param_2);
void FUN_80283f44(int param_1,char param_2);

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_80283e4c(int param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_80283e74(int param_1,ushort param_2)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: address-of global symbols need manual typing, forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_80283eec(int param_1,uint param_2)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: address-of global symbols need manual typing, forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_80283f18(int param_1,uint param_2)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_80283f44(int param_1,char param_2)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}
