/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/unknown/autos/placeholder_80292C14.c
 * Text span: 0x80292C14-0x80292F04
 * Imported Ghidra functions: 2
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 2
 */

#include "ghidra_import.h"
#include "main/unknown/autos/placeholder_80292C14.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_802867a8();
extern undefined4 FUN_802867f4();

/* Local declarations keep imported functions visible within the TU. */
void FUN_80292c14(void);
void FUN_80292d24(void);

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_80292c14(void)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_80292d24(void)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}
