/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/unknown/autos/placeholder_802818F8.c
 * Text span: 0x802818F8-0x80281A9C
 * Imported Ghidra functions: 5
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 5
 */

#include "ghidra_import.h"
#include "main/unknown/autos/placeholder_802818F8.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 SQRT();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4 DAT_803bdfc1;
extern undefined4 DAT_803bdfc2;
extern undefined4 DAT_803d4900;
extern undefined4 DAT_803deeb8;
extern f64 DOUBLE_803e8568;
extern f64 DOUBLE_803e8570;
extern f32 FLOAT_803e8560;

/* Local declarations keep imported functions visible within the TU. */
void FUN_802818f8(undefined param_1,undefined param_2);
undefined FUN_8028190c(void);
void FUN_80281914(float *param_1,float *param_2,float *param_3);
void FUN_802819c0(float *param_1);
void FUN_80281a74(uint param_1,uint param_2,uint param_3);

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_802818f8(undefined param_1,undefined param_2)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

undefined FUN_8028190c(void)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0;
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_80281914(float *param_1,float *param_2,float *param_3)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_802819c0(float *param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: address-of global symbols need manual typing, forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_80281a74(uint param_1,uint param_2,uint param_3)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}
