/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/unknown/autos/placeholder_802836E4.c
 * Text span: 0x802836E4-0x802836F4
 * Imported Ghidra functions: 1
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 1
 */

#include "ghidra_import.h"
#include "main/unknown/autos/placeholder_802836E4.h"

/* Local declarations keep imported functions visible within the TU. */
void FUN_802836e4(int *param_1);

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_802836e4(int *param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}
