/*
 * Auto-generated by tools/ghidra_unmanaged_homes.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists so every raw Ghidra function mapped to an unmanaged live owner
 * still has a concrete .c home for iteration/reference work.
 *
 * Live owner: dolphin/TRK_MINNOW_DOLPHIN/msg.c
 * Text span: 0x80287460-0x8028763C
 * Imported Ghidra functions: 1
 * Verbatim-safe functions: 1
 * Auto-stubbed functions: 0
 */
/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: dolphin/TRK_MINNOW_DOLPHIN/msg.c
 * Text span: 0x80287460-0x8028763C
 * Imported Ghidra functions: 1
 * Verbatim-safe functions: 1
 * Auto-stubbed functions: 0
 */

#include "ghidra_import.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern int FUN_8028d7ec();
extern undefined4 FUN_8028d814();

/* Local declarations keep imported functions visible within the TU. */
void FUN_80287460(int param_1);

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80287460
 * EN v1.0 Size: 476b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80287460(int param_1)
{
  byte bVar2;
  int iVar1;
  byte bVar3;
  uint uVar4;
  uint uVar5;
  int iVar6;
  char *pcVar7;
  byte bVar8;
  uint uVar9;
  
  bVar2 = 0;
  uVar5 = *(uint *)(param_1 + 8);
  uVar4 = 0;
  if (uVar5 != 0) {
    if ((8 < uVar5) && (uVar9 = uVar5 - 1 >> 3, uVar5 != 8)) {
      do {
        iVar6 = uVar4 + 0x10;
        uVar4 = uVar4 + 8;
        pcVar7 = (char *)(param_1 + iVar6);
        bVar2 = bVar2 + *pcVar7 + pcVar7[1] + pcVar7[2] + pcVar7[3] + pcVar7[4] + pcVar7[5] +
                pcVar7[6] + pcVar7[7];
        uVar9 = uVar9 - 1;
      } while (uVar9 != 0);
    }
    iVar6 = uVar5 - uVar4;
    if (uVar4 < uVar5) {
      do {
        iVar1 = uVar4 + 0x10;
        uVar4 = uVar4 + 1;
        bVar2 = bVar2 + *(char *)(param_1 + iVar1);
        iVar6 = iVar6 + -1;
      } while (iVar6 != 0);
    }
  }
  bVar3 = bVar2 ^ 0xff;
  iVar6 = FUN_8028d7ec(0x7e);
  if (iVar6 == 0) {
    for (uVar4 = 0; uVar4 < *(uint *)(param_1 + 8); uVar4 = uVar4 + 1) {
      bVar8 = *(byte *)(param_1 + uVar4 + 0x10);
      if ((bVar8 == 0x7e) || (bVar8 == 0x7d)) {
        iVar6 = FUN_8028d7ec(0x7d);
        bVar8 = bVar8 ^ 0x20;
        if (iVar6 != 0) break;
      }
      iVar6 = FUN_8028d7ec(bVar8);
      if (iVar6 != 0) break;
    }
  }
  if (iVar6 == 0) {
    if ((bVar3 == 0x7e) || (bVar3 == 0x7d)) {
      iVar6 = FUN_8028d7ec(0x7d);
      bVar3 = bVar2 ^ 0xdf;
      if (iVar6 != 0) goto LAB_80287600;
    }
    iVar6 = FUN_8028d7ec(bVar3);
  }
LAB_80287600:
  if (iVar6 == 0) {
    iVar6 = FUN_8028d7ec(0x7e);
  }
  if (iVar6 == 0) {
    FUN_8028d814();
  }
  return;
}
