/*
 * Auto-generated by tools/ghidra_unmanaged_homes.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists so every raw Ghidra function mapped to an unmanaged live owner
 * still has a concrete .c home for iteration/reference work.
 *
 * Live owner: dolphin/TRK_MINNOW_DOLPHIN/mutex_TRK.c
 * Text span: 0x8028B658-0x8028B670
 * Imported Ghidra functions: 3
 * Verbatim-safe functions: 3
 * Auto-stubbed functions: 0
 */
/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: dolphin/TRK_MINNOW_DOLPHIN/mutex_TRK.c
 * Text span: 0x8028B658-0x8028B670
 * Imported Ghidra functions: 3
 * Verbatim-safe functions: 3
 * Auto-stubbed functions: 0
 */

#include "ghidra_import.h"

/* Local declarations keep imported functions visible within the TU. */
undefined4 FUN_8028b658(void);
undefined4 FUN_8028b660(void);
undefined4 FUN_8028b668(void);

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8028B658
 * EN v1.0 Size: 8b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
undefined4 FUN_8028b658(void)
{
  return 0;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8028B660
 * EN v1.0 Size: 8b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
undefined4 FUN_8028b660(void)
{
  return 0;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8028B668
 * EN v1.0 Size: 8b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
undefined4 FUN_8028b668(void)
{
  return 0;
}
