/*
 * Auto-generated by tools/ghidra_unmanaged_homes.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists so every raw Ghidra function mapped to an unmanaged live owner
 * still has a concrete .c home for iteration/reference work.
 *
 * Live owner: dolphin/TRK_MINNOW_DOLPHIN/MWCriticalSection_gc.c
 * Text span: 0x801B1398-0x801B13F0
 * Imported Ghidra functions: 1
 * Verbatim-safe functions: 1
 * Auto-stubbed functions: 0
 */
/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: dolphin/TRK_MINNOW_DOLPHIN/MWCriticalSection_gc.c
 * Text span: 0x801B1398-0x801B13F0
 * Imported Ghidra functions: 1
 * Verbatim-safe functions: 1
 * Auto-stubbed functions: 0
 */

#include "ghidra_import.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_8003b9ec();

/* Local declarations keep imported functions visible within the TU. */
void FUN_801b139c(int param_1);

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801B139C
 * EN v1.0 Size: 84b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_801b139c(int param_1)
{
  char in_r8;
  
  if (in_r8 != '\0') {
    FUN_8003b9ec(param_1);
  }
  return;
}
