/*
 * Auto-generated by tools/ghidra_unmanaged_homes.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists so every raw Ghidra function mapped to an unmanaged live owner
 * still has a concrete .c home for iteration/reference work.
 *
 * Live owner: main/audio/synth_handle.c
 * Text span: 0x8026D7C4-0x8026DFE4
 * Imported Ghidra functions: 7
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 7
 */
/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/audio/synth_handle.c
 * Text span: 0x8026D7C4-0x8026DFE4
 * Imported Ghidra functions: 7
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 7
 */

#include "ghidra_import.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_8026c6b8();
extern undefined4 FUN_802722b0();
extern undefined4 FUN_8027a830();

/* Raw global references kept as loose externs for later cleanup. */
extern int DAT_803b15b0;
extern undefined4 DAT_803b15b4;
extern undefined4 DAT_803b15b8;
extern undefined4 DAT_803b16cc;
extern undefined4 DAT_803b16d0;
extern undefined4 DAT_803b2480;
extern undefined4 DAT_803b2484;
extern undefined4 DAT_803b2488;
extern undefined4 DAT_803b248a;
extern undefined4 DAT_803b2aca;
extern undefined4 DAT_803b2b02;
extern undefined4 DAT_803b2b3a;
extern undefined4 DAT_803b2b72;
extern undefined4 DAT_803b2baa;
extern undefined4 DAT_803b2be2;
extern undefined4 DAT_803b2c1a;
extern undefined4 DAT_803b2c52;
extern undefined4 DAT_803b2c8a;
extern undefined4 DAT_803b2cc2;
extern undefined4 DAT_803b2cfa;
extern undefined4 DAT_803b2d32;
extern undefined4 DAT_803b2d6a;
extern undefined4 DAT_803b2da2;
extern undefined4 DAT_803b2dda;
extern undefined4 DAT_803b2e12;
extern undefined4* DAT_803deeac;
extern int* DAT_803deeb0;
extern undefined4* DAT_803deeb4;

/* Local declarations keep imported functions visible within the TU. */
void FUN_8026d7c4();
void FUN_8026d828();
void FUN_8026d9dc();
void FUN_8026dbac();
void FUN_8026dc88();
void FUN_8026dd94();
void FUN_8026de48();

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8026D7C4
 * EN v1.0 Size: 100b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8026d7c4()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8026D828
 * EN v1.0 Size: 436b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8026d828()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8026D9DC
 * EN v1.0 Size: 464b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8026d9dc()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8026DBAC
 * EN v1.0 Size: 220b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8026dbac()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8026DC88
 * EN v1.0 Size: 268b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8026dc88()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8026DD94
 * EN v1.0 Size: 180b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8026dd94()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8026DE48
 * EN v1.0 Size: 412b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8026de48()
{
}
