/*
 * Auto-generated by tools/ghidra_unmanaged_homes.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists so every raw Ghidra function mapped to an unmanaged live owner
 * still has a concrete .c home for iteration/reference work.
 *
 * Live owner: main/audio/synth_channel.c
 * Text span: 0x8026D6DC-0x8026D7C4
 * Imported Ghidra functions: 1
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 1
 */
/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/audio/synth_channel.c
 * Text span: 0x8026D6DC-0x8026D7C4
 * Imported Ghidra functions: 1
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 1
 */

#include "ghidra_import.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_8026fca0();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4 DAT_803dee98;
extern undefined4 DAT_803deea0;

/* Local declarations keep imported functions visible within the TU. */
void FUN_8026d6dc();

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8026D6DC
 * EN v1.0 Size: 232b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8026d6dc()
{
}
