/*
 * Auto-generated by tools/ghidra_unmanaged_homes.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists so every raw Ghidra function mapped to an unmanaged live owner
 * still has a concrete .c home for iteration/reference work.
 *
 * Live owner: main/audio/synth_seq_queue.c
 * Text span: 0x8026EFC8-0x8026F134
 * Imported Ghidra functions: 2
 * Verbatim-safe functions: 2
 * Auto-stubbed functions: 0
 */
#include "ghidra_import.h"

extern undefined4 FUN_8026e5bc();
extern undefined4 FUN_8026e7d4();

extern undefined4 DAT_803dee98;

void FUN_8026efc8(void);
void FUN_8026f070(uint param_1);

void FUN_8026efc8(void)
{
  undefined4 *puVar1;
  uint uVar2;

  if (*(int *)(DAT_803dee98 + 0x14e4) == 0) {
    uVar2 = 0;
    do {
      puVar1 = (undefined4 *)FUN_8026e5bc((byte)uVar2);
      if (puVar1 != (undefined4 *)0x0) {
        FUN_8026e7d4(DAT_803dee98 + 0x14e8,puVar1);
      }
      uVar2 = uVar2 + 1;
    } while (uVar2 < 0x40);
  }
  else {
    uVar2 = 0;
    do {
      puVar1 = (undefined4 *)FUN_8026e5bc((byte)uVar2);
      if (puVar1 != (undefined4 *)0x0) {
        FUN_8026e7d4(DAT_803dee98 +
                     (uint)*(byte *)(*(int *)(DAT_803dee98 + 0x14e4) + uVar2) * 0x38 + 0x14e8,puVar1
                    );
      }
      uVar2 = uVar2 + 1;
    } while (uVar2 < 0x40);
  }
  return;
}

void FUN_8026f070(uint param_1)
{
  undefined4 *puVar1;
  uint uVar2;

  if (*(int *)(DAT_803dee98 + 0x14e4) == 0) {
    uVar2 = 0;
    do {
      puVar1 = (undefined4 *)FUN_8026e5bc((byte)uVar2);
      if (puVar1 != (undefined4 *)0x0) {
        FUN_8026e7d4(DAT_803dee98 + 0x14e8,puVar1);
      }
      uVar2 = uVar2 + 1;
    } while (uVar2 < 0x40);
  }
  else {
    uVar2 = 0;
    do {
      if (((param_1 & 0xff) == (uint)*(byte *)(*(int *)(DAT_803dee98 + 0x14e4) + uVar2)) &&
         (puVar1 = (undefined4 *)FUN_8026e5bc((byte)uVar2), puVar1 != (undefined4 *)0x0)) {
        FUN_8026e7d4(DAT_803dee98 + (param_1 & 0xff) * 0x38 + 0x14e8,puVar1);
      }
      uVar2 = uVar2 + 1;
    } while (uVar2 < 0x40);
  }
  return;
}
