/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 */

#ifndef DOLPHIN_MTX_VEC_H_
#define DOLPHIN_MTX_VEC_H_

#include "ghidra_import.h"

void FUN_80247e94(float *param_1,float *param_2,float *param_3);
void FUN_80247eb8(float *param_1,float *param_2,float *param_3);
void FUN_80247edc(double param_1,float *param_2,float *param_3);
void FUN_80247ef8();
double FUN_80247f3c(float *param_1);
double FUN_80247f54(float *param_1);
double FUN_80247f90(float *param_1,float *param_2);
void FUN_80247fb0();
void FUN_80247fec(float *param_1,float *param_2,float *param_3);
double FUN_802480c0(float *param_1,float *param_2);
double FUN_802480e8(float *param_1,float *param_2);

#endif /* DOLPHIN_MTX_VEC_H_ */
