from __future__ import annotations

import argparse
import csv
import io
import re
import struct
import sys
import zlib
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path


PRINTABLE_RE = re.compile(rb"[ -~]{5,}")
SOURCE_TOKEN_RE = re.compile(
    r"(?<![A-Za-z0-9_./-])<?([A-Za-z][A-Za-z0-9_/-]{2,}\.(?:c|cpp|h|hpp))>?",
    re.IGNORECASE,
)
DIRECT_ARTIFACT_RE = re.compile(r"\.(?:c|cpp)\.new$|\.(?:h|hpp)\.bak$", re.IGNORECASE)
SKIPPED_EMBEDDED_SUFFIXES = {".iso", ".adp", ".sam", ".thp"}


@dataclass(frozen=True)
class DirectSourceArtifact:
    relative_path: str
    kind: str
    source_tokens: tuple[str, ...]


@dataclass(frozen=True)
class EmbeddedSourceLeak:
    relative_path: str
    stream: str
    token: str
    context: str
    score: int
    confidence: str
    reasons: tuple[str, ...]


def clean_context(text: str, limit: int = 160) -> str:
    normalized = re.sub(r"\s+", " ", text.strip())
    if len(normalized) <= limit:
        return normalized
    return normalized[: limit - 3] + "..."


def unique_strings(values: list[str]) -> tuple[str, ...]:
    result: list[str] = []
    seen: set[str] = set()
    for value in values:
        if value in seen:
            continue
        seen.add(value)
        result.append(value)
    return tuple(result)


def iter_printable_strings(data: bytes) -> list[str]:
    return [match.group(0).decode("ascii", "ignore") for match in PRINTABLE_RE.finditer(data)]


def extract_source_tokens(text: str) -> list[str]:
    tokens: list[str] = []
    seen: set[str] = set()
    for match in SOURCE_TOKEN_RE.finditer(text):
        token = match.group(1)
        if token in seen:
            continue
        seen.add(token)
        tokens.append(token)
    return tokens


def classify_embedded_hit(relative_path: str, stream: str, token: str, context: str) -> tuple[int, str, tuple[str, ...]]:
    basename = Path(token.replace("\\", "/")).name
    stem = Path(basename).stem
    alpha_count = sum(char.isalpha() for char in stem)
    score = 0
    reasons: list[str] = []
    lowered_context = context.lower()
    lowered_path = relative_path.lower()

    if "/" in token or "\\" in token:
        score += 4
        reasons.append("path-token")
    if alpha_count >= 5 and len(stem) >= 5:
        score += 2
        reasons.append("word-like-stem")
    elif alpha_count >= 4:
        score += 1
        reasons.append("usable-stem")
    if f"<{token}" in context or f"{token}:" in context or "File:" in context:
        score += 2
        reasons.append("tagged-context")
    if any(word in lowered_context for word in ("warning", "error", "failed", "include", "generated by", "file:")):
        score += 2
        reasons.append("diagnostic-context")
    if any(char.isspace() for char in context):
        score += 1
        reasons.append("sentence-context")

    if lowered_path == "sys/main.dol":
        score += 2
        reasons.append("main-dol")
    elif lowered_path == "sys/apploader.img":
        score += 2
        reasons.append("apploader")
        if context == token:
            score += 2
            reasons.append("standalone-sdk-name")
    elif lowered_path == "sys/fst.bin":
        score -= 2
        reasons.append("fst-filename-only")
    elif lowered_path.endswith((".thp", ".adp", ".sam")):
        score -= 2
        reasons.append("media-noise")
    elif lowered_path.endswith((".bin", ".tab")) and not lowered_path.startswith("sys/"):
        score -= 1
        reasons.append("data-noise")

    if stream == "zlb":
        score -= 1
        reasons.append("compressed-payload")

    if (
        len(stem) <= 4
        and "/" not in token
        and "\\" not in token
        and lowered_path not in {"sys/main.dol", "sys/apploader.img"}
    ):
        score -= 3
        reasons.append("short-stem")
    elif (
        not re.search(r"[aeiou]", stem.lower())
        and len(stem) < 7
        and "/" not in token
        and "\\" not in token
        and lowered_path not in {"sys/main.dol", "sys/apploader.img"}
    ):
        score -= 1
        reasons.append("low-vowel-stem")

    if score >= 6:
        confidence = "high"
    elif score >= 4:
        confidence = "medium"
    else:
        confidence = "low"
    return score, confidence, tuple(reasons)


def scan_embedded_source_leaks(path: Path, relative_path: str) -> list[EmbeddedSourceLeak]:
    leaks: list[EmbeddedSourceLeak] = []
    seen: set[tuple[str, str, str]] = set()

    def scan_stream(stream: str, data: bytes) -> None:
        for printable in iter_printable_strings(data):
            context = clean_context(printable)
            for token in extract_source_tokens(printable):
                key = (stream, token, context)
                if key in seen:
                    continue
                seen.add(key)
                score, confidence, reasons = classify_embedded_hit(relative_path, stream, token, context)
                leaks.append(
                    EmbeddedSourceLeak(
                        relative_path=relative_path,
                        stream=stream,
                        token=token,
                        context=context,
                        score=score,
                        confidence=confidence,
                        reasons=reasons,
                    )
                )

    data = path.read_bytes()
    scan_stream("raw", data)

    if data[:4] == b"ZLB\0" and len(data) >= 16:
        try:
            version, _decompressed_size, compressed_size = struct.unpack_from(">3I", data, 4)
            if version == 1:
                payload = zlib.decompress(data[16 : 16 + compressed_size])
                scan_stream("zlb", payload)
        except (struct.error, zlib.error):
            pass

    leaks.sort(key=lambda item: (-item.score, item.token.lower(), item.relative_path.lower(), item.stream))
    return leaks


def collect_direct_source_artifacts(orig_root: Path) -> list[DirectSourceArtifact]:
    artifacts: list[DirectSourceArtifact] = []
    for path in sorted(orig_root.rglob("*")):
        if not path.is_file():
            continue
        relative_path = path.relative_to(orig_root).as_posix()
        if not DIRECT_ARTIFACT_RE.search(relative_path):
            continue
        flattened_tokens: list[str] = []
        for text in iter_printable_strings(path.read_bytes()):
            flattened_tokens.extend(extract_source_tokens(text))
        artifacts.append(
            DirectSourceArtifact(
                relative_path=relative_path,
                kind="generated-source" if relative_path.lower().endswith(".new") else "backup-header",
                source_tokens=unique_strings(flattened_tokens),
            )
        )
    return artifacts


def collect_source_leaks(orig_root: Path) -> tuple[list[DirectSourceArtifact], list[EmbeddedSourceLeak]]:
    artifacts = collect_direct_source_artifacts(orig_root)
    leaks: list[EmbeddedSourceLeak] = []
    for path in sorted(orig_root.rglob("*")):
        if not path.is_file() or path.suffix.lower() in SKIPPED_EMBEDDED_SUFFIXES:
            continue
        relative_path = path.relative_to(orig_root).as_posix()
        leaks.extend(scan_embedded_source_leaks(path, relative_path))
    return artifacts, leaks


def grouped_leaks(leaks: list[EmbeddedSourceLeak], confidence: str) -> dict[str, list[EmbeddedSourceLeak]]:
    grouped: dict[str, list[EmbeddedSourceLeak]] = defaultdict(list)
    for leak in leaks:
        if leak.confidence != confidence:
            continue
        grouped[leak.relative_path].append(leak)
    for values in grouped.values():
        values.sort(key=lambda item: (-item.score, item.token.lower(), item.stream))
    return dict(sorted(grouped.items()))


def search_matches(
    artifacts: list[DirectSourceArtifact],
    leaks: list[EmbeddedSourceLeak],
    patterns: list[str],
) -> tuple[list[DirectSourceArtifact], list[EmbeddedSourceLeak]]:
    lowered = [pattern.lower() for pattern in patterns]

    artifact_matches: list[DirectSourceArtifact] = []
    for artifact in artifacts:
        fields = [artifact.relative_path.lower(), artifact.kind.lower()]
        fields.extend(token.lower() for token in artifact.source_tokens)
        if any(any(pattern in field for field in fields) for pattern in lowered):
            artifact_matches.append(artifact)

    leak_matches: list[EmbeddedSourceLeak] = []
    for leak in leaks:
        fields = [
            leak.relative_path.lower(),
            leak.stream.lower(),
            leak.token.lower(),
            leak.context.lower(),
            leak.confidence.lower(),
        ]
        fields.extend(reason.lower() for reason in leak.reasons)
        if any(any(pattern in field for field in fields) for pattern in lowered):
            leak_matches.append(leak)
    return artifact_matches, leak_matches


def summary_markdown(artifacts: list[DirectSourceArtifact], leaks: list[EmbeddedSourceLeak]) -> str:
    high_grouped = grouped_leaks(leaks, "high")
    medium_grouped = grouped_leaks(leaks, "medium")
    zlb_strong = [leak for leak in leaks if leak.stream == "zlb" and leak.confidence in {"high", "medium"}]

    lines: list[str] = []
    lines.append("# Retail source-leak inventory")
    lines.append("")
    lines.append("## Summary")
    lines.append(f"- Direct source/header artifacts on disc: `{len(artifacts)}`")
    lines.append(f"- High-confidence embedded source leaks: `{sum(len(values) for values in high_grouped.values())}`")
    lines.append(f"- Medium-confidence embedded source leaks: `{sum(len(values) for values in medium_grouped.values())}`")
    lines.append(f"- Strong decompressed ZLB source leaks: `{len(zlb_strong)}`")
    lines.append("")

    lines.append("## Direct source/header artifacts")
    for artifact in artifacts:
        token_preview = ", ".join(f"`{token}`" for token in artifact.source_tokens[:4])
        lines.append(f"- `{artifact.relative_path}` ({artifact.kind})")
        if token_preview:
            lines.append(f"  embedded tokens: {token_preview}")
    lines.append("")

    lines.append("## High-confidence embedded source leaks")
    if high_grouped:
        for relative_path, values in high_grouped.items():
            preview = ", ".join(f"`{token}`" for token in unique_strings([value.token for value in values])[:8])
            lines.append(f"- `{relative_path}`: {preview}")
            for value in values[:3]:
                lines.append(f"  context: `{value.context}`")
    else:
        lines.append("- None")
    lines.append("")

    lines.append("## Medium-confidence embedded source leaks")
    if medium_grouped:
        for relative_path, values in medium_grouped.items():
            preview = ", ".join(f"`{token}`" for token in unique_strings([value.token for value in values])[:8])
            lines.append(f"- `{relative_path}`: {preview}")
            for value in values[:2]:
                lines.append(f"  context: `{value.context}`")
    else:
        lines.append("- None")
    lines.append("")

    lines.append("## Negative finding")
    if zlb_strong:
        lines.append("- Some compressed payloads still produced medium/high-confidence source-like strings.")
    else:
        lines.append("- No decompressed `*.zlb` payloads produced trustworthy medium/high-confidence source leaks.")
        lines.append("- Most apparent `.c` / `.h` hits in media and asset binaries are accidental byte noise, not recoverable source names.")
    lines.append("")

    lines.append("## Usage")
    lines.append("- Summary: `python tools/orig/source_leaks.py`")
    lines.append("- Search specific names or subsystems: `python tools/orig/source_leaks.py --search camcontrol dvd GameTextData`")
    lines.append("- CSV dump: `python tools/orig/source_leaks.py --format csv`")
    return "\n".join(lines)


def search_markdown(artifacts: list[DirectSourceArtifact], leaks: list[EmbeddedSourceLeak], patterns: list[str]) -> str:
    artifact_matches, leak_matches = search_matches(artifacts, leaks, patterns)
    lines = ["# Source-leak search", ""]

    if not artifact_matches and not leak_matches:
        lines.append("- No matching source leaks.")
        return "\n".join(lines)

    for artifact in artifact_matches:
        token_preview = ", ".join(f"`{token}`" for token in artifact.source_tokens[:8])
        lines.append(f"- `{artifact.relative_path}` (`{artifact.kind}`)")
        if token_preview:
            lines.append(f"  embedded tokens: {token_preview}")

    for leak in leak_matches[:40]:
        reason_preview = ", ".join(f"`{reason}`" for reason in leak.reasons[:4])
        lines.append(
            f"- `{leak.relative_path}` {leak.stream} `{leak.token}` confidence=`{leak.confidence}` score=`{leak.score}`"
        )
        lines.append(f"  context: `{leak.context}`")
        if reason_preview:
            lines.append(f"  reasons: {reason_preview}")

    if len(leak_matches) > 40:
        lines.append(f"- ... {len(leak_matches) - 40} more matching embedded leaks omitted")
    return "\n".join(lines)


def rows_to_csv(artifacts: list[DirectSourceArtifact], leaks: list[EmbeddedSourceLeak]) -> str:
    fieldnames = ["kind", "path", "stream", "token", "confidence", "score", "context", "reasons"]
    buffer = io.StringIO()
    writer = csv.DictWriter(buffer, fieldnames=fieldnames)
    writer.writeheader()

    for artifact in artifacts:
        writer.writerow(
            {
                "kind": artifact.kind,
                "path": artifact.relative_path,
                "stream": "direct",
                "token": ",".join(artifact.source_tokens),
                "confidence": "direct",
                "score": "",
                "context": "",
                "reasons": "",
            }
        )

    for leak in leaks:
        writer.writerow(
            {
                "kind": "embedded-source-leak",
                "path": leak.relative_path,
                "stream": leak.stream,
                "token": leak.token,
                "confidence": leak.confidence,
                "score": leak.score,
                "context": leak.context,
                "reasons": ",".join(leak.reasons),
            }
        )

    return buffer.getvalue()


def build_argument_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Inventory source-file and header-name leaks across the bundled EN orig/ assets."
    )
    parser.add_argument(
        "--orig-root",
        type=Path,
        default=Path("orig/GSAE01"),
        help="Path to the EN orig bundle root.",
    )
    parser.add_argument(
        "--format",
        choices=("markdown", "csv"),
        default="markdown",
        help="Output format.",
    )
    parser.add_argument(
        "--search",
        nargs="+",
        help="Substring search across artifact paths, tokens, contexts, and scoring reasons.",
    )
    return parser


def main() -> None:
    parser = build_argument_parser()
    args = parser.parse_args()
    artifacts, leaks = collect_source_leaks(args.orig_root)

    try:
        if args.format == "csv":
            sys.stdout.write(rows_to_csv(artifacts, leaks))
        elif args.search:
            sys.stdout.write(search_markdown(artifacts, leaks, args.search))
            sys.stdout.write("\n")
        else:
            sys.stdout.write(summary_markdown(artifacts, leaks))
            sys.stdout.write("\n")
    except BrokenPipeError:
        pass


if __name__ == "__main__":
    main()
