/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 */

#ifndef DOLPHIN_CARD_CARDREAD_H_
#define DOLPHIN_CARD_CARDREAD_H_

#include "ghidra_import.h"

int FUN_80263c7c();
int FUN_80263f64();
void FUN_802640ac();

#endif /* DOLPHIN_CARD_CARDREAD_H_ */
