/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 */

#ifndef DOLPHIN_CARD_CARDOPEN_H_
#define DOLPHIN_CARD_CARDOPEN_H_

#include "ghidra_import.h"

undefined4 FUN_80263490(int param_1,char *param_2);
undefined4 FUN_802634f8();
undefined4 FUN_80263590(char *param_1);
undefined4 FUN_802635c0();
void FUN_80263710();
void FUN_80263888(int *param_1);
undefined4 FUN_802638dc(void);

#endif /* DOLPHIN_CARD_CARDOPEN_H_ */
