/*
 * Auto-generated by tools/ghidra_unmanaged_homes.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists so every raw Ghidra function mapped to an unmanaged live owner
 * still has a concrete .c home for iteration/reference work.
 *
 * Live owner: dolphin/os/OSError.c
 * Text span: 0x80242F78-0x80243308
 * Imported Ghidra functions: 4
 * Verbatim-safe functions: 1
 * Auto-stubbed functions: 3
 */
/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: dolphin/os/OSError.c
 * Text span: 0x80242F78-0x80243308
 * Imported Ghidra functions: 4
 * Verbatim-safe functions: 1
 * Auto-stubbed functions: 3
 */

#include "ghidra_import.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_8007d858();
extern undefined4 FUN_802412bc();
extern undefined4 FUN_80242a8c();
extern undefined4 FUN_80242b64();
extern undefined4 FUN_80242c4c();
extern undefined4 FUN_80243e74();
extern undefined4 FUN_802464f8();
extern undefined4 FUN_80246538();
extern undefined4 FUN_802469dc();
extern undefined4 FUN_802473b4();
extern undefined4 FUN_80247568();
extern undefined4 FUN_8028ff40();
extern undefined4 FUN_80294da8();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4 DAT_800000d8;
extern undefined4 DAT_803adfd0;
extern undefined4 DAT_cc005020;
extern undefined4 DAT_cc005022;
extern undefined4 DAT_cc005030;
extern undefined4 DAT_cc005032;
extern undefined4 DAT_cc006014;

/* Local declarations keep imported functions visible within the TU. */
void FUN_80242f78();
void FUN_80242fc0(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 undefined4 param_9,undefined4 param_10,char *param_11,undefined4 param_12,
                 undefined4 param_13,undefined4 param_14,undefined4 param_15,undefined4 param_16);
undefined4 FUN_802430ec();
void FUN_80243108();

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80242F78
 * EN v1.0 Size: 72b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80242f78()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80242FC0
 * EN v1.0 Size: 300b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80242fc0(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 undefined4 param_9,undefined4 param_10,char *param_11,undefined4 param_12,
                 undefined4 param_13,undefined4 param_14,undefined4 param_15,undefined4 param_16)
{
  bool bVar1;
  undefined4 *puVar2;
  uint uVar3;
  byte in_cr1;
  undefined4 local_88;
  undefined4 local_84;
  char *local_80;
  undefined4 local_7c;
  undefined4 local_78;
  undefined4 local_74;
  undefined4 local_70;
  undefined4 local_6c;
  undefined8 local_68;
  undefined8 local_60;
  undefined8 local_58;
  undefined8 local_50;
  undefined8 local_48;
  undefined8 local_40;
  undefined8 local_38;
  undefined8 local_30;
  char local_1c [4];
  undefined *local_18;
  undefined4 *local_14;
  
  if ((bool)(in_cr1 >> 1 & 1)) {
    local_68 = param_1;
    local_60 = param_2;
    local_58 = param_3;
    local_50 = param_4;
    local_48 = param_5;
    local_40 = param_6;
    local_38 = param_7;
    local_30 = param_8;
  }
  local_88 = param_9;
  local_84 = param_10;
  local_80 = param_11;
  local_7c = param_12;
  local_78 = param_13;
  local_74 = param_14;
  local_70 = param_15;
  local_6c = param_16;
  FUN_80243e74();
  local_1c[0] = '\x03';
  local_1c[1] = '\0';
  local_1c[2] = '\0';
  local_1c[3] = '\0';
  local_18 = &stack0x00000008;
  local_14 = &local_88;
  FUN_8028ff40(param_11,local_1c);
  FUN_8007d858();
  FUN_8007d858();
  uVar3 = 0;
  puVar2 = (undefined4 *)FUN_80242b64();
  while (((puVar2 != (undefined4 *)0x0 && (puVar2 != (undefined4 *)0xffffffff)) &&
         (bVar1 = uVar3 < 0x10, uVar3 = uVar3 + 1, bVar1))) {
    FUN_8007d858();
    puVar2 = (undefined4 *)*puVar2;
  }
  FUN_80294da8();
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x802430EC
 * EN v1.0 Size: 28b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
undefined4 FUN_802430ec()
{
    return 0;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80243108
 * EN v1.0 Size: 512b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80243108()
{
}
