/*
 * Auto-generated by tools/ghidra_unmanaged_homes.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists so every raw Ghidra function mapped to an unmanaged live owner
 * still has a concrete .c home for iteration/reference work.
 *
 * Live owner: dolphin/os/OSInterrupt.c
 * Text span: 0x80243E74-0x802446E0
 * Imported Ghidra functions: 9
 * Verbatim-safe functions: 4
 * Auto-stubbed functions: 5
 */
/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: dolphin/os/OSInterrupt.c
 * Text span: 0x80243E74-0x802446E0
 * Imported Ghidra functions: 9
 * Verbatim-safe functions: 4
 * Auto-stubbed functions: 5
 */

#include "ghidra_import.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_800033a8();
extern undefined4 FUN_802412bc();
extern int countLeadingZeros();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4 DAT_800000c4;
extern undefined4 DAT_800000c8;
extern undefined4 DAT_80003040;
extern undefined4* DAT_803deab8;
extern undefined4 DAT_cc003004;
extern undefined4 DAT_cc00401c;
extern undefined4 DAT_cc00500a;
extern undefined4 DAT_cc006800;
extern undefined4 DAT_cc006814;
extern undefined4 DAT_cc006828;
extern undefined4 DAT_cc006c00;

/* Local declarations keep imported functions visible within the TU. */
ulonglong FUN_80243e74(void);
ulonglong FUN_80243e88(void);
uint FUN_80243e9c(void);
undefined4 FUN_80243ec0();
undefined4 FUN_80243edc(short param_1);
void FUN_80243ef0();
uint FUN_80243f64();
uint FUN_8024423c();
uint FUN_802442c4();

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80243E74
 * EN v1.0 Size: 20b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
ulonglong FUN_80243e74(void)
{
  uint in_MSR;
  
  return CONCAT44(in_MSR >> 0xf,in_MSR) & 0x1ffff7fff;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80243E88
 * EN v1.0 Size: 20b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
ulonglong FUN_80243e88(void)
{
  uint in_MSR;
  
  return CONCAT44(in_MSR >> 0xf,in_MSR) & 0x1ffffffff | 0x8000;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80243E9C
 * EN v1.0 Size: 36b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
uint FUN_80243e9c(void)
{
  uint in_MSR;
  
  return in_MSR >> 0xf & 1;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80243EC0
 * EN v1.0 Size: 28b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
undefined4 FUN_80243ec0()
{
    return 0;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80243EDC
 * EN v1.0 Size: 20b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
undefined4 FUN_80243edc(short param_1)
{
  return *(undefined4 *)(DAT_803deab8 + param_1 * 4);
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80243EF0
 * EN v1.0 Size: 116b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80243ef0()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80243F64
 * EN v1.0 Size: 728b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
uint FUN_80243f64()
{
    return 0;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8024423C
 * EN v1.0 Size: 136b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
uint FUN_8024423c()
{
    return 0;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x802442C4
 * EN v1.0 Size: 1052b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
uint FUN_802442c4()
{
    return 0;
}
