/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/SH/SHrocketmushroom.c
 * Text span: 0x801D3B8C-0x801D441C
 * Imported Ghidra functions: 2
 * Verbatim-safe functions: 1
 * Auto-stubbed functions: 1
 */

#include "ghidra_import.h"
#include "main/dll/SH/SHrocketmushroom.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_8000bb38();
extern undefined4 FUN_8001dc30();
extern undefined4 FUN_80020000();
extern uint FUN_80022264();
extern undefined4 FUN_8002ba34();
extern int FUN_8002bac4();
extern undefined4 FUN_8002cc9c();
extern undefined4 FUN_80035ff8();
extern undefined4 FUN_80036018();
extern undefined4 FUN_80036974();
extern int FUN_800375e4();
extern undefined4 FUN_800379bc();
extern undefined4 FUN_80097568();
extern undefined4 FUN_801d39c4();
extern undefined4 FUN_802945e0();
extern undefined4 FUN_80294964();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4 DAT_803dc070;
extern undefined4* DAT_803dd6f8;
extern undefined4* DAT_803dd708;
extern undefined4* DAT_803dd728;
extern f64 DOUBLE_803e6038;
extern f64 DOUBLE_803e6068;
extern f64 DOUBLE_803e6070;
extern f32 FLOAT_803dc074;
extern f32 FLOAT_803e6028;
extern f32 FLOAT_803e602c;
extern f32 FLOAT_803e6040;
extern f32 FLOAT_803e6044;
extern f32 FLOAT_803e6048;
extern f32 FLOAT_803e604c;
extern f32 FLOAT_803e6050;
extern f32 FLOAT_803e6054;
extern f32 FLOAT_803e6058;
extern f32 FLOAT_803e605c;
extern f32 FLOAT_803e6060;
extern f32 FLOAT_803e6078;
extern f32 FLOAT_803e607c;
extern f32 FLOAT_803e6080;
extern f32 FLOAT_803e6084;

/* Local declarations keep imported functions visible within the TU. */
void FUN_801d3b8c(int param_1,int param_2);
void FUN_801d3e2c(double param_1,undefined8 param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 short *param_9);

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801D3B8C
 * EN v1.0 Size: 672b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

// Function: FUN_801d3b8c
// Entry: 801d3b8c
// Size: 672 bytes

void FUN_801d3b8c(int param_1,int param_2)

{
  ushort uVar1;
  uint uVar2;
  int iVar3;
  int iVar4;
  double dVar5;
  
  iVar4 = *(int *)(param_1 + 0x4c);
  uVar1 = *(ushort *)(iVar4 + 0x1c);
  uVar2 = FUN_80022264(0,100);
  if ((int)uVar2 < 10) {
    if (*(float *)(param_2 + 0x2a0) <= FLOAT_803e602c) {
      uVar2 = FUN_80022264(2000,4000);
      *(short *)(param_2 + 0x2ac) = (short)uVar2;
      uVar2 = FUN_80022264(0,1);
      if (uVar2 != 0) {
        *(short *)(param_2 + 0x2ac) = -*(short *)(param_2 + 0x2ac);
      }
      *(short *)(param_2 + 0x2ac) = *(short *)(param_2 + 0x2ac) + *(short *)(param_2 + 0x2a8);
      iVar3 = (int)*(short *)(param_2 + 0x2ac) - (uint)uVar1;
      if (0x8000 < iVar3) {
        iVar3 = iVar3 + -0xffff;
      }
      if (iVar3 < -0x8000) {
        iVar3 = iVar3 + 0xffff;
      }
      if (*(short *)(iVar4 + 0x1a) < iVar3) {
        *(ushort *)(param_2 + 0x2ac) = uVar1 + *(short *)(iVar4 + 0x1a);
      }
      if (iVar3 < -(int)*(short *)(iVar4 + 0x1a)) {
        *(ushort *)(param_2 + 0x2ac) = uVar1 - *(short *)(iVar4 + 0x1a);
      }
      *(float *)(param_2 + 0x2a0) = FLOAT_803e6040;
    }
  }
  uVar2 = FUN_80022264(0,100);
  if ((int)uVar2 < 10) {
    if (*(float *)(param_2 + 0x2a0) <= FLOAT_803e602c) {
      uVar2 = FUN_80022264(0xffffff38,200);
      *(float *)(param_2 + 0x280) =
           *(float *)(param_2 + 0x278) +
           (float)((double)CONCAT44(0x43300000,uVar2 ^ 0x80000000) - DOUBLE_803e6038) /
           FLOAT_803e6028;
      if (FLOAT_803e6044 <= *(float *)(param_2 + 0x280)) {
        if (FLOAT_803e6048 < *(float *)(param_2 + 0x280)) {
          *(float *)(param_2 + 0x280) = FLOAT_803e6048;
        }
      }
      else {
        *(float *)(param_2 + 0x280) = FLOAT_803e6044;
      }
    }
  }
  iVar4 = (int)*(short *)(param_2 + 0x2ac) - (uint)*(ushort *)(param_2 + 0x2a8);
  if (0x8000 < iVar4) {
    iVar4 = iVar4 + -0xffff;
  }
  if (iVar4 < -0x8000) {
    iVar4 = iVar4 + 0xffff;
  }
  *(short *)(param_2 + 0x2a8) =
       *(short *)(param_2 + 0x2a8) + (short)((int)(iVar4 * (uint)DAT_803dc070) >> 4);
  *(float *)(param_2 + 0x278) =
       FLOAT_803e604c * (*(float *)(param_2 + 0x280) - *(float *)(param_2 + 0x278)) * FLOAT_803dc074
       + *(float *)(param_2 + 0x278);
  dVar5 = (double)FUN_802945e0();
  *(float *)(param_2 + 0x288) = (float)((double)*(float *)(param_2 + 0x278) * dVar5);
  dVar5 = (double)FUN_80294964();
  *(float *)(param_2 + 0x28c) = (float)((double)*(float *)(param_2 + 0x278) * dVar5);
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801D3E2C
 * EN v1.0 Size: 1520b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: function-pointer stores need manual cleanup. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801d3e2c(double param_1,undefined8 param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 short *param_9)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}
