/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 */

#ifndef MAIN_UNKNOWN_AUTOS_PLACEHOLDER_80283BF0_H_
#define MAIN_UNKNOWN_AUTOS_PLACEHOLDER_80283BF0_H_

#include "ghidra_import.h"

void FUN_80283bf0();

#endif /* MAIN_UNKNOWN_AUTOS_PLACEHOLDER_80283BF0_H_ */
