/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 */

#ifndef MAIN_UNKNOWN_AUTOS_PLACEHOLDER_80283BF0_H_
#define MAIN_UNKNOWN_AUTOS_PLACEHOLDER_80283BF0_H_

#include "ghidra_import.h"

void FUN_80283bf0(int param_1,uint *param_2,byte param_3);

#endif /* MAIN_UNKNOWN_AUTOS_PLACEHOLDER_80283BF0_H_ */
