/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 */

#ifndef MAIN_UNKNOWN_AUTOS_PLACEHOLDER_80280F28_H_
#define MAIN_UNKNOWN_AUTOS_PLACEHOLDER_80280F28_H_

#include "ghidra_import.h"

void FUN_80280f28();
undefined4 FUN_8028103c();

#endif /* MAIN_UNKNOWN_AUTOS_PLACEHOLDER_80280F28_H_ */
