/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 */

#ifndef MAIN_UNKNOWN_AUTOS_PLACEHOLDER_80284988_H_
#define MAIN_UNKNOWN_AUTOS_PLACEHOLDER_80284988_H_

#include "ghidra_import.h"

void FUN_80284988(int param_1);

#endif /* MAIN_UNKNOWN_AUTOS_PLACEHOLDER_80284988_H_ */
