/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 */

#ifndef MAIN_UNKNOWN_AUTOS_PLACEHOLDER_80292C14_H_
#define MAIN_UNKNOWN_AUTOS_PLACEHOLDER_80292C14_H_

#include "ghidra_import.h"

void FUN_80292c14();
void FUN_80292d24();

#endif /* MAIN_UNKNOWN_AUTOS_PLACEHOLDER_80292C14_H_ */
