/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 */

#ifndef MAIN_UNKNOWN_AUTOS_PLACEHOLDER_8026F134_H_
#define MAIN_UNKNOWN_AUTOS_PLACEHOLDER_8026F134_H_

#include "ghidra_import.h"

undefined4 FUN_8026f134();
void FUN_8026f3a8();

#endif /* MAIN_UNKNOWN_AUTOS_PLACEHOLDER_8026F134_H_ */
