/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 */

#ifndef MAIN_UNKNOWN_AUTOS_PLACEHOLDER_80283488_H_
#define MAIN_UNKNOWN_AUTOS_PLACEHOLDER_80283488_H_

#include "ghidra_import.h"

uint FUN_80283488();
void FUN_80283528();

#endif /* MAIN_UNKNOWN_AUTOS_PLACEHOLDER_80283488_H_ */
