/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 */

#ifndef MAIN_UNKNOWN_AUTOS_PLACEHOLDER_8027979C_H_
#define MAIN_UNKNOWN_AUTOS_PLACEHOLDER_8027979C_H_

#include "ghidra_import.h"

void FUN_8027979c();

#endif /* MAIN_UNKNOWN_AUTOS_PLACEHOLDER_8027979C_H_ */
