/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 */

#ifndef MAIN_UNKNOWN_AUTOS_PLACEHOLDER_80275684_H_
#define MAIN_UNKNOWN_AUTOS_PLACEHOLDER_80275684_H_

#include "ghidra_import.h"

undefined4 FUN_80275684();

#endif /* MAIN_UNKNOWN_AUTOS_PLACEHOLDER_80275684_H_ */
