/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 */

#ifndef MAIN_UNKNOWN_AUTOS_PLACEHOLDER_80275674_H_
#define MAIN_UNKNOWN_AUTOS_PLACEHOLDER_80275674_H_

/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/unknown/autos/placeholder_80275674.c
 * Text span: 0x80275674-0x80275684
 * No raw Ghidra functions mapped into this owner yet.
 */

#include "ghidra_import.h"

#endif /* MAIN_UNKNOWN_AUTOS_PLACEHOLDER_80275674_H_ */
