/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 */

#ifndef MAIN_UNKNOWN_AUTOS_PLACEHOLDER_8029312C_H_
#define MAIN_UNKNOWN_AUTOS_PLACEHOLDER_8029312C_H_

#include "ghidra_import.h"

void FUN_8029312c();
void FUN_802932a4();
void FUN_80293390();
void FUN_802933d4();
double FUN_802933fc();
void FUN_80293424();

#endif /* MAIN_UNKNOWN_AUTOS_PLACEHOLDER_8029312C_H_ */
