/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 */

#ifndef MAIN_UNKNOWN_AUTOS_PLACEHOLDER_80272F0C_H_
#define MAIN_UNKNOWN_AUTOS_PLACEHOLDER_80272F0C_H_

#include "ghidra_import.h"

undefined4 FUN_80272f0c(uint param_1,byte param_2,byte param_3);
undefined4 FUN_80272f6c(uint param_1,byte param_2,uint param_3);
undefined4 FUN_80272fcc(uint param_1);
undefined4 FUN_8027300c(undefined2 param_1,byte param_2,uint param_3,byte param_4);
uint FUN_80273090(uint param_1);
void FUN_802730d4(uint param_1,uint param_2,uint param_3);
void FUN_80273134(uint param_1,uint param_2,char param_3,char param_4);
void FUN_802731c8(int param_1);
void FUN_802732c0(uint param_1,int param_2,undefined4 param_3,char param_4,uint param_5,int param_6,
                 undefined4 param_7,char param_8,uint param_9);
void FUN_80273428(uint param_1,undefined param_2,undefined4 param_3);
void FUN_802734d8(uint param_1);
void FUN_802735c8(uint param_1,byte *param_2);
void FUN_802735e8(uint param_1,int param_2);

#endif /* MAIN_UNKNOWN_AUTOS_PLACEHOLDER_80272F0C_H_ */
