/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 */

#ifndef DOLPHIN_GX_GXFRAMEBUF_H_
#define DOLPHIN_GX_GXFRAMEBUF_H_

#include "ghidra_import.h"

void FUN_80259340(uint param_1,uint param_2,uint param_3,uint param_4);
void FUN_80259400(uint param_1,uint param_2,uint param_3,uint param_4);
void FUN_802594c0(uint param_1);
void FUN_80259504(ushort param_1,ushort param_2,uint param_3,uint param_4);
void FUN_80259674(int param_1);
void FUN_802596a0(uint param_1);
uint FUN_8025971c();
void FUN_802597f0();
void FUN_80259858();
void FUN_80259a80(int param_1);
void FUN_80259a9c();
void FUN_80259c0c();
void FUN_80259d9c();

#endif /* DOLPHIN_GX_GXFRAMEBUF_H_ */
