/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/df_partfx.c
 * Text span: 0x800D6778-0x800D8FE0
 * Imported Ghidra functions: 23
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 23
 */

#include "ghidra_import.h"
#include "main/dll/df_partfx.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_8000bb38();
extern undefined4 FUN_8000f3f8();
extern undefined4 FUN_80013e4c();
extern undefined4 FUN_80013ee8();
extern int FUN_80021884();
extern undefined4 FUN_80021fac();
extern undefined4 FUN_80022790();
extern undefined4 FUN_8002ba34();
extern undefined4 FUN_8002ee64();
extern int FUN_8002f6cc();
extern undefined4 FUN_8003042c();
extern undefined4 FUN_80070538();
extern undefined4 FUN_80075534();
extern int FUN_800d57bc();
extern undefined4 FUN_8025da88();
extern undefined4 FUN_8025db38();
extern undefined8 FUN_8028682c();
extern undefined8 FUN_80286840();
extern undefined4 FUN_80286878();
extern undefined4 FUN_8028688c();
extern double FUN_80293900();
extern undefined4 FUN_802945e0();
extern undefined4 FUN_80294964();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4 DAT_8039d0b8;
extern undefined4 DAT_8039d0bc;
extern undefined4 DAT_803dd5d0;
extern undefined4* DAT_803dd6cc;
extern undefined4* DAT_803dd708;
extern undefined4* DAT_803dd71c;
extern undefined4 DAT_803de090;
extern undefined4 DAT_803de0ac;
extern undefined4 DAT_803de0ad;
extern undefined4 DAT_803de0ae;
extern undefined4 DAT_803de0af;
extern undefined4 DAT_803de0b4;
extern undefined4 DAT_803de0b8;
extern undefined4 DAT_803de0bc;
extern undefined4 DAT_803de0cc;
extern f64 DOUBLE_803e1178;
extern f64 DOUBLE_803e11a0;
extern f64 DOUBLE_803e11d0;
extern f64 DOUBLE_803e1218;
extern f32 FLOAT_803dc074;
extern f32 FLOAT_803de0a0;
extern f32 FLOAT_803de0a4;
extern f32 FLOAT_803de0a8;
extern f32 FLOAT_803e1168;
extern f32 FLOAT_803e1184;
extern f32 FLOAT_803e118c;
extern f32 FLOAT_803e1190;
extern f32 FLOAT_803e1194;
extern f32 FLOAT_803e1198;
extern f32 FLOAT_803e119c;
extern f32 FLOAT_803e11a8;
extern f32 FLOAT_803e11ac;
extern f32 FLOAT_803e11b0;
extern f32 FLOAT_803e11b4;
extern f32 FLOAT_803e11b8;
extern f32 FLOAT_803e11c0;
extern f32 FLOAT_803e11c4;
extern f32 FLOAT_803e11c8;
extern f32 FLOAT_803e11d8;
extern f32 FLOAT_803e11dc;
extern f32 FLOAT_803e11e0;
extern f32 FLOAT_803e11e4;
extern f32 FLOAT_803e11e8;
extern f32 FLOAT_803e11f0;
extern f32 FLOAT_803e11f4;
extern f32 FLOAT_803e11f8;
extern f32 FLOAT_803e11fc;
extern f32 FLOAT_803e1200;
extern f32 FLOAT_803e1204;
extern f32 FLOAT_803e1208;
extern f32 FLOAT_803e120c;
extern f32 FLOAT_803e1210;
extern f32 FLOAT_803e1214;
extern f32 FLOAT_803e1220;
extern f32 FLOAT_803e122c;
extern f32 FLOAT_803e1230;

/* Local declarations keep imported functions visible within the TU. */
void FUN_800d6844(int param_1);
void FUN_800d68ec(void);
void FUN_800d6d5c(undefined4 param_1,undefined4 param_2,int param_3);
void FUN_800d77f4(void);
void FUN_800d7cfc(undefined param_1);
void FUN_800d7d18(double param_1,uint param_2,undefined param_3);
uint FUN_800d7d78(void);
void FUN_800d7d90(uint param_1,undefined param_2);
void FUN_800d7de4(uint param_1,undefined param_2);
void FUN_800d7e58(uint param_1,undefined param_2);
void FUN_800d7ed0(void);
void FUN_800d82ac(double param_1,double param_2,double param_3,double param_4,double param_5,
                 int param_6,int param_7);
void FUN_800d83f8(double param_1,double param_2,double param_3,int param_4,uint *param_5);
void FUN_800d8534(double param_1,ushort *param_2,uint *param_3);
void FUN_800d86a0(ushort *param_1,int param_2);
void FUN_800d8830(int param_1,undefined4 param_2,undefined4 param_3,int param_4,int param_5);
void FUN_800d8938(undefined4 param_1,undefined4 param_2,int param_3,int param_4,undefined4 param_5,
                 int param_6);
void FUN_800d8a44(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 int param_9,int param_10,uint param_11,uint param_12,undefined4 param_13,
                 undefined4 param_14,undefined4 param_15,undefined4 param_16);
void FUN_800d8c10(double param_1,double param_2,int param_3,int param_4);
void FUN_800d8e40(double param_1,int param_2,uint *param_3);
void FUN_800d8ee8(int param_1,int param_2,undefined4 param_3);
void FUN_800d8f48(uint param_1,int param_2,int param_3,int param_4,int param_5);
void FUN_800d8f94(uint param_1,int param_2,int param_3,int param_4,int param_5);

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800D6844
 * EN v1.0 Size: 168b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_800d6844(int param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800D68EC
 * EN v1.0 Size: 1136b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_800d68ec(void)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800D6D5C
 * EN v1.0 Size: 2712b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: address-of global symbols need manual typing, NAN macro needs manual cleanup, forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_800d6d5c(undefined4 param_1,undefined4 param_2,int param_3)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800D77F4
 * EN v1.0 Size: 1288b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_800d77f4(void)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800D7CFC
 * EN v1.0 Size: 28b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_800d7cfc(undefined param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800D7D18
 * EN v1.0 Size: 96b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_800d7d18(double param_1,uint param_2,undefined param_3)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800D7D78
 * EN v1.0 Size: 24b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

uint FUN_800d7d78(void)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800D7D90
 * EN v1.0 Size: 84b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_800d7d90(uint param_1,undefined param_2)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800D7DE4
 * EN v1.0 Size: 116b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_800d7de4(uint param_1,undefined param_2)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800D7E58
 * EN v1.0 Size: 120b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_800d7e58(uint param_1,undefined param_2)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800D7ED0
 * EN v1.0 Size: 988b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: function-pointer stores need manual cleanup, forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_800d7ed0(void)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800D82AC
 * EN v1.0 Size: 332b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_800d82ac(double param_1,double param_2,double param_3,double param_4,double param_5,
                 int param_6,int param_7)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800D83F8
 * EN v1.0 Size: 316b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_800d83f8(double param_1,double param_2,double param_3,int param_4,uint *param_5)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800D8534
 * EN v1.0 Size: 364b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_800d8534(double param_1,ushort *param_2,uint *param_3)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800D86A0
 * EN v1.0 Size: 400b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_800d86a0(ushort *param_1,int param_2)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800D8830
 * EN v1.0 Size: 264b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: function-pointer stores need manual cleanup, forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_800d8830(int param_1,undefined4 param_2,undefined4 param_3,int param_4,int param_5)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800D8938
 * EN v1.0 Size: 268b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: function-pointer stores need manual cleanup, forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_800d8938(undefined4 param_1,undefined4 param_2,int param_3,int param_4,undefined4 param_5,
                 int param_6)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800D8A44
 * EN v1.0 Size: 460b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_800d8a44(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 int param_9,int param_10,uint param_11,uint param_12,undefined4 param_13,
                 undefined4 param_14,undefined4 param_15,undefined4 param_16)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800D8C10
 * EN v1.0 Size: 560b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_800d8c10(double param_1,double param_2,int param_3,int param_4)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800D8E40
 * EN v1.0 Size: 168b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: function-pointer stores need manual cleanup, forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_800d8e40(double param_1,int param_2,uint *param_3)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800D8EE8
 * EN v1.0 Size: 96b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: function-pointer stores need manual cleanup, forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_800d8ee8(int param_1,int param_2,undefined4 param_3)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800D8F48
 * EN v1.0 Size: 76b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_800d8f48(uint param_1,int param_2,int param_3,int param_4,int param_5)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800D8F94
 * EN v1.0 Size: 76b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_800d8f94(uint param_1,int param_2,int param_3,int param_4,int param_5)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}
