/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/dll_150.c
 * Text span: 0x80181C50-0x80182754
 * Imported Ghidra functions: 1
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 1
 */

#include "ghidra_import.h"
#include "main/dll/dll_150.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_800201ac();
extern uint FUN_80021884();
extern undefined4 FUN_80021b8c();
extern uint FUN_80022264();
extern undefined2* FUN_8002becc();
extern undefined4 FUN_8002e088();
extern uint FUN_8002e144();
extern undefined8 FUN_8028683c();
extern undefined4 FUN_80286888();
extern double FUN_80293900();
extern uint FUN_80297234();
extern uint FUN_80297248();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4 DAT_803ad3f0;
extern undefined4 DAT_803ad3f4;
extern undefined4 DAT_803ad3f8;
extern f64 DOUBLE_803e4600;
extern f32 FLOAT_803e45c8;
extern f32 FLOAT_803e45d0;
extern f32 FLOAT_803e45d4;
extern f32 FLOAT_803e45d8;
extern f32 FLOAT_803e45dc;
extern f32 FLOAT_803e45e0;
extern f32 FLOAT_803e45e4;
extern f32 FLOAT_803e45e8;
extern f32 FLOAT_803e45ec;
extern f32 FLOAT_803e45f0;
extern f32 FLOAT_803e45f4;
extern f32 FLOAT_803e45f8;
extern f32 FLOAT_803e45fc;

/* Local declarations keep imported functions visible within the TU. */
void FUN_80181c50(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 undefined4 param_9,undefined4 param_10,int param_11,undefined4 param_12,
                 undefined4 param_13,undefined4 param_14,undefined4 param_15,undefined4 param_16);

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80181C50
 * EN v1.0 Size: 2820b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: function-pointer stores need manual cleanup. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_80181c50(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 undefined4 param_9,undefined4 param_10,int param_11,undefined4 param_12,
                 undefined4 param_13,undefined4 param_14,undefined4 param_15,undefined4 param_16)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}
