/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/dll_131.c
 * Text span: 0x801678A4-0x80167D90
 * Imported Ghidra functions: 5
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 5
 */

#include "ghidra_import.h"
#include "main/dll/dll_131.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_800033a8();
extern uint FUN_80022264();
extern undefined4 FUN_8003042c();
extern undefined4 FUN_80035ff8();
extern undefined4 FUN_8003b9ec();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4* DAT_803dd70c;
extern undefined4* DAT_803dd738;
extern f64 DOUBLE_803e3ce8;
extern f64 DOUBLE_803e3d00;
extern f64 DOUBLE_803e3d08;
extern f32 FLOAT_803dc074;
extern f32 FLOAT_803e3c74;
extern f32 FLOAT_803e3c8c;
extern f32 FLOAT_803e3ce0;
extern f32 FLOAT_803e3cf8;

/* Local declarations keep imported functions visible within the TU. */
void FUN_801678a4(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 int param_9,int param_10,int param_11);
void FUN_801679fc(int param_1);
void FUN_80167a8c(int param_1,float *param_2,byte *param_3);
void FUN_80167b80(int param_1);
undefined4 FUN_80167c10(int param_1,int param_2);

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801678a4(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 int param_9,int param_10,int param_11)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801679fc(int param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_80167a8c(int param_1,float *param_2,byte *param_3)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_80167b80(int param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

undefined4 FUN_80167c10(int param_1,int param_2)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0;
}
