/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/dll_13C.c
 * Text span: 0x80169CF8-0x8016B550
 * Imported Ghidra functions: 17
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 17
 */

#include "ghidra_import.h"
#include "main/dll/dll_13C.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_8000b4f0();
extern undefined8 FUN_8000b7dc();
extern undefined4 FUN_8000b8a8();
extern undefined4 FUN_8000bb38();
extern undefined4 FUN_8000da78();
extern undefined4 FUN_8000e69c();
extern undefined4 FUN_8000faf8();
extern undefined4 FUN_8001d6e4();
extern undefined4 FUN_8001d7f4();
extern undefined4 FUN_8001dadc();
extern undefined4 FUN_8001db7c();
extern undefined4 FUN_8001dbb4();
extern undefined4 FUN_8001dbf0();
extern undefined4 FUN_8001dc18();
extern undefined4 FUN_8001dc30();
extern undefined4 FUN_8001dcfc();
extern undefined4 FUN_8001de4c();
extern undefined4 FUN_8001f448();
extern int* FUN_8001f58c();
extern int FUN_80021884();
extern uint FUN_80022264();
extern undefined4 FUN_8002ba34();
extern int FUN_8002ba84();
extern int FUN_8002bac4();
extern undefined2* FUN_8002becc();
extern undefined4 FUN_8002cc9c();
extern undefined4 FUN_8002e088();
extern uint FUN_8002e144();
extern undefined4 FUN_80035a6c();
extern undefined4 FUN_80035eec();
extern undefined4 FUN_80035ff8();
extern undefined8 FUN_80036018();
extern int FUN_80036974();
extern int FUN_80036f50();
extern undefined4 FUN_80038524();
extern undefined4 FUN_8003b9ec();
extern undefined4 FUN_80060630();
extern uint FUN_800803dc();
extern undefined4 FUN_80080404();
extern int FUN_80080434();
extern int FUN_80080490();
extern undefined4 FUN_80098da4();
extern undefined4 FUN_8009adfc();
extern undefined4 FUN_80169b80();
extern undefined4 FUN_80222ba0();
extern undefined4 FUN_80247e94();
extern undefined4 FUN_80247eb8();
extern undefined4 FUN_80247edc();
extern undefined4 FUN_80247ef8();
extern undefined4 FUN_80247f54();
extern int FUN_8028683c();
extern int FUN_80286840();
extern undefined4 FUN_80286888();
extern undefined4 FUN_8028688c();
extern double FUN_80293900();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4 DAT_803dc070;
extern undefined4* DAT_803dd6f8;
extern undefined4* DAT_803dd708;
extern f64 DOUBLE_803e3d80;
extern f64 DOUBLE_803e3d98;
extern f64 DOUBLE_803e3dc8;
extern f64 DOUBLE_803e3de8;
extern f64 DOUBLE_803e3e20;
extern f64 DOUBLE_803e3e28;
extern f32 FLOAT_803dc074;
extern f32 FLOAT_803dc9b0;
extern f32 FLOAT_803dc9b4;
extern f32 FLOAT_803e3d78;
extern f32 FLOAT_803e3d88;
extern f32 FLOAT_803e3d8c;
extern f32 FLOAT_803e3d90;
extern f32 FLOAT_803e3d94;
extern f32 FLOAT_803e3da0;
extern f32 FLOAT_803e3da4;
extern f32 FLOAT_803e3da8;
extern f32 FLOAT_803e3dac;
extern f32 FLOAT_803e3db0;
extern f32 FLOAT_803e3db4;
extern f32 FLOAT_803e3db8;
extern f32 FLOAT_803e3dbc;
extern f32 FLOAT_803e3dc0;
extern f32 FLOAT_803e3dc4;
extern f32 FLOAT_803e3dd0;
extern f32 FLOAT_803e3dd4;
extern f32 FLOAT_803e3dd8;
extern f32 FLOAT_803e3ddc;
extern f32 FLOAT_803e3de0;
extern f32 FLOAT_803e3df0;
extern f32 FLOAT_803e3df4;
extern f32 FLOAT_803e3df8;
extern f32 FLOAT_803e3dfc;
extern f32 FLOAT_803e3e00;
extern f32 FLOAT_803e3e04;
extern f32 FLOAT_803e3e08;
extern f32 FLOAT_803e3e0c;
extern f32 FLOAT_803e3e10;
extern f32 FLOAT_803e3e14;
extern f32 FLOAT_803e3e18;

/* Local declarations keep imported functions visible within the TU. */
void FUN_80169cf8(void);
void FUN_80169d94(undefined8 param_1,undefined8 param_2,undefined8 param_3,double param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 short *param_9);
void FUN_8016a170(uint param_1);
int FUN_8016a3a0(double param_1,double param_2,float *param_3,float *param_4,char param_5);
void FUN_8016a514(void);
void FUN_8016a54c(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 short *param_9);
void FUN_8016a814(uint param_1);
void FUN_8016a884(void);
void FUN_8016a8b4(int param_1);
void FUN_8016a8e4(int param_1);
void FUN_8016a950(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 uint param_9);
void FUN_8016ab0c(double param_1,double param_2,double param_3,undefined8 param_4,undefined8 param_5
                 ,undefined8 param_6,undefined8 param_7,undefined8 param_8,int param_9);
void FUN_8016aca4(int param_1);
void FUN_8016ad9c(int param_1);
void FUN_8016ae00(void);
void FUN_8016ae70(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 uint param_9);
void FUN_8016afbc(undefined8 param_1,undefined8 param_2,undefined8 param_3,double param_4,
                 double param_5,double param_6,undefined8 param_7,undefined8 param_8,ushort *param_9
                 );

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_80169cf8(void)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_80169d94(undefined8 param_1,undefined8 param_2,undefined8 param_3,double param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 short *param_9)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_8016a170(uint param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

int FUN_8016a3a0(double param_1,double param_2,float *param_3,float *param_4,char param_5)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0;
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_8016a514(void)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_8016a54c(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 short *param_9)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_8016a814(uint param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_8016a884(void)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_8016a8b4(int param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_8016a8e4(int param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_8016a950(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 uint param_9)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_8016ab0c(double param_1,double param_2,double param_3,undefined8 param_4,undefined8 param_5
                 ,undefined8 param_6,undefined8 param_7,undefined8 param_8,int param_9)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_8016aca4(int param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_8016ad9c(int param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_8016ae00(void)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_8016ae70(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 uint param_9)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_8016afbc(undefined8 param_1,undefined8 param_2,undefined8 param_3,double param_4,
                 double param_5,double param_6,undefined8 param_7,undefined8 param_8,ushort *param_9
                 )
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}
