/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/dll_141.c
 * Text span: 0x80173750-0x80174B14
 * Imported Ghidra functions: 8
 * Verbatim-safe functions: 5
 * Auto-stubbed functions: 3
 */

#include "ghidra_import.h"
#include "main/dll/dll_141.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_8000b7dc();
extern undefined4 FUN_8000b844();
extern undefined4 FUN_8000bb38();
extern uint FUN_80020078();
extern undefined4 FUN_800201ac();
extern double FUN_80021730();
extern uint FUN_80022264();
extern int FUN_8002b660();
extern undefined4 FUN_8002b830();
extern undefined4 FUN_8002b938();
extern undefined4 FUN_8002ba34();
extern undefined4 FUN_8002ba84();
extern int FUN_8002bac4();
extern undefined4 FUN_8002cc9c();
extern undefined4 FUN_80035ff8();
extern int* FUN_80037048();
extern int FUN_800375e4();
extern undefined4 FUN_800379bc();
extern undefined4 FUN_80037a5c();
extern undefined4 FUN_800395a4();
extern undefined4 FUN_8003b9ec();
extern undefined4 FUN_8007d858();
extern undefined4 FUN_80099c40();
extern undefined4 FUN_801750a8();
extern undefined4 FUN_80286840();
extern undefined4 FUN_8028688c();
extern double FUN_80293900();
extern undefined4 FUN_802945e0();
extern undefined4 FUN_80294964();
extern undefined4 FUN_80296078();
extern uint FUN_80296164();
extern uint FUN_8029698c();
extern undefined4 FUN_80297184();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4 DAT_80321908;
extern undefined4 DAT_803dc070;
extern undefined4* DAT_803dd6f8;
extern undefined4* DAT_803dd708;
extern undefined4* DAT_803dd728;
extern undefined4 DAT_803e4140;
extern undefined4 DAT_803e4144;
extern f64 DOUBLE_803e4198;
extern f64 DOUBLE_803e41b0;
extern f64 DOUBLE_803e41b8;
extern f64 DOUBLE_803e41c8;
extern f64 DOUBLE_803e41d0;
extern f32 FLOAT_803dc074;
extern f32 FLOAT_803e4148;
extern f32 FLOAT_803e414c;
extern f32 FLOAT_803e4150;
extern f32 FLOAT_803e4154;
extern f32 FLOAT_803e4158;
extern f32 FLOAT_803e415c;
extern f32 FLOAT_803e4160;
extern f32 FLOAT_803e4164;
extern f32 FLOAT_803e4168;
extern f32 FLOAT_803e416c;
extern f32 FLOAT_803e4170;
extern f32 FLOAT_803e4174;
extern f32 FLOAT_803e4178;
extern f32 FLOAT_803e417c;
extern f32 FLOAT_803e4188;
extern f32 FLOAT_803e418c;
extern f32 FLOAT_803e4190;
extern f32 FLOAT_803e4194;
extern f32 FLOAT_803e41ac;
extern f32 FLOAT_803e41c4;

/* Local declarations keep imported functions visible within the TU. */
void FUN_80173750(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8);
void FUN_80173f98(int param_1,int param_2);
void FUN_8017443c(int param_1);
void FUN_8017445c(int param_1);
void FUN_80174490(int param_1);
void FUN_80174864(int param_1,int param_2);
undefined4 FUN_801748e4(uint param_1,int param_2);
void FUN_80174a34(int param_1,int param_2);

/* Auto-stubbed for compileability: function-pointer stores need manual cleanup. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_80173750(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: address-of global symbols need manual typing, function-pointer stores need manual cleanup. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_80173f98(int param_1,int param_2)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

// Function: FUN_8017443c
// Entry: 8017443c
// Size: 32 bytes

void FUN_8017443c(int param_1)

{
  FUN_8002b830(param_1);
  return;
}

// Function: FUN_8017445c
// Entry: 8017445c
// Size: 48 bytes

void FUN_8017445c(int param_1)

{
  char in_r8;
  
  if (in_r8 != '\0') {
    FUN_8003b9ec(param_1);
  }
  return;
}

/* Auto-stubbed for compileability: function-pointer stores need manual cleanup. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_80174490(int param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

// Function: FUN_80174864
// Entry: 80174864
// Size: 120 bytes

void FUN_80174864(int param_1,int param_2)

{
  if (*(int *)(param_1 + 0xf4) == 0) {
    FUN_8002b938(param_1);
  }
  *(undefined4 *)(param_1 + 0xf4) = 1;
  if (*(short *)(param_2 + 0x20) < 0) {
    *(undefined4 *)(param_1 + 0xf8) = 0xffffffff;
  }
  else {
    *(int *)(param_1 + 0xf8) = (int)*(short *)(param_2 + 0x20);
  }
  *(ushort *)(param_1 + 0xb0) = *(ushort *)(param_1 + 0xb0) | 0x6000;
  return;
}

// Function: FUN_801748e4
// Entry: 801748e4
// Size: 336 bytes

undefined4 FUN_801748e4(uint param_1,int param_2)

{
  int iVar1;
  uint uVar2;
  int iVar3;
  
  iVar3 = *(int *)(param_1 + 0x4c);
  iVar1 = FUN_8002bac4();
  if (((*(ushort *)(param_2 + 0x100) & 0x80) == 0) && (uVar2 = FUN_80296164(iVar1,10), uVar2 == 0))
  {
    FUN_8000bb38(param_1,0x66);
    *(ushort *)(param_2 + 0x100) = *(ushort *)(param_2 + 0x100) | 2;
    if ((*(ushort *)(param_2 + 0x100) & 4) == 0) {
      FUN_801750a8();
    }
    if (*(float *)(param_1 + 0xc) <= FLOAT_803e41c4 + *(float *)(iVar3 + 8)) {
      FUN_800201ac((int)*(short *)(param_2 + 0xac),1);
      *(ushort *)(param_2 + 0x100) = *(ushort *)(param_2 + 0x100) | 0x80;
      *(float *)(param_1 + 0xc) = (float)((double)*(float *)(iVar3 + 8) - DOUBLE_803e41c8);
      *(undefined4 *)(param_1 + 0x10) = *(undefined4 *)(iVar3 + 0xc);
      *(float *)(param_1 + 0x14) = (float)(DOUBLE_803e41d0 + (double)*(float *)(iVar3 + 0x10));
      FUN_8000bb38(param_1,0x68);
    }
    uVar2 = FUN_80020078(0xa1a);
    if (uVar2 != 0) {
      *(undefined4 *)(param_1 + 0xc) = *(undefined4 *)(iVar3 + 8);
      *(undefined4 *)(param_1 + 0x10) = *(undefined4 *)(iVar3 + 0xc);
      *(undefined4 *)(param_1 + 0x14) = *(undefined4 *)(iVar3 + 0x10);
    }
  }
  else {
    FUN_8000b7dc(param_1,8);
  }
  return 0;
}

// Function: FUN_80174a34
// Entry: 80174a34
// Size: 224 bytes

void FUN_80174a34(int param_1,int param_2)

{
  uint uVar1;
  undefined4 *puVar2;
  int iVar3;
  int iVar4;
  
  iVar4 = *(int *)(param_1 + 0x4c);
  iVar3 = *(int *)(iVar4 + 0x14);
  if (iVar3 == 0x49b5d) {
    *(undefined *)(param_2 + 0x144) = 0xb;
    *(undefined *)(param_1 + 0xad) = 1;
  }
  else if (iVar3 < 0x49b5d) {
    if (iVar3 == 0x49b2c) {
      *(undefined *)(param_2 + 0x144) = 10;
    }
  }
  else if (iVar3 < 0x49b5f) {
    *(undefined *)(param_2 + 0x144) = 0xc;
    *(undefined *)(param_1 + 0xad) = 1;
  }
  uVar1 = FUN_80020078((int)*(short *)(iVar4 + 0x18));
  if (uVar1 != 0) {
    *(ushort *)(param_2 + 0x100) = *(ushort *)(param_2 + 0x100) | 0x80;
    puVar2 = (undefined4 *)FUN_800395a4(param_1,0);
    if (puVar2 != (undefined4 *)0x0) {
      *puVar2 = 0x100;
    }
  }
  return;
}
