/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/dll_14D.c
 * Text span: 0x8017F1EC-0x8017F548
 * Imported Ghidra functions: 3
 * Verbatim-safe functions: 2
 * Auto-stubbed functions: 1
 */

#include "ghidra_import.h"
#include "main/dll/dll_14D.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern uint FUN_80020078();
extern undefined4 FUN_800201ac();
extern uint FUN_80022264();
extern undefined4 FUN_80036f50();
extern undefined4 FUN_8003b9ec();
extern undefined4 FUN_80041110();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4* DAT_803dd6d4;
extern f32 FLOAT_803e44e4;

/* Local declarations keep imported functions visible within the TU. */
void FUN_8017f1ec(undefined2 *param_1);
void FUN_8017f4d8(int param_1);
void FUN_8017f508(int param_1);

/* Auto-stubbed for compileability: pointer-heavy local typing needs manual cleanup, function-pointer stores need manual cleanup. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_8017f1ec(undefined2 *param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

// Function: FUN_8017f4d8
// Entry: 8017f4d8
// Size: 48 bytes

void FUN_8017f4d8(int param_1)

{
  char in_r8;
  
  if (in_r8 != '\0') {
    FUN_8003b9ec(param_1);
  }
  return;
}

// Function: FUN_8017f508
// Entry: 8017f508
// Size: 64 bytes

void FUN_8017f508(int param_1)

{
  if (((*(uint *)(*(int *)(param_1 + 0x50) + 0x44) & 1) != 0) && (*(int *)(param_1 + 0x74) != 0)) {
    FUN_80041110();
  }
  return;
}
