/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/dll_9D.c
 * Text span: 0x80100BDC-0x80100C0C
 * Imported Ghidra functions: 1
 * Verbatim-safe functions: 1
 * Auto-stubbed functions: 0
 */

#include "ghidra_import.h"
#include "main/dll/dll_9D.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_8007d858();

/* Local declarations keep imported functions visible within the TU. */
undefined4 FUN_80100bdc(void);

// Function: FUN_80100bdc
// Entry: 80100bdc
// Size: 48 bytes

undefined4 FUN_80100bdc(void)

{
  FUN_8007d858();
  return 0xffffffff;
}
