/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/dll_82.c
 * Text span: 0x801009E4-0x80100A14
 * Imported Ghidra functions: 1
 * Verbatim-safe functions: 1
 * Auto-stubbed functions: 0
 */

#include "ghidra_import.h"
#include "main/dll/dll_82.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_8007d858();

/* Local declarations keep imported functions visible within the TU. */
undefined4 FUN_801009e4(void);

// Function: FUN_801009e4
// Entry: 801009e4
// Size: 48 bytes

undefined4 FUN_801009e4(void)

{
  FUN_8007d858();
  return 0xffffffff;
}
