/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/foodbag.c
 * Text span: 0x800F49C8-0x800FA86C
 * Imported Ghidra functions: 21
 * Verbatim-safe functions: 1
 * Auto-stubbed functions: 20
 */

#include "ghidra_import.h"
#include "main/dll/foodbag.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern uint FUN_80022264();
extern undefined8 FUN_8028681c();
extern undefined8 FUN_80286834();
extern undefined8 FUN_80286838();
extern undefined8 FUN_8028683c();
extern int FUN_80286840();
extern undefined4 FUN_80286868();
extern undefined4 FUN_80286880();
extern undefined4 FUN_80286884();
extern undefined4 FUN_80286888();
extern undefined4 FUN_8028688c();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4 DAT_80315a58;
extern undefined4 DAT_80315b2c;
extern undefined DAT_80315bbc;
extern undefined DAT_80315bcc;
extern undefined DAT_80315c08;
extern undefined4 DAT_80315c50;
extern undefined4 DAT_80315c52;
extern undefined4 DAT_80315c54;
extern undefined4 DAT_80315c56;
extern undefined4 DAT_80315c58;
extern undefined4 DAT_80315c5a;
extern undefined4 DAT_80315c5c;
extern undefined4 DAT_80315c80;
extern undefined4 DAT_80315d54;
extern undefined DAT_80315de4;
extern undefined DAT_80315df4;
extern undefined DAT_80315e04;
extern undefined DAT_80315e30;
extern undefined4 DAT_80315e78;
extern undefined4 DAT_80315e7a;
extern undefined4 DAT_80315e7c;
extern undefined4 DAT_80315e7e;
extern undefined4 DAT_80315e80;
extern undefined4 DAT_80315e82;
extern undefined4 DAT_80315e84;
extern undefined4 DAT_80315ea8;
extern undefined4 DAT_80315f04;
extern undefined DAT_80315f24;
extern undefined DAT_80315f38;
extern undefined4 DAT_80315f44;
extern undefined4 DAT_80315f46;
extern undefined4 DAT_80315f48;
extern undefined4 DAT_80315f4a;
extern undefined4 DAT_80315f4c;
extern undefined4 DAT_80315f4e;
extern undefined4 DAT_80315f50;
extern undefined4 DAT_80315f78;
extern undefined4 DAT_80315fd4;
extern undefined4 DAT_80316030;
extern undefined DAT_80316060;
extern undefined4 DAT_80316074;
extern undefined4 DAT_80316084;
extern undefined4 DAT_80316086;
extern undefined4 DAT_80316088;
extern undefined4 DAT_8031608a;
extern undefined4 DAT_8031608c;
extern undefined4 DAT_8031608e;
extern undefined4 DAT_80316090;
extern undefined4 DAT_803160b8;
extern undefined4 DAT_80316114;
extern undefined DAT_80316144;
extern undefined DAT_80316158;
extern undefined4 DAT_80316168;
extern undefined4 DAT_8031616a;
extern undefined4 DAT_8031616c;
extern undefined4 DAT_8031616e;
extern undefined4 DAT_80316170;
extern undefined4 DAT_80316172;
extern undefined4 DAT_80316174;
extern undefined4 DAT_80316198;
extern undefined4 DAT_8031626c;
extern undefined DAT_80316348;
extern undefined4 DAT_80316390;
extern undefined4 DAT_80316392;
extern undefined4 DAT_80316394;
extern undefined4 DAT_80316396;
extern undefined4 DAT_80316398;
extern undefined4 DAT_8031639a;
extern undefined4 DAT_8031639c;
extern undefined4 DAT_803163c0;
extern undefined4 DAT_80316494;
extern undefined DAT_80316524;
extern undefined DAT_80316534;
extern undefined DAT_80316570;
extern undefined4 DAT_803165b8;
extern undefined4 DAT_803165ba;
extern undefined4 DAT_803165bc;
extern undefined4 DAT_803165be;
extern undefined4 DAT_803165c0;
extern undefined4 DAT_803165c2;
extern undefined4 DAT_803165c4;
extern undefined4 DAT_803165e8;
extern undefined4 DAT_80316750;
extern undefined DAT_803167b0;
extern undefined DAT_803167c4;
extern undefined DAT_803167d8;
extern undefined DAT_803167ec;
extern undefined DAT_80316848;
extern undefined DAT_80316890;
extern undefined4 DAT_803168b4;
extern undefined4 DAT_803168b6;
extern undefined4 DAT_803168b8;
extern undefined4 DAT_803168ba;
extern undefined4 DAT_803168bc;
extern undefined4 DAT_803168be;
extern undefined4 DAT_803168c0;
extern undefined4 DAT_803168c4;
extern undefined4 DAT_803168f8;
extern undefined4 DAT_80316a60;
extern undefined DAT_80316ac0;
extern undefined DAT_80316ad4;
extern undefined DAT_80316ae8;
extern undefined DAT_80316afc;
extern undefined DAT_80316b58;
extern undefined DAT_80316ba0;
extern undefined4 DAT_80316bc4;
extern undefined4 DAT_80316bc6;
extern undefined4 DAT_80316bc8;
extern undefined4 DAT_80316bca;
extern undefined4 DAT_80316bcc;
extern undefined4 DAT_80316bce;
extern undefined4 DAT_80316bd0;
extern undefined4 DAT_80316bf8;
extern undefined4 DAT_80316c20;
extern undefined4 DAT_80316c2c;
extern undefined4 DAT_80316c2e;
extern undefined4 DAT_80316c30;
extern undefined4 DAT_80316c32;
extern undefined4 DAT_80316c34;
extern undefined4 DAT_80316c36;
extern undefined4 DAT_80316c38;
extern undefined4 DAT_80316c3c;
extern undefined4 DAT_80316c70;
extern undefined4 DAT_80316c72;
extern undefined4 DAT_80316c74;
extern undefined4 DAT_80316c76;
extern undefined4 DAT_80316c78;
extern undefined4 DAT_80316c7a;
extern undefined4 DAT_80316c7c;
extern undefined4 DAT_80316ca0;
extern undefined4 DAT_80316e08;
extern undefined DAT_80316e38;
extern undefined DAT_80316e4c;
extern undefined4 DAT_80316e60;
extern undefined4 DAT_80316e62;
extern undefined4 DAT_80316e64;
extern undefined4 DAT_80316e66;
extern undefined4 DAT_80316e68;
extern undefined4 DAT_80316e6a;
extern undefined4 DAT_80316e6c;
extern undefined4 DAT_80316e90;
extern undefined4 DAT_80316f8c;
extern undefined DAT_8031704c;
extern undefined4 DAT_80317080;
extern undefined4 DAT_80317082;
extern undefined4 DAT_80317084;
extern undefined4 DAT_80317086;
extern undefined4 DAT_80317088;
extern undefined4 DAT_8031708a;
extern undefined4 DAT_8031708c;
extern undefined4 DAT_803170b0;
extern undefined4 DAT_80317218;
extern undefined DAT_80317248;
extern undefined DAT_8031725c;
extern undefined4 DAT_80317270;
extern undefined4 DAT_80317272;
extern undefined4 DAT_80317274;
extern undefined4 DAT_80317276;
extern undefined4 DAT_80317278;
extern undefined4 DAT_8031727a;
extern undefined4 DAT_8031727c;
extern undefined4 DAT_803172a0;
extern undefined4 DAT_803172f0;
extern undefined DAT_80317338;
extern undefined4 DAT_80317348;
extern undefined4 DAT_8031734a;
extern undefined4 DAT_8031734c;
extern undefined4 DAT_8031734e;
extern undefined4 DAT_80317350;
extern undefined4 DAT_80317352;
extern undefined4 DAT_80317354;
extern undefined4 DAT_80317378;
extern undefined4 DAT_8031744c;
extern undefined DAT_80317528;
extern undefined4 DAT_80317570;
extern undefined4 DAT_80317572;
extern undefined4 DAT_80317574;
extern undefined4 DAT_80317576;
extern undefined4 DAT_80317578;
extern undefined4 DAT_8031757a;
extern undefined4 DAT_8031757c;
extern undefined4 DAT_803175a0;
extern undefined4 DAT_80317674;
extern undefined DAT_80317714;
extern undefined DAT_80317724;
extern undefined DAT_80317734;
extern undefined DAT_80317750;
extern undefined4 DAT_8031777c;
extern undefined4 DAT_8031777e;
extern undefined4 DAT_80317780;
extern undefined4 DAT_80317782;
extern undefined4 DAT_80317784;
extern undefined4 DAT_80317786;
extern undefined4 DAT_80317788;
extern undefined4 DAT_803177b0;
extern undefined4 DAT_8031780c;
extern undefined DAT_8031783c;
extern undefined4 DAT_80317860;
extern undefined4 DAT_80317862;
extern undefined4 DAT_80317864;
extern undefined4 DAT_80317866;
extern undefined4 DAT_80317868;
extern undefined4 DAT_8031786a;
extern undefined4 DAT_8031786c;
extern undefined4 DAT_80317890;
extern undefined4 DAT_803178b0;
extern undefined4 DAT_803178b2;
extern undefined4 DAT_803178b4;
extern undefined4 DAT_803178b6;
extern undefined4 DAT_803178b8;
extern undefined4 DAT_803178ba;
extern undefined4 DAT_803178bc;
extern undefined4 DAT_803178e0;
extern undefined4 DAT_80317994;
extern undefined DAT_80317a08;
extern undefined4 DAT_80317a40;
extern undefined4 DAT_80317a42;
extern undefined4 DAT_80317a44;
extern undefined4 DAT_80317a46;
extern undefined4 DAT_80317a48;
extern undefined4 DAT_80317a4a;
extern undefined4 DAT_80317a4c;
extern undefined4 DAT_80317a80;
extern undefined4 DAT_80317b34;
extern undefined DAT_80317b94;
extern undefined DAT_80317ba8;
extern undefined DAT_80317bd0;
extern undefined DAT_80317c08;
extern undefined4 DAT_80317c14;
extern undefined4 DAT_80317c16;
extern undefined4 DAT_80317c18;
extern undefined4 DAT_80317c1a;
extern undefined4 DAT_80317c1c;
extern undefined4 DAT_80317c1e;
extern undefined4 DAT_80317c20;
extern undefined DAT_803dc540;
extern undefined4 DAT_803dc548;
extern undefined DAT_803dc550;
extern undefined DAT_803dc554;
extern undefined DAT_803dc55c;
extern undefined DAT_803dc560;
extern undefined DAT_803dc568;
extern undefined4 DAT_803dc570;
extern undefined DAT_803dc578;
extern undefined DAT_803dc580;
extern undefined4* DAT_803dd6fc;
extern undefined4 DAT_803de128;
extern f64 DOUBLE_803e1c28;
extern f64 DOUBLE_803e1c60;
extern f64 DOUBLE_803e1d28;
extern f64 DOUBLE_803e1d58;
extern f64 DOUBLE_803e1db0;
extern f64 DOUBLE_803e1df0;
extern f32 FLOAT_803e1a08;
extern f32 FLOAT_803e1a0c;
extern f32 FLOAT_803e1a10;
extern f32 FLOAT_803e1a14;
extern f32 FLOAT_803e1a18;
extern f32 FLOAT_803e1a1c;
extern f32 FLOAT_803e1a20;
extern f32 FLOAT_803e1a24;
extern f32 FLOAT_803e1a28;
extern f32 FLOAT_803e1a2c;
extern f32 FLOAT_803e1a30;
extern f32 FLOAT_803e1a34;
extern f32 FLOAT_803e1a38;
extern f32 FLOAT_803e1a3c;
extern f32 FLOAT_803e1a40;
extern f32 FLOAT_803e1a44;
extern f32 FLOAT_803e1a48;
extern f32 FLOAT_803e1a4c;
extern f32 FLOAT_803e1a50;
extern f32 FLOAT_803e1a58;
extern f32 FLOAT_803e1a5c;
extern f32 FLOAT_803e1a60;
extern f32 FLOAT_803e1a64;
extern f32 FLOAT_803e1a68;
extern f32 FLOAT_803e1a6c;
extern f32 FLOAT_803e1a70;
extern f32 FLOAT_803e1a74;
extern f32 FLOAT_803e1a78;
extern f32 FLOAT_803e1a80;
extern f32 FLOAT_803e1a84;
extern f32 FLOAT_803e1a88;
extern f32 FLOAT_803e1a8c;
extern f32 FLOAT_803e1a90;
extern f32 FLOAT_803e1a94;
extern f32 FLOAT_803e1a98;
extern f32 FLOAT_803e1a9c;
extern f32 FLOAT_803e1aa0;
extern f32 FLOAT_803e1aa4;
extern f32 FLOAT_803e1aa8;
extern f32 FLOAT_803e1aac;
extern f32 FLOAT_803e1ab0;
extern f32 FLOAT_803e1ab4;
extern f32 FLOAT_803e1ab8;
extern f32 FLOAT_803e1abc;
extern f32 FLOAT_803e1ac0;
extern f32 FLOAT_803e1ac4;
extern f32 FLOAT_803e1ac8;
extern f32 FLOAT_803e1acc;
extern f32 FLOAT_803e1ad0;
extern f32 FLOAT_803e1ad4;
extern f32 FLOAT_803e1ad8;
extern f32 FLOAT_803e1adc;
extern f32 FLOAT_803e1ae0;
extern f32 FLOAT_803e1ae4;
extern f32 FLOAT_803e1ae8;
extern f32 FLOAT_803e1aec;
extern f32 FLOAT_803e1af0;
extern f32 FLOAT_803e1af4;
extern f32 FLOAT_803e1af8;
extern f32 FLOAT_803e1afc;
extern f32 FLOAT_803e1b00;
extern f32 FLOAT_803e1b04;
extern f32 FLOAT_803e1b08;
extern f32 FLOAT_803e1b0c;
extern f32 FLOAT_803e1b10;
extern f32 FLOAT_803e1b14;
extern f32 FLOAT_803e1b18;
extern f32 FLOAT_803e1b1c;
extern f32 FLOAT_803e1b20;
extern f32 FLOAT_803e1b24;
extern f32 FLOAT_803e1b28;
extern f32 FLOAT_803e1b30;
extern f32 FLOAT_803e1b34;
extern f32 FLOAT_803e1b38;
extern f32 FLOAT_803e1b3c;
extern f32 FLOAT_803e1b40;
extern f32 FLOAT_803e1b44;
extern f32 FLOAT_803e1b48;
extern f32 FLOAT_803e1b4c;
extern f32 FLOAT_803e1b50;
extern f32 FLOAT_803e1b58;
extern f32 FLOAT_803e1b5c;
extern f32 FLOAT_803e1b60;
extern f32 FLOAT_803e1b64;
extern f32 FLOAT_803e1b68;
extern f32 FLOAT_803e1b6c;
extern f32 FLOAT_803e1b70;
extern f32 FLOAT_803e1b74;
extern f32 FLOAT_803e1b78;
extern f32 FLOAT_803e1b7c;
extern f32 FLOAT_803e1b80;
extern f32 FLOAT_803e1b84;
extern f32 FLOAT_803e1b88;
extern f32 FLOAT_803e1b8c;
extern f32 FLOAT_803e1b90;
extern f32 FLOAT_803e1b94;
extern f32 FLOAT_803e1b98;
extern f32 FLOAT_803e1ba0;
extern f32 FLOAT_803e1ba4;
extern f32 FLOAT_803e1ba8;
extern f32 FLOAT_803e1bac;
extern f32 FLOAT_803e1bb0;
extern f32 FLOAT_803e1bb4;
extern f32 FLOAT_803e1bb8;
extern f32 FLOAT_803e1bbc;
extern f32 FLOAT_803e1bc0;
extern f32 FLOAT_803e1bc4;
extern f32 FLOAT_803e1bc8;
extern f32 FLOAT_803e1bcc;
extern f32 FLOAT_803e1bd0;
extern f32 FLOAT_803e1bd4;
extern f32 FLOAT_803e1bd8;
extern f32 FLOAT_803e1bdc;
extern f32 FLOAT_803e1be0;
extern f32 FLOAT_803e1be4;
extern f32 FLOAT_803e1be8;
extern f32 FLOAT_803e1bec;
extern f32 FLOAT_803e1bf0;
extern f32 FLOAT_803e1bf4;
extern f32 FLOAT_803e1bf8;
extern f32 FLOAT_803e1bfc;
extern f32 FLOAT_803e1c00;
extern f32 FLOAT_803e1c04;
extern f32 FLOAT_803e1c08;
extern f32 FLOAT_803e1c0c;
extern f32 FLOAT_803e1c10;
extern f32 FLOAT_803e1c14;
extern f32 FLOAT_803e1c18;
extern f32 FLOAT_803e1c1c;
extern f32 FLOAT_803e1c20;
extern f32 FLOAT_803e1c30;
extern f32 FLOAT_803e1c34;
extern f32 FLOAT_803e1c38;
extern f32 FLOAT_803e1c3c;
extern f32 FLOAT_803e1c40;
extern f32 FLOAT_803e1c44;
extern f32 FLOAT_803e1c48;
extern f32 FLOAT_803e1c4c;
extern f32 FLOAT_803e1c50;
extern f32 FLOAT_803e1c54;
extern f32 FLOAT_803e1c58;
extern f32 FLOAT_803e1c68;
extern f32 FLOAT_803e1c6c;
extern f32 FLOAT_803e1c70;
extern f32 FLOAT_803e1c74;
extern f32 FLOAT_803e1c78;
extern f32 FLOAT_803e1c7c;
extern f32 FLOAT_803e1c80;
extern f32 FLOAT_803e1c84;
extern f32 FLOAT_803e1c88;
extern f32 FLOAT_803e1c90;
extern f32 FLOAT_803e1c94;
extern f32 FLOAT_803e1c98;
extern f32 FLOAT_803e1c9c;
extern f32 FLOAT_803e1ca0;
extern f32 FLOAT_803e1ca4;
extern f32 FLOAT_803e1ca8;
extern f32 FLOAT_803e1cac;
extern f32 FLOAT_803e1cb0;
extern f32 FLOAT_803e1cb4;
extern f32 FLOAT_803e1cb8;
extern f32 FLOAT_803e1cbc;
extern f32 FLOAT_803e1cc0;
extern f32 FLOAT_803e1cc4;
extern f32 FLOAT_803e1cc8;
extern f32 FLOAT_803e1cd0;
extern f32 FLOAT_803e1cd4;
extern f32 FLOAT_803e1cd8;
extern f32 FLOAT_803e1ce0;
extern f32 FLOAT_803e1ce4;
extern f32 FLOAT_803e1ce8;
extern f32 FLOAT_803e1cec;
extern f32 FLOAT_803e1cf0;
extern f32 FLOAT_803e1cf4;
extern f32 FLOAT_803e1cf8;
extern f32 FLOAT_803e1cfc;
extern f32 FLOAT_803e1d00;
extern f32 FLOAT_803e1d04;
extern f32 FLOAT_803e1d08;
extern f32 FLOAT_803e1d0c;
extern f32 FLOAT_803e1d10;
extern f32 FLOAT_803e1d14;
extern f32 FLOAT_803e1d18;
extern f32 FLOAT_803e1d1c;
extern f32 FLOAT_803e1d20;
extern f32 FLOAT_803e1d24;
extern f32 FLOAT_803e1d30;
extern f32 FLOAT_803e1d34;
extern f32 FLOAT_803e1d38;
extern f32 FLOAT_803e1d3c;
extern f32 FLOAT_803e1d40;
extern f32 FLOAT_803e1d44;
extern f32 FLOAT_803e1d48;
extern f32 FLOAT_803e1d4c;
extern f32 FLOAT_803e1d50;
extern f32 FLOAT_803e1d54;
extern f32 FLOAT_803e1d60;
extern f32 FLOAT_803e1d64;
extern f32 FLOAT_803e1d68;
extern f32 FLOAT_803e1d6c;
extern f32 FLOAT_803e1d70;
extern f32 FLOAT_803e1d74;
extern f32 FLOAT_803e1d78;
extern f32 FLOAT_803e1d7c;
extern f32 FLOAT_803e1d80;
extern f32 FLOAT_803e1d84;
extern f32 FLOAT_803e1d88;
extern f32 FLOAT_803e1d8c;
extern f32 FLOAT_803e1d90;
extern f32 FLOAT_803e1d94;
extern f32 FLOAT_803e1d98;
extern f32 FLOAT_803e1d9c;
extern f32 FLOAT_803e1da0;
extern f32 FLOAT_803e1da4;
extern f32 FLOAT_803e1da8;
extern f32 FLOAT_803e1db8;
extern f32 FLOAT_803e1dbc;
extern f32 FLOAT_803e1dc0;
extern f32 FLOAT_803e1dc4;
extern f32 FLOAT_803e1dc8;
extern f32 FLOAT_803e1dcc;
extern f32 FLOAT_803e1dd0;
extern f32 FLOAT_803e1dd4;
extern f32 FLOAT_803e1dd8;
extern f32 FLOAT_803e1ddc;
extern f32 FLOAT_803e1de0;
extern f32 FLOAT_803e1de4;
extern f32 FLOAT_803e1de8;
extern f32 FLOAT_803e1dec;
extern f32 FLOAT_803e1df8;
extern f32 FLOAT_803e1dfc;
extern f32 FLOAT_803e1e00;
extern f32 FLOAT_803e1e04;
extern f32 FLOAT_803e1e08;
extern f32 FLOAT_803e1e0c;
extern f32 FLOAT_803e1e10;
extern f32 FLOAT_803e1e14;
extern f32 FLOAT_803e1e18;
extern f32 FLOAT_803e1e1c;
extern f32 FLOAT_803e1e20;
extern f32 FLOAT_803e1e24;
extern f32 FLOAT_803e1e28;
extern f32 FLOAT_803e1e2c;
extern f32 FLOAT_803e1e30;
extern f32 FLOAT_803e1e34;
extern f32 FLOAT_803e1e38;
extern f32 FLOAT_803e1e3c;
extern f32 FLOAT_803e1e40;
extern f32 FLOAT_803e1e44;
extern f32 FLOAT_803e1e48;
extern f32 FLOAT_803e1e4c;
extern f32 FLOAT_803e1e50;
extern f32 FLOAT_803e1e54;

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800F49C8
 * EN v1.0 Size: 1348b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800f49c8(undefined4 param_1,undefined4 param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800F4F0C
 * EN v1.0 Size: 820b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800f4f0c(undefined4 param_1,undefined4 param_2,int param_3,uint param_4,undefined4 param_5,
                 float *param_6)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800F5240
 * EN v1.0 Size: 828b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800f5240(int param_1,int param_2,int param_3,uint param_4,undefined4 param_5,float *param_6
                 )
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800F557C
 * EN v1.0 Size: 1272b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800f557c(int param_1,int param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800F5A74
 * EN v1.0 Size: 692b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800f5a74(int param_1,int param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800F5D28
 * EN v1.0 Size: 1732b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800f5d28(int param_1,int param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800F63EC
 * EN v1.0 Size: 996b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800f63ec(undefined4 param_1,undefined4 param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800F67D0
 * EN v1.0 Size: 1108b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800f67d0(undefined4 param_1,undefined4 param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800F6C24
 * EN v1.0 Size: 1108b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800f6c24(undefined4 param_1,undefined4 param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800F7078
 * EN v1.0 Size: 1624b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800f7078(undefined4 param_1,undefined4 param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800F76D0
 * EN v1.0 Size: 904b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800f76d0(undefined4 param_1,undefined4 param_2,int param_3,uint param_4)
{
  int iVar1;
  double in_f30;
  double dVar2;
  double in_f31;
  double dVar3;
  double in_ps30_1;
  double in_ps31_1;
  undefined8 uVar4;
  undefined4 *local_3b8;
  int local_3b4;
  float local_398;
  float local_394;
  float local_390;
  float local_38c;
  float local_388;
  float local_384;
  float local_380;
  undefined4 local_37c;
  undefined4 local_378;
  undefined2 local_374;
  undefined2 local_372;
  undefined2 local_370;
  undefined2 local_36e;
  undefined2 local_36c;
  undefined2 local_36a;
  undefined2 local_368;
  undefined2 local_366;
  uint local_364;
  undefined local_360;
  undefined local_35f;
  undefined local_35e;
  undefined local_35d;
  char local_35b;
  undefined4 local_358;
  float local_354;
  float local_350;
  float local_34c;
  undefined4 local_348;
  undefined2 local_344;
  undefined local_342;
  undefined4 local_340;
  float local_33c;
  float local_338;
  float local_334;
  undefined4 local_330;
  undefined2 local_32c;
  undefined local_32a;
  undefined4 local_328;
  float local_324;
  float local_320;
  float local_31c;
  undefined4 local_318;
  undefined2 local_314;
  undefined local_312;
  undefined4 local_310;
  float local_30c;
  float local_308;
  float local_304;
  undefined4 local_300;
  undefined2 local_2fc;
  undefined local_2fa;
  undefined4 local_2f8;
  float local_2f4;
  float local_2f0;
  float local_2ec;
  undefined4 local_2e8;
  undefined2 local_2e4;
  undefined local_2e2;
  undefined auStack_2e0 [648];
  undefined4 local_58;
  uint uStack_54;
  undefined4 local_50;
  uint uStack_4c;
  undefined4 local_48;
  uint uStack_44;
  float local_18;
  float fStack_14;
  float local_8;
  float fStack_4;
  
  local_8 = (float)in_f31;
  fStack_4 = (float)in_ps31_1;
  local_18 = (float)in_f30;
  fStack_14 = (float)in_ps30_1;
  uVar4 = FUN_80286840();
  local_3b4 = (int)((ulonglong)uVar4 >> 0x20);
  iVar1 = (int)uVar4;
  dVar3 = (double)FLOAT_803e1c30;
  dVar2 = (double)FLOAT_803e1c34;
  local_344 = 100;
  if (iVar1 == 0) {
    dVar3 = (double)FLOAT_803e1c38;
    dVar2 = (double)FLOAT_803e1c3c;
    local_344 = 0x410;
  }
  else if (iVar1 == 1) {
    dVar3 = (double)FLOAT_803e1c40;
    dVar2 = (double)FLOAT_803e1c44;
    local_344 = 0x410;
  }
  else if (iVar1 == 2) {
    dVar3 = (double)FLOAT_803e1c48;
    dVar2 = (double)FLOAT_803e1c4c;
    local_344 = 0x410;
  }
  else if (iVar1 == 3) {
    dVar3 = (double)FLOAT_803e1c48;
    dVar2 = (double)FLOAT_803e1c4c;
    local_344 = 0x410;
  }
  local_342 = 0;
  local_348 = 0;
  local_358 = 0x20000000;
  local_354 = FLOAT_803e1c50;
  local_350 = (float)dVar3;
  local_34c = (float)dVar2;
  local_32a = 1;
  local_32c = 0;
  local_330 = 0;
  local_340 = 0x400000;
  uStack_54 = FUN_80022264(0xffffff9c,100);
  uStack_54 = uStack_54 ^ 0x80000000;
  local_58 = 0x43300000;
  local_33c = (float)((double)CONCAT44(0x43300000,uStack_54) - DOUBLE_803e1c60);
  local_338 = FLOAT_803e1c54;
  uStack_4c = FUN_80022264(0xfffffb50,0xfffffce0);
  uStack_4c = uStack_4c ^ 0x80000000;
  local_50 = 0x43300000;
  local_334 = (float)((double)CONCAT44(0x43300000,uStack_4c) - DOUBLE_803e1c60);
  local_312 = 1;
  local_314 = 0;
  local_318 = 0;
  local_328 = 0x40000000;
  local_324 = local_33c;
  local_320 = FLOAT_803e1c54;
  local_31c = local_338;
  local_2fa = 1;
  local_2fc = 0x65;
  local_300 = 0;
  local_310 = 0x800000;
  local_30c = FLOAT_803e1c58;
  local_308 = FLOAT_803e1c58;
  local_304 = FLOAT_803e1c54;
  local_2e2 = 2;
  local_2e4 = 0;
  local_2e8 = 0;
  local_2f8 = 0x20000000;
  local_2f4 = FLOAT_803e1c50;
  local_2f0 = (float)dVar3;
  local_2ec = (float)dVar2;
  local_360 = 0;
  local_374 = (undefined2)uVar4;
  uStack_44 = FUN_80022264(0xffffff9c,100);
  uStack_44 = uStack_44 ^ 0x80000000;
  local_48 = 0x43300000;
  local_38c = (float)((double)CONCAT44(0x43300000,uStack_44) - DOUBLE_803e1c60);
  local_388 = FLOAT_803e1c54;
  local_384 = FLOAT_803e1c54;
  local_398 = FLOAT_803e1c54;
  local_394 = FLOAT_803e1c54;
  local_390 = FLOAT_803e1c54;
  local_380 = FLOAT_803e1c58;
  local_378 = 0;
  local_37c = 0;
  local_35f = 0;
  local_35e = 0;
  local_35d = 0;
  iVar1 = (int)(auStack_2e0 + -(int)&local_358) / 0x18 +
          ((int)(auStack_2e0 + -(int)&local_358) >> 0x1f);
  local_35b = (char)iVar1 - (char)(iVar1 >> 0x1f);
  local_372 = DAT_80316c70;
  local_370 = DAT_80316c72;
  local_36e = DAT_80316c74;
  local_36c = DAT_80316c76;
  local_36a = DAT_80316c78;
  local_368 = DAT_80316c7a;
  local_366 = DAT_80316c7c;
  local_364 = param_4 | 0x10400;
  if ((param_4 & 1) != 0) {
    if (local_3b4 == 0) {
      local_38c = local_38c + *(float *)(param_3 + 0xc);
      local_388 = FLOAT_803e1c54 + *(float *)(param_3 + 0x10);
      local_384 = FLOAT_803e1c54 + *(float *)(param_3 + 0x14);
    }
    else {
      local_38c = local_38c + *(float *)(local_3b4 + 0x18);
      local_388 = FLOAT_803e1c54 + *(float *)(local_3b4 + 0x1c);
      local_384 = FLOAT_803e1c54 + *(float *)(local_3b4 + 0x20);
    }
  }
  local_3b8 = &local_358;
  (**(code **)(*DAT_803dd6fc + 8))(&local_3b8,0,0,0,0,0,0,0);
  FUN_8028688c();
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800F7A58
 * EN v1.0 Size: 772b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800f7a58(int param_1,undefined2 param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800F7D5C
 * EN v1.0 Size: 720b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800f7d5c(int param_1,undefined2 param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800F802C
 * EN v1.0 Size: 772b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800f802c(int param_1,undefined2 param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800F8330
 * EN v1.0 Size: 444b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800f8330(int param_1,undefined2 param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800F84EC
 * EN v1.0 Size: 1432b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800f84ec(undefined4 param_1,undefined4 param_2,int param_3,uint param_4,undefined4 param_5,
                 float *param_6)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800F8A84
 * EN v1.0 Size: 1408b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800f8a84(int param_1,undefined2 param_2,short *param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800F9004
 * EN v1.0 Size: 2580b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800f9004(undefined4 param_1,undefined4 param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800F9A18
 * EN v1.0 Size: 1788b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800f9a18(undefined4 param_1,undefined4 param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800FA114
 * EN v1.0 Size: 756b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800fa114(int param_1,undefined2 param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800FA408
 * EN v1.0 Size: 1124b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800fa408(undefined4 param_1,undefined4 param_2,int param_3,uint param_4)
{
}
