/*
 * Auto-generated by tools/orig/source_materialize.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists to turn a retail-backed gap-window estimate into a concrete
 * source-file target that can be filled in during decomp work.
 *
 * Retail source name: gameplay.c
 * Output path: main/dll/gameplay.c
 * Confidence: medium
 * Reason: gap-window-brief
 *
 * Gap-window brief evidence:
 * - left anchor: dll/curves.c
 * - right anchor: dll/CAM/camcontrol.c
 * - current EN window: 0x800E56A4-0x800FD9E0
 * - debug split: 0x8012CF08-0x8012E6F8
 * - debug function count: 53
 * - confidence note: Resolved gap names give a usable local skeleton, but the interval is only partially constrained.
 *
 * Current EN functions in this estimated window:
 * - `fn_800E56A4@0x800E56A4-0x800E56B0` size=`0xC`
 * - `fn_800E56B0@0x800E56B0-0x800E56B4` size=`0x4`
 * - `fn_800E56B4@0x800E56B4-0x800E56B8` size=`0x4`
 * - `fn_800E56B8@0x800E56B8-0x800E5928` size=`0x270`
 * - `fn_800E5928@0x800E5928-0x800E5B80` size=`0x258`
 * - `fn_800E5B80@0x800E5B80-0x800E5F40` size=`0x3C0`
 * - `fn_800E5F40@0x800E5F40-0x800E60BC` size=`0x17C`
 * - `fn_800E60BC@0x800E60BC-0x800E61A0` size=`0xE4`
 * - `fn_800E61A0@0x800E61A0-0x800E6410` size=`0x270`
 * - `fn_800E6410@0x800E6410-0x800E6778` size=`0x368`
 * - `fn_800E6778@0x800E6778-0x800E6A30` size=`0x2B8`
 * - `fn_800E6A30@0x800E6A30-0x800E6BA0` size=`0x170`
 * - `fn_800E6BA0@0x800E6BA0-0x800E6D14` size=`0x174`
 * - `fn_800E6D14@0x800E6D14-0x800E6DBC` size=`0xA8`
 * - `fn_800E6DBC@0x800E6DBC-0x800E6F68` size=`0x1AC`
 * - `fn_800E6F68@0x800E6F68-0x800E7910` size=`0x9A8`
 */

/*
 * No function names were promoted here yet.
 * Start from the estimated window and nearby anchors above.
 */
