/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/gameplay.c
 * Text span: 0x800E8118-0x800F49C8
 * Imported Ghidra functions: 96
 * Verbatim-safe functions: 28
 * Auto-stubbed functions: 68
 */

#include "ghidra_import.h"
#include "main/dll/gameplay.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_800033a8();
extern undefined8 FUN_80003494();
extern undefined4 FUN_80009920();
extern undefined4 FUN_80009a28();
extern undefined4 FUN_80009a94();
extern undefined4 FUN_8000bb38();
extern int FUN_8001496c();
extern undefined4 FUN_80014974();
extern undefined4 FUN_80014a54();
extern uint FUN_80014b50();
extern undefined4 FUN_80014b68();
extern uint FUN_80014e9c();
extern undefined4 FUN_800154d0();
extern undefined4 FUN_800191fc();
extern undefined4 FUN_800195a8();
extern undefined4 FUN_800199a8();
extern undefined4 FUN_80019c28();
extern undefined4 FUN_8001bd8c();
extern undefined4 FUN_8001f7e0();
extern undefined8 FUN_8001f82c();
extern uint FUN_80020078();
extern undefined8 FUN_800201ac();
extern undefined4 FUN_800207d0();
extern undefined4 FUN_80020834();
extern undefined4 FUN_80021b8c();
extern uint FUN_80022264();
extern undefined8 FUN_800238c4();
extern undefined4 FUN_80023d8c();
extern int FUN_8002bac4();
extern undefined4 FUN_80035f84();
extern undefined4 FUN_80035f9c();
extern undefined4 FUN_8003709c();
extern undefined4 FUN_800372f8();
extern undefined4 FUN_800379bc();
extern undefined4 FUN_80043604();
extern uint FUN_8005383c();
extern undefined4 FUN_8005ced0();
extern int FUN_80065fcc();
extern undefined4 FUN_8007dca0();
extern int FUN_8007dd3c();
extern int FUN_8007ddd8();
extern undefined4 FUN_800d7d90();
extern undefined4 FUN_8011f678();
extern undefined4 FUN_80137c30();
extern undefined4 FUN_80244e58();
extern int FUN_80286718();
extern undefined8 FUN_80286810();
extern undefined8 FUN_80286820();
extern int FUN_80286824();
extern longlong FUN_80286830();
extern uint FUN_80286834();
extern undefined8 FUN_80286838();
extern uint FUN_8028683c();
extern undefined8 FUN_80286840();
extern undefined4 FUN_8028685c();
extern undefined4 FUN_8028686c();
extern undefined4 FUN_80286870();
extern undefined4 FUN_8028687c();
extern undefined4 FUN_80286880();
extern undefined4 FUN_80286884();
extern undefined4 FUN_80286888();
extern undefined4 FUN_8028688c();
extern uint FUN_80296350();
extern undefined4 FUN_80296ce0();
extern undefined4 FUN_80296e34();
extern int FUN_80297248();
extern undefined4 FUN_8029725c();
extern uint countLeadingZeros();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4 DAT_802c28f0;
extern undefined4 DAT_802c28f4;
extern undefined4 DAT_802c28f8;
extern short DAT_80312370;
extern short DAT_80312460;
extern undefined4 DAT_80312630;
extern short DAT_80312632;
extern undefined4 DAT_803128a8;
extern undefined4 DAT_80312954;
extern undefined DAT_80312984;
extern undefined DAT_803129a8;
extern undefined4 DAT_803129c8;
extern undefined4 DAT_803129ca;
extern undefined4 DAT_803129cc;
extern undefined4 DAT_803129ce;
extern undefined4 DAT_803129d0;
extern undefined4 DAT_803129d2;
extern undefined4 DAT_803129d4;
extern undefined DAT_80312a18;
extern undefined DAT_80312a40;
extern undefined4 DAT_80312a4c;
extern undefined4 DAT_80312a4e;
extern undefined4 DAT_80312a50;
extern undefined4 DAT_80312a52;
extern undefined4 DAT_80312a54;
extern undefined4 DAT_80312a56;
extern undefined4 DAT_80312a58;
extern undefined4 DAT_80312a80;
extern undefined4 DAT_80312aa8;
extern undefined4 DAT_80312ac0;
extern undefined4 DAT_80312ac2;
extern undefined4 DAT_80312ac4;
extern undefined4 DAT_80312ac6;
extern undefined4 DAT_80312ac8;
extern undefined4 DAT_80312aca;
extern undefined4 DAT_80312acc;
extern undefined4 DAT_80312b70;
extern undefined4 DAT_80312c44;
extern undefined DAT_80312ce4;
extern undefined DAT_80312d20;
extern undefined4 DAT_80312d4c;
extern undefined4 DAT_80312d4e;
extern undefined4 DAT_80312d50;
extern undefined4 DAT_80312d52;
extern undefined4 DAT_80312d54;
extern undefined4 DAT_80312d56;
extern undefined4 DAT_80312d58;
extern undefined4 DAT_80312d80;
extern undefined4 DAT_80312e54;
extern undefined DAT_80312ef4;
extern undefined DAT_80312f30;
extern undefined4 DAT_80312f5c;
extern undefined4 DAT_80312f5e;
extern undefined4 DAT_80312f60;
extern undefined4 DAT_80312f62;
extern undefined4 DAT_80312f64;
extern undefined4 DAT_80312f66;
extern undefined4 DAT_80312f68;
extern undefined4 DAT_80312f90;
extern undefined4 DAT_803130f8;
extern undefined4 DAT_80313158;
extern undefined4 DAT_8031316c;
extern undefined4 DAT_80313180;
extern undefined4 DAT_80313194;
extern undefined4 DAT_803131f0;
extern undefined4 DAT_80313238;
extern undefined4 DAT_8031325c;
extern undefined4 DAT_803132a0;
extern undefined4 DAT_8031332c;
extern undefined DAT_80313374;
extern undefined DAT_80313390;
extern undefined DAT_803133a0;
extern undefined4 DAT_803133b0;
extern undefined4 DAT_803133b2;
extern undefined4 DAT_803133b4;
extern undefined4 DAT_803133b6;
extern undefined4 DAT_803133b8;
extern undefined4 DAT_803133ba;
extern undefined4 DAT_803133bc;
extern undefined4 DAT_803133e0;
extern undefined4 DAT_8031346c;
extern undefined DAT_803134d4;
extern undefined DAT_803134f0;
extern undefined4 DAT_80313504;
extern undefined4 DAT_80313506;
extern undefined4 DAT_80313508;
extern undefined4 DAT_8031350a;
extern undefined4 DAT_8031350c;
extern undefined4 DAT_8031350e;
extern undefined4 DAT_80313510;
extern undefined4 DAT_80313538;
extern undefined4 DAT_80313594;
extern undefined DAT_803135c4;
extern undefined DAT_803135d8;
extern undefined4 DAT_803135e8;
extern undefined4 DAT_803135ea;
extern undefined4 DAT_803135ec;
extern undefined4 DAT_803135ee;
extern undefined4 DAT_803135f0;
extern undefined4 DAT_803135f2;
extern undefined4 DAT_803135f4;
extern undefined4 DAT_80313618;
extern undefined4 DAT_803136ec;
extern undefined DAT_8031378c;
extern undefined DAT_8031379c;
extern undefined DAT_803137ac;
extern undefined DAT_803137c8;
extern undefined4 DAT_803137f4;
extern undefined4 DAT_803137f6;
extern undefined4 DAT_803137f8;
extern undefined4 DAT_803137fa;
extern undefined4 DAT_803137fc;
extern undefined4 DAT_803137fe;
extern undefined4 DAT_80313800;
extern short DAT_80313828;
extern undefined4 DAT_803138b4;
extern undefined DAT_803138fc;
extern undefined DAT_80313918;
extern undefined DAT_80313928;
extern undefined4 DAT_80313938;
extern undefined4 DAT_8031393a;
extern undefined4 DAT_8031393c;
extern undefined4 DAT_8031393e;
extern undefined4 DAT_80313940;
extern undefined4 DAT_80313942;
extern undefined4 DAT_80313944;
extern undefined4 DAT_80313968;
extern undefined4 DAT_803139f4;
extern undefined DAT_80313a3c;
extern undefined DAT_80313a58;
extern undefined DAT_80313a68;
extern undefined4 DAT_80313a78;
extern undefined4 DAT_80313a7a;
extern undefined4 DAT_80313a7c;
extern undefined4 DAT_80313a7e;
extern undefined4 DAT_80313a80;
extern undefined4 DAT_80313a82;
extern undefined4 DAT_80313a84;
extern undefined4 DAT_80313aa8;
extern undefined4 DAT_80313b34;
extern undefined DAT_80313b7c;
extern undefined DAT_80313b98;
extern undefined DAT_80313ba8;
extern undefined4 DAT_80313bb8;
extern undefined4 DAT_80313bba;
extern undefined4 DAT_80313bbc;
extern undefined4 DAT_80313bbe;
extern undefined4 DAT_80313bc0;
extern undefined4 DAT_80313bc2;
extern undefined4 DAT_80313bc4;
extern undefined4 DAT_80313be8;
extern undefined4 DAT_80313cbc;
extern undefined DAT_80313d5c;
extern undefined DAT_80313d6c;
extern undefined DAT_80313d7c;
extern undefined DAT_80313d98;
extern undefined4 DAT_80313dc4;
extern undefined4 DAT_80313dc6;
extern undefined4 DAT_80313dc8;
extern undefined4 DAT_80313dca;
extern undefined4 DAT_80313dcc;
extern undefined4 DAT_80313dce;
extern undefined4 DAT_80313dd0;
extern undefined4 DAT_80313df8;
extern undefined4 DAT_80313ecc;
extern undefined DAT_80313f6c;
extern undefined DAT_80313fa8;
extern undefined4 DAT_80313fd4;
extern undefined4 DAT_80313fd6;
extern undefined4 DAT_80313fd8;
extern undefined4 DAT_80313fda;
extern undefined4 DAT_80313fdc;
extern undefined4 DAT_80313fde;
extern undefined4 DAT_80313fe0;
extern undefined4 DAT_80314008;
extern undefined4 DAT_803140dc;
extern undefined DAT_8031417c;
extern undefined DAT_803141b8;
extern undefined4 DAT_803141e4;
extern undefined4 DAT_803141e6;
extern undefined4 DAT_803141e8;
extern undefined4 DAT_803141ea;
extern undefined4 DAT_803141ec;
extern undefined4 DAT_803141ee;
extern undefined4 DAT_803141f0;
extern undefined4 DAT_80314218;
extern undefined4 DAT_803142ec;
extern undefined DAT_8031437c;
extern undefined DAT_8031438c;
extern undefined DAT_803143c8;
extern undefined4 DAT_803143f4;
extern undefined4 DAT_803143f6;
extern undefined4 DAT_803143f8;
extern undefined4 DAT_803143fa;
extern undefined4 DAT_803143fc;
extern undefined4 DAT_803143fe;
extern undefined4 DAT_80314400;
extern undefined4 DAT_80314448;
extern undefined4 DAT_80314498;
extern undefined DAT_803144b0;
extern undefined4 DAT_803144c0;
extern undefined4 DAT_803144c2;
extern undefined4 DAT_803144c4;
extern undefined4 DAT_803144c6;
extern undefined4 DAT_803144c8;
extern undefined4 DAT_803144ca;
extern undefined4 DAT_803144cc;
extern undefined4 DAT_803144f0;
extern undefined4 DAT_803145a4;
extern undefined DAT_80314604;
extern undefined DAT_80314618;
extern undefined4 DAT_80314650;
extern undefined4 DAT_80314652;
extern undefined4 DAT_80314654;
extern undefined4 DAT_80314656;
extern undefined4 DAT_80314658;
extern undefined4 DAT_8031465a;
extern undefined4 DAT_8031465c;
extern undefined4 DAT_80314660;
extern undefined4 DAT_80314661;
extern undefined4 DAT_80314662;
extern undefined4 DAT_80314690;
extern undefined4 DAT_803146c4;
extern undefined DAT_803146e4;
extern undefined4 DAT_803146f0;
extern undefined4 DAT_803146f2;
extern undefined4 DAT_803146f4;
extern undefined4 DAT_803146f6;
extern undefined4 DAT_803146f8;
extern undefined4 DAT_803146fa;
extern undefined4 DAT_803146fc;
extern undefined4 DAT_80314740;
extern undefined4 DAT_803147cc;
extern undefined DAT_80314814;
extern undefined DAT_80314830;
extern undefined DAT_80314840;
extern undefined4 DAT_80314850;
extern undefined4 DAT_80314852;
extern undefined4 DAT_80314854;
extern undefined4 DAT_80314856;
extern undefined4 DAT_80314858;
extern undefined4 DAT_8031485a;
extern undefined4 DAT_8031485c;
extern undefined4 DAT_80314880;
extern undefined4 DAT_803148b4;
extern undefined DAT_803148d4;
extern undefined4 DAT_803148e0;
extern undefined4 DAT_803148e2;
extern undefined4 DAT_803148e4;
extern undefined4 DAT_803148e6;
extern undefined4 DAT_803148e8;
extern undefined4 DAT_803148ea;
extern undefined4 DAT_803148ec;
extern undefined4 DAT_80314910;
extern undefined4 DAT_80314a00;
extern undefined DAT_80314a60;
extern undefined DAT_80314a90;
extern undefined DAT_80314aa0;
extern undefined4 DAT_80314ab8;
extern undefined4 DAT_80314aba;
extern undefined4 DAT_80314abc;
extern undefined4 DAT_80314abe;
extern undefined4 DAT_80314ac0;
extern undefined4 DAT_80314ac2;
extern undefined4 DAT_80314ac4;
extern undefined4 DAT_80314ae8;
extern undefined4 DAT_80314b9c;
extern undefined DAT_80314bfc;
extern undefined DAT_80314c10;
extern undefined DAT_80314c38;
extern undefined DAT_80314c70;
extern undefined4 DAT_80314c7c;
extern undefined4 DAT_80314c7e;
extern undefined4 DAT_80314c80;
extern undefined4 DAT_80314c82;
extern undefined4 DAT_80314c84;
extern undefined4 DAT_80314c86;
extern undefined4 DAT_80314c88;
extern undefined4 DAT_80314cb0;
extern undefined4 DAT_80314d84;
extern undefined DAT_80314e60;
extern undefined DAT_80314e8c;
extern undefined4 DAT_80314ea8;
extern undefined4 DAT_80314eaa;
extern undefined4 DAT_80314eac;
extern undefined4 DAT_80314eae;
extern undefined4 DAT_80314eb0;
extern undefined4 DAT_80314eb2;
extern undefined4 DAT_80314eb4;
extern undefined4 DAT_80314ed8;
extern undefined4 DAT_80314fac;
extern undefined DAT_80315088;
extern undefined DAT_803150b4;
extern undefined4 DAT_803150d0;
extern undefined4 DAT_803150d2;
extern undefined4 DAT_803150d4;
extern undefined4 DAT_803150d6;
extern undefined4 DAT_803150d8;
extern undefined4 DAT_803150da;
extern undefined4 DAT_803150dc;
extern undefined4 DAT_80315100;
extern undefined4 DAT_803151d4;
extern undefined DAT_803152b0;
extern undefined DAT_803152dc;
extern undefined4 DAT_803152f8;
extern undefined4 DAT_803152fa;
extern undefined4 DAT_803152fc;
extern undefined4 DAT_803152fe;
extern undefined4 DAT_80315300;
extern undefined4 DAT_80315302;
extern undefined4 DAT_80315304;
extern undefined4 DAT_80315328;
extern undefined4 DAT_803153fc;
extern undefined DAT_8031548c;
extern undefined DAT_8031549c;
extern undefined DAT_803154d8;
extern undefined DAT_80315520;
extern undefined4 DAT_8031553c;
extern undefined4 DAT_8031553e;
extern undefined4 DAT_80315540;
extern undefined4 DAT_80315542;
extern undefined4 DAT_80315544;
extern undefined4 DAT_80315546;
extern undefined4 DAT_80315548;
extern undefined4 DAT_80315570;
extern undefined4 DAT_80315572;
extern undefined4 DAT_80315574;
extern undefined4 DAT_80315576;
extern undefined4 DAT_80315578;
extern undefined4 DAT_8031557a;
extern undefined4 DAT_8031557c;
extern undefined4 DAT_803155a0;
extern undefined4 DAT_803155a2;
extern undefined4 DAT_803155a4;
extern undefined4 DAT_803155a6;
extern undefined4 DAT_803155a8;
extern undefined4 DAT_803155aa;
extern undefined4 DAT_803155ac;
extern undefined4 DAT_803155d0;
extern undefined4 DAT_803155d2;
extern undefined4 DAT_803155d4;
extern undefined4 DAT_803155d6;
extern undefined4 DAT_803155d8;
extern undefined4 DAT_803155da;
extern undefined4 DAT_803155dc;
extern undefined4 DAT_80315600;
extern undefined4 DAT_8031568c;
extern undefined DAT_803156d4;
extern undefined DAT_803156f0;
extern undefined DAT_80315700;
extern undefined4 DAT_80315710;
extern undefined4 DAT_80315712;
extern undefined4 DAT_80315714;
extern undefined4 DAT_80315716;
extern undefined4 DAT_80315718;
extern undefined4 DAT_8031571a;
extern undefined4 DAT_8031571c;
extern undefined4 DAT_80315740;
extern undefined4 DAT_8031579c;
extern undefined DAT_803157cc;
extern undefined DAT_803157e0;
extern undefined4 DAT_803157f0;
extern undefined4 DAT_803157f2;
extern undefined4 DAT_803157f4;
extern undefined4 DAT_803157f6;
extern undefined4 DAT_803157f8;
extern undefined4 DAT_803157fa;
extern undefined4 DAT_803157fc;
extern undefined4 DAT_80315820;
extern undefined4 DAT_8031587c;
extern undefined DAT_803158ac;
extern undefined DAT_803158c0;
extern undefined4 DAT_803158d0;
extern undefined4 DAT_803158d2;
extern undefined4 DAT_803158d4;
extern undefined4 DAT_803158d6;
extern undefined4 DAT_803158d8;
extern undefined4 DAT_803158da;
extern undefined4 DAT_803158dc;
extern undefined4 DAT_80315900;
extern undefined4 DAT_8031598c;
extern undefined DAT_803159f4;
extern undefined4 DAT_80315a10;
extern undefined4 DAT_80315a24;
extern undefined4 DAT_80315a26;
extern undefined4 DAT_80315a28;
extern undefined4 DAT_80315a2a;
extern undefined4 DAT_80315a2c;
extern undefined4 DAT_80315a2e;
extern undefined4 DAT_80315a30;
extern char DAT_803a3be0;
extern undefined4 DAT_803a3be1;
extern undefined4 DAT_803a3be2;
extern undefined4 DAT_803a3be3;
extern undefined4 DAT_803a3be6;
extern undefined4 DAT_803a3be9;
extern undefined4 DAT_803a3bec;
extern undefined4 DAT_803a3bef;
extern undefined4 DAT_803a3bf2;
extern undefined4 DAT_803a3bf5;
extern undefined4 DAT_803a3bf8;
extern undefined4 DAT_803a3bfb;
extern undefined4 DAT_803a3bfe;
extern undefined4 DAT_803a3c01;
extern undefined4 DAT_803a3c04;
extern undefined4 DAT_803a3c07;
extern undefined4 DAT_803a3c0a;
extern undefined4 DAT_803a3c0d;
extern undefined4 DAT_803a3c10;
extern undefined4 DAT_803a3c13;
extern undefined4 DAT_803a3c16;
extern undefined4 DAT_803a3c19;
extern uint DAT_803a3c1c;
extern undefined4 DAT_803a3dac;
extern undefined1 DAT_803a3e24;
extern undefined4 DAT_803a3e26;
extern undefined4 DAT_803a3e27;
extern undefined4 DAT_803a3e28;
extern undefined4 DAT_803a3e2a;
extern undefined4 DAT_803a3e2c;
extern undefined4 DAT_803a3e2d;
extern undefined4 DAT_803a3e2e;
extern undefined4 DAT_803a3e2f;
extern undefined4 DAT_803a3e30;
extern undefined4 DAT_803a3e34;
extern undefined4 DAT_803a3e38;
extern undefined4 DAT_803a3e40;
extern undefined DAT_803a3e44;
extern undefined1 DAT_803a3f08;
extern undefined4 DAT_803a3f09;
extern undefined4 DAT_803a3f0c;
extern undefined4 DAT_803a3f0e;
extern undefined4 DAT_803a3f12;
extern undefined4 DAT_803a3f14;
extern undefined4 DAT_803a3f15;
extern undefined4 DAT_803a3f18;
extern undefined4 DAT_803a3f1a;
extern undefined4 DAT_803a3f1e;
extern undefined4 DAT_803a3f21;
extern char DAT_803a3f24;
extern undefined4 DAT_803a3f25;
extern undefined4 DAT_803a3f26;
extern undefined4 DAT_803a3f27;
extern undefined4 DAT_803a3f28;
extern undefined4 DAT_803a3f29;
extern undefined4 DAT_803a3f2a;
extern undefined4 DAT_803a3f2b;
extern undefined4 DAT_803a4070;
extern undefined4 DAT_803a4074;
extern undefined4 DAT_803a4078;
extern undefined4 DAT_803a407c;
extern undefined4 DAT_803a4460;
extern undefined4 DAT_803a4465;
extern undefined4 DAT_803a4468;
extern undefined4 DAT_803a458c;
extern undefined4 DAT_803a4590;
extern undefined4 DAT_803a4594;
extern undefined4 DAT_803a4598;
extern undefined4 DAT_803a4599;
extern undefined4 DAT_803a459a;
extern undefined4 DAT_803a45aa;
extern undefined4 DAT_803a45ac;
extern undefined4 DAT_803a45b0;
extern undefined4 DAT_803a45b4;
extern undefined4 DAT_803a45b6;
extern undefined4 DAT_803a45ba;
extern undefined4 DAT_803a45bc;
extern undefined4 DAT_803a45be;
extern undefined4 DAT_803a45c0;
extern undefined4 DAT_803a45c2;
extern undefined4 DAT_803a45f0;
extern undefined4 DAT_803a45f1;
extern undefined4 DAT_803a45f2;
extern undefined4 DAT_803a45f3;
extern undefined4 DAT_803a4e48;
extern undefined4 DAT_803a4e78;
extern undefined4 DAT_803c4060;
extern undefined4 DAT_803dc4f0;
extern undefined DAT_803dc4f8;
extern undefined DAT_803dc500;
extern undefined DAT_803dc508;
extern undefined DAT_803dc510;
extern undefined DAT_803dc514;
extern undefined DAT_803dc520;
extern undefined DAT_803dc528;
extern undefined DAT_803dc530;
extern undefined4 DAT_803dc538;
extern undefined4* DAT_803dd6d0;
extern undefined4* DAT_803dd6e8;
extern undefined4* DAT_803dd6fc;
extern undefined4* DAT_803dd708;
extern undefined4* DAT_803dd72c;
extern undefined4 DAT_803de100;
extern undefined4 DAT_803de104;
extern undefined4 DAT_803de10c;
extern undefined4* DAT_803de110;
extern undefined4 DAT_803de114;
extern undefined4 DAT_803de118;
extern undefined4 DAT_803de11c;
extern undefined4 DAT_803de120;
extern undefined4 DAT_803de124;
extern undefined4 DAT_803e13b0;
extern f64 DOUBLE_803e13a8;
extern f64 DOUBLE_803e13d8;
extern f64 DOUBLE_803e14d0;
extern f64 DOUBLE_803e1510;
extern f64 DOUBLE_803e1540;
extern f64 DOUBLE_803e1580;
extern f64 DOUBLE_803e15a8;
extern f64 DOUBLE_803e15e0;
extern f64 DOUBLE_803e1608;
extern f64 DOUBLE_803e16a0;
extern f64 DOUBLE_803e16d0;
extern f64 DOUBLE_803e1830;
extern f64 DOUBLE_803e1928;
extern f64 DOUBLE_803e1980;
extern f64 DOUBLE_803e19b0;
extern f64 DOUBLE_803e1a00;
extern f32 FLOAT_803dc074;
extern f32 FLOAT_803e1348;
extern f32 FLOAT_803e134c;
extern f32 FLOAT_803e1358;
extern f32 FLOAT_803e135c;
extern f32 FLOAT_803e1360;
extern f32 FLOAT_803e1364;
extern f32 FLOAT_803e1368;
extern f32 FLOAT_803e1370;
extern f32 FLOAT_803e1374;
extern f32 FLOAT_803e1378;
extern f32 FLOAT_803e137c;
extern f32 FLOAT_803e1380;
extern f32 FLOAT_803e1384;
extern f32 FLOAT_803e1388;
extern f32 FLOAT_803e138c;
extern f32 FLOAT_803e1390;
extern f32 FLOAT_803e1394;
extern f32 FLOAT_803e1398;
extern f32 FLOAT_803e139c;
extern f32 FLOAT_803e13a0;
extern f32 FLOAT_803e13b4;
extern f32 FLOAT_803e13b8;
extern f32 FLOAT_803e13bc;
extern f32 FLOAT_803e13c0;
extern f32 FLOAT_803e13c4;
extern f32 FLOAT_803e13c8;
extern f32 FLOAT_803e13cc;
extern f32 FLOAT_803e13d0;
extern f32 FLOAT_803e13d4;
extern f32 FLOAT_803e13e0;
extern f32 FLOAT_803e13e4;
extern f32 FLOAT_803e13e8;
extern f32 FLOAT_803e13ec;
extern f32 FLOAT_803e13f0;
extern f32 FLOAT_803e13f4;
extern f32 FLOAT_803e13f8;
extern f32 FLOAT_803e13fc;
extern f32 FLOAT_803e1400;
extern f32 FLOAT_803e1404;
extern f32 FLOAT_803e1408;
extern f32 FLOAT_803e140c;
extern f32 FLOAT_803e1410;
extern f32 FLOAT_803e1414;
extern f32 FLOAT_803e1418;
extern f32 FLOAT_803e141c;
extern f32 FLOAT_803e1420;
extern f32 FLOAT_803e1424;
extern f32 FLOAT_803e1428;
extern f32 FLOAT_803e142c;
extern f32 FLOAT_803e1430;
extern f32 FLOAT_803e1434;
extern f32 FLOAT_803e1438;
extern f32 FLOAT_803e143c;
extern f32 FLOAT_803e1440;
extern f32 FLOAT_803e1444;
extern f32 FLOAT_803e1448;
extern f32 FLOAT_803e144c;
extern f32 FLOAT_803e1450;
extern f32 FLOAT_803e1454;
extern f32 FLOAT_803e1458;
extern f32 FLOAT_803e145c;
extern f32 FLOAT_803e1460;
extern f32 FLOAT_803e1464;
extern f32 FLOAT_803e1468;
extern f32 FLOAT_803e146c;
extern f32 FLOAT_803e1470;
extern f32 FLOAT_803e1474;
extern f32 FLOAT_803e1478;
extern f32 FLOAT_803e1480;
extern f32 FLOAT_803e1484;
extern f32 FLOAT_803e1488;
extern f32 FLOAT_803e148c;
extern f32 FLOAT_803e1490;
extern f32 FLOAT_803e1494;
extern f32 FLOAT_803e1498;
extern f32 FLOAT_803e149c;
extern f32 FLOAT_803e14a0;
extern f32 FLOAT_803e14a4;
extern f32 FLOAT_803e14a8;
extern f32 FLOAT_803e14b0;
extern f32 FLOAT_803e14b4;
extern f32 FLOAT_803e14b8;
extern f32 FLOAT_803e14bc;
extern f32 FLOAT_803e14c0;
extern f32 FLOAT_803e14c4;
extern f32 FLOAT_803e14c8;
extern f32 FLOAT_803e14cc;
extern f32 FLOAT_803e14d8;
extern f32 FLOAT_803e14dc;
extern f32 FLOAT_803e14e0;
extern f32 FLOAT_803e14e4;
extern f32 FLOAT_803e14e8;
extern f32 FLOAT_803e14ec;
extern f32 FLOAT_803e14f0;
extern f32 FLOAT_803e14f4;
extern f32 FLOAT_803e14f8;
extern f32 FLOAT_803e14fc;
extern f32 FLOAT_803e1500;
extern f32 FLOAT_803e1504;
extern f32 FLOAT_803e1508;
extern f32 FLOAT_803e150c;
extern f32 FLOAT_803e1518;
extern f32 FLOAT_803e151c;
extern f32 FLOAT_803e1520;
extern f32 FLOAT_803e1524;
extern f32 FLOAT_803e1528;
extern f32 FLOAT_803e152c;
extern f32 FLOAT_803e1530;
extern f32 FLOAT_803e1534;
extern f32 FLOAT_803e1538;
extern f32 FLOAT_803e1548;
extern f32 FLOAT_803e154c;
extern f32 FLOAT_803e1550;
extern f32 FLOAT_803e1554;
extern f32 FLOAT_803e1558;
extern f32 FLOAT_803e155c;
extern f32 FLOAT_803e1560;
extern f32 FLOAT_803e1564;
extern f32 FLOAT_803e1568;
extern f32 FLOAT_803e156c;
extern f32 FLOAT_803e1570;
extern f32 FLOAT_803e1574;
extern f32 FLOAT_803e1578;
extern f32 FLOAT_803e157c;
extern f32 FLOAT_803e1588;
extern f32 FLOAT_803e158c;
extern f32 FLOAT_803e1590;
extern f32 FLOAT_803e1594;
extern f32 FLOAT_803e1598;
extern f32 FLOAT_803e159c;
extern f32 FLOAT_803e15a0;
extern f32 FLOAT_803e15a4;
extern f32 FLOAT_803e15b0;
extern f32 FLOAT_803e15b4;
extern f32 FLOAT_803e15b8;
extern f32 FLOAT_803e15bc;
extern f32 FLOAT_803e15c0;
extern f32 FLOAT_803e15c4;
extern f32 FLOAT_803e15c8;
extern f32 FLOAT_803e15cc;
extern f32 FLOAT_803e15d0;
extern f32 FLOAT_803e15d4;
extern f32 FLOAT_803e15d8;
extern f32 FLOAT_803e15dc;
extern f32 FLOAT_803e15e8;
extern f32 FLOAT_803e15ec;
extern f32 FLOAT_803e15f0;
extern f32 FLOAT_803e15f4;
extern f32 FLOAT_803e15f8;
extern f32 FLOAT_803e15fc;
extern f32 FLOAT_803e1600;
extern f32 FLOAT_803e1604;
extern f32 FLOAT_803e1610;
extern f32 FLOAT_803e1614;
extern f32 FLOAT_803e1618;
extern f32 FLOAT_803e161c;
extern f32 FLOAT_803e1620;
extern f32 FLOAT_803e1624;
extern f32 FLOAT_803e1628;
extern f32 FLOAT_803e162c;
extern f32 FLOAT_803e1630;
extern f32 FLOAT_803e1634;
extern f32 FLOAT_803e1638;
extern f32 FLOAT_803e163c;
extern f32 FLOAT_803e1640;
extern f32 FLOAT_803e1648;
extern f32 FLOAT_803e164c;
extern f32 FLOAT_803e1650;
extern f32 FLOAT_803e1654;
extern f32 FLOAT_803e1658;
extern f32 FLOAT_803e165c;
extern f32 FLOAT_803e1660;
extern f32 FLOAT_803e1664;
extern f32 FLOAT_803e1668;
extern f32 FLOAT_803e166c;
extern f32 FLOAT_803e1670;
extern f32 FLOAT_803e1674;
extern f32 FLOAT_803e1678;
extern f32 FLOAT_803e1680;
extern f32 FLOAT_803e1684;
extern f32 FLOAT_803e1688;
extern f32 FLOAT_803e168c;
extern f32 FLOAT_803e1690;
extern f32 FLOAT_803e1694;
extern f32 FLOAT_803e1698;
extern f32 FLOAT_803e16a8;
extern f32 FLOAT_803e16ac;
extern f32 FLOAT_803e16b0;
extern f32 FLOAT_803e16b4;
extern f32 FLOAT_803e16b8;
extern f32 FLOAT_803e16bc;
extern f32 FLOAT_803e16c0;
extern f32 FLOAT_803e16c4;
extern f32 FLOAT_803e16c8;
extern f32 FLOAT_803e16cc;
extern f32 FLOAT_803e16d8;
extern f32 FLOAT_803e16dc;
extern f32 FLOAT_803e16e0;
extern f32 FLOAT_803e16e4;
extern f32 FLOAT_803e16e8;
extern f32 FLOAT_803e16ec;
extern f32 FLOAT_803e16f0;
extern f32 FLOAT_803e16f8;
extern f32 FLOAT_803e16fc;
extern f32 FLOAT_803e1700;
extern f32 FLOAT_803e1704;
extern f32 FLOAT_803e1708;
extern f32 FLOAT_803e170c;
extern f32 FLOAT_803e1710;
extern f32 FLOAT_803e1718;
extern f32 FLOAT_803e171c;
extern f32 FLOAT_803e1720;
extern f32 FLOAT_803e1724;
extern f32 FLOAT_803e1728;
extern f32 FLOAT_803e172c;
extern f32 FLOAT_803e1730;
extern f32 FLOAT_803e1738;
extern f32 FLOAT_803e173c;
extern f32 FLOAT_803e1740;
extern f32 FLOAT_803e1744;
extern f32 FLOAT_803e1748;
extern f32 FLOAT_803e174c;
extern f32 FLOAT_803e1750;
extern f32 FLOAT_803e1754;
extern f32 FLOAT_803e1758;
extern f32 FLOAT_803e175c;
extern f32 FLOAT_803e1760;
extern f32 FLOAT_803e1764;
extern f32 FLOAT_803e1768;
extern f32 FLOAT_803e176c;
extern f32 FLOAT_803e1770;
extern f32 FLOAT_803e1778;
extern f32 FLOAT_803e177c;
extern f32 FLOAT_803e1780;
extern f32 FLOAT_803e1784;
extern f32 FLOAT_803e1788;
extern f32 FLOAT_803e178c;
extern f32 FLOAT_803e1790;
extern f32 FLOAT_803e1794;
extern f32 FLOAT_803e1798;
extern f32 FLOAT_803e179c;
extern f32 FLOAT_803e17a0;
extern f32 FLOAT_803e17a4;
extern f32 FLOAT_803e17a8;
extern f32 FLOAT_803e17ac;
extern f32 FLOAT_803e17b0;
extern f32 FLOAT_803e17b8;
extern f32 FLOAT_803e17bc;
extern f32 FLOAT_803e17c0;
extern f32 FLOAT_803e17c4;
extern f32 FLOAT_803e17c8;
extern f32 FLOAT_803e17cc;
extern f32 FLOAT_803e17d0;
extern f32 FLOAT_803e17d4;
extern f32 FLOAT_803e17d8;
extern f32 FLOAT_803e17e0;
extern f32 FLOAT_803e17e4;
extern f32 FLOAT_803e17e8;
extern f32 FLOAT_803e17ec;
extern f32 FLOAT_803e17f0;
extern f32 FLOAT_803e17f4;
extern f32 FLOAT_803e17f8;
extern f32 FLOAT_803e17fc;
extern f32 FLOAT_803e1800;
extern f32 FLOAT_803e1804;
extern f32 FLOAT_803e1808;
extern f32 FLOAT_803e180c;
extern f32 FLOAT_803e1810;
extern f32 FLOAT_803e1814;
extern f32 FLOAT_803e1818;
extern f32 FLOAT_803e181c;
extern f32 FLOAT_803e1820;
extern f32 FLOAT_803e1824;
extern f32 FLOAT_803e1828;
extern f32 FLOAT_803e182c;
extern f32 FLOAT_803e1838;
extern f32 FLOAT_803e183c;
extern f32 FLOAT_803e1840;
extern f32 FLOAT_803e1844;
extern f32 FLOAT_803e1848;
extern f32 FLOAT_803e184c;
extern f32 FLOAT_803e1850;
extern f32 FLOAT_803e1854;
extern f32 FLOAT_803e1858;
extern f32 FLOAT_803e185c;
extern f32 FLOAT_803e1860;
extern f32 FLOAT_803e1864;
extern f32 FLOAT_803e1868;
extern f32 FLOAT_803e186c;
extern f32 FLOAT_803e1870;
extern f32 FLOAT_803e1874;
extern f32 FLOAT_803e1878;
extern f32 FLOAT_803e187c;
extern f32 FLOAT_803e1880;
extern f32 FLOAT_803e1884;
extern f32 FLOAT_803e1888;
extern f32 FLOAT_803e188c;
extern f32 FLOAT_803e1890;
extern f32 FLOAT_803e1894;
extern f32 FLOAT_803e1898;
extern f32 FLOAT_803e189c;
extern f32 FLOAT_803e18a0;
extern f32 FLOAT_803e18a4;
extern f32 FLOAT_803e18a8;
extern f32 FLOAT_803e18ac;
extern f32 FLOAT_803e18b0;
extern f32 FLOAT_803e18b4;
extern f32 FLOAT_803e18b8;
extern f32 FLOAT_803e18bc;
extern f32 FLOAT_803e18c0;
extern f32 FLOAT_803e18c4;
extern f32 FLOAT_803e18c8;
extern f32 FLOAT_803e18cc;
extern f32 FLOAT_803e18d0;
extern f32 FLOAT_803e18d4;
extern f32 FLOAT_803e18d8;
extern f32 FLOAT_803e18dc;
extern f32 FLOAT_803e18e0;
extern f32 FLOAT_803e18e4;
extern f32 FLOAT_803e18e8;
extern f32 FLOAT_803e18ec;
extern f32 FLOAT_803e18f0;
extern f32 FLOAT_803e18f4;
extern f32 FLOAT_803e18f8;
extern f32 FLOAT_803e18fc;
extern f32 FLOAT_803e1900;
extern f32 FLOAT_803e1904;
extern f32 FLOAT_803e1908;
extern f32 FLOAT_803e190c;
extern f32 FLOAT_803e1910;
extern f32 FLOAT_803e1914;
extern f32 FLOAT_803e1918;
extern f32 FLOAT_803e191c;
extern f32 FLOAT_803e1920;
extern f32 FLOAT_803e1930;
extern f32 FLOAT_803e1934;
extern f32 FLOAT_803e1938;
extern f32 FLOAT_803e193c;
extern f32 FLOAT_803e1940;
extern f32 FLOAT_803e1944;
extern f32 FLOAT_803e1948;
extern f32 FLOAT_803e194c;
extern f32 FLOAT_803e1950;
extern f32 FLOAT_803e1954;
extern f32 FLOAT_803e1958;
extern f32 FLOAT_803e195c;
extern f32 FLOAT_803e1960;
extern f32 FLOAT_803e1964;
extern f32 FLOAT_803e1968;
extern f32 FLOAT_803e196c;
extern f32 FLOAT_803e1970;
extern f32 FLOAT_803e1974;
extern f32 FLOAT_803e1978;
extern f32 FLOAT_803e197c;
extern f32 FLOAT_803e1988;
extern f32 FLOAT_803e198c;
extern f32 FLOAT_803e1990;
extern f32 FLOAT_803e1994;
extern f32 FLOAT_803e1998;
extern f32 FLOAT_803e199c;
extern f32 FLOAT_803e19a0;
extern f32 FLOAT_803e19a4;
extern f32 FLOAT_803e19a8;
extern f32 FLOAT_803e19ac;
extern f32 FLOAT_803e19b8;
extern f32 FLOAT_803e19bc;
extern f32 FLOAT_803e19c0;
extern f32 FLOAT_803e19c4;
extern f32 FLOAT_803e19c8;
extern f32 FLOAT_803e19cc;
extern f32 FLOAT_803e19d0;
extern f32 FLOAT_803e19d4;
extern f32 FLOAT_803e19d8;
extern f32 FLOAT_803e19dc;
extern f32 FLOAT_803e19e0;
extern f32 FLOAT_803e19e4;
extern f32 FLOAT_803e19e8;
extern f32 FLOAT_803e19ec;
extern f32 FLOAT_803e19f0;
extern f32 FLOAT_803e19f4;
extern f32 FLOAT_803e19f8;
extern char s______This_modgfx_needs_an_owner_o_80312af0[];
extern undefined4 uRam803de108;
extern undefined uRam803de10d;

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800E8118
 * EN v1.0 Size: 68b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
undefined4 FUN_800e8118(uint param_1)
{
  uint uVar1;
  
  uVar1 = 1 << (param_1 & 0xff);
  if (((DAT_803a3e34 & uVar1) != 0) && ((DAT_803a3e38 & uVar1) != 0)) {
    return 1;
  }
  return 0;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800E815C
 * EN v1.0 Size: 36b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800e815c(uint param_1)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800E8180
 * EN v1.0 Size: 32b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
uint FUN_800e8180(uint param_1)
{
  return DAT_803a3e34 & 1 << (param_1 & 0xff);
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800E81A0
 * EN v1.0 Size: 28b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800e81a0(void)
{
  DAT_803a3e2e = 0x7f;
  DAT_803a3e2f = 0x7f;
  DAT_803a3e30 = 0x7f;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800E81BC
 * EN v1.0 Size: 12b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
undefined1 * FUN_800e81bc(void)
{
    return 0;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800E81C8
 * EN v1.0 Size: 256b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800e81c8(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8)
{
  FUN_8005ced0(DAT_803a3e2a);
  FUN_8001bd8c(param_1,param_2,param_3,param_4,param_5,param_6,param_7,param_8,(uint)DAT_803a3e26);
  FUN_800154d0(DAT_803a3e2c);
  FUN_80009920(DAT_803a3e2d,'\0');
  (**(code **)(*DAT_803dd6e8 + 0x50))(DAT_803a3e27);
  (**(code **)(*DAT_803dd6d0 + 0x6c))(DAT_803a3e28);
  FUN_80009a28((uint)DAT_803a3e2f,10,0,1,0);
  FUN_80009a28((uint)DAT_803a3e2e,10,1,0,0);
  FUN_80009a28((uint)DAT_803a3e30,10,0,0,1);
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800E82C8
 * EN v1.0 Size: 16b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
undefined * FUN_800e82c8(void)
{
    return 0;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800E82D8
 * EN v1.0 Size: 172b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
undefined4 FUN_800e82d8(int param_1)
{
    return 0;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800E8384
 * EN v1.0 Size: 104b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
undefined4 FUN_800e8384(int param_1)
{
    return 0;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800E83EC
 * EN v1.0 Size: 520b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800e83ec(int param_1)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800E85F4
 * EN v1.0 Size: 360b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800e85f4(int param_1)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800E875C
 * EN v1.0 Size: 16b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800e875c(undefined2 param_1)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800E876C
 * EN v1.0 Size: 16b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
int FUN_800e876c(void)
{
  return (int)DAT_803a45ac;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800E877C
 * EN v1.0 Size: 16b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
undefined4 * FUN_800e877c(void)
{
    return 0;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800E878C
 * EN v1.0 Size: 152b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
int FUN_800e878c(undefined8 param_1,double param_2,undefined8 param_3,undefined8 param_4,
                undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8)
{
    return 0;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800E8824
 * EN v1.0 Size: 204b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800e8824(undefined8 param_1,double param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 byte param_9)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800E88F0
 * EN v1.0 Size: 100b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800e88f0(void)
{
  FUN_80244e58(0,0);
  DAT_803dc4f0 = (undefined)((int)(*(byte *)(DAT_803de110 + 0x21) & 0x60) >> 5);
  *(byte *)(DAT_803de110 + 0x21) = *(byte *)(DAT_803de110 + 0x21) & 0x1f;
  (**(code **)(*DAT_803dd72c + 0x20))();
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800E8954
 * EN v1.0 Size: 188b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800e8954(undefined8 param_1,double param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800E8A10
 * EN v1.0 Size: 12b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800e8a10(void)
{
  DAT_803de100 = 0;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800E8A1C
 * EN v1.0 Size: 24b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800e8a1c(void)
{
  if (DAT_803de100 != '\x02') {
    return;
  }
  DAT_803de100 = 1;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800E8A34
 * EN v1.0 Size: 20b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
uint FUN_800e8a34(void)
{
  uint uVar1;
  
  uVar1 = countLeadingZeros(2 - (uint)DAT_803de100);
  return uVar1 >> 5;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800E8A48
 * EN v1.0 Size: 8b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
undefined FUN_800e8a48(void)
{
  return DAT_803de100;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800E8A50
 * EN v1.0 Size: 192b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
int FUN_800e8a50(undefined8 param_1,double param_2,undefined8 param_3,undefined8 param_4,
                undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                byte param_9)
{
    return 0;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800E8B10
 * EN v1.0 Size: 40b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
undefined * FUN_800e8b10(uint param_1,uint param_2)
{
    return 0;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800E8B38
 * EN v1.0 Size: 504b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
int FUN_800e8b38(uint param_1,byte param_2,uint param_3,undefined *param_4)
{
    return 0;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800E8D30
 * EN v1.0 Size: 16b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
undefined1 * FUN_800e8d30(void)
{
    return 0;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800E8D40
 * EN v1.0 Size: 736b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800e8d40(undefined8 param_1,double param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800E9020
 * EN v1.0 Size: 604b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800e9020(undefined8 param_1,double param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8)
{
  uint uVar1;
  int iVar2;
  undefined4 uVar3;
  undefined4 uVar4;
  undefined4 in_r6;
  undefined4 in_r7;
  undefined4 in_r8;
  undefined4 in_r9;
  undefined4 in_r10;
  uint uVar5;
  byte *pbVar6;
  uint uVar7;
  double extraout_f1;
  double dVar8;
  undefined auStack_708 [28];
  undefined auStack_6ec [5];
  char local_6e7;
  byte local_1b0 [5];
  byte local_1ab;
  byte local_1aa;
  float local_1a8;
  
  uVar1 = FUN_8028683c();
  uVar7 = 0;
  dVar8 = extraout_f1;
  do {
    iVar2 = FUN_8007ddd8(dVar8,param_2,param_3,param_4,param_5,param_6,param_7,param_8,uVar7 & 0xff,
                         auStack_708);
    if (iVar2 == 0) break;
    *(char *)(uVar1 + 0x20) = local_6e7;
    if (local_6e7 == '\0') {
      FUN_800033a8(uVar1,0,0x24);
    }
    else {
      uVar4 = 4;
      FUN_80003494(uVar1,(uint)auStack_6ec,4);
      *(char *)(uVar1 + 4) = (char)(((uint)local_1ab * 100) / 0xbb);
      if (local_1ab < 0xb4) {
        if (local_1ab < 0xb1) {
          if (local_1ab < 0xa2) {
            if (local_1ab < 0x8b) {
              if (local_1ab < 0x82) {
                if (local_1ab < 0x72) {
                  if (local_1ab < 99) {
                    if (local_1ab < 0x49) {
                      if (local_1ab < 0x3e) {
                        if (local_1ab < 9) {
                          *(undefined *)(uVar1 + 5) = 0;
                          *(undefined *)(uVar1 + 6) = 0;
                        }
                        else {
                          *(undefined *)(uVar1 + 5) = 1;
                          *(undefined *)(uVar1 + 6) = 0;
                        }
                      }
                      else {
                        *(undefined *)(uVar1 + 5) = 1;
                        *(undefined *)(uVar1 + 6) = 1;
                      }
                    }
                    else {
                      *(undefined *)(uVar1 + 5) = 2;
                      *(undefined *)(uVar1 + 6) = 1;
                    }
                  }
                  else {
                    *(undefined *)(uVar1 + 5) = 2;
                    *(undefined *)(uVar1 + 6) = 2;
                  }
                }
                else {
                  *(undefined *)(uVar1 + 5) = 3;
                  *(undefined *)(uVar1 + 6) = 2;
                }
              }
              else {
                *(undefined *)(uVar1 + 5) = 3;
                *(undefined *)(uVar1 + 6) = 3;
              }
            }
            else {
              *(undefined *)(uVar1 + 5) = 4;
              *(undefined *)(uVar1 + 6) = 3;
            }
          }
          else {
            *(undefined *)(uVar1 + 5) = 4;
            *(undefined *)(uVar1 + 6) = 4;
          }
        }
        else {
          *(undefined *)(uVar1 + 5) = 5;
          *(undefined *)(uVar1 + 6) = 4;
        }
      }
      else {
        *(undefined *)(uVar1 + 5) = 6;
        *(undefined *)(uVar1 + 6) = 4;
      }
      dVar8 = (double)(local_1a8 / FLOAT_803e134c);
      iVar2 = FUN_80286718(dVar8);
      *(int *)(uVar1 + 8) = iVar2;
      *(undefined4 *)(uVar1 + 0xc) = 0;
      *(undefined4 *)(uVar1 + 0x10) = 0;
      *(undefined4 *)(uVar1 + 0x14) = 0;
      *(undefined4 *)(uVar1 + 0x18) = 0;
      *(undefined4 *)(uVar1 + 0x1c) = 0;
      pbVar6 = local_1b0;
      uVar5 = uVar1;
      for (iVar2 = 0; iVar2 < (int)(uint)local_1aa; iVar2 = iVar2 + 1) {
        uVar3 = FUN_800191fc(dVar8,param_2,param_3,param_4,param_5,param_6,param_7,param_8,
                             *pbVar6 + 0xf4,0,uVar4,in_r6,in_r7,in_r8,in_r9,in_r10);
        *(undefined4 *)(uVar5 + 0xc) = uVar3;
        uVar5 = uVar5 + 4;
        pbVar6 = pbVar6 + 1;
      }
      *(undefined *)(uVar1 + 0x21) = 0;
      *(char *)(uVar1 + 0x20) = local_6e7;
    }
    uVar1 = uVar1 + 0x24;
    uVar7 = uVar7 + 1;
  } while ((int)uVar7 < 3);
  FUN_80286888();
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800E927C
 * EN v1.0 Size: 1056b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800e927c(undefined4 param_1,undefined4 param_2,int param_3)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800E969C
 * EN v1.0 Size: 296b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800e969c(void)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800E97C4
 * EN v1.0 Size: 252b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
int FUN_800e97c4(int param_1,uint param_2)
{
    return 0;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800E98C0
 * EN v1.0 Size: 156b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800e98c0(uint param_1,int param_2)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800E995C
 * EN v1.0 Size: 128b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800e995c(uint param_1)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800E99DC
 * EN v1.0 Size: 124b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
uint FUN_800e99dc(uint param_1,uint param_2)
{
    return 0;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800E9A58
 * EN v1.0 Size: 156b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
undefined FUN_800e9a58(uint param_1)
{
    return 0;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800E9AF4
 * EN v1.0 Size: 216b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800e9af4(uint param_1,uint param_2)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800E9BCC
 * EN v1.0 Size: 32b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800e9bcc(void)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800E9BEC
 * EN v1.0 Size: 632b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
double FUN_800e9bec(void)
{
  return (double)DAT_803a4468;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800E9E64
 * EN v1.0 Size: 204b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800e9e64(void)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800E9F30
 * EN v1.0 Size: 52b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800e9f30(void)
{
  if (DAT_803de114 != 0) {
    FUN_800238c4(DAT_803de114);
    DAT_803de114 = 0;
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800E9F64
 * EN v1.0 Size: 84b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800e9f64(void)
{
  if (DAT_803de114 == 0) {
    FUN_80003494(0x803a3f08,DAT_803de110,0x6ec);
  }
  else {
    FUN_80003494(0x803a3f08,DAT_803de114,0x6ec);
  }
  FUN_800e9e64();
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800E9FB8
 * EN v1.0 Size: 356b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800e9fb8(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 undefined4 param_9,undefined4 param_10,undefined param_11,int param_12)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800EA11C
 * EN v1.0 Size: 108b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800ea11c(void)
{
  if (*DAT_803de110 < '\x01') {
    *DAT_803de110 = '\x01';
  }
  if (DAT_803de110[0xc] < '\x01') {
    DAT_803de110[0xc] = '\x01';
  }
  FUN_80003494(0x803a3f08,(uint)DAT_803de110,0x6ec);
  FUN_800e9e64();
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800EA188
 * EN v1.0 Size: 328b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800ea188(undefined4 *param_1,undefined2 param_2,uint param_3,undefined param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800EA2D0
 * EN v1.0 Size: 44b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800ea2d0(void)
{
  if (DAT_803de114 != 0) {
    FUN_800238c4(DAT_803de114);
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800EA2FC
 * EN v1.0 Size: 252b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800ea2fc(void)
{
  FUN_800033a8(-0x7fc5c0f8,0,0xf70);
  if ((*(byte *)(DAT_803de110 + 0x21) & 0x80) == 0) {
    FUN_800033a8(DAT_803de110,0,0x6ec);
  }
  DAT_803de114 = 0;
  DAT_803de10c = 0xff;
  DAT_803de104 = 0xffffffff;
  FUN_800033a8(-0x7fc5c1dc,0,0xe4);
  DAT_803a3e2a = 0;
  DAT_803a3e26 = 1;
  DAT_803a3e2c = 1;
  DAT_803a3e24 = 1;
  DAT_803a3e2e = 0x7f;
  DAT_803a3e2f = 0x7f;
  DAT_803a3e30 = 0x7f;
  DAT_803a3be0 = 0xff;
  DAT_803a3be3 = 0xff;
  DAT_803a3be6 = 0xff;
  DAT_803a3be9 = 0xff;
  DAT_803a3bec = 0xff;
  DAT_803a3bef = 0xff;
  DAT_803a3bf2 = 0xff;
  DAT_803a3bf5 = 0xff;
  DAT_803a3bf8 = 0xff;
  DAT_803a3bfb = 0xff;
  DAT_803a3bfe = 0xff;
  DAT_803a3c01 = 0xff;
  DAT_803a3c04 = 0xff;
  DAT_803a3c07 = 0xff;
  DAT_803a3c0a = 0xff;
  DAT_803a3c0d = 0xff;
  DAT_803a3c10 = 0xff;
  DAT_803a3c13 = 0xff;
  DAT_803a3c16 = 0xff;
  DAT_803a3c19 = 0xff;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800EA3F8
 * EN v1.0 Size: 140b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800ea3f8(int param_1)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800EA484
 * EN v1.0 Size: 56b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
ushort FUN_800ea484(void)
{
    return 0;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800EA4BC
 * EN v1.0 Size: 44b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800ea4bc(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8)
{
  undefined *puVar1;
  
  puVar1 = FUN_800e82c8();
  FUN_800195a8(param_1,param_2,param_3,param_4,param_5,param_6,param_7,param_8,
               (byte)puVar1[5] + 0xf4);
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800EA4E8
 * EN v1.0 Size: 88b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
undefined4
FUN_800ea4e8(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
            undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8)
{
    return 0;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800EA540
 * EN v1.0 Size: 36b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
undefined FUN_800ea540(void)
{
  undefined *puVar1;
  
  puVar1 = FUN_800e82c8();
  return puVar1[5];
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800EA564
 * EN v1.0 Size: 488b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800ea564(void)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800EA74C
 * EN v1.0 Size: 260b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800ea74c(void)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800EA850
 * EN v1.0 Size: 64b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800ea850(void)
{
  if (DAT_803de118 != 0) {
    FUN_800238c4(DAT_803de118);
    DAT_803de118 = 0;
    DAT_803de11c = 0;
    DAT_803de124 = 0xffffffff;
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800EA890
 * EN v1.0 Size: 68b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800ea890(void)
{
  if (DAT_803de118 != 0) {
    FUN_800238c4(DAT_803de118);
    DAT_803de118 = 0;
    DAT_803de124 = 0xffffffff;
    DAT_803de11c = 0;
    DAT_803de120 = 0;
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800EA8D4
 * EN v1.0 Size: 292b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800ea8d4(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 int param_9,undefined4 param_10,undefined4 param_11,undefined4 param_12,
                 undefined4 param_13,undefined4 param_14,undefined4 param_15,undefined4 param_16)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800EA9F8
 * EN v1.0 Size: 120b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800ea9f8(int param_1)
{
  int iVar1;
  
  if (*(short *)(param_1 + 0x46) != 0x112) {
    iVar1 = *(int *)(param_1 + 0xb8);
    *(undefined *)(iVar1 + 5) = 0;
    *(undefined *)(iVar1 + 6) = 0;
    if ((*(byte *)(iVar1 + 7) & 8) == 0) {
      *(float *)(param_1 + 0x10) = *(float *)(param_1 + 0x10) + FLOAT_803e1358;
      FUN_800e85f4(param_1);
      *(float *)(param_1 + 0x10) = *(float *)(param_1 + 0x10) - FLOAT_803e1358;
    }
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800EAA70
 * EN v1.0 Size: 320b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800eaa70(int param_1,int param_2)
{
  int iVar1;
  int local_18 [3];
  
  iVar1 = FUN_8002bac4();
  *(undefined *)(param_2 + 5) = 0;
  FUN_80296e34(iVar1,local_18);
  if (local_18[0] == param_1) {
    FUN_80296ce0(iVar1,0);
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800EABB0
 * EN v1.0 Size: 156b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800eabb0(int param_1)
{
  FUN_8003709c(param_1,0x10);
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800EAC4C
 * EN v1.0 Size: 960b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
int FUN_800eac4c(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
                undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                uint param_9)
{
    return 0;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800EB00C
 * EN v1.0 Size: 92b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800eb00c(int param_1,int param_2)
{
  FUN_800372f8(param_1,0x10);
  *(undefined2 *)(param_2 + 2) = 0;
  *(undefined *)(param_2 + 5) = 0;
  *(undefined *)(param_2 + 4) = 0;
  *(undefined *)(param_2 + 6) = 0;
  *(undefined4 *)(param_1 + 0xf8) = 0;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800EB068
 * EN v1.0 Size: 716b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800eb068(undefined4 param_1,undefined4 param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800EB334
 * EN v1.0 Size: 1408b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800eb334(undefined4 param_1,undefined4 param_2,int param_3,uint param_4,undefined4 param_5,
                 int *param_6)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800EB8B4
 * EN v1.0 Size: 4516b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800eb8b4(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 undefined4 param_9,undefined4 param_10,undefined4 param_11,uint param_12,
                 undefined4 param_13,undefined4 *param_14,undefined4 param_15,undefined4 param_16)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800ECA58
 * EN v1.0 Size: 804b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800eca58(undefined4 param_1,undefined4 param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800ECD7C
 * EN v1.0 Size: 804b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800ecd7c(undefined4 param_1,undefined4 param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800ED0A0
 * EN v1.0 Size: 1168b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800ed0a0(undefined4 param_1,undefined param_2,undefined4 param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800ED530
 * EN v1.0 Size: 848b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800ed530(int param_1,undefined2 param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800ED880
 * EN v1.0 Size: 1092b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800ed880(undefined4 param_1,undefined4 param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800EDCC4
 * EN v1.0 Size: 1100b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800edcc4(undefined4 param_1,undefined4 param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800EE110
 * EN v1.0 Size: 1000b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800ee110(undefined4 param_1,undefined4 param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800EE4F8
 * EN v1.0 Size: 1696b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800ee4f8(undefined4 param_1,undefined4 param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800EEB98
 * EN v1.0 Size: 824b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800eeb98(int param_1,int param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800EEED0
 * EN v1.0 Size: 952b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800eeed0(undefined4 param_1,undefined4 param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800EF288
 * EN v1.0 Size: 948b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800ef288(undefined4 param_1,undefined4 param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800EF63C
 * EN v1.0 Size: 1044b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800ef63c(undefined4 param_1,undefined4 param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800EFA50
 * EN v1.0 Size: 636b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800efa50(int param_1,undefined2 param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800EFCCC
 * EN v1.0 Size: 788b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800efccc(int param_1,undefined2 param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800EFFE0
 * EN v1.0 Size: 1256b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800effe0(short *param_1,int param_2,int param_3,uint param_4,undefined4 param_5,
                 uint *param_6)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800F04C8
 * EN v1.0 Size: 864b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800f04c8(int param_1,int param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800F0828
 * EN v1.0 Size: 608b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800f0828(int param_1,undefined2 param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800F0A88
 * EN v1.0 Size: 608b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800f0a88(int param_1,undefined2 param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800F0CE8
 * EN v1.0 Size: 592b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800f0ce8(int param_1,undefined2 param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800F0F38
 * EN v1.0 Size: 1352b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800f0f38(undefined4 param_1,undefined4 param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800F1480
 * EN v1.0 Size: 1280b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800f1480(undefined4 param_1,undefined4 param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800F1980
 * EN v1.0 Size: 884b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800f1980(undefined4 param_1,undefined4 param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800F1CF4
 * EN v1.0 Size: 780b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800f1cf4(int param_1,undefined2 param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800F2000
 * EN v1.0 Size: 1192b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800f2000(undefined4 param_1,undefined4 param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800F24A8
 * EN v1.0 Size: 1160b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800f24a8(int param_1,int param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800F2930
 * EN v1.0 Size: 1016b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800f2930(int param_1,int param_2,int param_3,uint param_4)
{
  int iVar1;
  undefined4 *puVar2;
  undefined4 *local_368;
  int local_364;
  float local_348;
  float local_344;
  float local_340;
  float local_33c;
  float local_338;
  float local_334;
  float local_330;
  undefined4 local_32c;
  undefined4 local_328;
  undefined2 local_324;
  undefined2 local_322;
  undefined2 local_320;
  undefined2 local_31e;
  undefined2 local_31c;
  undefined2 local_31a;
  undefined2 local_318;
  undefined2 local_316;
  uint local_314;
  undefined local_310;
  undefined local_30f;
  undefined local_30e;
  undefined local_30d;
  char local_30b;
  undefined4 local_308;
  float local_304;
  float local_300;
  float local_2fc;
  undefined4 local_2f8;
  undefined2 local_2f4;
  undefined local_2f2;
  undefined4 local_2f0;
  float local_2ec;
  float local_2e8;
  float local_2e4;
  undefined4 local_2e0;
  undefined2 local_2dc;
  undefined local_2da [2];
  undefined4 local_2d8;
  float local_2d4;
  float local_2d0;
  float local_2cc;
  undefined4 local_2c8;
  undefined2 local_2c4;
  undefined local_2c2;
  undefined4 local_2c0;
  float local_2bc;
  float local_2b8;
  float local_2b4;
  undefined4 local_2b0;
  undefined2 local_2ac;
  undefined local_2aa;
  undefined4 local_2a8 [170];
  
  local_2f4 = 100;
  local_300 = FLOAT_803e1868;
  local_2fc = FLOAT_803e186c;
  if (param_2 == 0) {
    local_2f4 = 0x8c;
  }
  else if (param_2 == 1) {
    local_2f4 = 0x8c;
    local_300 = FLOAT_803e1870;
    local_2fc = FLOAT_803e1874;
  }
  else if (param_2 == 2) {
    local_2f4 = 0x8c;
    local_300 = FLOAT_803e1878;
    local_2fc = FLOAT_803e187c;
  }
  else if (param_2 == 3) {
    local_2f4 = 0x8c;
    local_300 = FLOAT_803e1880;
    local_2fc = FLOAT_803e1884;
  }
  else if (param_2 == 4) {
    local_2f4 = 0x154;
    local_300 = FLOAT_803e1888;
    local_2fc = FLOAT_803e188c;
  }
  else if (param_2 == 5) {
    local_2f4 = 0x280;
    DAT_80315574 = 800;
    local_300 = FLOAT_803e1890;
    local_2fc = FLOAT_803e1894;
  }
  else if (param_2 == 6) {
    local_2f4 = 100;
    DAT_80315574 = 0x14;
    local_300 = FLOAT_803e1898;
    local_2fc = FLOAT_803e189c;
  }
  else if (param_2 == 7) {
    local_2f4 = 200;
    DAT_80315572 = 0x14;
    DAT_80315574 = 0x14;
    DAT_80315576 = 0x14;
    local_300 = FLOAT_803e18a0;
    local_2fc = FLOAT_803e18a4;
  }
  else if (param_2 == 8) {
    local_2f4 = 0x41;
    DAT_80315572 = 0x14;
    DAT_80315574 = 0x14;
    DAT_80315576 = 0x14;
    local_300 = FLOAT_803e18a8;
    local_2fc = FLOAT_803e18ac;
  }
  local_2f2 = 0;
  local_2f8 = 0;
  local_308 = 0x20000000;
  local_304 = FLOAT_803e18b0;
  puVar2 = &local_2f0;
  if (param_2 == 0) {
    local_2da[0] = 0;
    local_2dc = 0;
    local_2e0 = 0;
    local_2f0 = 0x80000;
    local_2ec = FLOAT_803e18b4;
    local_2e8 = FLOAT_803e18b8;
    local_2e4 = FLOAT_803e18b4;
    local_2c2 = 1;
    local_2c4 = 0;
    local_2c8 = 0;
    local_2d8 = 0x80000;
    local_2d4 = FLOAT_803e18b4;
    local_2d0 = FLOAT_803e18b4;
    local_2cc = FLOAT_803e18b4;
    local_2aa = 3;
    local_2ac = 0;
    local_2b0 = 0;
    local_2c0 = 0x80000;
    local_2bc = FLOAT_803e18b4;
    local_2b8 = FLOAT_803e18b8;
    local_2b4 = FLOAT_803e18b4;
    puVar2 = local_2a8;
  }
  else if (param_2 == 6) {
    local_2da[0] = 3;
    local_2dc = 1;
    local_2e0 = 0;
    local_2f0 = 0x2000;
    local_2ec = FLOAT_803e18b4;
    local_2e8 = FLOAT_803e18b4;
    local_2e4 = FLOAT_803e18b4;
    puVar2 = &local_2d8;
  }
  else if (param_2 == 8) {
    local_2da[0] = 3;
    local_2dc = 1;
    local_2e0 = 0;
    local_2f0 = 0x2000;
    local_2ec = FLOAT_803e18b4;
    local_2e8 = FLOAT_803e18b4;
    local_2e4 = FLOAT_803e18b4;
    puVar2 = &local_2d8;
  }
  *(undefined *)((int)puVar2 + 0x16) = 4;
  *(undefined2 *)(puVar2 + 5) = 0;
  puVar2[4] = 0;
  *puVar2 = 0x20000000;
  puVar2[1] = FLOAT_803e18b0;
  puVar2[2] = local_300;
  puVar2[3] = local_2fc;
  local_310 = 0;
  local_324 = (undefined2)param_2;
  local_33c = FLOAT_803e18b4;
  local_338 = FLOAT_803e18b4;
  local_334 = FLOAT_803e18b4;
  local_348 = FLOAT_803e18b4;
  local_344 = FLOAT_803e18b4;
  local_340 = FLOAT_803e18b4;
  local_330 = FLOAT_803e18bc;
  local_328 = 0;
  local_32c = 0;
  local_30f = 0;
  local_30e = 0;
  local_30d = 0;
  iVar1 = (int)puVar2 + (0x18 - (int)&local_308);
  iVar1 = iVar1 / 0x18 + (iVar1 >> 0x1f);
  local_30b = (char)iVar1 - (char)(iVar1 >> 0x1f);
  local_322 = DAT_80315570;
  local_320 = DAT_80315572;
  local_31e = DAT_80315574;
  local_31c = DAT_80315576;
  local_31a = DAT_80315578;
  local_318 = DAT_8031557a;
  local_316 = DAT_8031557c;
  local_368 = &local_308;
  local_314 = param_4 | 0x10800;
  if ((param_4 & 1) != 0) {
    if (param_1 == 0) {
      local_33c = FLOAT_803e18b4 + *(float *)(param_3 + 0xc);
      local_338 = FLOAT_803e18b4 + *(float *)(param_3 + 0x10);
      local_334 = FLOAT_803e18b4 + *(float *)(param_3 + 0x14);
    }
    else {
      local_33c = FLOAT_803e18b4 + *(float *)(param_1 + 0x18);
      local_338 = FLOAT_803e18b4 + *(float *)(param_1 + 0x1c);
      local_334 = FLOAT_803e18b4 + *(float *)(param_1 + 0x20);
    }
  }
  local_364 = param_1;
  (**(code **)(*DAT_803dd6fc + 8))(&local_368,0,0,0,0,0,0,0);
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800F2D28
 * EN v1.0 Size: 608b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800f2d28(int param_1,undefined2 param_2,int param_3,uint param_4)
{
  int iVar1;
  undefined4 *local_368;
  int local_364;
  float local_348;
  float local_344;
  float local_340;
  float local_33c;
  float local_338;
  float local_334;
  float local_330;
  undefined4 local_32c;
  undefined4 local_328;
  undefined2 local_324;
  undefined2 local_322;
  undefined2 local_320;
  undefined2 local_31e;
  undefined2 local_31c;
  undefined2 local_31a;
  undefined2 local_318;
  undefined2 local_316;
  uint local_314;
  undefined local_310;
  undefined local_30f;
  undefined local_30e;
  undefined local_30d;
  char local_30b;
  undefined4 local_308;
  float local_304;
  float local_300;
  float local_2fc;
  undefined4 local_2f8;
  undefined2 local_2f4;
  undefined local_2f2;
  undefined4 local_2f0;
  float local_2ec;
  float local_2e8;
  float local_2e4;
  undefined4 local_2e0;
  undefined2 local_2dc;
  undefined local_2da;
  undefined4 local_2d8;
  float local_2d4;
  float local_2d0;
  float local_2cc;
  undefined4 local_2c8;
  undefined2 local_2c4;
  undefined local_2c2;
  undefined4 local_2c0;
  float local_2bc;
  float local_2b8;
  float local_2b4;
  undefined4 local_2b0;
  undefined2 local_2ac;
  undefined local_2aa;
  undefined4 local_2a8;
  float local_2a4;
  float local_2a0;
  float local_29c;
  undefined4 local_298;
  undefined2 local_294;
  undefined local_292;
  undefined4 local_290;
  float local_28c;
  float local_288;
  float local_284;
  undefined4 local_280;
  undefined2 local_27c;
  undefined local_27a;
  undefined auStack_278 [632];
  
  local_368 = &local_308;
  local_2f2 = 0;
  local_2f4 = 0x8c;
  local_2f8 = 0;
  local_308 = 0x20000000;
  local_304 = FLOAT_803e18c0;
  local_300 = FLOAT_803e18c4;
  local_2fc = FLOAT_803e18c8;
  local_2da = 0;
  local_2dc = 0;
  local_2e0 = 0;
  local_2f0 = 0x80000;
  local_2ec = FLOAT_803e18cc;
  local_2e8 = FLOAT_803e18d0;
  local_2e4 = FLOAT_803e18cc;
  local_2c2 = 1;
  local_2c4 = 0;
  local_2c8 = 0;
  local_2d8 = 0x80000;
  local_2d4 = FLOAT_803e18cc;
  local_2d0 = FLOAT_803e18cc;
  local_2cc = FLOAT_803e18cc;
  local_2aa = 3;
  local_2ac = 1;
  local_2b0 = 0;
  local_2c0 = 0x2000;
  local_2bc = FLOAT_803e18cc;
  local_2b8 = FLOAT_803e18cc;
  local_2b4 = FLOAT_803e18cc;
  local_292 = 4;
  local_294 = 0;
  local_298 = 0;
  local_2a8 = 0x80000;
  local_2a4 = FLOAT_803e18cc;
  local_2a0 = FLOAT_803e18d0;
  local_29c = FLOAT_803e18cc;
  local_27a = 5;
  local_27c = 0;
  local_280 = 0;
  local_290 = 0x20000000;
  local_28c = FLOAT_803e18c0;
  local_288 = FLOAT_803e18c4;
  local_284 = FLOAT_803e18c8;
  local_310 = 0;
  local_33c = FLOAT_803e18cc;
  local_338 = FLOAT_803e18cc;
  local_334 = FLOAT_803e18cc;
  local_348 = FLOAT_803e18cc;
  local_344 = FLOAT_803e18cc;
  local_340 = FLOAT_803e18cc;
  local_330 = FLOAT_803e18d4;
  local_328 = 0;
  local_32c = 0;
  local_30f = 0;
  local_30e = 0;
  local_30d = 0;
  iVar1 = (int)(auStack_278 + -(int)local_368) / 0x18 +
          ((int)(auStack_278 + -(int)local_368) >> 0x1f);
  local_30b = (char)iVar1 - (char)(iVar1 >> 0x1f);
  local_322 = DAT_803155a0;
  local_320 = DAT_803155a2;
  local_31e = DAT_803155a4;
  local_31c = DAT_803155a6;
  local_31a = DAT_803155a8;
  local_318 = DAT_803155aa;
  local_316 = DAT_803155ac;
  local_314 = param_4 | 0x10c00;
  if ((param_4 & 1) != 0) {
    if (param_1 == 0) {
      local_33c = FLOAT_803e18cc + *(float *)(param_3 + 0xc);
      local_338 = FLOAT_803e18cc + *(float *)(param_3 + 0x10);
      local_334 = FLOAT_803e18cc + *(float *)(param_3 + 0x14);
    }
    else {
      local_33c = FLOAT_803e18cc + *(float *)(param_1 + 0x18);
      local_338 = FLOAT_803e18cc + *(float *)(param_1 + 0x1c);
      local_334 = FLOAT_803e18cc + *(float *)(param_1 + 0x20);
    }
  }
  local_364 = param_1;
  local_324 = param_2;
  (**(code **)(*DAT_803dd6fc + 8))(&local_368,0,0,0,0,0,0,0);
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800F2F88
 * EN v1.0 Size: 608b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800f2f88(int param_1,undefined2 param_2,int param_3,uint param_4)
{
  int iVar1;
  undefined4 *local_368;
  int local_364;
  float local_348;
  float local_344;
  float local_340;
  float local_33c;
  float local_338;
  float local_334;
  float local_330;
  undefined4 local_32c;
  undefined4 local_328;
  undefined2 local_324;
  undefined2 local_322;
  undefined2 local_320;
  undefined2 local_31e;
  undefined2 local_31c;
  undefined2 local_31a;
  undefined2 local_318;
  undefined2 local_316;
  uint local_314;
  undefined local_310;
  undefined local_30f;
  undefined local_30e;
  undefined local_30d;
  char local_30b;
  undefined4 local_308;
  float local_304;
  float local_300;
  float local_2fc;
  undefined4 local_2f8;
  undefined2 local_2f4;
  undefined local_2f2;
  undefined4 local_2f0;
  float local_2ec;
  float local_2e8;
  float local_2e4;
  undefined4 local_2e0;
  undefined2 local_2dc;
  undefined local_2da;
  undefined4 local_2d8;
  float local_2d4;
  float local_2d0;
  float local_2cc;
  undefined4 local_2c8;
  undefined2 local_2c4;
  undefined local_2c2;
  undefined4 local_2c0;
  float local_2bc;
  float local_2b8;
  float local_2b4;
  undefined4 local_2b0;
  undefined2 local_2ac;
  undefined local_2aa;
  undefined4 local_2a8;
  float local_2a4;
  float local_2a0;
  float local_29c;
  undefined4 local_298;
  undefined2 local_294;
  undefined local_292;
  undefined4 local_290;
  float local_28c;
  float local_288;
  float local_284;
  undefined4 local_280;
  undefined2 local_27c;
  undefined local_27a;
  undefined auStack_278 [632];
  
  local_368 = &local_308;
  local_2f2 = 0;
  local_2f4 = 0x8c;
  local_2f8 = 0;
  local_308 = 0x20000000;
  local_304 = FLOAT_803e18d8;
  local_300 = FLOAT_803e18dc;
  local_2fc = FLOAT_803e18e0;
  local_2da = 0;
  local_2dc = 0;
  local_2e0 = 0;
  local_2f0 = 0x80000;
  local_2ec = FLOAT_803e18e4;
  local_2e8 = FLOAT_803e18e8;
  local_2e4 = FLOAT_803e18e4;
  local_2c2 = 1;
  local_2c4 = 0;
  local_2c8 = 0;
  local_2d8 = 0x80000;
  local_2d4 = FLOAT_803e18e4;
  local_2d0 = FLOAT_803e18e4;
  local_2cc = FLOAT_803e18e4;
  local_2aa = 3;
  local_2ac = 1;
  local_2b0 = 0;
  local_2c0 = 0x2000;
  local_2bc = FLOAT_803e18e4;
  local_2b8 = FLOAT_803e18e4;
  local_2b4 = FLOAT_803e18e4;
  local_292 = 4;
  local_294 = 0;
  local_298 = 0;
  local_2a8 = 0x80000;
  local_2a4 = FLOAT_803e18e4;
  local_2a0 = FLOAT_803e18e8;
  local_29c = FLOAT_803e18e4;
  local_27a = 5;
  local_27c = 0;
  local_280 = 0;
  local_290 = 0x20000000;
  local_28c = FLOAT_803e18d8;
  local_288 = FLOAT_803e18dc;
  local_284 = FLOAT_803e18e0;
  local_310 = 0;
  local_33c = FLOAT_803e18e4;
  local_338 = FLOAT_803e18e4;
  local_334 = FLOAT_803e18e4;
  local_348 = FLOAT_803e18e4;
  local_344 = FLOAT_803e18e4;
  local_340 = FLOAT_803e18e4;
  local_330 = FLOAT_803e18ec;
  local_328 = 0;
  local_32c = 0;
  local_30f = 0;
  local_30e = 0;
  local_30d = 0;
  iVar1 = (int)(auStack_278 + -(int)local_368) / 0x18 +
          ((int)(auStack_278 + -(int)local_368) >> 0x1f);
  local_30b = (char)iVar1 - (char)(iVar1 >> 0x1f);
  local_322 = DAT_803155d0;
  local_320 = DAT_803155d2;
  local_31e = DAT_803155d4;
  local_31c = DAT_803155d6;
  local_31a = DAT_803155d8;
  local_318 = DAT_803155da;
  local_316 = DAT_803155dc;
  local_314 = param_4 | 0x10c00;
  if ((param_4 & 1) != 0) {
    if (param_1 == 0) {
      local_33c = FLOAT_803e18e4 + *(float *)(param_3 + 0xc);
      local_338 = FLOAT_803e18e4 + *(float *)(param_3 + 0x10);
      local_334 = FLOAT_803e18e4 + *(float *)(param_3 + 0x14);
    }
    else {
      local_33c = FLOAT_803e18e4 + *(float *)(param_1 + 0x18);
      local_338 = FLOAT_803e18e4 + *(float *)(param_1 + 0x1c);
      local_334 = FLOAT_803e18e4 + *(float *)(param_1 + 0x20);
    }
  }
  local_364 = param_1;
  local_324 = param_2;
  (**(code **)(*DAT_803dd6fc + 8))(&local_368,0,0,0,0,0,0,0);
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800F31E8
 * EN v1.0 Size: 1204b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800f31e8(int param_1,undefined2 param_2,short *param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800F369C
 * EN v1.0 Size: 2256b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800f369c(undefined4 param_1,undefined4 param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800F3F6C
 * EN v1.0 Size: 1188b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800f3f6c(undefined4 param_1,undefined4 param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800F4410
 * EN v1.0 Size: 1464b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800f4410(undefined4 param_1,undefined4 param_2,int param_3,uint param_4)
{
}
