/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/landedArwing.c
 * Text span: 0x80165884-0x80165A38
 * Imported Ghidra functions: 1
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 1
 */

#include "ghidra_import.h"
#include "main/dll/landedArwing.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern int FUN_8002bac4();
extern undefined4 FUN_80035ff8();
extern undefined4 FUN_80165fe8();
extern undefined4 FUN_80166138();
extern undefined4 FUN_801668f0();
extern undefined4 FUN_80166efc();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4 DAT_803dc070;
extern f32 FLOAT_803e3c74;
extern f32 FLOAT_803e3c8c;
extern f32 FLOAT_803e3c94;
extern f32 FLOAT_803e3c98;

/* Local declarations keep imported functions visible within the TU. */
undefined4 FUN_80165884(short *param_1,int param_2);

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

undefined4 FUN_80165884(short *param_1,int param_2)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0;
}
