/*
 * Auto-generated by tools/orig/source_materialize.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists to turn a retail-backed gap-window estimate into a concrete
 * source-file target that can be filled in during decomp work.
 *
 * Retail source name: modanimeflash1.c
 * Output path: main/dll/modanimeflash1.c
 * Confidence: medium
 * Reason: gap-window-brief
 *
 * Gap-window brief evidence:
 * - left anchor: dll/curves.c
 * - right anchor: dll/CAM/camcontrol.c
 * - current EN window: 0x80102CA0-0x80102CC8
 * - debug split: 0x8012FB7C-0x8012FB84
 * - debug function count: 2
 * - confidence note: Resolved gap names give a usable local skeleton, but the interval is only partially constrained.
 *
 * Current EN functions in this estimated window:
 * - `fn_80102CA0@0x80102CA0-0x80102CC8` size=`0x28`
 */

/*
 * No function names were promoted here yet.
 * Start from the estimated window and nearby anchors above.
 */
