/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/ped.c
 * Text span: 0x801CDC2C-0x801CE1A0
 * Imported Ghidra functions: 4
 * Verbatim-safe functions: 1
 * Auto-stubbed functions: 3
 */

#include "ghidra_import.h"
#include "main/dll/ped.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_80013ee8();
extern uint FUN_80020078();
extern undefined4 FUN_80036f50();
extern undefined4 FUN_80038524();
extern undefined4 FUN_8003b9ec();
extern int FUN_80286840();
extern undefined4 FUN_8028688c();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4* DAT_803dd6d4;
extern undefined4* DAT_803dd708;
extern f64 DOUBLE_803e5e88;
extern f32 FLOAT_803e5e78;
extern f32 FLOAT_803e5e7c;
extern f32 FLOAT_803e5e80;
extern f32 FLOAT_803e5e94;

/* Local declarations keep imported functions visible within the TU. */
void FUN_801cdc2c(undefined2 *param_1,int param_2);
void FUN_801cdd90(undefined4 param_1,undefined4 param_2,int param_3);
void FUN_801ce004(int param_1);
void FUN_801ce08c(int param_1);

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801CDC2C
 * EN v1.0 Size: 356b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: function-pointer stores need manual cleanup. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801cdc2c(undefined2 *param_1,int param_2)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801CDD90
 * EN v1.0 Size: 628b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: function-pointer stores need manual cleanup. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801cdd90(undefined4 param_1,undefined4 param_2,int param_3)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801CE004
 * EN v1.0 Size: 136b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

// Function: FUN_801ce004
// Entry: 801ce004
// Size: 136 bytes

void FUN_801ce004(int param_1)

{
  int iVar1;
  float local_18;
  undefined4 local_14;
  float local_10 [2];
  
  iVar1 = *(int *)(param_1 + 0xb8);
  FUN_8003b9ec(param_1);
  if (*(int *)(iVar1 + 8) != 0) {
    FUN_80038524(param_1,0,local_10,&local_14,&local_18,0);
    *(float *)(*(int *)(iVar1 + 8) + 0xc) = local_10[0];
    *(undefined4 *)(*(int *)(iVar1 + 8) + 0x10) = local_14;
    *(float *)(*(int *)(iVar1 + 8) + 0x14) = local_18;
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801CE08C
 * EN v1.0 Size: 276b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: function-pointer stores need manual cleanup. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801ce08c(int param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}
