/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/projball1D8.c
 * Text span: 0x801D0494-0x801D0AB0
 * Imported Ghidra functions: 2
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 2
 */

#include "ghidra_import.h"
#include "main/dll/projball1D8.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_8000a538();
extern undefined4 FUN_8000bb38();
extern byte FUN_80014074();
extern double FUN_80014694();
extern byte FUN_8001469c();
extern undefined4 FUN_800146a8();
extern undefined4 FUN_800146c8();
extern undefined4 FUN_800146e8();
extern undefined4 FUN_800168a8();
extern uint FUN_80020078();
extern undefined4 FUN_800201ac();
extern undefined4 FUN_8002bac4();
extern undefined4 FUN_80088a84();
extern int FUN_801d0338();
extern undefined4 FUN_801d84c4();
extern int FUN_80286840();
extern undefined4 FUN_8028688c();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4* DAT_803dd6d4;
extern undefined4* DAT_803dd6d8;
extern undefined4* DAT_803dd72c;
extern f32 FLOAT_803dc074;
extern f32 FLOAT_803e5f10;
extern f32 FLOAT_803e5f14;

/* Local declarations keep imported functions visible within the TU. */
void FUN_801d049c(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 int param_9);
void FUN_801d04f0(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8);

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801d049c(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 int param_9)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801d04f0(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}
