/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/savegame.c
 * Text span: 0x800FA86C-0x800FC84C
 * Imported Ghidra functions: 9
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 9
 */

#include "ghidra_import.h"
#include "main/dll/savegame.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern uint FUN_80020078();
extern uint FUN_80022264();
extern int FUN_80286834();
extern int FUN_8028683c();
extern undefined4 FUN_80286880();
extern undefined4 FUN_80286888();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4 DAT_80317c48;
extern undefined4 DAT_80317cfc;
extern undefined DAT_80317d5c;
extern undefined DAT_80317d70;
extern undefined DAT_80317d98;
extern undefined DAT_80317dd0;
extern undefined4 DAT_80317ddc;
extern undefined4 DAT_80317dde;
extern undefined4 DAT_80317de0;
extern undefined4 DAT_80317de2;
extern undefined4 DAT_80317de4;
extern undefined4 DAT_80317de6;
extern undefined4 DAT_80317de8;
extern undefined4 DAT_80317e10;
extern undefined4 DAT_80317e4c;
extern undefined DAT_80317e64;
extern undefined DAT_80317e70;
extern undefined4 DAT_80317e7c;
extern undefined4 DAT_80317e7e;
extern undefined4 DAT_80317e80;
extern undefined4 DAT_80317e82;
extern undefined4 DAT_80317e84;
extern undefined4 DAT_80317e86;
extern undefined4 DAT_80317e88;
extern undefined4 DAT_80317eb0;
extern undefined4 DAT_80317f84;
extern undefined DAT_80318060;
extern undefined4 DAT_803180a8;
extern undefined4 DAT_803180aa;
extern undefined4 DAT_803180ac;
extern undefined4 DAT_803180ae;
extern undefined4 DAT_803180b0;
extern undefined4 DAT_803180b2;
extern undefined4 DAT_803180b4;
extern undefined4 DAT_803180d8;
extern undefined4 DAT_80318114;
extern undefined DAT_8031812c;
extern undefined DAT_80318138;
extern undefined4 DAT_80318144;
extern undefined4 DAT_80318146;
extern undefined4 DAT_80318148;
extern undefined4 DAT_8031814a;
extern undefined4 DAT_8031814c;
extern undefined4 DAT_8031814e;
extern undefined4 DAT_80318150;
extern undefined4 DAT_80318178;
extern undefined4 DAT_803181c8;
extern undefined DAT_803181f8;
extern undefined4 DAT_80318208;
extern undefined4 DAT_8031820a;
extern undefined4 DAT_8031820c;
extern undefined4 DAT_8031820e;
extern undefined4 DAT_80318210;
extern undefined4 DAT_80318212;
extern undefined4 DAT_80318214;
extern undefined4 DAT_80318238;
extern undefined4 DAT_8031830c;
extern undefined DAT_8031839c;
extern undefined DAT_803183e8;
extern undefined4 DAT_80318430;
extern undefined4 DAT_80318432;
extern undefined4 DAT_80318434;
extern undefined4 DAT_80318436;
extern undefined4 DAT_80318438;
extern undefined4 DAT_8031843a;
extern undefined4 DAT_8031843c;
extern undefined4 DAT_80318460;
extern undefined4 DAT_8031849c;
extern undefined DAT_803184b4;
extern undefined DAT_803184c0;
extern undefined4 DAT_803184cc;
extern undefined4 DAT_803184ce;
extern undefined4 DAT_803184d0;
extern undefined4 DAT_803184d2;
extern undefined4 DAT_803184d4;
extern undefined4 DAT_803184d6;
extern undefined4 DAT_803184d8;
extern undefined DAT_80318500;
extern undefined DAT_803185b4;
extern undefined4 DAT_80318668;
extern undefined DAT_803186dc;
extern undefined4 DAT_80318714;
extern undefined4 DAT_80318716;
extern undefined4 DAT_80318718;
extern undefined4 DAT_8031871a;
extern undefined4 DAT_8031871c;
extern undefined4 DAT_8031871e;
extern undefined4 DAT_80318720;
extern undefined4 DAT_80318748;
extern undefined4 DAT_80318784;
extern undefined DAT_8031879c;
extern undefined DAT_803187a8;
extern undefined4 DAT_803187b4;
extern undefined4 DAT_803187b6;
extern undefined4 DAT_803187b8;
extern undefined4 DAT_803187ba;
extern undefined4 DAT_803187bc;
extern undefined4 DAT_803187be;
extern undefined4 DAT_803187c0;
extern undefined DAT_803dc588;
extern undefined DAT_803dc590;
extern undefined DAT_803dc598;
extern undefined DAT_803dc5a0;
extern undefined DAT_803dc5a8;
extern undefined DAT_803dc5b0;
extern undefined4* DAT_803dd6fc;
extern f64 DOUBLE_803e1ee0;
extern f64 DOUBLE_803e1f60;
extern f32 FLOAT_803e1e58;
extern f32 FLOAT_803e1e5c;
extern f32 FLOAT_803e1e60;
extern f32 FLOAT_803e1e64;
extern f32 FLOAT_803e1e68;
extern f32 FLOAT_803e1e6c;
extern f32 FLOAT_803e1e70;
extern f32 FLOAT_803e1e74;
extern f32 FLOAT_803e1e78;
extern f32 FLOAT_803e1e7c;
extern f32 FLOAT_803e1e80;
extern f32 FLOAT_803e1e84;
extern f32 FLOAT_803e1e88;
extern f32 FLOAT_803e1e90;
extern f32 FLOAT_803e1e94;
extern f32 FLOAT_803e1e98;
extern f32 FLOAT_803e1e9c;
extern f32 FLOAT_803e1ea0;
extern f32 FLOAT_803e1ea4;
extern f32 FLOAT_803e1ea8;
extern f32 FLOAT_803e1eac;
extern f32 FLOAT_803e1eb0;
extern f32 FLOAT_803e1eb4;
extern f32 FLOAT_803e1eb8;
extern f32 FLOAT_803e1ec0;
extern f32 FLOAT_803e1ec4;
extern f32 FLOAT_803e1ec8;
extern f32 FLOAT_803e1ecc;
extern f32 FLOAT_803e1ed0;
extern f32 FLOAT_803e1ed4;
extern f32 FLOAT_803e1ed8;
extern f32 FLOAT_803e1ee8;
extern f32 FLOAT_803e1eec;
extern f32 FLOAT_803e1ef0;
extern f32 FLOAT_803e1ef4;
extern f32 FLOAT_803e1ef8;
extern f32 FLOAT_803e1efc;
extern f32 FLOAT_803e1f00;
extern f32 FLOAT_803e1f04;
extern f32 FLOAT_803e1f08;
extern f32 FLOAT_803e1f0c;
extern f32 FLOAT_803e1f10;
extern f32 FLOAT_803e1f18;
extern f32 FLOAT_803e1f1c;
extern f32 FLOAT_803e1f20;
extern f32 FLOAT_803e1f24;
extern f32 FLOAT_803e1f28;
extern f32 FLOAT_803e1f2c;
extern f32 FLOAT_803e1f30;
extern f32 FLOAT_803e1f34;
extern f32 FLOAT_803e1f38;
extern f32 FLOAT_803e1f40;
extern f32 FLOAT_803e1f44;
extern f32 FLOAT_803e1f48;
extern f32 FLOAT_803e1f4c;
extern f32 FLOAT_803e1f50;
extern f32 FLOAT_803e1f54;
extern f32 FLOAT_803e1f58;
extern f32 FLOAT_803e1f68;
extern f32 FLOAT_803e1f6c;
extern f32 FLOAT_803e1f70;
extern f32 FLOAT_803e1f74;
extern f32 FLOAT_803e1f78;
extern f32 FLOAT_803e1f7c;
extern f32 FLOAT_803e1f80;
extern f32 FLOAT_803e1f84;
extern f32 FLOAT_803e1f88;
extern f32 FLOAT_803e1f8c;
extern f32 FLOAT_803e1f90;
extern f32 FLOAT_803e1f98;
extern f32 FLOAT_803e1f9c;
extern f32 FLOAT_803e1fa0;
extern f32 FLOAT_803e1fa4;
extern f32 FLOAT_803e1fa8;
extern f32 FLOAT_803e1fac;
extern f32 FLOAT_803e1fb0;
extern f32 FLOAT_803e1fb4;
extern f32 FLOAT_803e1fb8;
extern f32 FLOAT_803e1fbc;
extern f32 FLOAT_803e1fc0;
extern f32 FLOAT_803e1fc4;
extern f32 FLOAT_803e1fc8;
extern f32 FLOAT_803e1fcc;
extern f32 FLOAT_803e1fd0;
extern f32 FLOAT_803e1fd4;
extern f32 FLOAT_803e1fd8;
extern f32 FLOAT_803e1fdc;
extern f32 FLOAT_803e1fe0;
extern f32 FLOAT_803e1fe4;
extern f32 FLOAT_803e1fe8;

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800FA874
 * EN v1.0 Size: 1056b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800fa874(undefined4 param_1,undefined4 param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800FAC94
 * EN v1.0 Size: 944b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800fac94(int param_1,int param_2,int param_3,uint param_4,undefined4 param_5,float *param_6
                 )
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800FB044
 * EN v1.0 Size: 720b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800fb044(undefined4 param_1,undefined4 param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800FB314
 * EN v1.0 Size: 944b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800fb314(int param_1,int param_2,int param_3,uint param_4,undefined4 param_5,float *param_6
                 )
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800FB6C4
 * EN v1.0 Size: 760b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800fb6c4(int param_1,undefined2 param_2,int param_3)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800FB9BC
 * EN v1.0 Size: 800b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800fb9bc(undefined4 param_1,undefined4 param_2,int param_3,uint param_4)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800FBCDC
 * EN v1.0 Size: 944b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800fbcdc(int param_1,int param_2,int param_3,uint param_4,undefined4 param_5,float *param_6
                 )
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800FC08C
 * EN v1.0 Size: 1048b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800fc08c(undefined4 param_1,undefined4 param_2,int param_3,uint param_4,undefined4 param_5,
                 int param_6)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x800FC4A4
 * EN v1.0 Size: 936b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_800fc4a4(int param_1,int param_2,int param_3,uint param_4,undefined4 param_5,float *param_6
                 )
{
}
