/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/tFrameAnimator.c
 * Text span: 0x80179F40-0x8017A3F4
 * Imported Ghidra functions: 1
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 1
 */

#include "ghidra_import.h"
#include "main/dll/tFrameAnimator.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_8000bb38();
extern undefined4 FUN_8002a6b4();
extern undefined4 FUN_8002ba34();
extern undefined4 FUN_80036018();
extern undefined4 FUN_8007d858();
extern undefined4 FUN_80137cd0();
extern undefined4 FUN_80247eb8();
extern undefined4 FUN_80247edc();
extern undefined4 FUN_80247ef8();
extern double FUN_80293900();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4* DAT_803dd728;
extern f32 FLOAT_803dc074;
extern f32 FLOAT_803e4334;
extern f32 FLOAT_803e4338;
extern f32 FLOAT_803e4348;
extern f32 FLOAT_803e434c;
extern f32 FLOAT_803e4350;
extern f32 FLOAT_803e4354;
extern f32 FLOAT_803e4358;
extern f32 FLOAT_803e435c;
extern f32 FLOAT_803e4360;
extern f32 FLOAT_803e4364;
extern f32 FLOAT_803e4368;
extern f32 FLOAT_803e436c;

/* Local declarations keep imported functions visible within the TU. */
undefined4 FUN_80179f40(ushort *param_1);

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80179F40
 * EN v1.0 Size: 1204b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: function-pointer stores need manual cleanup. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

undefined4 FUN_80179f40(ushort *param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0;
}
