/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/tricky.c
 * Text span: 0x8011DC94-0x80121F30
 * Imported Ghidra functions: 33
 * Verbatim-safe functions: 18
 * Auto-stubbed functions: 15
 */

#include "ghidra_import.h"
#include "main/dll/tricky.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_800033a8();
extern undefined4 FUN_8000f478();
extern undefined4 FUN_8000f500();
extern undefined4 FUN_8000f530();
extern undefined4 FUN_8000f584();
extern short* FUN_8000facc();
extern undefined4 FUN_8000fb20();
extern double FUN_8000fc08();
extern double FUN_8000fc3c();
extern double FUN_8000fc54();
extern undefined4 FUN_8000fc5c();
extern undefined4 FUN_80015e00();
extern undefined4 FUN_80019940();
extern undefined4 FUN_800199a8();
extern undefined4 FUN_80019c28();
extern uint FUN_80020078();
extern undefined4 FUN_800206ec();
extern undefined4 FUN_800207ac();
extern int FUN_80020800();
extern int FUN_80021884();
extern undefined4 FUN_800238c4();
extern undefined4 FUN_80023d8c();
extern int FUN_800284e8();
extern undefined8 FUN_80028600();
extern int FUN_8002b660();
extern int FUN_8002ba84();
extern int FUN_8002bac4();
extern undefined2* FUN_8002becc();
extern undefined8 FUN_8002cc9c();
extern int FUN_8002e088();
extern int FUN_80036f50();
extern undefined4 FUN_8004c3cc();
extern undefined4 FUN_8004c3e0();
extern undefined4 FUN_8004c460();
extern uint FUN_8005383c();
extern undefined4 FUN_80054484();
extern undefined4 FUN_80054ed0();
extern char FUN_80055218();
extern int FUN_8005b128();
extern undefined4 FUN_8006c748();
extern undefined4 FUN_8006ff74();
extern undefined4 FUN_80070434();
extern undefined4 FUN_8007048c();
extern undefined4 FUN_80075534();
extern undefined4 FUN_80075800();
extern undefined4 FUN_80076144();
extern undefined4 FUN_80076998();
extern undefined4 FUN_80077318();
extern uint FUN_800e8024();
extern undefined4 FUN_80121f30();
extern undefined8 FUN_801228d8();
extern undefined4 FUN_80124a78();
extern undefined4 FUN_80124b38();
extern undefined8 FUN_8012c894();
extern undefined4 FUN_802475e4();
extern undefined4 FUN_80247618();
extern undefined4 FUN_8024782c();
extern undefined4 FUN_80247a48();
extern undefined4 FUN_80247a7c();
extern undefined4 FUN_80247d2c();
extern undefined4 FUN_802570dc();
extern undefined4 FUN_80257b5c();
extern undefined4 FUN_80258674();
extern undefined4 FUN_80258944();
extern undefined4 FUN_80259000();
extern undefined4 FUN_80259288();
extern undefined4 FUN_8025a454();
extern undefined4 FUN_8025a5bc();
extern undefined4 FUN_8025a608();
extern undefined4 FUN_8025b94c();
extern undefined4 FUN_8025b9e8();
extern undefined4 FUN_8025bb48();
extern undefined4 FUN_8025bd1c();
extern undefined4 FUN_8025be54();
extern undefined4 FUN_8025be80();
extern undefined4 FUN_8025c1a4();
extern undefined4 FUN_8025c224();
extern undefined4 FUN_8025c2a8();
extern undefined4 FUN_8025c368();
extern undefined4 FUN_8025c428();
extern undefined4 FUN_8025c510();
extern undefined4 FUN_8025c584();
extern undefined4 FUN_8025c5f0();
extern undefined4 FUN_8025c65c();
extern undefined4 FUN_8025c754();
extern undefined4 FUN_8025c828();
extern undefined4 FUN_8025ca04();
extern undefined4 FUN_8025cce8();
extern undefined4 FUN_8025d80c();
extern undefined4 FUN_8025d848();
extern undefined4 FUN_8025d888();
extern undefined4 FUN_8025d8c4();
extern undefined8 FUN_8025da88();
extern undefined4 FUN_8025db38();
extern undefined4 FUN_80286834();
extern undefined8 FUN_80286838();
extern undefined8 FUN_8028683c();
extern undefined4 FUN_80286840();
extern undefined4 FUN_80286880();
extern undefined4 FUN_80286884();
extern undefined4 FUN_80286888();
extern undefined4 FUN_8028688c();
extern undefined4 FUN_8028fde8();
extern undefined4 FUN_802945e0();
extern undefined4 FUN_80294964();
extern undefined4 FUN_80294cac();
extern uint FUN_80296328();
extern int FUN_80297a08();
extern undefined4 SUB42();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4 DAT_802c292c;
extern undefined4 DAT_802c2930;
extern undefined4 DAT_802c2934;
extern undefined4 DAT_802c2938;
extern undefined4 DAT_802c293c;
extern undefined4 DAT_802c2940;
extern undefined4 DAT_8031cbf0;
extern undefined4 DAT_80397480;
extern undefined4 DAT_803a9450;
extern undefined4 DAT_803a9490;
extern undefined4 DAT_803a95b0;
extern undefined4 DAT_803a9610;
extern undefined4 DAT_803a9764;
extern undefined4 DAT_803a9768;
extern undefined4 DAT_803a976c;
extern undefined4 DAT_803a978c;
extern undefined4 DAT_803a9790;
extern undefined4 DAT_803a9794;
extern undefined4 DAT_803a9798;
extern undefined4 DAT_803a97a4;
extern undefined4 DAT_803a9f1c;
extern undefined4 DAT_803a9f24;
extern undefined4 DAT_803a9f28;
extern undefined4 DAT_803a9f40;
extern undefined4 DAT_803a9f44;
extern undefined4 DAT_803a9f48;
extern undefined4 DAT_803a9f4c;
extern undefined4 DAT_803a9f50;
extern undefined4 DAT_803a9f58;
extern undefined4 DAT_803a9f5c;
extern undefined4 DAT_803a9f60;
extern undefined4 DAT_803a9f68;
extern undefined4 DAT_803a9f70;
extern undefined4 DAT_803a9f74;
extern undefined4 DAT_803a9f78;
extern undefined4 DAT_803a9f7c;
extern undefined4 DAT_803a9fc4;
extern undefined4 DAT_803a9fc8;
extern undefined4 DAT_803a9fd0;
extern undefined4 DAT_803a9fd4;
extern undefined4 DAT_803a9fe0;
extern undefined4 DAT_803a9fe8;
extern undefined4 DAT_803a9fec;
extern undefined4 DAT_803a9ff0;
extern undefined4 DAT_803a9ff4;
extern undefined4 DAT_803a9ff8;
extern undefined4 DAT_803a9ffc;
extern undefined4 DAT_803aa000;
extern undefined4 DAT_803aa004;
extern int DAT_803aa040;
extern int DAT_803aa04c;
extern int DAT_803aa070;
extern int DAT_803aa080;
extern undefined4 DAT_803aa088;
extern undefined4 DAT_803aa094;
extern undefined DAT_803b0000;
extern undefined4 DAT_803dc070;
extern undefined4 DAT_803dc084;
extern undefined4 DAT_803dc6c0;
extern undefined4 DAT_803dc6c1;
extern undefined4 DAT_803dc6c2;
extern undefined4 DAT_803dc6d8;
extern undefined4 DAT_803dc6f2;
extern undefined4 DAT_803dc750;
extern undefined4 DAT_803dc754;
extern undefined4 DAT_803dc755;
extern undefined4 DAT_803dc756;
extern undefined4 DAT_803dc757;
extern undefined4 DAT_803dc758;
extern undefined4 DAT_803dc778;
extern undefined4 DAT_803dc780;
extern undefined4 DAT_803dc784;
extern undefined4 DAT_803dc788;
extern undefined4 DAT_803dc78c;
extern undefined4 DAT_803dc790;
extern undefined4 DAT_803dc794;
extern undefined4 DAT_803dc798;
extern undefined4 DAT_803dc79c;
extern undefined4 DAT_803dc7a0;
extern undefined4 DAT_803dc7a8;
extern undefined4* DAT_803dd6d0;
extern undefined4* DAT_803dd72c;
extern undefined4 DAT_803de3b0;
extern undefined4 DAT_803de3c0;
extern undefined4 DAT_803de3da;
extern undefined4 DAT_803de3db;
extern undefined4 DAT_803de3ec;
extern undefined4 DAT_803de3ee;
extern undefined4 DAT_803de3f0;
extern undefined4 DAT_803de3f2;
extern undefined4 DAT_803de3f8;
extern undefined4 DAT_803de400;
extern undefined4 DAT_803de408;
extern undefined4 DAT_803de412;
extern undefined4 DAT_803de413;
extern undefined4 DAT_803de418;
extern undefined4 DAT_803de428;
extern undefined4 DAT_803de42a;
extern undefined4 DAT_803de42c;
extern undefined4 DAT_803de433;
extern undefined4 DAT_803de445;
extern undefined4 DAT_803de44c;
extern undefined4 DAT_803de450;
extern undefined4 DAT_803de458;
extern undefined4 DAT_803de46c;
extern undefined4 DAT_803de478;
extern undefined4 DAT_803de479;
extern undefined4 DAT_803de4b8;
extern undefined4 DAT_803de4dc;
extern undefined4* DAT_803de4e0;
extern undefined4* DAT_803de4e8;
extern undefined4 DAT_803de4f4;
extern undefined4 DAT_803de504;
extern undefined4 DAT_803de50a;
extern undefined4 DAT_803de550;
extern undefined4 DAT_803de55c;
extern undefined4 DAT_803e2aac;
extern undefined4 DAT_803e2ab0;
extern undefined4 DAT_803e2ab4;
extern undefined4 DAT_803e2ab8;
extern undefined4 DAT_cc008000;
extern f64 DOUBLE_803e2af8;
extern f64 DOUBLE_803e2b08;
extern f64 DOUBLE_803e2b20;
extern f64 DOUBLE_803e2b28;
extern f64 DOUBLE_803e2b30;
extern f64 DOUBLE_803e2b38;
extern f64 DOUBLE_803e2b70;
extern f64 DOUBLE_803e2b78;
extern f64 DOUBLE_803e2b80;
extern f64 DOUBLE_803e2ba0;
extern f64 DOUBLE_803e2bb8;
extern f64 DOUBLE_803e2bc0;
extern f64 DOUBLE_803e2bd0;
extern f64 DOUBLE_803e2bd8;
extern f64 DOUBLE_803e2be0;
extern f64 DOUBLE_803e2be8;
extern f64 DOUBLE_803e2bf8;
extern f64 DOUBLE_803e2c00;
extern f64 DOUBLE_803e2c08;
extern f32 FLOAT_803dc074;
extern f32 FLOAT_803dc6f4;
extern f32 FLOAT_803dc74c;
extern f32 FLOAT_803dc75c;
extern f32 FLOAT_803dc760;
extern f32 FLOAT_803dc764;
extern f32 FLOAT_803dc768;
extern f32 FLOAT_803dc76c;
extern f32 FLOAT_803dc770;
extern f32 FLOAT_803dc774;
extern f32 FLOAT_803dc77c;
extern f32 FLOAT_803de3e0;
extern f32 FLOAT_803de3e4;
extern f32 FLOAT_803de470;
extern f32 FLOAT_803de474;
extern f32 FLOAT_803de47c;
extern f32 FLOAT_803de480;
extern f32 FLOAT_803de484;
extern f32 FLOAT_803de488;
extern f32 FLOAT_803de48c;
extern f32 FLOAT_803de490;
extern f32 FLOAT_803de494;
extern f32 FLOAT_803de498;
extern f32 FLOAT_803de4bc;
extern f32 FLOAT_803de4c4;
extern f32 FLOAT_803de4d0;
extern f32 FLOAT_803e2abc;
extern f32 FLOAT_803e2ac0;
extern f32 FLOAT_803e2ac4;
extern f32 FLOAT_803e2ac8;
extern f32 FLOAT_803e2acc;
extern f32 FLOAT_803e2ad0;
extern f32 FLOAT_803e2ad4;
extern f32 FLOAT_803e2ad8;
extern f32 FLOAT_803e2adc;
extern f32 FLOAT_803e2ae0;
extern f32 FLOAT_803e2ae4;
extern f32 FLOAT_803e2ae8;
extern f32 FLOAT_803e2aec;
extern f32 FLOAT_803e2af0;
extern f32 FLOAT_803e2b00;
extern f32 FLOAT_803e2b10;
extern f32 FLOAT_803e2b14;
extern f32 FLOAT_803e2b18;
extern f32 FLOAT_803e2b1c;
extern f32 FLOAT_803e2b40;
extern f32 FLOAT_803e2b44;
extern f32 FLOAT_803e2b4c;
extern f32 FLOAT_803e2b50;
extern f32 FLOAT_803e2b54;
extern f32 FLOAT_803e2b5c;
extern f32 FLOAT_803e2b60;
extern f32 FLOAT_803e2b64;
extern f32 FLOAT_803e2b68;
extern f32 FLOAT_803e2b88;
extern f32 FLOAT_803e2b8c;
extern f32 FLOAT_803e2b90;
extern f32 FLOAT_803e2b94;
extern f32 FLOAT_803e2b98;
extern f32 FLOAT_803e2bb0;
extern f32 FLOAT_803e2bc8;
extern f32 FLOAT_803e2bcc;
extern f32 FLOAT_803e2bf0;
extern f32 FLOAT_803e2c10;
extern f32 FLOAT_803e2c14;
extern f32 FLOAT_803e2c18;
extern f32 FLOAT_803e2c1c;
extern f32 FLOAT_803e2c20;
extern f32 FLOAT_803e2c24;
extern f32 FLOAT_803e2c28;
extern f32 FLOAT_803e2c2c;
extern f32 FLOAT_803e2c30;
extern f32 FLOAT_803e2c34;
extern undefined* PTR_DAT_8031c228;
extern int iRam803de4e4;
extern undefined4* puRam803de4e4;
extern undefined4* puRam803de4ec;
extern char s_x___2f_8031ccf4[];

/* Local declarations keep imported functions visible within the TU. */
void FUN_8011dc94(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8);
void FUN_8011e014(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8);
void FUN_8011e06c(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8);
void FUN_8011e104(int param_1,undefined param_2,undefined4 param_3,char param_4);
undefined4 FUN_8011e3bc(int param_1,int *param_2,int param_3);
void FUN_8011e974(double param_1,double param_2,double param_3,double param_4,int param_5,
                 int param_6,int param_7,int param_8);
void FUN_8011ebbc(undefined8 param_1,double param_2,undefined4 param_3,undefined4 param_4,
                 undefined param_5,int param_6,int param_7,int param_8,int param_9);
void FUN_8011ee20(undefined8 param_1,double param_2,undefined4 param_3,undefined4 param_4,
                 undefined param_5,uint param_6,int param_7,int param_8,uint param_9);
void FUN_8011f088(double param_1,double param_2,int param_3,int param_4,undefined param_5,
                 uint param_6,byte param_7);
void FUN_8011f234(double param_1,double param_2,double param_3,double param_4,ushort param_5,
                 ushort param_6,ushort param_7);
void FUN_8011f534(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8);
undefined FUN_8011f628(void);
void FUN_8011f630(undefined param_1);
void FUN_8011f638(byte param_1);
void FUN_8011f670(undefined param_1);
void FUN_8011f678(void);
short FUN_8011f68c(undefined2 *param_1);
void FUN_8011f6ac(undefined param_1);
void FUN_8011f6c4(undefined2 param_1);
void FUN_8011f6d0(undefined2 param_1);
void FUN_8011f6e8(void);
void FUN_8011f9b8(ushort param_1);
void FUN_8011f9c4(undefined param_1,undefined param_2,undefined2 param_3);
void FUN_8011f9d4(undefined param_1);
void FUN_8011fa10(void);
void FUN_8011faa8(void);
void FUN_8011ff40(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 undefined4 param_9,undefined4 param_10,undefined4 param_11,undefined4 param_12,
                 undefined4 param_13,undefined4 param_14,undefined4 param_15,undefined4 param_16);
void FUN_80120028(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 undefined4 param_9,undefined4 param_10,undefined4 param_11,undefined4 param_12,
                 undefined4 param_13,undefined4 param_14,undefined4 param_15,undefined4 param_16);
void FUN_801200f0(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4,
                 undefined4 param_5,undefined4 param_6,undefined4 param_7,undefined4 param_8);
void FUN_8012146c(undefined4 param_1,undefined4 *param_2);
void FUN_801215c8(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 short param_9,undefined4 param_10,undefined4 param_11,undefined4 param_12,
                 undefined4 param_13,undefined4 param_14,undefined4 param_15,undefined4 param_16);
void FUN_8012162c(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 undefined4 param_9,undefined4 param_10,undefined4 param_11,undefined4 param_12,
                 undefined4 param_13,undefined4 param_14,undefined4 param_15,undefined4 param_16);
void FUN_80121724(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8);

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8011DC94
 * EN v1.0 Size: 896b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: address-of global symbols need manual typing. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_8011dc94(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8011E014
 * EN v1.0 Size: 88b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

// Function: FUN_8011e014
// Entry: 8011e014
// Size: 88 bytes

void FUN_8011e014(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8)

{
  double dVar1;
  undefined8 uVar2;
  
  FUN_800207ac(1);
  dVar1 = (double)FUN_800206ec(0xff);
  uVar2 = FUN_8012c894(dVar1,param_2,param_3,param_4,param_5,param_6,param_7,param_8);
  DAT_803de400 = 0xb;
  DAT_803de55c = FUN_80019c28();
  FUN_800199a8(uVar2,param_2,param_3,param_4,param_5,param_6,param_7,param_8,0xb);
  FLOAT_803de3e4 = FLOAT_803e2ae0;
  DAT_803de458 = 1;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8011E06C
 * EN v1.0 Size: 152b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: function-pointer stores need manual cleanup. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_8011e06c(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8011E104
 * EN v1.0 Size: 696b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: unsupported body pseudo-types, address-of global symbols need manual typing. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_8011e104(int param_1,undefined param_2,undefined4 param_3,char param_4)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8011E3BC
 * EN v1.0 Size: 1464b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: address-of global symbols need manual typing. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

undefined4 FUN_8011e3bc(int param_1,int *param_2,int param_3)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8011E974
 * EN v1.0 Size: 584b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: invalid Ghidra slice syntax, address-of global symbols need manual typing. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_8011e974(double param_1,double param_2,double param_3,double param_4,int param_5,
                 int param_6,int param_7,int param_8)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8011EBBC
 * EN v1.0 Size: 612b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: invalid Ghidra slice syntax. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_8011ebbc(undefined8 param_1,double param_2,undefined4 param_3,undefined4 param_4,
                 undefined param_5,int param_6,int param_7,int param_8,int param_9)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8011EE20
 * EN v1.0 Size: 616b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: invalid Ghidra slice syntax. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_8011ee20(undefined8 param_1,double param_2,undefined4 param_3,undefined4 param_4,
                 undefined param_5,uint param_6,int param_7,int param_8,uint param_9)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8011F088
 * EN v1.0 Size: 428b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: invalid Ghidra slice syntax. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_8011f088(double param_1,double param_2,int param_3,int param_4,undefined param_5,
                 uint param_6,byte param_7)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8011F234
 * EN v1.0 Size: 768b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: address-of global symbols need manual typing. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_8011f234(double param_1,double param_2,double param_3,double param_4,ushort param_5,
                 ushort param_6,ushort param_7)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8011F534
 * EN v1.0 Size: 244b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: address-of global symbols need manual typing. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_8011f534(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8011F628
 * EN v1.0 Size: 8b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

// Function: FUN_8011f628
// Entry: 8011f628
// Size: 8 bytes

undefined FUN_8011f628(void)

{
  return DAT_803de400;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8011F630
 * EN v1.0 Size: 8b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

// Function: FUN_8011f630
// Entry: 8011f630
// Size: 8 bytes

void FUN_8011f630(undefined param_1)

{
  DAT_803de433 = param_1;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8011F638
 * EN v1.0 Size: 56b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

// Function: FUN_8011f638
// Entry: 8011f638
// Size: 56 bytes

void FUN_8011f638(byte param_1)

{
  DAT_803de44c = param_1 & 1;
  if (param_1 == 3) {
    DAT_803de4b8 = 0xff;
    return;
  }
  if (2 < param_1) {
    return;
  }
  if (param_1 < 2) {
    return;
  }
  DAT_803de4b8 = 0;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8011F670
 * EN v1.0 Size: 8b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

// Function: FUN_8011f670
// Entry: 8011f670
// Size: 8 bytes

void FUN_8011f670(undefined param_1)

{
  DAT_803de412 = param_1;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8011F678
 * EN v1.0 Size: 20b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

// Function: FUN_8011f678
// Entry: 8011f678
// Size: 20 bytes

void FUN_8011f678(void)

{
  DAT_803de504 = 0;
  DAT_803de4f4 = 0xffff;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8011F68C
 * EN v1.0 Size: 32b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

// Function: FUN_8011f68c
// Entry: 8011f68c
// Size: 32 bytes

short FUN_8011f68c(undefined2 *param_1)

{
  if (DAT_803de504 != 0) {
    *param_1 = DAT_803de50a;
  }
  return DAT_803de504;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8011F6AC
 * EN v1.0 Size: 24b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

// Function: FUN_8011f6ac
// Entry: 8011f6ac
// Size: 24 bytes

void FUN_8011f6ac(undefined param_1)

{
  if (DAT_803de42c != '\0') {
    return;
  }
  DAT_803de42c = param_1;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8011F6C4
 * EN v1.0 Size: 12b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

// Function: FUN_8011f6c4
// Entry: 8011f6c4
// Size: 12 bytes

void FUN_8011f6c4(undefined2 param_1)

{
  DAT_803de42a = param_1;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8011F6D0
 * EN v1.0 Size: 24b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

// Function: FUN_8011f6d0
// Entry: 8011f6d0
// Size: 24 bytes

void FUN_8011f6d0(undefined2 param_1)

{
  if (DAT_803de42a != 0) {
    return;
  }
  DAT_803de42a = param_1;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8011F6E8
 * EN v1.0 Size: 720b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

// Function: FUN_8011f6e8
// Entry: 8011f6e8
// Size: 720 bytes

void FUN_8011f6e8(void)

{
  short sVar1;
  uint uVar2;
  uint uVar3;
  uint uVar4;
  uint uVar5;
  undefined4 local_58;
  int local_54;
  int local_50;
  int local_4c;
  int local_48;
  undefined4 local_44;
  undefined4 local_40;
  uint uStack_3c;
  undefined4 local_38;
  uint uStack_34;
  undefined4 local_30;
  uint uStack_2c;
  undefined4 local_28;
  uint uStack_24;
  undefined4 local_20;
  uint uStack_1c;
  
  uVar5 = (uint)*(ushort *)(DAT_803a9790 + 0xc);
  uVar3 = (uint)DAT_803dc6c1;
  uVar2 = (uint)DAT_803dc6c0;
  uVar4 = *(ushort *)(DAT_803a978c + 10) & 0xff;
  if (DAT_803de3ee == 0) {
    sVar1 = -((ushort)DAT_803dc758 * (ushort)DAT_803dc070);
  }
  else {
    sVar1 = (ushort)DAT_803dc758 * (ushort)DAT_803dc070;
  }
  DAT_803de3ec = DAT_803de3ec + sVar1;
  if (DAT_803de3ec < 0) {
    DAT_803de3ec = 0;
  }
  else if (0xff < DAT_803de3ec) {
    DAT_803de3ec = 0xff;
  }
  if (DAT_803de3ec != 0) {
    FUN_8025db38(&local_48,&local_4c,&local_50,&local_54);
    FUN_8025da88(0,0,0x280,0x1e0);
    uStack_3c = (0x140 - (uint)DAT_803dc6c0) - uVar4 ^ 0x80000000;
    local_40 = 0x43300000;
    FUN_80076998((double)(float)((double)CONCAT44(0x43300000,uStack_3c) - DOUBLE_803e2af8),
                 (double)FLOAT_803e2b1c,DAT_803a978c,(int)DAT_803de3ec & 0xff,0x100,uVar4,uVar5,1);
    uStack_34 = 0x140 - DAT_803dc6c1 ^ 0x80000000;
    local_38 = 0x43300000;
    FUN_80076998((double)(float)((double)CONCAT44(0x43300000,uStack_34) - DOUBLE_803e2af8),
                 (double)FLOAT_803e2b1c,DAT_803a9790,(int)DAT_803de3ec & 0xff,0x100,
                 (uint)DAT_803dc6c1 << 1,uVar5,0);
    uStack_2c = 0x140 - DAT_803dc6c0 ^ 0x80000000;
    local_30 = 0x43300000;
    FUN_80076998((double)(float)((double)CONCAT44(0x43300000,uStack_2c) - DOUBLE_803e2af8),
                 (double)FLOAT_803e2b1c,DAT_803a9794,(int)DAT_803de3ec & 0xff,0x100,uVar2 - uVar3,
                 uVar5,0);
    uStack_24 = DAT_803dc6c1 + 0x140 ^ 0x80000000;
    local_28 = 0x43300000;
    FUN_80076998((double)(float)((double)CONCAT44(0x43300000,uStack_24) - DOUBLE_803e2af8),
                 (double)FLOAT_803e2b1c,DAT_803a9794,(int)DAT_803de3ec & 0xff,0x100,uVar2 - uVar3,
                 uVar5,0);
    uStack_1c = DAT_803dc6c0 + 0x140 ^ 0x80000000;
    local_20 = 0x43300000;
    FUN_80077318((double)(float)((double)CONCAT44(0x43300000,uStack_1c) - DOUBLE_803e2af8),
                 (double)FLOAT_803e2b1c,DAT_803a978c,(int)DAT_803de3ec & 0xff,0x100);
    local_44 = CONCAT31(0xff0000,(char)DAT_803de3ec);
    local_58 = local_44;
    FUN_80075534((DAT_803dc6c2 + 0x140) - (uint)DAT_803dc757,DAT_803dc756 + 0x32,
                 (uint)DAT_803dc757 + DAT_803dc6c2 + 0x140,(uVar5 + 0x32) - (uint)DAT_803dc756,
                 &local_58);
    FUN_8025da88(local_48,local_4c,local_50,local_54);
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8011F9B8
 * EN v1.0 Size: 12b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

// Function: FUN_8011f9b8
// Entry: 8011f9b8
// Size: 12 bytes

void FUN_8011f9b8(ushort param_1)

{
  DAT_803de3ee = param_1 & 0xff;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8011F9C4
 * EN v1.0 Size: 16b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

// Function: FUN_8011f9c4
// Entry: 8011f9c4
// Size: 16 bytes

void FUN_8011f9c4(undefined param_1,undefined param_2,undefined2 param_3)

{
  DAT_803dc6c0 = param_1;
  DAT_803dc6c1 = param_2;
  DAT_803dc6c2 = param_3;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8011F9D4
 * EN v1.0 Size: 60b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

// Function: FUN_8011f9d4
// Entry: 8011f9d4
// Size: 8 bytes

void FUN_8011f9d4(undefined param_1)

{
  DAT_803de3da = param_1;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8011FA10
 * EN v1.0 Size: 152b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

// Function: FUN_8011fa10
// Entry: 8011fa10
// Size: 152 bytes

void FUN_8011fa10(void)

{
  uint uVar1;
  int iVar2;
  
  uVar1 = DAT_803de450;
  if (DAT_803de450 != 0) {
    *(undefined *)(DAT_803de450 + 0x18) = 0;
    iVar2 = *(int *)(uVar1 + 0x40);
    if (iVar2 == 1) {
      FUN_80054484();
      FUN_80054484();
      FUN_80054484();
      FUN_80054484();
    }
    else if ((iVar2 < 1) && (-1 < iVar2)) {
      FUN_80054484();
      FUN_80054484();
    }
    FUN_800238c4(DAT_803de450);
    DAT_803de450 = 0;
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8011FAA8
 * EN v1.0 Size: 1176b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

// Function: FUN_8011faa8
// Entry: 8011faa8
// Size: 1092 bytes

/* WARNING: Removing unreachable block (ram,0x8011fec4) */
/* WARNING: Removing unreachable block (ram,0x8011febc) */
/* WARNING: Removing unreachable block (ram,0x8011fac0) */
/* WARNING: Removing unreachable block (ram,0x8011fab8) */

void FUN_8011faa8(void)

{
  byte bVar1;
  int iVar2;
  short sVar3;
  ushort uVar4;
  int iVar5;
  int iVar6;
  char cVar7;
  uint uVar8;
  double dVar9;
  double dVar10;
  int local_78;
  int local_74;
  int local_70;
  int local_6c [3];
  undefined4 local_60;
  uint uStack_5c;
  undefined4 local_58;
  uint uStack_54;
  undefined4 local_50;
  uint uStack_4c;
  undefined4 local_48;
  uint uStack_44;
  undefined4 local_40;
  uint uStack_3c;
  
  iVar5 = FUN_8002bac4();
  iVar2 = DAT_803de450;
  if (DAT_803de450 != 0) {
    bVar1 = *(byte *)(DAT_803de450 + 0x18);
    if ((((*(char *)(DAT_803de450 + 0x44) < '\0') || (DAT_803de400 != '\0')) ||
        (iVar6 = FUN_80020800(), iVar6 != 0)) ||
       (((iVar5 != 0 && ((*(ushort *)(iVar5 + 0xb0) & 0x1000) != 0)) &&
        (*(short *)(iVar2 + 0x2c) != 0x5d5)))) {
      sVar3 = (ushort)bVar1 + (ushort)DAT_803dc070 * -4;
      if (sVar3 < 0) {
        sVar3 = 0;
      }
      *(char *)(iVar2 + 0x18) = (char)sVar3;
      if ((*(char *)(iVar2 + 0x18) == '\0') && ((char)*(byte *)(iVar2 + 0x44) < '\0')) {
        *(byte *)(iVar2 + 0x44) = *(byte *)(iVar2 + 0x44) & 0x7f;
        FUN_8011fa10();
        return;
      }
    }
    else {
      uVar4 = (ushort)bVar1 + (ushort)DAT_803dc070 * 4;
      if (0xff < uVar4) {
        uVar4 = 0xff;
      }
      *(char *)(iVar2 + 0x18) = (char)uVar4;
    }
    FUN_8025db38(local_6c,&local_70,&local_74,&local_78);
    FUN_8025da88(0,0,0x280,0x1e0);
    iVar5 = *(int *)(iVar2 + 0x40);
    if (iVar5 == 1) {
      uVar4 = *(ushort *)(iVar2 + 0x2c);
      if (uVar4 == 0x643) {
        cVar7 = -0xc;
      }
      else if ((uVar4 < 0x643) && (uVar4 == 0x63e)) {
        cVar7 = -10;
      }
      else {
        cVar7 = '\0';
      }
      uStack_5c = (int)DAT_803de479 + 0xb5U ^ 0x80000000;
      local_60 = 0x43300000;
      local_6c[2] = (0x1a4 - (uint)(*(ushort *)(*(int *)(iVar2 + 0x30) + 0xc) >> 1)) +
                    (int)DAT_803dc754 + (int)cVar7 + (int)DAT_803de478 ^ 0x80000000;
      local_6c[1] = 0x43300000;
      FUN_80077318((double)(float)((double)CONCAT44(0x43300000,uStack_5c) - DOUBLE_803e2af8),
                   (double)(float)((double)CONCAT44(0x43300000,local_6c[2]) - DOUBLE_803e2af8),
                   *(int *)(iVar2 + 0x30),(uint)*(byte *)(iVar2 + 0x18),0x100);
      uVar8 = *(ushort *)(*(int *)(iVar2 + 0x30) + 10) + 0xb4;
      uStack_4c = 0x1a4 - (*(ushort *)(*(int *)(iVar2 + 0x34) + 0xc) >> 1);
      if (*(int *)(iVar2 + 8) < 0x9e) {
        *(uint *)(iVar2 + 8) = *(int *)(iVar2 + 8) + (uint)DAT_803dc070 * (uint)DAT_803dc755;
      }
      iVar5 = *(int *)(iVar2 + 0xc);
      if (iVar5 < 0) {
        iVar5 = 0;
      }
      else if (*(int *)(iVar2 + 8) < iVar5) {
        iVar5 = *(int *)(iVar2 + 8);
      }
      *(int *)(iVar2 + 0xc) = iVar5;
      iVar5 = (int)(short)iVar5;
      uStack_5c = uVar8 + iVar5 ^ 0x80000000;
      local_60 = 0x43300000;
      local_6c[2] = uStack_4c ^ 0x80000000;
      local_6c[1] = 0x43300000;
      FUN_80076998((double)(float)((double)CONCAT44(0x43300000,uStack_5c) - DOUBLE_803e2af8),
                   (double)(float)((double)CONCAT44(0x43300000,local_6c[2]) - DOUBLE_803e2af8),
                   *(undefined4 *)(iVar2 + 0x3c),(uint)*(byte *)(iVar2 + 0x18),0x100,
                   *(int *)(iVar2 + 8) - iVar5,0x1a,0);
      uStack_54 = uVar8 ^ 0x80000000;
      local_58 = 0x43300000;
      uStack_4c = uStack_4c ^ 0x80000000;
      local_50 = 0x43300000;
      FUN_80076998((double)(float)((double)CONCAT44(0x43300000,uStack_54) - DOUBLE_803e2af8),
                   (double)(float)((double)CONCAT44(0x43300000,uStack_4c) - DOUBLE_803e2af8),
                   *(undefined4 *)(iVar2 + 0x38),(uint)*(byte *)(iVar2 + 0x18),0x100,iVar5,0x1a,0);
      uStack_44 = uVar8 + *(int *)(iVar2 + 8) ^ 0x80000000;
      local_48 = 0x43300000;
      uStack_3c = 0x1a4 - (*(ushort *)(*(int *)(iVar2 + 0x34) + 0xc) >> 1) ^ 0x80000000;
      local_40 = 0x43300000;
      FUN_80077318((double)(float)((double)CONCAT44(0x43300000,uStack_44) - DOUBLE_803e2af8),
                   (double)(float)((double)CONCAT44(0x43300000,uStack_3c) - DOUBLE_803e2af8),
                   *(int *)(iVar2 + 0x34),(uint)*(byte *)(iVar2 + 0x18),0x100);
    }
    else if ((iVar5 < 1) && (-1 < iVar5)) {
      uVar8 = 0x140 - ((uint)(*(int *)(iVar2 + 0x10) * *(int *)(iVar2 + 4)) >> 1);
      dVar9 = DOUBLE_803e2af8;
      dVar10 = DOUBLE_803e2b08;
      for (iVar5 = 0; iVar5 < *(int *)(iVar2 + 4); iVar5 = iVar5 + 1) {
        if (iVar5 < *(int *)(iVar2 + 0xc)) {
          iVar6 = *(int *)(iVar2 + 0x2c);
        }
        else {
          iVar6 = *(int *)(iVar2 + 0x30);
        }
        local_6c[2] = uVar8 ^ 0x80000000;
        local_6c[1] = 0x43300000;
        uStack_5c = 0x1a4 - *(int *)(iVar2 + 0x14);
        local_60 = 0x43300000;
        FUN_80077318((double)(float)((double)CONCAT44(0x43300000,local_6c[2]) - dVar9),
                     (double)(float)((double)CONCAT44(0x43300000,uStack_5c) - dVar10),iVar6,
                     (uint)*(byte *)(iVar2 + 0x18),0x100);
        uVar8 = uVar8 + *(int *)(iVar2 + 0x10);
      }
    }
    FUN_8025da88(local_6c[0],local_70,local_74,local_78);
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8011FF40
 * EN v1.0 Size: 232b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: typed global pointer comparisons need manual cleanup. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_8011ff40(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 undefined4 param_9,undefined4 param_10,undefined4 param_11,undefined4 param_12,
                 undefined4 param_13,undefined4 param_14,undefined4 param_15,undefined4 param_16)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80120028
 * EN v1.0 Size: 200b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: typed global pointer comparisons need manual cleanup. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_80120028(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 undefined4 param_9,undefined4 param_10,undefined4 param_11,undefined4 param_12,
                 undefined4 param_13,undefined4 param_14,undefined4 param_15,undefined4 param_16)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801200F0
 * EN v1.0 Size: 4988b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: unsupported body pseudo-types, raw string-label references need manual cleanup, address-of global symbols need manual typing. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801200f0(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4,
                 undefined4 param_5,undefined4 param_6,undefined4 param_7,undefined4 param_8)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8012146C
 * EN v1.0 Size: 348b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

// Function: FUN_8012146c
// Entry: 8012146c
// Size: 348 bytes

void FUN_8012146c(undefined4 param_1,undefined4 *param_2)

{
  float fVar1;
  uint uVar2;
  
  if (-1 < (int)param_2[1]) {
    param_2[1] = param_2[1] - (uint)DAT_803dc070;
    fVar1 = FLOAT_803e2b40;
    if ((int)param_2[1] < 0) {
      FUN_80054484();
      *param_2 = 0;
    }
    else {
      uVar2 = param_2[1] ^ 0x80000000;
      if (FLOAT_803e2c1c <= (float)((double)CONCAT44(0x43300000,uVar2) - DOUBLE_803e2af8)) {
        if (FLOAT_803e2b40 != (float)param_2[2]) {
          param_2[2] = FLOAT_803e2c20 *
                       (float)((double)CONCAT44(0x43300000,(uint)DAT_803dc070) - DOUBLE_803e2b08) +
                       (float)param_2[2];
          if (fVar1 < (float)param_2[2]) {
            param_2[2] = fVar1;
          }
        }
      }
      else {
        param_2[2] = (FLOAT_803e2b40 * (float)((double)CONCAT44(0x43300000,uVar2) - DOUBLE_803e2af8)
                     ) / FLOAT_803e2c1c;
      }
      FUN_800033a8(-0x7fc55f78,0,0xc);
      DAT_803aa088 = *param_2;
      DAT_803aa094 = 0;
      FUN_80077318((double)FLOAT_803e2c24,
                   (double)(float)((double)CONCAT44(0x43300000,DAT_803de3c0 + 0xafU ^ 0x80000000) -
                                  DOUBLE_803e2af8),-0x7fc55f78,(int)(float)param_2[2],0x100);
    }
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801215C8
 * EN v1.0 Size: 100b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

// Function: FUN_801215c8
// Entry: 801215c8
// Size: 100 bytes

void FUN_801215c8(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 short param_9,undefined4 param_10,undefined4 param_11,undefined4 param_12,
                 undefined4 param_13,undefined4 param_14,undefined4 param_15,undefined4 param_16)

{
  DAT_803a9ff8 = FUN_80054ed0(param_1,param_2,param_3,param_4,param_5,param_6,param_7,param_8,
                              (int)param_9,param_10,param_11,param_12,param_13,param_14,param_15,
                              param_16);
  if (DAT_803a9ff8 != 0) {
    DAT_803aa004 = (undefined2)param_11;
    DAT_803aa000 = FLOAT_803e2abc;
    DAT_803a9ffc = param_10;
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8012162C
 * EN v1.0 Size: 248b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: unsupported body pseudo-types, address-of global symbols need manual typing. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_8012162c(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 undefined4 param_9,undefined4 param_10,undefined4 param_11,undefined4 param_12,
                 undefined4 param_13,undefined4 param_14,undefined4 param_15,undefined4 param_16)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80121724
 * EN v1.0 Size: 2060b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: address-of global symbols need manual typing, unsupported helper macros: SUB42, function-pointer stores need manual cleanup. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_80121724(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}
