/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/waterfallControl.c
 * Text span: 0x80163E3C-0x80164438
 * Imported Ghidra functions: 2
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 2
 */

#include "ghidra_import.h"
#include "main/dll/waterfallControl.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_8000bb38();
extern uint FUN_80022264();
extern int FUN_80065800();
extern int FUN_80065fcc();

/* Raw global references kept as loose externs for later cleanup. */
extern f64 DOUBLE_803e3c08;
extern f64 DOUBLE_803e3c28;
extern f32 FLOAT_803dc074;
extern f32 FLOAT_803e3bf4;
extern f32 FLOAT_803e3bf8;
extern f32 FLOAT_803e3bfc;
extern f32 FLOAT_803e3c00;
extern f32 FLOAT_803e3c10;
extern f32 FLOAT_803e3c14;
extern f32 FLOAT_803e3c18;
extern f32 FLOAT_803e3c1c;
extern f32 FLOAT_803e3c20;

/* Local declarations keep imported functions visible within the TU. */
void FUN_80163e3c(short *param_1,int param_2);
void FUN_80164068(short *param_1,int param_2);

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_80163e3c(short *param_1,int param_2)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_80164068(short *param_1,int param_2)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}
