/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 */

#ifndef DOLPHIN_TRK_MINNOW_DOLPHIN_MSG_H_
#define DOLPHIN_TRK_MINNOW_DOLPHIN_MSG_H_

#include "ghidra_import.h"

void FUN_80287460(int param_1);

#endif /* DOLPHIN_TRK_MINNOW_DOLPHIN_MSG_H_ */
