/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 */

#ifndef DOLPHIN_TRK_MINNOW_DOLPHIN_MSGHNDLR_H_
#define DOLPHIN_TRK_MINNOW_DOLPHIN_MSGHNDLR_H_

#include "ghidra_import.h"

void FUN_8028855c(int param_1);
void FUN_80288700(int param_1);
void FUN_80288800(int param_1);
void FUN_80288d30(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4,
                 undefined4 param_5,undefined4 param_6,undefined4 param_7,undefined4 param_8);
void FUN_80288e84(int param_1);
void FUN_8028917c(int param_1);
void FUN_80289544(int param_1);
void FUN_80289910(int param_1);
void FUN_80289d30(int param_1);
void FUN_8028a140(int param_1);
void FUN_8028a4d8(int param_1);
void FUN_8028a708(int param_1);
undefined4 FUN_8028a9e0(int param_1);
int FUN_8028aa98(int param_1);
void FUN_8028ab7c(int param_1);
void FUN_8028ac38(int param_1);
void FUN_8028ace8(int param_1,undefined param_2,undefined param_3);
void FUN_8028ada0();
undefined4 FUN_8028adac(void);

#endif /* DOLPHIN_TRK_MINNOW_DOLPHIN_MSGHNDLR_H_ */
