/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 */

#ifndef DOLPHIN_TRK_MINNOW_DOLPHIN_MUTEX_TRK_H_
#define DOLPHIN_TRK_MINNOW_DOLPHIN_MUTEX_TRK_H_

#include "ghidra_import.h"

undefined4 FUN_8028b658(void);
undefined4 FUN_8028b660(void);
undefined4 FUN_8028b668(void);

#endif /* DOLPHIN_TRK_MINNOW_DOLPHIN_MUTEX_TRK_H_ */
