/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/NW/NWtricky.c
 * Text span: 0x801D21EC-0x801D23AC
 * Imported Ghidra functions: 2
 * Verbatim-safe functions: 1
 * Auto-stubbed functions: 1
 */

#include "ghidra_import.h"
#include "main/dll/NW/NWtricky.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern uint FUN_80022264();
extern undefined4 FUN_80036018();
extern undefined4 FUN_8003613c();
extern undefined4 FUN_8003709c();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4* DAT_803dd6f8;
extern f64 DOUBLE_803e5fa0;
extern f32 FLOAT_803e5f90;
extern f32 FLOAT_803e5f94;
extern f32 FLOAT_803e5f98;
extern f32 FLOAT_803e5f9c;

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801D21EC
 * EN v1.0 Size: 376b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_801d21ec(undefined2 *param_1,undefined4 *param_2,int param_3)
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801D2364
 * EN v1.0 Size: 72b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_801d2364(int param_1)
{
  (**(code **)(*DAT_803dd6f8 + 0x14))();
  FUN_8003709c(param_1,3);
  return;
}
