/*
 * Auto-generated by tools/ghidra_unmanaged_homes.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists so every raw Ghidra function mapped to an unmanaged live owner
 * still has a concrete .c home for iteration/reference work.
 *
 * Live owner: dolphin/dsp/dsp.c
 * Text span: 0x80251624-0x80251830
 * Imported Ghidra functions: 9
 * Verbatim-safe functions: 6
 * Auto-stubbed functions: 3
 */
/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: dolphin/dsp/dsp.c
 * Text span: 0x80251624-0x80251830
 * Imported Ghidra functions: 9
 * Verbatim-safe functions: 6
 * Auto-stubbed functions: 3
 */

#include "ghidra_import.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_80243e74();
extern undefined4 FUN_80243e9c();
extern undefined4 FUN_80243ec0();
extern undefined4 FUN_802442c4();
extern undefined4 FUN_80251830();
extern undefined4 FUN_80251e44();
extern undefined4 FUN_80251fd0();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4 DAT_803dece0;
extern undefined4 DAT_803decf0;
extern undefined4 DAT_803decf4;
extern undefined4 DAT_803decf8;
extern undefined4 DAT_803decfc;
extern undefined4 DAT_cc005000;
extern undefined4 DAT_cc005002;
extern undefined4 DAT_cc005004;
extern undefined4 DAT_cc005006;
extern undefined4 DAT_cc00500a;

/* Local declarations keep imported functions visible within the TU. */
ushort FUN_80251624(void);
ushort FUN_80251634(void);
undefined4 FUN_80251644(void);
void FUN_8025165c(undefined4 param_1);
void FUN_80251670();
void FUN_80251728();
void FUN_80251770();
ushort FUN_802517b0(void);
undefined4 * FUN_802517c0(undefined4 *param_1);

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80251624
 * EN v1.0 Size: 16b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
ushort FUN_80251624(void)
{
  ushort uVar1;
  
  uVar1 = DAT_cc005000;
  return uVar1 >> 0xf;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80251634
 * EN v1.0 Size: 16b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
ushort FUN_80251634(void)
{
  ushort uVar1;
  
  uVar1 = DAT_cc005004;
  return uVar1 >> 0xf;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80251644
 * EN v1.0 Size: 24b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
undefined4 FUN_80251644(void)
{
  undefined2 uVar1;
  undefined2 uVar2;
  
  uVar1 = DAT_cc005004;
  uVar2 = DAT_cc005006;
  return CONCAT22(uVar1,uVar2);
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8025165C
 * EN v1.0 Size: 20b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8025165c(undefined4 param_1)
{
  DAT_cc005000 = (short)((uint)param_1 >> 0x10);
  DAT_cc005002 = (short)param_1;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80251670
 * EN v1.0 Size: 184b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80251670()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80251728
 * EN v1.0 Size: 72b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80251728()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80251770
 * EN v1.0 Size: 64b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80251770()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x802517B0
 * EN v1.0 Size: 16b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
ushort FUN_802517b0(void)
{
  ushort uVar1;
  
  uVar1 = DAT_cc00500a;
  return uVar1 & 0x200;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x802517C0
 * EN v1.0 Size: 112b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
undefined4 * FUN_802517c0(undefined4 *param_1)
{
  FUN_80243e74();
  FUN_80251fd0((int)param_1);
  *param_1 = 0;
  param_1[2] = 1;
  FUN_80243e9c();
  if (param_1 == DAT_803decf8) {
    FUN_80251e44((int)param_1);
  }
  return param_1;
}
