/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/SC/SCcollectables.c
 * Text span: 0x801D6F04-0x801D76A4
 * Imported Ghidra functions: 4
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 4
 */

#include "ghidra_import.h"
#include "main/dll/SC/SCcollectables.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_8000bb00();
extern undefined4 FUN_8000bb38();
extern undefined8 FUN_80014ba4();
extern uint FUN_80014e9c();
extern uint FUN_80020078();
extern uint FUN_80022264();
extern int FUN_8002bac4();
extern undefined4 FUN_8002fb40();
extern undefined4 FUN_80038524();
extern undefined4 FUN_80043070();
extern undefined4 FUN_80043604();
extern undefined4 FUN_80043658();
extern undefined8 FUN_80043938();
extern undefined4 FUN_8004832c();
extern uint FUN_800e8024();
extern undefined4 FUN_8028683c();
extern undefined4 FUN_80286888();
extern undefined4 FUN_80296cb4();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined DAT_803adca8;
extern undefined4 DAT_803adcb6;
extern undefined4 DAT_803adcba;
extern undefined4 DAT_803adcc3;
extern undefined4 DAT_803dccb8;
extern undefined4* DAT_803dd708;
extern undefined4* DAT_803dd72c;
extern undefined4 DAT_803de874;
extern f64 DOUBLE_803e6128;
extern f32 FLOAT_803dc074;
extern f32 FLOAT_803e60f8;
extern f32 FLOAT_803e60fc;
extern f32 FLOAT_803e6100;
extern f32 FLOAT_803e6104;
extern f32 FLOAT_803e6108;
extern f32 FLOAT_803e610c;
extern f32 FLOAT_803e6110;
extern f32 FLOAT_803e6114;
extern f32 FLOAT_803e6118;
extern f32 FLOAT_803e611c;
extern f32 FLOAT_803e6120;
extern f32 FLOAT_803e6130;

/* Local declarations keep imported functions visible within the TU. */
void FUN_801d6f04(int param_1);
void FUN_801d71f4(void);
undefined4 FUN_801d7348(void);
undefined4
FUN_801d7388(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
            undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
            undefined4 param_9,undefined4 param_10,int param_11);

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801d6f04(int param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: address-of global symbols need manual typing, forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801d71f4(void)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

undefined4 FUN_801d7348(void)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0;
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

undefined4
FUN_801d7388(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
            undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
            undefined4 param_9,undefined4 param_10,int param_11)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0;
}
