/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/SC/SCtotemstrength.c
 * Text span: 0x801D8190-0x801D8284
 * Imported Ghidra functions: 2
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 2
 */

#include "ghidra_import.h"
#include "main/dll/SC/SCtotemstrength.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern uint FUN_80020078();
extern undefined4 FUN_800201ac();
extern undefined4 FUN_80088a84();
extern undefined4 FUN_801d8284();
extern undefined4 FUN_801d86e4();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4* DAT_803dd6e8;

/* Local declarations keep imported functions visible within the TU. */
void FUN_801d81a0(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8);
undefined4
FUN_801d8204(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
            undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,int param_9,
            undefined4 param_10,int param_11);

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801d81a0(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

undefined4
FUN_801d8204(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
            undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,int param_9,
            undefined4 param_10,int param_11)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0;
}
