/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/DR/DRhalolight.c
 * Text span: 0x801ED1FC-0x801ED5CC
 * Imported Ghidra functions: 4
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 4
 */

#include "ghidra_import.h"
#include "main/dll/DR/DRhalolight.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_800201ac();
extern undefined4 FUN_800238c4();
extern undefined4 FUN_8003709c();
extern undefined4 FUN_80038524();
extern undefined4 FUN_8003b9ec();
extern undefined4 FUN_801e9f54();
extern undefined4 FUN_801ecea8();
extern int FUN_80286838();
extern undefined4 FUN_80286884();
extern double FUN_80293900();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4* DAT_803dd6e8;
extern f32 FLOAT_803e6784;
extern f32 FLOAT_803e6828;
extern f32 FLOAT_803e682c;
extern f32 FLOAT_803e6830;
extern f32 FLOAT_803e6840;
extern f32 FLOAT_803e6850;

/* Local declarations keep imported functions visible within the TU. */
double FUN_801ed20c(int param_1,undefined4 *param_2);
void FUN_801ed2cc(int param_1,int param_2);
void FUN_801ed478(int param_1);
void FUN_801ed4fc(void);

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

double FUN_801ed20c(int param_1,undefined4 *param_2)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0.0;
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801ed2cc(int param_1,int param_2)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801ed478(int param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801ed4fc(void)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}
