/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/DR/DRpickup.c
 * Text span: 0x801EC398-0x801EC7E4
 * Imported Ghidra functions: 1
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 1
 */

#include "ghidra_import.h"
#include "main/dll/DR/DRpickup.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_80014acc();
extern uint FUN_80022264();
extern double FUN_80247f54();
extern double FUN_80293900();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4* DAT_803dd708;
extern f64 DOUBLE_803e6798;
extern f32 FLOAT_803dc074;
extern f32 FLOAT_803e6780;
extern f32 FLOAT_803e6784;
extern f32 FLOAT_803e6790;
extern f32 FLOAT_803e67b4;
extern f32 FLOAT_803e67b8;
extern f32 FLOAT_803e67c4;
extern f32 FLOAT_803e67cc;
extern f32 FLOAT_803e6820;
extern f32 FLOAT_803e6854;
extern f32 FLOAT_803e685c;
extern f32 FLOAT_803e6870;
extern f32 FLOAT_803e6874;
extern f32 FLOAT_803e6878;
extern f32 FLOAT_803e687c;
extern f32 FLOAT_803e6880;
extern f32 FLOAT_803e6884;
extern f32 FLOAT_803e6888;
extern f32 FLOAT_803e688c;
extern f32 FLOAT_803e6890;
extern f32 FLOAT_803e6894;
extern f32 FLOAT_803e6898;
extern f32 FLOAT_803e689c;
extern f32 FLOAT_803e68a0;
extern f32 FLOAT_803e68a4;
extern f32 FLOAT_803e68a8;
extern f32 FLOAT_803e68ac;

/* Local declarations keep imported functions visible within the TU. */
void FUN_801ec398(int param_1,int param_2);

/* Auto-stubbed for compileability: function-pointer stores need manual cleanup. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801ec398(int param_1,int param_2)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}
