/*
 * Auto-generated by tools/ghidra_unmanaged_homes.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists so every raw Ghidra function mapped to an unmanaged live owner
 * still has a concrete .c home for iteration/reference work.
 *
 * Live owner: dolphin/amcstubs/AmcExi2Stubs.c
 * Text span: 0x8026C680-0x8026C6B0
 * Imported Ghidra functions: 1
 * Verbatim-safe functions: 1
 * Auto-stubbed functions: 0
 */
/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: dolphin/amcstubs/AmcExi2Stubs.c
 * Text span: 0x8026C680-0x8026C6B0
 * Imported Ghidra functions: 1
 * Verbatim-safe functions: 1
 * Auto-stubbed functions: 0
 */

#include "ghidra_import.h"

/* Local declarations keep imported functions visible within the TU. */
undefined4 FUN_8026c6a8(void);

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8026C6A8
 * EN v1.0 Size: 8b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
undefined4 FUN_8026c6a8(void)
{
  return 1;
}
