/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/baddie/dll_DA.c
 * Text span: 0x801309A8-0x80131078
 * Imported Ghidra functions: 2
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 2
 */

#include "ghidra_import.h"
#include "main/dll/baddie/dll_DA.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_80015e00();
extern undefined4 FUN_80016848();
extern undefined4 FUN_800168a8();
extern undefined* FUN_80017400();
extern undefined4 FUN_8001741c();
extern undefined8 FUN_80019940();
extern undefined4 FUN_80054484();
extern undefined4 FUN_80054ed0();
extern undefined4 FUN_80077318();
extern undefined4 FUN_80286830();
extern undefined4 FUN_8028687c();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4 DAT_8031ce04;
extern undefined4 DAT_8031ce0a;
extern undefined2 DAT_803aa0b8;
extern undefined DAT_803b0000;
extern undefined4 DAT_803de330;
extern undefined4 DAT_803de57a;
extern undefined4 DAT_803de57c;
extern undefined4 DAT_803de57e;
extern undefined4 DAT_803de580;
extern undefined4 DAT_803de582;
extern undefined4 DAT_803de584;
extern undefined4 DAT_803de58c;
extern undefined4 DAT_803de58e;
extern undefined4 DAT_803de591;
extern undefined4 DAT_803de592;
extern f64 DOUBLE_803e2e70;

/* Local declarations keep imported functions visible within the TU. */
void FUN_801309a8(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 int param_9,undefined4 param_10,undefined4 param_11,undefined4 param_12,
                 undefined4 param_13,undefined4 param_14,undefined4 param_15,undefined4 param_16);
void FUN_80130c10(undefined8 param_1,double param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8);

/* Auto-stubbed for compileability: address-of global symbols need manual typing. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801309a8(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 int param_9,undefined4 param_10,undefined4 param_11,undefined4 param_12,
                 undefined4 param_13,undefined4 param_14,undefined4 param_15,undefined4 param_16)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: address-of global symbols need manual typing. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_80130c10(undefined8 param_1,double param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}
