/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/CR/CRfueltank.c
 * Text span: 0x801E3A44-0x801E3AB0
 * Imported Ghidra functions: 1
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 1
 */

#include "ghidra_import.h"
#include "main/dll/CR/CRfueltank.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_8003b9ec();

/* Local declarations keep imported functions visible within the TU. */
void FUN_801e3a44(int param_1);

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801e3a44(int param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}
