/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/DIM/DIM2projrock.c
 * Text span: 0x801B8980-0x801BA3CC
 * Imported Ghidra functions: 20
 * Verbatim-safe functions: 13
 * Auto-stubbed functions: 7
 */

#include "ghidra_import.h"
#include "main/dll/DIM/DIM2projrock.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined8 FUN_80008b74();
extern undefined8 FUN_80008cbc();
extern undefined4 FUN_8000a538();
extern undefined4 FUN_8000b7dc();
extern undefined4 FUN_8000bb38();
extern undefined4 FUN_80010340();
extern undefined4 FUN_80010a8c();
extern undefined4 FUN_80010de0();
extern uint FUN_80020078();
extern undefined4 FUN_800201ac();
extern double FUN_80021794();
extern undefined4 FUN_800217c8();
extern uint FUN_80022264();
extern undefined4 FUN_8002ba34();
extern int FUN_8002bac4();
extern undefined2* FUN_8002becc();
extern undefined4 FUN_8002cc9c();
extern undefined4 FUN_8002e088();
extern uint FUN_8002e144();
extern undefined4 FUN_8002e1ac();
extern undefined4 FUN_80035ff8();
extern undefined4 FUN_80036800();
extern int FUN_80036974();
extern int* FUN_80037048();
extern undefined4 FUN_8003709c();
extern int FUN_800395a4();
extern undefined4 FUN_8003b9ec();
extern undefined8 FUN_8004c360();
extern undefined4 FUN_8005517c();
extern int FUN_80064248();
extern int FUN_80065fcc();
extern undefined4 FUN_80088a84();
extern undefined4 FUN_800e85f4();
extern int FUN_800e8a48();
extern undefined4 FUN_800ea564();
extern undefined4 FUN_801d84c4();
extern undefined4 FUN_801d8650();
extern int FUN_8028683c();
extern undefined4 FUN_80286888();
extern double FUN_80293900();
extern uint FUN_80296e34();
extern undefined4 FUN_80297480();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4 DAT_803dc070;
extern undefined4 DAT_803dcb90;
extern undefined4* DAT_803dd708;
extern undefined4* DAT_803dd718;
extern undefined4* DAT_803dd71c;
extern f64 DOUBLE_803e57c0;
extern f64 DOUBLE_803e57d8;
extern f64 DOUBLE_803e57f8;
extern f64 DOUBLE_803e5820;
extern f32 FLOAT_803dc074;
extern f32 FLOAT_803e5770;
extern f32 FLOAT_803e5774;
extern f32 FLOAT_803e5778;
extern f32 FLOAT_803e577c;
extern f32 FLOAT_803e5780;
extern f32 FLOAT_803e5784;
extern f32 FLOAT_803e5788;
extern f32 FLOAT_803e5790;
extern f32 FLOAT_803e5794;
extern f32 FLOAT_803e5798;
extern f32 FLOAT_803e579c;
extern f32 FLOAT_803e57a4;
extern f32 FLOAT_803e57a8;
extern f32 FLOAT_803e57ac;
extern f32 FLOAT_803e57b0;
extern f32 FLOAT_803e57b4;
extern f32 FLOAT_803e57b8;
extern f32 FLOAT_803e57bc;
extern f32 FLOAT_803e57cc;
extern f32 FLOAT_803e57d0;
extern f32 FLOAT_803e57d4;
extern f32 FLOAT_803e57e0;
extern f32 FLOAT_803e57e4;
extern f32 FLOAT_803e57e8;
extern f32 FLOAT_803e57ec;
extern f32 FLOAT_803e57f0;
extern f32 FLOAT_803e5804;
extern f32 FLOAT_803e5808;
extern f32 FLOAT_803e580c;
extern f32 FLOAT_803e5810;
extern f32 FLOAT_803e5814;
extern f32 FLOAT_803e5818;
extern f32 FLOAT_803e5828;
extern f32 FLOAT_803e5834;
extern f32 FLOAT_803e5838;
extern f32 FLOAT_803e583c;
extern undefined uRam803dcb93;

/* Local declarations keep imported functions visible within the TU. */
void FUN_801b8980(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8);
void FUN_801b8d60(int param_1);
void FUN_801b8d90(uint param_1);
void FUN_801b8e14(int *param_1);
void FUN_801b9138(int param_1);
void FUN_801b916c(uint param_1);
void FUN_801b94ac(undefined2 *param_1,int param_2);
void FUN_801b9544(int param_1);
void FUN_801b9578(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 int param_9);
void FUN_801b97b8(undefined2 *param_1,int param_2);
void FUN_801b99c4(int param_1);
void FUN_801b99f8(uint param_1);
void FUN_801b9d1c(undefined2 *param_1,int param_2);
void FUN_801b9dc4(int param_1);
void FUN_801b9e48(void);
void FUN_801b9e80(int param_1);
void FUN_801b9eb0(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 int param_9);
void FUN_801ba134(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 int param_9,int param_10);
void FUN_801ba27c(int param_1);
void FUN_801ba2b0(int param_1);

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801B8980
 * EN v1.0 Size: 992b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: function-pointer stores need manual cleanup. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801b8980(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801B8D60
 * EN v1.0 Size: 48b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

// Function: FUN_801b8d60
// Entry: 801b8d60
// Size: 48 bytes

void FUN_801b8d60(int param_1)

{
  char in_r8;
  
  if (in_r8 != '\0') {
    FUN_8003b9ec(param_1);
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801B8D90
 * EN v1.0 Size: 132b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

// Function: FUN_801b8d90
// Entry: 801b8d90
// Size: 132 bytes

void FUN_801b8d90(uint param_1)

{
  float fVar1;
  int iVar2;
  int local_18 [5];
  
  iVar2 = FUN_80036974(param_1,local_18,(int *)0x0,(uint *)0x0);
  if (iVar2 == 0xe) {
    iVar2 = FUN_8002bac4();
    FUN_800217c8((float *)(param_1 + 0x18),(float *)(iVar2 + 0x18));
    fVar1 = FLOAT_803e5774;
    *(float *)(param_1 + 0x24) = *(float *)(local_18[0] + 0x24) * FLOAT_803e5774;
    *(float *)(param_1 + 0x2c) = *(float *)(local_18[0] + 0x2c) * fVar1;
    FUN_8000bb38(param_1,0x1f9);
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801B8E14
 * EN v1.0 Size: 804b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

// Function: FUN_801b8e14
// Entry: 801b8e14
// Size: 744 bytes

/* WARNING: Removing unreachable block (ram,0x801b90dc) */
/* WARNING: Removing unreachable block (ram,0x801b90d4) */
/* WARNING: Removing unreachable block (ram,0x801b90cc) */
/* WARNING: Removing unreachable block (ram,0x801b8e34) */
/* WARNING: Removing unreachable block (ram,0x801b8e2c) */
/* WARNING: Removing unreachable block (ram,0x801b8e24) */

void FUN_801b8e14(int *param_1)

{
  float fVar1;
  float fVar2;
  int iVar3;
  undefined4 *puVar4;
  int iVar5;
  float *pfVar6;
  double dVar7;
  double dVar8;
  double dVar9;
  double dVar10;
  double dVar11;
  undefined4 *local_90;
  int aiStack_8c [7];
  float local_70;
  float local_6c;
  float local_68;
  
  fVar2 = FLOAT_803e577c;
  fVar1 = FLOAT_803e5778;
  pfVar6 = (float *)param_1[0x2e];
  if (*(char *)(pfVar6 + 1) == '\0') {
    param_1[9] = (int)((float)param_1[9] * FLOAT_803e577c);
    param_1[0xb] = (int)((float)param_1[0xb] * fVar2);
  }
  else {
    param_1[9] = (int)((float)param_1[9] * FLOAT_803e5778);
    param_1[0xb] = (int)((float)param_1[0xb] * fVar1);
  }
  fVar1 = FLOAT_803e5788;
  if (((((float)param_1[9] < FLOAT_803e5780) && (FLOAT_803e5784 < (float)param_1[9])) &&
      ((float)param_1[0xb] < FLOAT_803e5780)) && (FLOAT_803e5784 < (float)param_1[0xb])) {
    param_1[9] = (int)FLOAT_803e5788;
    param_1[0xb] = (int)fVar1;
  }
  FUN_8002ba34((double)((float)param_1[9] * FLOAT_803dc074),(double)FLOAT_803e5788,
               (double)((float)param_1[0xb] * FLOAT_803dc074),(int)param_1);
  iVar3 = FUN_80064248(param_1 + 0x20,param_1 + 3,(float *)0x1,aiStack_8c,param_1,8,0xffffffff,0xff,
                       0);
  if (iVar3 != 0) {
    dVar11 = -(double)(float)param_1[9];
    dVar10 = -(double)(float)param_1[10];
    dVar9 = -(double)(float)param_1[0xb];
    dVar8 = FUN_80293900((double)(float)(dVar9 * dVar9 +
                                        (double)(float)(dVar11 * dVar11 +
                                                       (double)(float)(dVar10 * dVar10))));
    if ((double)FLOAT_803e5788 != dVar8) {
      dVar7 = (double)(float)((double)FLOAT_803e5770 / dVar8);
      dVar11 = (double)(float)(dVar11 * dVar7);
      dVar10 = (double)(float)(dVar10 * dVar7);
      dVar9 = (double)(float)(dVar9 * dVar7);
    }
    dVar7 = (double)(FLOAT_803e5790 *
                    (float)(dVar9 * (double)local_68 +
                           (double)(float)(dVar11 * (double)local_70 +
                                          (double)(float)(dVar10 * (double)local_6c))));
    param_1[9] = (int)(float)((double)local_70 * dVar7);
    param_1[10] = (int)(float)((double)local_6c * dVar7);
    param_1[0xb] = (int)(float)((double)local_68 * dVar7);
    param_1[9] = (int)(float)((double)(float)param_1[9] - dVar11);
    param_1[10] = (int)(float)((double)(float)param_1[10] - dVar10);
    param_1[0xb] = (int)(float)((double)(float)param_1[0xb] - dVar9);
    dVar9 = (double)FLOAT_803e5794;
    param_1[9] = (int)((float)param_1[9] * (float)(dVar9 * dVar8));
    param_1[10] = (int)((float)param_1[10] * (float)((double)FLOAT_803e5774 * dVar8));
    param_1[0xb] = (int)((float)param_1[0xb] * (float)(dVar9 * dVar8));
  }
  param_1[4] = (int)-(FLOAT_803e5798 * FLOAT_803dc074 - (float)param_1[4]);
  iVar3 = FUN_80065fcc((double)(float)param_1[3],(double)(float)param_1[4],(double)(float)param_1[5]
                       ,param_1,&local_90,0,0x11);
  *(undefined *)(pfVar6 + 1) = 0;
  iVar5 = 0;
  puVar4 = local_90;
  if (0 < iVar3) {
    do {
      if ((float)param_1[4] < FLOAT_803e579c + *(float *)*puVar4) {
        param_1[4] = *(int *)local_90[iVar5];
        FUN_80036800(*(int *)(local_90[iVar5] + 0x10),(int)param_1);
        *(undefined *)(pfVar6 + 1) = 1;
        break;
      }
      puVar4 = puVar4 + 1;
      iVar5 = iVar5 + 1;
      iVar3 = iVar3 + -1;
    } while (iVar3 != 0);
  }
  if ((float)param_1[4] < *pfVar6) {
    param_1[4] = (int)*pfVar6;
  }
  FUN_800e85f4((int)param_1);
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801B9138
 * EN v1.0 Size: 52b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

// Function: FUN_801b9138
// Entry: 801b9138
// Size: 48 bytes

void FUN_801b9138(int param_1)

{
  char in_r8;
  
  if (in_r8 != '\0') {
    FUN_8003b9ec(param_1);
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801B916C
 * EN v1.0 Size: 832b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

// Function: FUN_801b916c
// Entry: 801b916c
// Size: 832 bytes

void FUN_801b916c(uint param_1)

{
  byte bVar1;
  bool bVar2;
  int iVar3;
  int iVar4;
  uint uVar5;
  int iVar6;
  int iVar7;
  float *pfVar8;
  
  pfVar8 = *(float **)(param_1 + 0xb8);
  iVar4 = FUN_8002bac4();
  iVar7 = *(int *)(param_1 + 0x4c);
  bVar2 = false;
  iVar6 = 0;
  iVar3 = (int)*(char *)(*(int *)(param_1 + 0x58) + 0x10f);
  if (0 < iVar3) {
    do {
      if (*(int *)(*(int *)(param_1 + 0x58) + iVar6 + 0x100) == iVar4) {
        bVar2 = true;
        break;
      }
      iVar6 = iVar6 + 4;
      iVar3 = iVar3 + -1;
    } while (iVar3 != 0);
  }
  bVar1 = *(byte *)(pfVar8 + 1);
  if (bVar1 == 3) {
    *pfVar8 = *pfVar8 + FLOAT_803e57a8 * FLOAT_803dc074 +
                        FLOAT_803e57ac *
                        (float)((double)CONCAT44(0x43300000,
                                                 ((uint)(byte)((*pfVar8 < FLOAT_803e57a4) << 3) <<
                                                 0x1c) >> 0x1f ^ 0x80000000) - DOUBLE_803e57c0);
    if (FLOAT_803e57b0 < *pfVar8) {
      *pfVar8 = FLOAT_803e57b0;
    }
    *(float *)(param_1 + 0x10) = *pfVar8 * FLOAT_803dc074 + *(float *)(param_1 + 0x10);
    if (*(float *)(iVar7 + 0xc) < *(float *)(param_1 + 0x10)) {
      FUN_8000bb38(param_1,0x1f8);
      *(undefined4 *)(param_1 + 0x10) = *(undefined4 *)(iVar7 + 0xc);
      *(undefined *)(pfVar8 + 1) = 1;
      if (bVar2) {
        *(undefined *)((int)pfVar8 + 5) = 1;
        *(undefined *)((int)pfVar8 + 6) = 0;
      }
    }
  }
  else if (bVar1 < 3) {
    if (bVar1 == 1) {
      FUN_8000b7dc(param_1,8);
      if (bVar2) {
        if ((*(char *)((int)pfVar8 + 6) != '\0') && (*(char *)((int)pfVar8 + 5) != '\0')) {
          FUN_8000bb38(param_1,0x113);
          *(undefined *)(pfVar8 + 1) = 4;
          *pfVar8 = FLOAT_803e57a4;
        }
      }
      else {
        *(undefined *)((int)pfVar8 + 6) = 1;
      }
      uVar5 = FUN_80020078((int)*(short *)(iVar7 + 0x20));
      if (uVar5 != 0) {
        FUN_8000bb38(param_1,0x113);
        *(undefined *)(pfVar8 + 1) = 4;
        *pfVar8 = FLOAT_803e57a4;
      }
    }
    else if (bVar1 != 0) {
      FUN_8000b7dc(param_1,8);
      if (*(char *)((int)pfVar8 + 5) == '\0') {
        uVar5 = FUN_80020078((int)*(short *)(iVar7 + 0x20));
        if (uVar5 == 0) {
          FUN_8000bb38(param_1,0x113);
          *(undefined *)(pfVar8 + 1) = 3;
          *pfVar8 = FLOAT_803e57a4;
          *(undefined *)((int)pfVar8 + 5) = 0;
          FUN_800201ac((int)*(short *)(iVar7 + 0x1e),0);
        }
      }
      else if (!bVar2) {
        FUN_8000bb38(param_1,0x113);
        *(undefined *)(pfVar8 + 1) = 3;
        *pfVar8 = FLOAT_803e57a4;
        *(undefined *)((int)pfVar8 + 5) = 0;
        FUN_800201ac((int)*(short *)(iVar7 + 0x1e),0);
      }
    }
  }
  else if (bVar1 < 5) {
    *pfVar8 = FLOAT_803e57b4 * FLOAT_803dc074 + *pfVar8;
    if (*pfVar8 < FLOAT_803e57b8) {
      *pfVar8 = FLOAT_803e57b8;
    }
    *(float *)(param_1 + 0x10) = *pfVar8 * FLOAT_803dc074 + *(float *)(param_1 + 0x10);
    if (*(float *)(param_1 + 0x10) < *(float *)(iVar7 + 0xc) - FLOAT_803e57bc) {
      FUN_8000bb38(param_1,0x1f8);
      *(float *)(param_1 + 0x10) = *(float *)(iVar7 + 0xc) - FLOAT_803e57bc;
      *(undefined *)(pfVar8 + 1) = 2;
      FUN_800201ac((int)*(short *)(iVar7 + 0x1e),1);
    }
    if ((*(char *)((int)pfVar8 + 5) == '\0') &&
       (uVar5 = FUN_80020078((int)*(short *)(iVar7 + 0x20)), uVar5 == 0)) {
      *(undefined *)(pfVar8 + 1) = 3;
      FUN_800201ac((int)*(short *)(iVar7 + 0x1e),0);
    }
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801B94AC
 * EN v1.0 Size: 152b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

// Function: FUN_801b94ac
// Entry: 801b94ac
// Size: 124 bytes

void FUN_801b94ac(undefined2 *param_1,int param_2)

{
  uint uVar1;
  int iVar2;
  
  iVar2 = *(int *)(param_1 + 0x5c);
  *param_1 = (short)((int)*(char *)(param_2 + 0x18) << 8);
  uVar1 = FUN_80020078((int)*(short *)(param_2 + 0x1e));
  if (uVar1 == 0) {
    *(undefined *)(iVar2 + 4) = 1;
  }
  else {
    *(undefined *)(iVar2 + 4) = 2;
  }
  param_1[0x58] = param_1[0x58] | 0x2000;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801B9544
 * EN v1.0 Size: 52b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

// Function: FUN_801b9544
// Entry: 801b9544
// Size: 48 bytes

void FUN_801b9544(int param_1)

{
  char in_r8;
  
  if (in_r8 != '\0') {
    FUN_8003b9ec(param_1);
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801B9578
 * EN v1.0 Size: 576b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: address-label references need manual cleanup, function-pointer stores need manual cleanup. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801b9578(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 int param_9)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801B97B8
 * EN v1.0 Size: 524b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

// Function: FUN_801b97b8
// Entry: 801b97b8
// Size: 496 bytes

void FUN_801b97b8(undefined2 *param_1,int param_2)

{
  short sVar1;
  uint uVar2;
  int iVar3;
  
  iVar3 = *(int *)(param_1 + 0x5c);
  *(undefined4 *)(iVar3 + 0xa0) = *(undefined4 *)(param_2 + 0x14);
  *(float *)(iVar3 + 0xa4) =
       (float)((double)CONCAT44(0x43300000,(int)*(short *)(param_2 + 0x1c) ^ 0x80000000) -
              DOUBLE_803e57f8) / FLOAT_803e57e0;
  uVar2 = FUN_80022264(0xffffffe2,0x1e);
  *(float *)(iVar3 + 0xa8) =
       (float)((double)CONCAT44(0x43300000,uVar2 ^ 0x80000000) - DOUBLE_803e57f8);
  *(undefined4 *)(param_2 + 0x14) = 0xffffffff;
  uVar2 = FUN_80022264(0,(int)*(char *)(*(int *)(param_1 + 0x28) + 0x55) - 1);
  *(char *)((int)param_1 + 0xad) = (char)uVar2;
  *param_1 = (short)((int)*(char *)(param_2 + 0x18) << 8);
  uVar2 = FUN_80022264(0,0xffff);
  *param_1 = (short)uVar2;
  *(undefined *)(param_1 + 0x1b) = 0;
  sVar1 = param_1[0x23];
  if (sVar1 == 0x10d) {
    uVar2 = FUN_80022264(0,0x32);
    *(float *)(iVar3 + 0xac) =
         FLOAT_803e57ec + (float)((double)CONCAT44(0x43300000,uVar2 ^ 0x80000000) - DOUBLE_803e57f8)
    ;
    *(float *)(iVar3 + 0xb0) = FLOAT_803e57e8;
  }
  else if ((sVar1 < 0x10d) && (sVar1 == 0x109)) {
    uVar2 = FUN_80022264(0,0x28);
    *(float *)(iVar3 + 0xac) =
         FLOAT_803e57e4 + (float)((double)CONCAT44(0x43300000,uVar2 ^ 0x80000000) - DOUBLE_803e57f8)
    ;
    *(float *)(iVar3 + 0xb0) = FLOAT_803e57e8;
  }
  else {
    uVar2 = FUN_80022264(0,0x28);
    *(float *)(iVar3 + 0xac) =
         FLOAT_803e57f0 + (float)((double)CONCAT44(0x43300000,uVar2 ^ 0x80000000) - DOUBLE_803e57f8)
    ;
    *(float *)(iVar3 + 0xb0) = FLOAT_803e57e8;
  }
  param_1[0x58] = param_1[0x58] | 0x2000;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801B99C4
 * EN v1.0 Size: 52b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

// Function: FUN_801b99c4
// Entry: 801b99c4
// Size: 48 bytes

void FUN_801b99c4(int param_1)

{
  char in_r8;
  
  if (in_r8 != '\0') {
    FUN_8003b9ec(param_1);
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801B99F8
 * EN v1.0 Size: 804b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: function-pointer stores need manual cleanup. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801b99f8(uint param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801B9D1C
 * EN v1.0 Size: 168b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

// Function: FUN_801b9d1c
// Entry: 801b9d1c
// Size: 160 bytes

void FUN_801b9d1c(undefined2 *param_1,int param_2)

{
  uint uVar1;
  int iVar2;
  
  iVar2 = *(int *)(param_1 + 0x5c);
  uVar1 = FUN_80020078((int)*(short *)(param_2 + 0x1e));
  if (uVar1 == 0) {
    *(undefined *)(iVar2 + 6) = 0;
    *(undefined *)(param_1 + 0x1b) = 0xff;
  }
  else {
    *(undefined *)(iVar2 + 6) = 2;
    *(undefined *)(param_1 + 0x1b) = 0;
  }
  *param_1 = (short)((int)*(char *)(param_2 + 0x18) << 8);
  *(float *)(param_1 + 0x14) = FLOAT_803e5818;
  param_1[0x58] = param_1[0x58] | 0x2000;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801B9DC4
 * EN v1.0 Size: 132b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: pointer-heavy local typing needs manual cleanup. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801b9dc4(int param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801B9E48
 * EN v1.0 Size: 56b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

// Function: FUN_801b9e48
// Entry: 801b9e48
// Size: 56 bytes

void FUN_801b9e48(void)

{
  FUN_8004c360((double)FLOAT_803e5828,0xc0);
  FUN_8000a538((int *)0xc4,0);
  FUN_8005517c();
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801B9E80
 * EN v1.0 Size: 48b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

// Function: FUN_801b9e80
// Entry: 801b9e80
// Size: 48 bytes

void FUN_801b9e80(int param_1)

{
  char in_r8;
  
  if (in_r8 != '\0') {
    FUN_8003b9ec(param_1);
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801B9EB0
 * EN v1.0 Size: 644b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: address-of global symbols need manual typing. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801b9eb0(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 int param_9)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801BA134
 * EN v1.0 Size: 328b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: pointer-heavy local typing needs manual cleanup. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801ba134(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 int param_9,int param_10)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801BA27C
 * EN v1.0 Size: 52b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

// Function: FUN_801ba27c
// Entry: 801ba27c
// Size: 48 bytes

void FUN_801ba27c(int param_1)

{
  char in_r8;
  
  if (in_r8 != '\0') {
    FUN_8003b9ec(param_1);
  }
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x801BA2B0
 * EN v1.0 Size: 284b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: function-pointer stores need manual cleanup. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801ba2b0(int param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}
