/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/DIM/DIM2icicle.c
 * Text span: 0x801BB99C-0x801BD0E8
 * Imported Ghidra functions: 5
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 5
 */

#include "ghidra_import.h"
#include "main/dll/DIM/DIM2icicle.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_80003494();
extern undefined8 FUN_80008cbc();
extern undefined4 FUN_8000bb38();
extern undefined4 FUN_8000e670();
extern undefined4 FUN_8000e69c();
extern undefined4 FUN_8000faf8();
extern undefined4 FUN_80014acc();
extern undefined4 FUN_8001d6e4();
extern undefined4 FUN_8001d7d8();
extern undefined4 FUN_8001d7e0();
extern undefined4 FUN_8001d7f4();
extern undefined4 FUN_8001daa4();
extern undefined4 FUN_8001dab8();
extern undefined4 FUN_8001dadc();
extern undefined4 FUN_8001db7c();
extern undefined4 FUN_8001dbb4();
extern undefined4 FUN_8001dbf0();
extern undefined4 FUN_8001dc18();
extern undefined4 FUN_8001dc30();
extern undefined4 FUN_8001dcfc();
extern undefined4 FUN_8001de04();
extern undefined4 FUN_8001de4c();
extern int* FUN_8001f58c();
extern undefined8 FUN_800201ac();
extern uint FUN_80022264();
extern int FUN_8002ba84();
extern int FUN_8002bac4();
extern undefined4 FUN_80036018();
extern int FUN_80036974();
extern undefined4 FUN_800379bc();
extern uint FUN_80038498();
extern undefined4 FUN_80038524();
extern undefined4 FUN_80055464();
extern undefined4 FUN_80089734();
extern undefined4 FUN_8008986c();
extern undefined4 FUN_8008999c();
extern undefined8 FUN_8012e0b8();
extern undefined4 FUN_801bb8dc();
extern undefined4 FUN_80247bf8();
extern undefined8 FUN_80286824();
extern undefined8 FUN_80286840();
extern undefined4 FUN_80286870();
extern undefined4 FUN_8028688c();
extern uint FUN_80296164();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4 DAT_802c2ac8;
extern undefined4 DAT_802c2acc;
extern undefined4 DAT_802c2ad0;
extern undefined4 DAT_802c2ad4;
extern undefined4 DAT_80326620;
extern undefined4 DAT_80326624;
extern undefined4 DAT_803266f8;
extern undefined4 DAT_803266fc;
extern undefined4 DAT_80326700;
extern undefined4 DAT_80326704;
extern undefined4 DAT_803ad5d0;
extern undefined4 DAT_803ad5d4;
extern undefined4 DAT_803ad5d8;
extern undefined4 DAT_803ad5dc;
extern undefined4 DAT_803ad5e8;
extern undefined4 DAT_803ad5ec;
extern undefined4 DAT_803ad5f0;
extern undefined4 DAT_803ad5f4;
extern undefined4 DAT_803ad5f6;
extern undefined4 DAT_803ad5f8;
extern undefined4 DAT_803ad5fc;
extern undefined4 DAT_803ad600;
extern undefined4 DAT_803ad604;
extern undefined4 DAT_803ad608;
extern undefined4 DAT_803adc60;
extern undefined4 DAT_803adc78;
extern undefined4* DAT_803dd6f4;
extern undefined4* DAT_803dd708;
extern undefined4* DAT_803dd70c;
extern undefined4* DAT_803dd734;
extern undefined4* DAT_803dd738;
extern undefined4 DAT_803de800;
extern undefined4* DAT_803de808;
extern undefined4 DAT_803de80c;
extern f64 DOUBLE_803e5878;
extern f32 FLOAT_803dc074;
extern f32 FLOAT_803dda58;
extern f32 FLOAT_803dda5c;
extern f32 FLOAT_803e5854;
extern f32 FLOAT_803e585c;
extern f32 FLOAT_803e5860;
extern f32 FLOAT_803e5864;
extern f32 FLOAT_803e5870;
extern f32 FLOAT_803e5884;
extern f32 FLOAT_803e588c;
extern f32 FLOAT_803e5890;
extern f32 FLOAT_803e58a8;
extern f32 FLOAT_803e58c0;
extern f32 FLOAT_803e58c4;
extern f32 FLOAT_803e58c8;
extern f32 FLOAT_803e58cc;
extern f32 FLOAT_803e58d0;
extern f32 FLOAT_803e58d4;
extern f32 FLOAT_803e58d8;
extern f32 FLOAT_803e58dc;
extern f32 FLOAT_803e58e0;
extern f32 FLOAT_803e58e4;
extern f32 FLOAT_803e58e8;
extern f32 FLOAT_803e58ec;
extern f32 FLOAT_803e58f0;
extern f32 FLOAT_803e58f4;
extern f32 FLOAT_803e58f8;
extern f32 FLOAT_803e58fc;
extern f32 FLOAT_803e5900;
extern f32 FLOAT_803e5904;
extern f32 FLOAT_803e5908;
extern f32 FLOAT_803e590c;

/* Local declarations keep imported functions visible within the TU. */
void FUN_801bb99c(int param_1,char param_2);
void FUN_801bbb4c(void);
void FUN_801bc0f8(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 undefined4 param_9,undefined4 param_10,undefined4 param_11,undefined4 param_12,
                 undefined4 param_13,undefined4 param_14,undefined4 param_15,undefined4 param_16);
void FUN_801bc88c(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8);
void FUN_801bcd98(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 undefined4 param_9,undefined4 param_10,int param_11,int param_12);

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801bb99c(int param_1,char param_2)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: address-of global symbols need manual typing, forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801bbb4c(void)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801bc0f8(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 undefined4 param_9,undefined4 param_10,undefined4 param_11,undefined4 param_12,
                 undefined4 param_13,undefined4 param_14,undefined4 param_15,undefined4 param_16)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: address-of global symbols need manual typing, forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801bc88c(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: address-of global symbols need manual typing, forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801bcd98(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 undefined4 param_9,undefined4 param_10,int param_11,int param_12)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}
