/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/DIM/DIM2lift.c
 * Text span: 0x801BA3CC-0x801BB99C
 * Imported Ghidra functions: 18
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 18
 */

#include "ghidra_import.h"
#include "main/dll/DIM/DIM2lift.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_8000bb38();
extern undefined4 FUN_8000e670();
extern undefined4 FUN_8000faf8();
extern undefined4 FUN_80014acc();
extern undefined8 FUN_800201ac();
extern uint FUN_80022264();
extern int FUN_8002bac4();
extern undefined2* FUN_8002becc();
extern undefined4 FUN_8002cc9c();
extern int FUN_8002e088();
extern uint FUN_8002e144();
extern undefined4 FUN_8003042c();
extern undefined4 FUN_80035eec();
extern undefined8 FUN_80035ff8();
extern undefined4 FUN_800379bc();
extern undefined4 FUN_801bc88c();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4 DAT_803265a0;
extern undefined4 DAT_803265e0;
extern undefined4 DAT_803266e0;
extern undefined4 DAT_80326708;
extern undefined4 DAT_80326714;
extern undefined4 DAT_80326724;
extern undefined4 DAT_80326734;
extern undefined4 DAT_803adc4d;
extern undefined4 DAT_803dcb98;
extern undefined4 DAT_803dcba0;
extern undefined4* DAT_803dd70c;
extern undefined4* DAT_803dd738;
extern undefined4 DAT_803de800;
extern undefined4 DAT_803de804;
extern f64 DOUBLE_803e5848;
extern f64 DOUBLE_803e5878;
extern f32 FLOAT_803e5840;
extern f32 FLOAT_803e5844;
extern f32 FLOAT_803e5850;
extern f32 FLOAT_803e5854;
extern f32 FLOAT_803e5858;
extern f32 FLOAT_803e585c;
extern f32 FLOAT_803e5860;
extern f32 FLOAT_803e5864;
extern f32 FLOAT_803e5868;
extern f32 FLOAT_803e586c;
extern f32 FLOAT_803e5870;
extern f32 FLOAT_803e5880;
extern f32 FLOAT_803e5884;
extern f32 FLOAT_803e5888;
extern f32 FLOAT_803e588c;
extern f32 FLOAT_803e5890;
extern f32 FLOAT_803e5894;
extern f32 FLOAT_803e5898;
extern f32 FLOAT_803e589c;
extern f32 FLOAT_803e58a0;
extern f32 FLOAT_803e58a4;
extern f32 FLOAT_803e58a8;
extern f32 FLOAT_803e58ac;
extern f32 FLOAT_803e58b0;
extern f32 FLOAT_803e58b4;
extern f32 FLOAT_803e58b8;
extern f32 FLOAT_803e58bc;

/* Local declarations keep imported functions visible within the TU. */
void FUN_801ba3cc(short *param_1,int param_2);
undefined4
FUN_801ba480(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
            undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
            undefined4 param_9,int param_10);
undefined4
FUN_801ba7d8(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
            undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,int param_9,
            int param_10);
undefined4
FUN_801baa6c(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
            undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,uint param_9
            ,int param_10,undefined4 param_11,undefined4 param_12,undefined4 param_13,
            undefined4 param_14,undefined4 param_15,undefined4 param_16);
undefined4 FUN_801bab5c(undefined4 param_1,int param_2);
undefined4
FUN_801bac08(int param_1,int param_2,undefined4 param_3,undefined4 param_4,undefined4 param_5,
            undefined4 param_6,undefined4 param_7,undefined4 param_8);
undefined4
FUN_801bad34(int param_1,int param_2,undefined4 param_3,undefined4 param_4,undefined4 param_5,
            undefined4 param_6,undefined4 param_7,undefined4 param_8);
undefined4
FUN_801bae34(undefined8 param_1,double param_2,double param_3,undefined8 param_4,undefined8 param_5,
            undefined8 param_6,undefined8 param_7,undefined8 param_8,uint param_9,int param_10,
            undefined4 param_11,undefined4 param_12,undefined4 param_13,undefined4 param_14,
            undefined4 param_15,undefined4 param_16);
undefined4
FUN_801baf0c(undefined8 param_1,double param_2,double param_3,undefined8 param_4,undefined8 param_5,
            undefined8 param_6,undefined8 param_7,undefined8 param_8,int param_9,int param_10,
            undefined4 param_11,undefined4 param_12,undefined4 param_13,undefined4 param_14,
            undefined4 param_15,undefined4 param_16);
undefined4
FUN_801bb038(undefined8 param_1,double param_2,double param_3,undefined8 param_4,undefined8 param_5,
            undefined8 param_6,undefined8 param_7,undefined8 param_8,int param_9,int param_10,
            undefined4 param_11,undefined4 param_12,undefined4 param_13,undefined4 param_14,
            undefined4 param_15,undefined4 param_16);
undefined4
FUN_801bb13c(undefined8 param_1,double param_2,double param_3,undefined8 param_4,undefined8 param_5,
            undefined8 param_6,undefined8 param_7,undefined8 param_8,int param_9,int param_10,
            undefined4 param_11,undefined4 param_12,undefined4 param_13,undefined4 param_14,
            undefined4 param_15,undefined4 param_16);
undefined4
FUN_801bb26c(undefined8 param_1,double param_2,double param_3,undefined8 param_4,undefined8 param_5,
            undefined8 param_6,undefined8 param_7,undefined8 param_8,int param_9,int param_10,
            undefined4 param_11,undefined4 param_12,undefined4 param_13,undefined4 param_14,
            undefined4 param_15,undefined4 param_16);
undefined4
FUN_801bb3b4(undefined8 param_1,double param_2,double param_3,undefined8 param_4,undefined8 param_5,
            undefined8 param_6,undefined8 param_7,undefined8 param_8,int param_9,int param_10,
            undefined4 param_11,undefined4 param_12,undefined4 param_13,undefined4 param_14,
            undefined4 param_15,undefined4 param_16);
undefined4
FUN_801bb50c(undefined8 param_1,double param_2,double param_3,undefined8 param_4,undefined8 param_5,
            undefined8 param_6,undefined8 param_7,undefined8 param_8,int param_9,int param_10,
            undefined4 param_11,undefined4 param_12,undefined4 param_13,undefined4 param_14,
            undefined4 param_15,undefined4 param_16);
undefined4
FUN_801bb68c(undefined8 param_1,double param_2,double param_3,undefined8 param_4,undefined8 param_5,
            undefined8 param_6,undefined8 param_7,undefined8 param_8,int param_9,int param_10);
undefined4
FUN_801bb7a0(undefined8 param_1,double param_2,double param_3,undefined8 param_4,undefined8 param_5,
            undefined8 param_6,undefined8 param_7,undefined8 param_8,undefined4 param_9,int param_10
            ,undefined4 param_11,undefined4 param_12,undefined4 param_13,undefined4 param_14,
            undefined4 param_15,undefined4 param_16);
undefined4
FUN_801bb864(undefined8 param_1,double param_2,double param_3,undefined8 param_4,undefined8 param_5,
            undefined8 param_6,undefined8 param_7,undefined8 param_8,int param_9,int param_10,
            undefined4 param_11,undefined4 param_12,undefined4 param_13,undefined4 param_14,
            undefined4 param_15,undefined4 param_16);
void FUN_801bb8dc(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 int param_9,undefined4 *param_10);

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801ba3cc(short *param_1,int param_2)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: address-of global symbols need manual typing, forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

undefined4
FUN_801ba480(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
            undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
            undefined4 param_9,int param_10)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0;
}

/* Auto-stubbed for compileability: address-of global symbols need manual typing, forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

undefined4
FUN_801ba7d8(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
            undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,int param_9,
            int param_10)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0;
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

undefined4
FUN_801baa6c(undefined8 param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,
            undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,uint param_9
            ,int param_10,undefined4 param_11,undefined4 param_12,undefined4 param_13,
            undefined4 param_14,undefined4 param_15,undefined4 param_16)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0;
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

undefined4 FUN_801bab5c(undefined4 param_1,int param_2)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0;
}

/* Auto-stubbed for compileability: address-of global symbols need manual typing, forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

undefined4
FUN_801bac08(int param_1,int param_2,undefined4 param_3,undefined4 param_4,undefined4 param_5,
            undefined4 param_6,undefined4 param_7,undefined4 param_8)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0;
}

/* Auto-stubbed for compileability: address-of global symbols need manual typing, forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

undefined4
FUN_801bad34(int param_1,int param_2,undefined4 param_3,undefined4 param_4,undefined4 param_5,
            undefined4 param_6,undefined4 param_7,undefined4 param_8)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0;
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

undefined4
FUN_801bae34(undefined8 param_1,double param_2,double param_3,undefined8 param_4,undefined8 param_5,
            undefined8 param_6,undefined8 param_7,undefined8 param_8,uint param_9,int param_10,
            undefined4 param_11,undefined4 param_12,undefined4 param_13,undefined4 param_14,
            undefined4 param_15,undefined4 param_16)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0;
}

/* Auto-stubbed for compileability: address-of global symbols need manual typing, forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

undefined4
FUN_801baf0c(undefined8 param_1,double param_2,double param_3,undefined8 param_4,undefined8 param_5,
            undefined8 param_6,undefined8 param_7,undefined8 param_8,int param_9,int param_10,
            undefined4 param_11,undefined4 param_12,undefined4 param_13,undefined4 param_14,
            undefined4 param_15,undefined4 param_16)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0;
}

/* Auto-stubbed for compileability: address-of global symbols need manual typing, forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

undefined4
FUN_801bb038(undefined8 param_1,double param_2,double param_3,undefined8 param_4,undefined8 param_5,
            undefined8 param_6,undefined8 param_7,undefined8 param_8,int param_9,int param_10,
            undefined4 param_11,undefined4 param_12,undefined4 param_13,undefined4 param_14,
            undefined4 param_15,undefined4 param_16)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0;
}

/* Auto-stubbed for compileability: address-of global symbols need manual typing, forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

undefined4
FUN_801bb13c(undefined8 param_1,double param_2,double param_3,undefined8 param_4,undefined8 param_5,
            undefined8 param_6,undefined8 param_7,undefined8 param_8,int param_9,int param_10,
            undefined4 param_11,undefined4 param_12,undefined4 param_13,undefined4 param_14,
            undefined4 param_15,undefined4 param_16)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0;
}

/* Auto-stubbed for compileability: address-of global symbols need manual typing, forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

undefined4
FUN_801bb26c(undefined8 param_1,double param_2,double param_3,undefined8 param_4,undefined8 param_5,
            undefined8 param_6,undefined8 param_7,undefined8 param_8,int param_9,int param_10,
            undefined4 param_11,undefined4 param_12,undefined4 param_13,undefined4 param_14,
            undefined4 param_15,undefined4 param_16)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0;
}

/* Auto-stubbed for compileability: address-of global symbols need manual typing, forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

undefined4
FUN_801bb3b4(undefined8 param_1,double param_2,double param_3,undefined8 param_4,undefined8 param_5,
            undefined8 param_6,undefined8 param_7,undefined8 param_8,int param_9,int param_10,
            undefined4 param_11,undefined4 param_12,undefined4 param_13,undefined4 param_14,
            undefined4 param_15,undefined4 param_16)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0;
}

/* Auto-stubbed for compileability: address-of global symbols need manual typing, forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

undefined4
FUN_801bb50c(undefined8 param_1,double param_2,double param_3,undefined8 param_4,undefined8 param_5,
            undefined8 param_6,undefined8 param_7,undefined8 param_8,int param_9,int param_10,
            undefined4 param_11,undefined4 param_12,undefined4 param_13,undefined4 param_14,
            undefined4 param_15,undefined4 param_16)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0;
}

/* Auto-stubbed for compileability: address-of global symbols need manual typing, forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

undefined4
FUN_801bb68c(undefined8 param_1,double param_2,double param_3,undefined8 param_4,undefined8 param_5,
            undefined8 param_6,undefined8 param_7,undefined8 param_8,int param_9,int param_10)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0;
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

undefined4
FUN_801bb7a0(undefined8 param_1,double param_2,double param_3,undefined8 param_4,undefined8 param_5,
            undefined8 param_6,undefined8 param_7,undefined8 param_8,undefined4 param_9,int param_10
            ,undefined4 param_11,undefined4 param_12,undefined4 param_13,undefined4 param_14,
            undefined4 param_15,undefined4 param_16)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0;
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

undefined4
FUN_801bb864(undefined8 param_1,double param_2,double param_3,undefined8 param_4,undefined8 param_5,
            undefined8 param_6,undefined8 param_7,undefined8 param_8,int param_9,int param_10,
            undefined4 param_11,undefined4 param_12,undefined4 param_13,undefined4 param_14,
            undefined4 param_15,undefined4 param_16)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0;
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801bb8dc(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 int param_9,undefined4 *param_10)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}
