/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/DIM/DIMlavaball.c
 * Text span: 0x801A6AD0-0x801A9044
 * Imported Ghidra functions: 26
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 26
 */

#include "ghidra_import.h"
#include "main/dll/DIM/DIMlavaball.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined8 FUN_80008b74();
extern undefined8 FUN_80008cbc();
extern undefined4 FUN_8000a538();
extern undefined4 FUN_8000b8a8();
extern undefined4 FUN_8000bb38();
extern undefined4 FUN_8000da78();
extern undefined4 FUN_8000e670();
extern undefined4 FUN_80014acc();
extern undefined4 FUN_800168a8();
extern uint FUN_80020078();
extern undefined4 FUN_800201ac();
extern undefined4 FUN_80021754();
extern undefined4 FUN_800217c8();
extern undefined4 FUN_80021b8c();
extern uint FUN_80022264();
extern undefined4 FUN_8002ba34();
extern int FUN_8002bac4();
extern int FUN_8002e1f4();
extern undefined4 FUN_80035eec();
extern undefined4 FUN_80035ff8();
extern undefined4 FUN_80036018();
extern int FUN_80036974();
extern undefined4* FUN_80037048();
extern undefined4 FUN_8003709c();
extern undefined4 FUN_800372f8();
extern undefined4 FUN_8003b9ec();
extern undefined4 FUN_80043604();
extern int FUN_8004832c();
extern int FUN_8005b128();
extern int FUN_8005b478();
extern undefined4 FUN_8005cf74();
extern int FUN_80064248();
extern int FUN_80065fcc();
extern undefined4 FUN_80088a84();
extern undefined8 FUN_80088f20();
extern undefined4 FUN_80097568();
extern undefined4 FUN_8009a010();
extern undefined4 FUN_8009adfc();
extern undefined4 FUN_800e85f4();
extern int FUN_800e8a48();
extern undefined4 FUN_8011f6d0();
extern undefined4 FUN_801d84c4();
extern ulonglong FUN_80286830();
extern int FUN_8028683c();
extern int FUN_80286840();
extern undefined4 FUN_8028687c();
extern undefined4 FUN_80286888();
extern undefined4 FUN_8028688c();
extern undefined4 FUN_802945e0();
extern uint FUN_802979fc();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4 DAT_803ad560;
extern undefined4 DAT_803ad568;
extern undefined4 DAT_803ad56c;
extern undefined4 DAT_803ad570;
extern undefined4 DAT_803ad574;
extern undefined4 DAT_803ad578;
extern undefined4 DAT_803ad580;
extern undefined4 DAT_803ad584;
extern undefined4 DAT_803ad588;
extern undefined4 DAT_803ad58c;
extern undefined4* DAT_803dd6d4;
extern undefined4* DAT_803dd6f8;
extern undefined4* DAT_803dd708;
extern undefined4* DAT_803dd71c;
extern undefined4* DAT_803dd72c;
extern undefined4* DAT_803dd740;
extern undefined4 DAT_803de7ac;
extern undefined4 DAT_803de7b0;
extern undefined4 DAT_803e50f8;
extern undefined4 DAT_803e50fc;
extern f64 DOUBLE_803e5120;
extern f64 DOUBLE_803e5178;
extern f64 DOUBLE_803e5188;
extern f64 DOUBLE_803e51d8;
extern f64 DOUBLE_803e5240;
extern f32 FLOAT_803dc074;
extern f32 FLOAT_803de7a8;
extern f32 FLOAT_803e5100;
extern f32 FLOAT_803e5114;
extern f32 FLOAT_803e5150;
extern f32 FLOAT_803e5158;
extern f32 FLOAT_803e5160;
extern f32 FLOAT_803e5168;
extern f32 FLOAT_803e516c;
extern f32 FLOAT_803e5170;
extern f32 FLOAT_803e5180;
extern f32 FLOAT_803e5190;
extern f32 FLOAT_803e5194;
extern f32 FLOAT_803e5198;
extern f32 FLOAT_803e519c;
extern f32 FLOAT_803e51a0;
extern f32 FLOAT_803e51a4;
extern f32 FLOAT_803e51a8;
extern f32 FLOAT_803e51ac;
extern f32 FLOAT_803e51b0;
extern f32 FLOAT_803e51b4;
extern f32 FLOAT_803e51bc;
extern f32 FLOAT_803e51c0;
extern f32 FLOAT_803e51c4;
extern f32 FLOAT_803e51c8;
extern f32 FLOAT_803e51cc;
extern f32 FLOAT_803e51d0;
extern f32 FLOAT_803e51d4;
extern f32 FLOAT_803e51e0;
extern f32 FLOAT_803e51e4;
extern f32 FLOAT_803e51e8;
extern f32 FLOAT_803e51ec;
extern f32 FLOAT_803e51f0;
extern f32 FLOAT_803e51f4;
extern f32 FLOAT_803e51f8;
extern f32 FLOAT_803e51fc;
extern f32 FLOAT_803e5200;
extern f32 FLOAT_803e5204;
extern f32 FLOAT_803e5208;
extern f32 FLOAT_803e520c;
extern f32 FLOAT_803e5210;
extern f32 FLOAT_803e5214;
extern f32 FLOAT_803e5218;
extern f32 FLOAT_803e521c;
extern f32 FLOAT_803e5220;
extern f32 FLOAT_803e5224;
extern f32 FLOAT_803e5228;
extern f32 FLOAT_803e522c;
extern f32 FLOAT_803e5238;

/* Local declarations keep imported functions visible within the TU. */
void FUN_801a6ad0(int param_1,int param_2);
undefined4
FUN_801a6bec(undefined8 param_1,double param_2,double param_3,undefined8 param_4,undefined8 param_5,
            undefined8 param_6,undefined8 param_7,undefined8 param_8,int param_9,undefined4 param_10
            ,int param_11,undefined4 param_12,undefined4 param_13,undefined4 param_14,
            undefined4 param_15,undefined4 param_16);
void FUN_801a6cc0(void);
void FUN_801a6cf8(int param_1);
void FUN_801a6d2c(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 int param_9);
void FUN_801a70f8(int param_1);
void FUN_801a71dc(undefined4 param_1,undefined4 param_2,int param_3);
void FUN_801a7324(int param_1);
void FUN_801a7358(int param_1);
void FUN_801a7424(short *param_1,int param_2);
undefined4
FUN_801a7500(undefined8 param_1,double param_2,double param_3,undefined8 param_4,undefined8 param_5,
            undefined8 param_6,undefined8 param_7,undefined8 param_8,uint param_9,
            undefined4 param_10,int param_11);
void FUN_801a76a4(int param_1);
void FUN_801a76d8(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 uint param_9);
void FUN_801a7d54(int param_1);
int FUN_801a7e7c(undefined8 param_1,double param_2,double param_3,double param_4,undefined4 param_5,
                float *param_6,undefined4 *param_7);
void FUN_801a7f94(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 int *param_9);
void FUN_801a80c4(int param_1);
void FUN_801a8278(int param_1);
void FUN_801a8328(undefined4 param_1,undefined4 param_2,uint param_3);
void FUN_801a8678(double param_1,double param_2,double param_3,int param_4);
void FUN_801a86a4(int param_1,char param_2);
void FUN_801a870c(int param_1);
void FUN_801a8754(void);
void FUN_801a87d4(void);
void FUN_801a8e9c(int param_1,int param_2);
void FUN_801a9004(void);

/* Auto-stubbed for compileability: function-pointer stores need manual cleanup, forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801a6ad0(int param_1,int param_2)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

undefined4
FUN_801a6bec(undefined8 param_1,double param_2,double param_3,undefined8 param_4,undefined8 param_5,
            undefined8 param_6,undefined8 param_7,undefined8 param_8,int param_9,undefined4 param_10
            ,int param_11,undefined4 param_12,undefined4 param_13,undefined4 param_14,
            undefined4 param_15,undefined4 param_16)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0;
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801a6cc0(void)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801a6cf8(int param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: address-of global symbols need manual typing, forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801a6d2c(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 int param_9)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: function-pointer stores need manual cleanup, forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801a70f8(int param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: function-pointer stores need manual cleanup, forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801a71dc(undefined4 param_1,undefined4 param_2,int param_3)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801a7324(int param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: pointer-heavy local typing needs manual cleanup, function-pointer stores need manual cleanup, forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801a7358(int param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: function-pointer stores need manual cleanup, forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801a7424(short *param_1,int param_2)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

undefined4
FUN_801a7500(undefined8 param_1,double param_2,double param_3,undefined8 param_4,undefined8 param_5,
            undefined8 param_6,undefined8 param_7,undefined8 param_8,uint param_9,
            undefined4 param_10,int param_11)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0;
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801a76a4(int param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: address-of global symbols need manual typing, function-pointer stores need manual cleanup, forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801a76d8(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 uint param_9)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: function-pointer stores need manual cleanup, forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801a7d54(int param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

int FUN_801a7e7c(undefined8 param_1,double param_2,double param_3,double param_4,undefined4 param_5,
                float *param_6,undefined4 *param_7)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0;
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801a7f94(undefined8 param_1,double param_2,double param_3,undefined8 param_4,
                 undefined8 param_5,undefined8 param_6,undefined8 param_7,undefined8 param_8,
                 int *param_9)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801a80c4(int param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801a8278(int param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: function-pointer stores need manual cleanup, forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801a8328(undefined4 param_1,undefined4 param_2,uint param_3)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801a8678(double param_1,double param_2,double param_3,int param_4)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801a86a4(int param_1,char param_2)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: function-pointer stores need manual cleanup, forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801a870c(int param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: function-pointer stores need manual cleanup, forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801a8754(void)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: address-of global symbols need manual typing, function-pointer stores need manual cleanup, forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801a87d4(void)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: function-pointer stores need manual cleanup, forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801a8e9c(int param_1,int param_2)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: function-pointer stores need manual cleanup, forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801a9004(void)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}
