/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/CAM/attentioncam.c
 * Text span: 0x8010AEE4-0x8010B144
 * Imported Ghidra functions: 1
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 1
 */

#include "ghidra_import.h"
#include "main/dll/CAM/attentioncam.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern double FUN_80293900();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4* DAT_803dd71c;
extern f32 FLOAT_803e2508;
extern f32 FLOAT_803e2528;

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8010AEE4
 * EN v1.0 Size: 608b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
double FUN_8010aee4(double param_1,undefined8 param_2,double param_3,undefined4 *param_4)
{
    return 0.0;
}
