/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/CAM/camcannon.c
 * Text span: 0x8010B144-0x8010B6C0
 * Imported Ghidra functions: 3
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 3
 */

#include "ghidra_import.h"
#include "main/dll/CAM/camcannon.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern double FUN_80010c70();
extern double FUN_80010de0();
extern undefined4 FUN_800238c4();
extern double FUN_80293900();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4* DAT_803dd6d0;
extern undefined4 DAT_803de1d8;
extern f64 DOUBLE_803e2520;
extern f32 FLOAT_803dc074;
extern f32 FLOAT_803e2508;
extern f32 FLOAT_803e250c;
extern f32 FLOAT_803e2510;
extern f32 FLOAT_803e2514;
extern f32 FLOAT_803e2518;
extern f32 FLOAT_803e252c;
extern f32 FLOAT_803e2530;
extern f32 FLOAT_803e2534;
extern f32 FLOAT_803e2538;

/* Local declarations keep imported functions visible within the TU. */
uint FUN_8010b144(short *param_1,uint param_2);
void FUN_8010b4d4(double param_1,short *param_2,undefined4 *param_3,uint param_4,uint param_5,
                 uint param_6);
void FUN_8010b694(void);

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

uint FUN_8010b144(short *param_1,uint param_2)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
    return 0;
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_8010b4d4(double param_1,short *param_2,undefined4 *param_3,uint param_4,uint param_5,
                 uint param_6)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_8010b694(void)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}
