/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/CAM/camdrakor.c
 * Text span: 0x8010C374-0x8010D608
 * Imported Ghidra functions: 6
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 6
 */

#include "ghidra_import.h"
#include "main/dll/CAM/camdrakor.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_8000e054();
extern undefined2* FUN_8000facc();
extern uint FUN_80014e9c();
extern double FUN_80021434();
extern uint FUN_80021884();
extern undefined4 FUN_800238c4();
extern undefined4 FUN_80023d8c();
extern undefined4 FUN_800551f8();
extern undefined4 FUN_801037c0();
extern undefined4 FUN_8010c1a4();
extern uint FUN_801ef35c();
extern undefined4 FUN_80247e94();
extern undefined4 FUN_80247eb8();
extern undefined4 FUN_80247edc();
extern undefined4 FUN_80247ef8();
extern double FUN_80247f54();
extern undefined4 FUN_80286840();
extern undefined4 FUN_8028688c();
extern undefined4 FUN_802932a4();
extern double FUN_80293900();
extern undefined4 FUN_802945e0();
extern undefined4 FUN_80294964();
extern uint FUN_80296a6c();
extern int FUN_80296a88();
extern undefined4 FUN_80297334();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4* DAT_803dd6d0;
extern undefined4* DAT_803de1e0;
extern undefined4 DAT_803de1e4;
extern undefined4* DAT_803de1e8;
extern undefined4 DAT_803de1f0;
extern f64 DOUBLE_803e2598;
extern f64 DOUBLE_803e25b8;
extern f64 DOUBLE_803e2608;
extern f32 FLOAT_803dc074;
extern f32 FLOAT_803e2540;
extern f32 FLOAT_803e2544;
extern f32 FLOAT_803e254c;
extern f32 FLOAT_803e2550;
extern f32 FLOAT_803e2554;
extern f32 FLOAT_803e2558;
extern f32 FLOAT_803e255c;
extern f32 FLOAT_803e2560;
extern f32 FLOAT_803e2564;
extern f32 FLOAT_803e2568;
extern f32 FLOAT_803e256c;
extern f32 FLOAT_803e2570;
extern f32 FLOAT_803e2574;
extern f32 FLOAT_803e2578;
extern f32 FLOAT_803e2584;
extern f32 FLOAT_803e2588;
extern f32 FLOAT_803e258c;
extern f32 FLOAT_803e2590;
extern f32 FLOAT_803e25a0;
extern f32 FLOAT_803e25a4;
extern f32 FLOAT_803e25a8;
extern f32 FLOAT_803e25ac;
extern f32 FLOAT_803e25b0;
extern f32 FLOAT_803e25c0;
extern f32 FLOAT_803e25c8;
extern f32 FLOAT_803e25cc;
extern f32 FLOAT_803e25d0;
extern f32 FLOAT_803e25d4;
extern f32 FLOAT_803e25d8;
extern f32 FLOAT_803e25dc;
extern f32 FLOAT_803e25e0;
extern f32 FLOAT_803e25e4;
extern f32 FLOAT_803e25e8;
extern f32 FLOAT_803e25ec;
extern f32 FLOAT_803e25f0;
extern f32 FLOAT_803e25f4;
extern f32 FLOAT_803e25f8;
extern f32 FLOAT_803e25fc;
extern f32 FLOAT_803e2600;

/* Local declarations keep imported functions visible within the TU. */
void FUN_8010c374(void);
void FUN_8010cff8(int param_1,undefined4 param_2,undefined4 *param_3);
void FUN_8010d160(void);
void FUN_8010d18c(undefined2 *param_1);
void FUN_8010d534(void);
void FUN_8010d5dc(void);

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_8010c374(void)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: typed global pointer comparisons need manual cleanup, forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_8010cff8(int param_1,undefined4 param_2,undefined4 *param_3)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_8010d160(void)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_8010d18c(undefined2 *param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: typed global pointer comparisons need manual cleanup, forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_8010d534(void)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_8010d5dc(void)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}
