/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/CAM/camshipbattle.c
 * Text span: 0x80107020-0x80107398
 * Imported Ghidra functions: 3
 * Verbatim-safe functions: 1
 * Auto-stubbed functions: 2
 */

#include "ghidra_import.h"
#include "main/dll/CAM/camshipbattle.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern uint FUN_80014e9c();
extern undefined4 FUN_80021b8c();
extern undefined4 FUN_800238c4();
extern undefined4 FUN_80106ae8();
extern undefined4 FUN_80286834();
extern undefined4 FUN_80286880();
extern int FUN_80296a14();
extern int FUN_80296e60();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4* DAT_803dd6d0;
extern undefined4 DAT_803de1b0;
extern f64 DOUBLE_803e23d0;

/* Local declarations keep imported functions visible within the TU. */
void FUN_80107020(undefined8 param_1,double param_2,double param_3,double param_4,double param_5,
                 double param_6,undefined4 param_7,undefined4 param_8,int *param_9);
void FUN_80107214(int param_1,int param_2);
void FUN_8010736c(void);

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80107020
 * EN v1.0 Size: 500b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: unsupported body pseudo-types. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_80107020(undefined8 param_1,double param_2,double param_3,double param_4,double param_5,
                 double param_6,undefined4 param_7,undefined4 param_8,int *param_9)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80107214
 * EN v1.0 Size: 344b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

/* Auto-stubbed for compileability: function-pointer stores need manual cleanup. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_80107214(int param_1,int param_2)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8010736C
 * EN v1.0 Size: 44b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */

// Function: FUN_8010736c
// Entry: 8010736c
// Size: 44 bytes

void FUN_8010736c(void)

{
  FUN_800238c4(DAT_803de1b0);
  DAT_803de1b0 = 0;
  return;
}
