/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/CAM/firstperson.c
 * Text span: 0x8010525C-0x80105A4C
 * Imported Ghidra functions: 3
 * Verbatim-safe functions: 1
 * Auto-stubbed functions: 2
 */

#include "ghidra_import.h"
#include "main/dll/CAM/firstperson.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_8000e054();
extern double FUN_80021434();
extern uint FUN_80021884();
extern undefined4 FUN_801039a4();
extern double FUN_80247f54();
extern double FUN_80293900();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4* DAT_803dd6d0;
extern undefined4* DAT_803de1a8;
extern f64 DOUBLE_803e2318;
extern f64 DOUBLE_803e2378;
extern f32 FLOAT_803dc074;
extern f32 FLOAT_803e2314;
extern f32 FLOAT_803e2324;
extern f32 FLOAT_803e232c;
extern f32 FLOAT_803e2380;
extern f32 FLOAT_803e2384;
extern f32 FLOAT_803e2388;
extern f32 FLOAT_803e238c;
extern f32 FLOAT_803e2390;
extern f32 FLOAT_803e2394;

/* Local declarations keep imported functions visible within the TU. */
void FUN_8010525c(int param_1);
void FUN_80105338(int param_1,short *param_2);
void FUN_801057ac(int param_1);

// Function: FUN_8010525c
// Entry: 8010525c
// Size: 220 bytes

void FUN_8010525c(int param_1)

{
  uint uVar1;
  double dVar2;
  
  uVar1 = FUN_80021884();
  uVar1 = (uVar1 & 0xffff) - (uint)*(ushort *)(param_1 + 2);
  if (0x8000 < (int)uVar1) {
    uVar1 = uVar1 - 0xffff;
  }
  if ((int)uVar1 < -0x8000) {
    uVar1 = uVar1 + 0xffff;
  }
  dVar2 = FUN_80021434((double)(float)((double)CONCAT44(0x43300000,uVar1 ^ 0x80000000) -
                                      DOUBLE_803e2318),
                       (double)(FLOAT_803e2324 /
                               (float)((double)CONCAT44(0x43300000,
                                                        (uint)*(byte *)(DAT_803de1a8 + 0xc2)) -
                                      DOUBLE_803e2378)),(double)FLOAT_803dc074);
  *(short *)(param_1 + 2) = *(short *)(param_1 + 2) + (short)(int)dVar2;
  return;
}

/* Auto-stubbed for compileability: function-pointer stores need manual cleanup. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_80105338(int param_1,short *param_2)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: function-pointer stores need manual cleanup. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801057ac(int param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}
