/*
 * Auto-generated by tools/ghidra_unmanaged_homes.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists so every raw Ghidra function mapped to an unmanaged live owner
 * still has a concrete .c home for iteration/reference work.
 *
 * Live owner: dolphin/gx/GXAttr.c
 * Text span: 0x80256F84-0x8025898C
 * Imported Ghidra functions: 17
 * Verbatim-safe functions: 5
 * Auto-stubbed functions: 12
 */
/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: dolphin/gx/GXAttr.c
 * Text span: 0x80256F84-0x8025898C
 * Imported Ghidra functions: 17
 * Verbatim-safe functions: 5
 * Auto-stubbed functions: 12
 */

#include "ghidra_import.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_8025dbf4();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4 DAT_803dd210;
extern undefined4 DAT_803dd218;
extern undefined4 DAT_803dd21c;
extern undefined4 DAT_803dd220;
extern undefined4 DAT_cc008000;

/* Local declarations keep imported functions visible within the TU. */
void FUN_80256f84();
void FUN_802570dc(undefined4 param_1,uint param_2);
void FUN_8025743c(int *param_1);
void FUN_802577c0();
void FUN_80257814();
void FUN_80257938();
void FUN_80257aec(int param_1);
void FUN_80257b5c(void);
void FUN_80257ba8();
void FUN_80257f04();
void FUN_80258280();
void FUN_8025831c(int param_1,undefined4 param_2,uint *param_3,uint *param_4,byte *param_5);
void FUN_80258564();
void FUN_802585d8();
void FUN_80258664();
void FUN_80258674();
void FUN_80258944();

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80256F84
 * EN v1.0 Size: 344b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80256f84()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x802570DC
 * EN v1.0 Size: 864b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_802570dc(undefined4 param_1,uint param_2)
{
  switch(param_1) {
  case 0:
    *(uint *)(DAT_803dd210 + 0x14) = *(uint *)(DAT_803dd210 + 0x14) & 0xfffffffe | param_2;
    break;
  case 1:
    *(uint *)(DAT_803dd210 + 0x14) = *(uint *)(DAT_803dd210 + 0x14) & 0xfffffffd | param_2 << 1;
    break;
  case 2:
    *(uint *)(DAT_803dd210 + 0x14) = *(uint *)(DAT_803dd210 + 0x14) & 0xfffffffb | param_2 << 2;
    break;
  case 3:
    *(uint *)(DAT_803dd210 + 0x14) = *(uint *)(DAT_803dd210 + 0x14) & 0xfffffff7 | param_2 << 3;
    break;
  case 4:
    *(uint *)(DAT_803dd210 + 0x14) = *(uint *)(DAT_803dd210 + 0x14) & 0xffffffef | param_2 << 4;
    break;
  case 5:
    *(uint *)(DAT_803dd210 + 0x14) = *(uint *)(DAT_803dd210 + 0x14) & 0xffffffdf | param_2 << 5;
    break;
  case 6:
    *(uint *)(DAT_803dd210 + 0x14) = *(uint *)(DAT_803dd210 + 0x14) & 0xffffffbf | param_2 << 6;
    break;
  case 7:
    *(uint *)(DAT_803dd210 + 0x14) = *(uint *)(DAT_803dd210 + 0x14) & 0xffffff7f | param_2 << 7;
    break;
  case 8:
    *(uint *)(DAT_803dd210 + 0x14) = *(uint *)(DAT_803dd210 + 0x14) & 0xfffffeff | param_2 << 8;
    break;
  case 9:
    *(uint *)(DAT_803dd210 + 0x14) = *(uint *)(DAT_803dd210 + 0x14) & 0xfffff9ff | param_2 << 9;
    break;
  case 10:
    if (param_2 == 0) {
      *(undefined *)(DAT_803dd210 + 0x41c) = 0;
    }
    else {
      *(undefined *)(DAT_803dd210 + 0x41c) = 1;
      *(undefined *)(DAT_803dd210 + 0x41d) = 0;
      *(uint *)(DAT_803dd210 + 0x418) = param_2;
    }
    break;
  case 0xb:
    *(uint *)(DAT_803dd210 + 0x14) = *(uint *)(DAT_803dd210 + 0x14) & 0xffff9fff | param_2 << 0xd;
    break;
  case 0xc:
    *(uint *)(DAT_803dd210 + 0x14) = *(uint *)(DAT_803dd210 + 0x14) & 0xfffe7fff | param_2 << 0xf;
    break;
  case 0xd:
    *(uint *)(DAT_803dd210 + 0x18) = *(uint *)(DAT_803dd210 + 0x18) & 0xfffffffc | param_2;
    break;
  case 0xe:
    *(uint *)(DAT_803dd210 + 0x18) = *(uint *)(DAT_803dd210 + 0x18) & 0xfffffff3 | param_2 << 2;
    break;
  case 0xf:
    *(uint *)(DAT_803dd210 + 0x18) = *(uint *)(DAT_803dd210 + 0x18) & 0xffffffcf | param_2 << 4;
    break;
  case 0x10:
    *(uint *)(DAT_803dd210 + 0x18) = *(uint *)(DAT_803dd210 + 0x18) & 0xffffff3f | param_2 << 6;
    break;
  case 0x11:
    *(uint *)(DAT_803dd210 + 0x18) = *(uint *)(DAT_803dd210 + 0x18) & 0xfffffcff | param_2 << 8;
    break;
  case 0x12:
    *(uint *)(DAT_803dd210 + 0x18) = *(uint *)(DAT_803dd210 + 0x18) & 0xfffff3ff | param_2 << 10;
    break;
  case 0x13:
    *(uint *)(DAT_803dd210 + 0x18) = *(uint *)(DAT_803dd210 + 0x18) & 0xffffcfff | param_2 << 0xc;
    break;
  case 0x14:
    *(uint *)(DAT_803dd210 + 0x18) = *(uint *)(DAT_803dd210 + 0x18) & 0xffff3fff | param_2 << 0xe;
    break;
  case 0x19:
    if (param_2 == 0) {
      *(undefined *)(DAT_803dd210 + 0x41d) = 0;
    }
    else {
      *(undefined *)(DAT_803dd210 + 0x41d) = 1;
      *(undefined *)(DAT_803dd210 + 0x41c) = 0;
      *(uint *)(DAT_803dd210 + 0x418) = param_2;
    }
  }
  if ((*(char *)(DAT_803dd210 + 0x41c) == '\0') && (*(char *)(DAT_803dd210 + 0x41d) == '\0')) {
    *(uint *)(DAT_803dd210 + 0x14) = *(uint *)(DAT_803dd210 + 0x14) & 0xffffe7ff;
  }
  else {
    *(uint *)(DAT_803dd210 + 0x14) =
         *(uint *)(DAT_803dd210 + 0x14) & 0xffffe7ff | *(int *)(DAT_803dd210 + 0x418) << 0xb;
  }
  *(uint *)(DAT_803dd210 + 0x4f4) = *(uint *)(DAT_803dd210 + 0x4f4) | 8;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8025743C
 * EN v1.0 Size: 900b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8025743c(int *param_1)
{
  uint uVar1;
  
  for (; *param_1 != 0xff; param_1 = param_1 + 2) {
    uVar1 = param_1[1];
    switch(*param_1) {
    case 0:
      *(uint *)(DAT_803dd210 + 0x14) = *(uint *)(DAT_803dd210 + 0x14) & 0xfffffffe | uVar1;
      break;
    case 1:
      *(uint *)(DAT_803dd210 + 0x14) = *(uint *)(DAT_803dd210 + 0x14) & 0xfffffffd | uVar1 << 1;
      break;
    case 2:
      *(uint *)(DAT_803dd210 + 0x14) = *(uint *)(DAT_803dd210 + 0x14) & 0xfffffffb | uVar1 << 2;
      break;
    case 3:
      *(uint *)(DAT_803dd210 + 0x14) = *(uint *)(DAT_803dd210 + 0x14) & 0xfffffff7 | uVar1 << 3;
      break;
    case 4:
      *(uint *)(DAT_803dd210 + 0x14) = *(uint *)(DAT_803dd210 + 0x14) & 0xffffffef | uVar1 << 4;
      break;
    case 5:
      *(uint *)(DAT_803dd210 + 0x14) = *(uint *)(DAT_803dd210 + 0x14) & 0xffffffdf | uVar1 << 5;
      break;
    case 6:
      *(uint *)(DAT_803dd210 + 0x14) = *(uint *)(DAT_803dd210 + 0x14) & 0xffffffbf | uVar1 << 6;
      break;
    case 7:
      *(uint *)(DAT_803dd210 + 0x14) = *(uint *)(DAT_803dd210 + 0x14) & 0xffffff7f | uVar1 << 7;
      break;
    case 8:
      *(uint *)(DAT_803dd210 + 0x14) = *(uint *)(DAT_803dd210 + 0x14) & 0xfffffeff | uVar1 << 8;
      break;
    case 9:
      *(uint *)(DAT_803dd210 + 0x14) = *(uint *)(DAT_803dd210 + 0x14) & 0xfffff9ff | uVar1 << 9;
      break;
    case 10:
      if (uVar1 == 0) {
        *(undefined *)(DAT_803dd210 + 0x41c) = 0;
      }
      else {
        *(undefined *)(DAT_803dd210 + 0x41c) = 1;
        *(undefined *)(DAT_803dd210 + 0x41d) = 0;
        *(uint *)(DAT_803dd210 + 0x418) = uVar1;
      }
      break;
    case 0xb:
      *(uint *)(DAT_803dd210 + 0x14) = *(uint *)(DAT_803dd210 + 0x14) & 0xffff9fff | uVar1 << 0xd;
      break;
    case 0xc:
      *(uint *)(DAT_803dd210 + 0x14) = *(uint *)(DAT_803dd210 + 0x14) & 0xfffe7fff | uVar1 << 0xf;
      break;
    case 0xd:
      *(uint *)(DAT_803dd210 + 0x18) = *(uint *)(DAT_803dd210 + 0x18) & 0xfffffffc | uVar1;
      break;
    case 0xe:
      *(uint *)(DAT_803dd210 + 0x18) = *(uint *)(DAT_803dd210 + 0x18) & 0xfffffff3 | uVar1 << 2;
      break;
    case 0xf:
      *(uint *)(DAT_803dd210 + 0x18) = *(uint *)(DAT_803dd210 + 0x18) & 0xffffffcf | uVar1 << 4;
      break;
    case 0x10:
      *(uint *)(DAT_803dd210 + 0x18) = *(uint *)(DAT_803dd210 + 0x18) & 0xffffff3f | uVar1 << 6;
      break;
    case 0x11:
      *(uint *)(DAT_803dd210 + 0x18) = *(uint *)(DAT_803dd210 + 0x18) & 0xfffffcff | uVar1 << 8;
      break;
    case 0x12:
      *(uint *)(DAT_803dd210 + 0x18) = *(uint *)(DAT_803dd210 + 0x18) & 0xfffff3ff | uVar1 << 10;
      break;
    case 0x13:
      *(uint *)(DAT_803dd210 + 0x18) = *(uint *)(DAT_803dd210 + 0x18) & 0xffffcfff | uVar1 << 0xc;
      break;
    case 0x14:
      *(uint *)(DAT_803dd210 + 0x18) = *(uint *)(DAT_803dd210 + 0x18) & 0xffff3fff | uVar1 << 0xe;
      break;
    case 0x19:
      if (uVar1 == 0) {
        *(undefined *)(DAT_803dd210 + 0x41d) = 0;
      }
      else {
        *(undefined *)(DAT_803dd210 + 0x41d) = 1;
        *(undefined *)(DAT_803dd210 + 0x41c) = 0;
        *(uint *)(DAT_803dd210 + 0x418) = uVar1;
      }
    }
  }
  if ((*(char *)(DAT_803dd210 + 0x41c) == '\0') && (*(char *)(DAT_803dd210 + 0x41d) == '\0')) {
    *(uint *)(DAT_803dd210 + 0x14) = *(uint *)(DAT_803dd210 + 0x14) & 0xffffe7ff;
  }
  else {
    *(uint *)(DAT_803dd210 + 0x14) =
         *(uint *)(DAT_803dd210 + 0x14) & 0xffffe7ff | *(int *)(DAT_803dd210 + 0x418) << 0xb;
  }
  *(uint *)(DAT_803dd210 + 0x4f4) = *(uint *)(DAT_803dd210 + 0x4f4) | 8;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x802577C0
 * EN v1.0 Size: 84b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_802577c0()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80257814
 * EN v1.0 Size: 292b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80257814()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80257938
 * EN v1.0 Size: 436b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80257938()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80257AEC
 * EN v1.0 Size: 112b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80257aec(int param_1)
{
  int iVar1;
  int iVar2;
  
  iVar2 = 0;
  iVar1 = 0;
  do {
    *(int *)(param_1 + iVar2) = iVar1;
    FUN_80257938(iVar1,(uint *)((int *)(param_1 + iVar2) + 1));
    iVar1 = iVar1 + 1;
    iVar2 = iVar2 + 8;
  } while (iVar1 < 0x1a);
  *(undefined4 *)(param_1 + iVar1 * 8) = 0xff;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80257B5C
 * EN v1.0 Size: 76b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80257b5c(void)
{
  *(undefined4 *)(DAT_803dd210 + 0x14) = 0;
  *(uint *)(DAT_803dd210 + 0x14) = *(uint *)(DAT_803dd210 + 0x14) & 0xfffff9ff | 0x200;
  *(undefined4 *)(DAT_803dd210 + 0x18) = 0;
  *(undefined *)(DAT_803dd210 + 0x41c) = 0;
  *(undefined *)(DAT_803dd210 + 0x41d) = 0;
  *(uint *)(DAT_803dd210 + 0x4f4) = *(uint *)(DAT_803dd210 + 0x4f4) | 8;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80257BA8
 * EN v1.0 Size: 860b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80257ba8()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80257F04
 * EN v1.0 Size: 892b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80257f04()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80258280
 * EN v1.0 Size: 156b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80258280()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8025831C
 * EN v1.0 Size: 584b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8025831c(int param_1,undefined4 param_2,uint *param_3,uint *param_4,byte *param_5)
{
  uint *puVar1;
  int iVar2;
  uint *puVar3;
  uint *puVar4;
  
  iVar2 = DAT_803dd210 + param_1 * 4;
  puVar1 = (uint *)(iVar2 + 0x1c);
  puVar3 = (uint *)(iVar2 + 0x3c);
  puVar4 = (uint *)(iVar2 + 0x5c);
  switch(param_2) {
  case 9:
    *param_3 = *puVar1 & 1;
    *param_4 = *puVar1 >> 1 & 7;
    *param_5 = (byte)(*puVar1 >> 4) & 0x1f;
    return;
  case 10:
  case 0x19:
    break;
  case 0xb:
    *param_3 = *puVar1 >> 0xd & 1;
    *param_4 = *puVar1 >> 0xe & 7;
    *param_5 = 0;
    return;
  case 0xc:
    *param_3 = *puVar1 >> 0x11 & 1;
    *param_4 = *puVar1 >> 0x12 & 7;
    *param_5 = 0;
    return;
  case 0xd:
    *param_3 = *puVar1 >> 0x15 & 1;
    *param_4 = *puVar1 >> 0x16 & 7;
    *param_5 = (byte)(*puVar1 >> 0x19) & 0x1f;
    return;
  case 0xe:
    *param_3 = *puVar3 & 1;
    *param_4 = *puVar3 >> 1 & 7;
    *param_5 = (byte)(*puVar3 >> 4) & 0x1f;
    return;
  case 0xf:
    *param_3 = *puVar3 >> 9 & 1;
    *param_4 = *puVar3 >> 10 & 7;
    *param_5 = (byte)(*puVar3 >> 0xd) & 0x1f;
    return;
  case 0x10:
    *param_3 = *puVar3 >> 0x12 & 1;
    *param_4 = *puVar3 >> 0x13 & 7;
    *param_5 = (byte)(*puVar3 >> 0x16) & 0x1f;
    return;
  case 0x11:
    *param_3 = *puVar3 >> 0x1b & 1;
    *param_4 = *puVar3 >> 0x1c & 7;
    *param_5 = (byte)*puVar4 & 0x1f;
    return;
  case 0x12:
    *param_3 = *puVar4 >> 5 & 1;
    *param_4 = *puVar4 >> 6 & 7;
    *param_5 = (byte)(*puVar4 >> 9) & 0x1f;
    return;
  case 0x13:
    *param_3 = *puVar4 >> 0xe & 1;
    *param_4 = *puVar4 >> 0xf & 7;
    *param_5 = (byte)(*puVar4 >> 0x12) & 0x1f;
    return;
  case 0x14:
    *param_3 = *puVar4 >> 0x17 & 1;
    *param_4 = *puVar4 >> 0x18 & 7;
    *param_5 = (byte)(*puVar4 >> 0x1b);
    return;
  default:
    *param_3 = 1;
    *param_4 = 0;
    *param_5 = 0;
    return;
  }
  *param_3 = *puVar1 >> 9 & 1;
  if ((*param_3 == 1) && ((int)*puVar1 < 0)) {
    *param_3 = 2;
  }
  *param_4 = *puVar1 >> 10 & 7;
  *param_5 = 0;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80258564
 * EN v1.0 Size: 116b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80258564()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x802585D8
 * EN v1.0 Size: 140b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_802585d8()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80258664
 * EN v1.0 Size: 16b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80258664()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80258674
 * EN v1.0 Size: 720b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80258674()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80258944
 * EN v1.0 Size: 72b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80258944()
{
}
