/*
 * Auto-generated by tools/ghidra_unmanaged_homes.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists so every raw Ghidra function mapped to an unmanaged live owner
 * still has a concrete .c home for iteration/reference work.
 *
 * Live owner: dolphin/gx/GXMisc.c
 * Text span: 0x8025898C-0x80258F60
 * Imported Ghidra functions: 18
 * Verbatim-safe functions: 14
 * Auto-stubbed functions: 4
 */
/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: dolphin/gx/GXMisc.c
 * Text span: 0x8025898C-0x80258F60
 * Imported Ghidra functions: 18
 * Verbatim-safe functions: 14
 * Auto-stubbed functions: 4
 */

#include "ghidra_import.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_80240a74();
extern uint FUN_80240a8c();
extern undefined4 FUN_80240a98();
extern ulonglong FUN_80243e74();
extern undefined4 FUN_80243e9c();
extern undefined4 FUN_80243ec0();
extern undefined4 FUN_802442c4();
extern undefined4 FUN_802464dc();
extern undefined8 FUN_802473b4();
extern undefined4 FUN_80256e78();
extern undefined4 FUN_80258f60();
extern uint countLeadingZeros();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4* DAT_803dd210;
extern undefined4 DAT_803ded28;
extern undefined4* DAT_803ded30;
extern undefined4 DAT_803ded64;
extern undefined4 DAT_cc008000;

/* Local declarations keep imported functions visible within the TU. */
void FUN_8025898c(int param_1,int param_2);
void FUN_80258a04(undefined4 param_1,undefined4 param_2,uint param_3);
void FUN_80258a60(void);
void FUN_80258a94(void);
void FUN_80258b60();
undefined2 FUN_80258c18(void);
void FUN_80258c24();
void FUN_80258c48();
void FUN_80258c6c(int param_1,ushort param_2);
void FUN_80258c80(ushort param_1);
void FUN_80258c94(int param_1);
void FUN_80258cb0(int param_1,int param_2,int param_3,int param_4);
void FUN_80258d38(int param_1);
void FUN_80258d54(int param_1,ushort param_2);
void FUN_80258d68(int param_1);
void FUN_80258d84(ushort param_1,int param_2,int param_3);
void FUN_80258dac(uint param_1,uint param_2,undefined4 *param_3);
void FUN_80258ee0();

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8025898C
 * EN v1.0 Size: 120b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8025898c(int param_1,int param_2)
{
  uint uVar1;
  
  if (param_1 == 1) {
    DAT_803dd210[2] = (short)param_2;
    uVar1 = countLeadingZeros((uint)(ushort)DAT_803dd210[2]);
    *DAT_803dd210 = (short)(uVar1 >> 5);
    DAT_803dd210[1] = 1;
    if (DAT_803dd210[2] == 0) {
      return;
    }
    *(uint *)(DAT_803dd210 + 0x27a) = *(uint *)(DAT_803dd210 + 0x27a) | 8;
    return;
  }
  if (param_1 < 1) {
    return;
  }
  if (2 < param_1) {
    return;
  }
  *(char *)((int)DAT_803dd210 + 0x4f1) = '\x01' - (param_2 == 0);
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80258A04
 * EN v1.0 Size: 92b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80258a04(undefined4 param_1,undefined4 param_2,uint param_3)
{
  if (*(int *)(DAT_803dd210 + 0x4f4) != 0) {
    FUN_80258f60(DAT_803dd210,param_2,param_3);
  }
  DAT_cc008000 = 0;
  DAT_cc008000 = 0;
  DAT_cc008000 = 0;
  DAT_cc008000 = 0;
  DAT_cc008000 = 0;
  DAT_cc008000 = 0;
  DAT_cc008000 = 0;
  DAT_cc008000 = 0;
  FUN_80240a74();
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80258A60
 * EN v1.0 Size: 52b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80258a60(void)
{
  uint uVar1;
  
  do {
    uVar1 = FUN_80240a8c();
  } while ((uVar1 & 1) != 0);
  FUN_80240a98();
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80258A94
 * EN v1.0 Size: 204b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80258a94(void)
{
  undefined8 uVar1;
  undefined8 uVar2;
  
  *(undefined4 *)(DAT_803ded28 + 0x18) = 1;
  uVar1 = FUN_802473b4();
  do {
    uVar2 = FUN_802473b4();
  } while ((uint)(0x32 < (uint)uVar2 - (uint)uVar1) +
           ((int)((ulonglong)uVar2 >> 0x20) -
            ((uint)((uint)uVar2 < (uint)uVar1) + (int)((ulonglong)uVar1 >> 0x20)) ^ 0x80000000) <
           0x80000001);
  *(undefined4 *)(DAT_803ded28 + 0x18) = 0;
  uVar1 = FUN_802473b4();
  do {
    uVar2 = FUN_802473b4();
  } while ((uint)(5 < (uint)uVar2 - (uint)uVar1) +
           ((int)((ulonglong)uVar2 >> 0x20) -
            ((uint)((uint)uVar2 < (uint)uVar1) + (int)((ulonglong)uVar1 >> 0x20)) ^ 0x80000000) <
           0x80000001);
  FUN_80256e78();
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80258B60
 * EN v1.0 Size: 184b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80258b60()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80258C18
 * EN v1.0 Size: 12b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
undefined2 FUN_80258c18(void)
{
  return *(undefined2 *)(DAT_803ded30 + 0xe);
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80258C24
 * EN v1.0 Size: 36b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80258c24()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80258C48
 * EN v1.0 Size: 36b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80258c48()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80258C6C
 * EN v1.0 Size: 20b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80258c6c(int param_1,ushort param_2)
{
  *(ushort *)(DAT_803ded30 + 6) = (ushort)(param_1 << 8) | param_2 & 0xff;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80258C80
 * EN v1.0 Size: 20b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80258c80(ushort param_1)
{
  *(ushort *)(DAT_803ded30 + 8) = param_1 & 0xfffb | 4;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80258C94
 * EN v1.0 Size: 28b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80258c94(int param_1)
{
  *(ushort *)(DAT_803ded30 + 2) =
       *(ushort *)(DAT_803ded30 + 2) & 0xffef | (ushort)(param_1 << 4) & 0xff0;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80258CB0
 * EN v1.0 Size: 136b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80258cb0(int param_1,int param_2,int param_3,int param_4)
{
  uint uVar1;
  int iVar2;
  ushort uVar3;
  
  uVar3 = 1;
  if ((param_1 != 1) && (param_1 != 3)) {
    uVar3 = 0;
  }
  iVar2 = countLeadingZeros(3 - param_1);
  uVar1 = countLeadingZeros(2 - param_1);
  *(ushort *)(DAT_803ded30 + 2) =
       (*(ushort *)(DAT_803ded30 + 2) & 0xf7fc | uVar3 | (ushort)(iVar2 << 6) & 0xf800 |
       (ushort)(uVar1 >> 4) & 0xfffe) & 0x81f | (ushort)(param_4 << 0xc) | (ushort)(param_2 << 8) |
       (ushort)(param_3 << 5);
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80258D38
 * EN v1.0 Size: 28b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80258d38(int param_1)
{
  *(ushort *)(DAT_803ded30 + 2) =
       *(ushort *)(DAT_803ded30 + 2) & 0xfff7 | (ushort)(param_1 << 3) & 0x7f8;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80258D54
 * EN v1.0 Size: 20b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80258d54(int param_1,ushort param_2)
{
  *(ushort *)(DAT_803ded30 + 4) = param_2 & 0xff | (ushort)(param_1 << 8);
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80258D68
 * EN v1.0 Size: 28b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80258d68(int param_1)
{
  *(ushort *)(DAT_803ded30 + 2) =
       *(ushort *)(DAT_803ded30 + 2) & 0xfffb | (ushort)(param_1 << 2) & 0x3fc;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80258D84
 * EN v1.0 Size: 40b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80258d84(ushort param_1,int param_2,int param_3)
{
  *DAT_803ded30 =
       (param_1 & 0xf1 | (ushort)(param_2 << 1)) & 0xffef | (ushort)(param_3 << 4) & 0xff0;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80258DAC
 * EN v1.0 Size: 308b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80258dac(uint param_1,uint param_2,undefined4 *param_3)
{
  *param_3 = *(undefined4 *)
              ((param_1 & 0x3ff) << 2 | 0xc8000000 | (param_2 & 0xf3ff) << 0xc | 0x400000);
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80258EE0
 * EN v1.0 Size: 128b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80258ee0()
{
}
