/*
 * Auto-generated by tools/ghidra_unmanaged_homes.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists so every raw Ghidra function mapped to an unmanaged live owner
 * still has a concrete .c home for iteration/reference work.
 *
 * Live owner: dolphin/gx/GXTransform.c
 * Text span: 0x8025D6AC-0x8025DC78
 * Imported Ghidra functions: 15
 * Verbatim-safe functions: 2
 * Auto-stubbed functions: 13
 */
/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: dolphin/gx/GXTransform.c
 * Text span: 0x8025D6AC-0x8025DC78
 * Imported Ghidra functions: 15
 * Verbatim-safe functions: 2
 * Auto-stubbed functions: 13
 */

#include "ghidra_import.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_8025d49c();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4 DAT_803dd210;
extern undefined4 DAT_cc008000;
extern f32 FLOAT_803e83e8;
extern f32 FLOAT_803e83ec;
extern f32 FLOAT_803e83f0;

/* Local declarations keep imported functions visible within the TU. */
void FUN_8025d6ac();
void FUN_8025d780();
void FUN_8025d7b4();
void FUN_8025d7e8();
void FUN_8025d80c();
void FUN_8025d848();
void FUN_8025d888(uint param_1);
void FUN_8025d8c4();
void FUN_8025d948();
void FUN_8025da64(double param_1,double param_2,double param_3,double param_4,double param_5,
                 double param_6);
void FUN_8025da88();
void FUN_8025db38();
void FUN_8025db88();
void FUN_8025dbcc();
void FUN_8025dbf4();

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8025D6AC
 * EN v1.0 Size: 212b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8025d6ac()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8025D780
 * EN v1.0 Size: 52b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8025d780()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8025D7B4
 * EN v1.0 Size: 52b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8025d7b4()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8025D7E8
 * EN v1.0 Size: 36b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8025d7e8()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8025D80C
 * EN v1.0 Size: 60b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8025d80c()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8025D848
 * EN v1.0 Size: 64b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8025d848()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8025D888
 * EN v1.0 Size: 60b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8025d888(uint param_1)
{
  *(uint *)(DAT_803dd210 + 0x80) = *(uint *)(DAT_803dd210 + 0x80) & 0xffffffc0 | param_1;
  FUN_8025dbf4(0);
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8025D8C4
 * EN v1.0 Size: 132b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8025d8c4()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8025D948
 * EN v1.0 Size: 284b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8025d948()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8025DA64
 * EN v1.0 Size: 36b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8025da64(double param_1,double param_2,double param_3,double param_4,double param_5,
                 double param_6)
{
  FUN_8025d948(param_1,param_2,param_3,param_4,param_5,param_6,1);
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8025DA88
 * EN v1.0 Size: 176b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8025da88()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8025DB38
 * EN v1.0 Size: 80b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8025db38()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8025DB88
 * EN v1.0 Size: 68b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8025db88()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8025DBCC
 * EN v1.0 Size: 40b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8025dbcc()
{
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x8025DBF4
 * EN v1.0 Size: 132b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_8025dbf4()
{
}
