/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 */

#ifndef DOLPHIN_MSL_C_PPCEABI_BARE_H_ABORT_EXIT_H_
#define DOLPHIN_MSL_C_PPCEABI_BARE_H_ABORT_EXIT_H_

#include "ghidra_import.h"

undefined4 FUN_8028db4c();
void FUN_8028dc08();

#endif /* DOLPHIN_MSL_C_PPCEABI_BARE_H_ABORT_EXIT_H_ */
