/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 */

#ifndef DOLPHIN_MSL_C_PPCEABI_BARE_H_E_SQRT_H_
#define DOLPHIN_MSL_C_PPCEABI_BARE_H_E_SQRT_H_

#include "ghidra_import.h"

void FUN_80292f04(void);

#endif /* DOLPHIN_MSL_C_PPCEABI_BARE_H_E_SQRT_H_ */
