/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 */

#ifndef DOLPHIN_MSL_C_PPCEABI_BARE_H_FILE_POS_H_
#define DOLPHIN_MSL_C_PPCEABI_BARE_H_FILE_POS_H_

#include "ghidra_import.h"

void FUN_8028f578(undefined4 *param_1,uint param_2,int param_3);
undefined4 FUN_8028f598();
int FUN_8028f7d4(int param_1);

#endif /* DOLPHIN_MSL_C_PPCEABI_BARE_H_FILE_POS_H_ */
