#!/usr/bin/env python3
"""Audit materialized recovery stubs against live split ownership."""

from __future__ import annotations

import argparse
import re
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path


RECOVERY_MARKERS = (
    "Manual recovery stub",
    "Auto-generated by tools/orig/source_materialize.py.",
)

SPLIT_HEADER_RE = re.compile(r"^([^:\s][^:]*\.(?:c|cpp|s)):$", re.MULTILINE)
INLINE_RETAIL_RE = re.compile(r"Retail source name:\s*([^\s*]+)")
LIST_RETAIL_RE = re.compile(r"^\s*\*\s*-\s*([^\s*]+\.c)\s*$", re.MULTILINE)


@dataclass(frozen=True)
class StubEntry:
    path: str
    key: str
    claimed: bool
    category: str
    clues: tuple[str, ...]


def classify_category(path: str) -> str:
    return "sdk" if path.startswith(("dolphin/", "Runtime.PPCEABI.H/")) else "game"


def parse_claimed_paths(splits_path: Path) -> set[str]:
    text = splits_path.read_text(encoding="utf-8")
    return set(SPLIT_HEADER_RE.findall(text))


def is_recovery_stub(text: str) -> bool:
    return any(marker in text for marker in RECOVERY_MARKERS)


def extract_stub_key(text: str, fallback_name: str) -> str:
    inline = INLINE_RETAIL_RE.search(text)
    if inline:
        return inline.group(1)
    lines = text.splitlines()
    for idx, line in enumerate(lines):
        if "Retail source name:" not in line:
            continue
        for follow in lines[idx + 1 : idx + 4]:
            match = LIST_RETAIL_RE.match(follow)
            if match:
                return match.group(1)
    return fallback_name


def extract_clues(text: str) -> tuple[str, ...]:
    keywords = (
        "source gap packet:",
        "dark game gap:",
        "projected debug-side order:",
        "projected current EN window:",
        "debug-side path:",
        "debug-side text:",
        "indirect neighborhood",
        "best current evidence",
    )
    clues: list[str] = []
    for raw_line in text.splitlines():
        line = raw_line.strip().lstrip("*").strip()
        if not line or line.startswith("/"):
            continue
        if not any(keyword in line for keyword in keywords):
            continue
        clues.append(line)
        if len(clues) == 4:
            break
    return tuple(clues)


def collect_stubs(src_root: Path, claimed_paths: set[str], category_filter: str | None) -> list[StubEntry]:
    stubs: list[StubEntry] = []
    for path in sorted(src_root.rglob("*.c")):
        rel = path.relative_to(src_root).as_posix()
        text = path.read_text(encoding="utf-8", errors="ignore")
        if not is_recovery_stub(text[:600]):
            continue
        category = classify_category(rel)
        if category_filter and category != category_filter:
            continue
        stubs.append(
            StubEntry(
                path=rel,
                key=extract_stub_key(text[:1200], path.name),
                claimed=rel in claimed_paths,
                category=category,
                clues=extract_clues(text[:1600]),
            )
        )
    return stubs


def print_entries(title: str, entries: list[StubEntry]) -> None:
    if title:
        print(title)
    if not entries:
        print("- none")
        return
    for entry in entries:
        state = "claimed" if entry.claimed else "unclaimed"
        print(f"- `{entry.path}` key=`{entry.key}` category=`{entry.category}` state=`{state}`")
        for clue in entry.clues:
            print(f"  clue: `{clue}`")


def main() -> None:
    parser = argparse.ArgumentParser(description="Audit recovery stubs against split ownership.")
    parser.add_argument(
        "--splits",
        type=Path,
        default=Path("config/GSAE01/splits.txt"),
        help="Split file to compare against.",
    )
    parser.add_argument(
        "--src-root",
        type=Path,
        default=Path("src"),
        help="Source root to scan.",
    )
    parser.add_argument(
        "--category",
        choices=("game", "sdk"),
        help="Only show recovery stubs in one category.",
    )
    parser.add_argument(
        "--unclaimed-only",
        action="store_true",
        help="Only print recovery stubs that do not have a claimed split path.",
    )
    parser.add_argument(
        "--duplicates-only",
        action="store_true",
        help="Only print duplicate recovery keys.",
    )
    args = parser.parse_args()

    claimed_paths = parse_claimed_paths(args.splits)
    stubs = collect_stubs(args.src_root, claimed_paths, args.category)

    duplicate_groups: dict[str, list[StubEntry]] = defaultdict(list)
    for entry in stubs:
        duplicate_groups[entry.key].append(entry)
    duplicates = {
        key: sorted(entries, key=lambda item: item.path)
        for key, entries in duplicate_groups.items()
        if len(entries) > 1
    }

    unclaimed = [entry for entry in stubs if not entry.claimed]

    print("# Recovery stub audit")
    print(f"- splits: `{args.splits.as_posix()}`")
    print(f"- src root: `{args.src_root.as_posix()}`")
    if args.category:
        print(f"- category: `{args.category}`")
    print(f"- recovery stubs: `{len(stubs)}`")
    print(f"- claimed stubs: `{sum(1 for entry in stubs if entry.claimed)}`")
    print(f"- unclaimed stubs: `{len(unclaimed)}`")
    print(f"- duplicate keys: `{len(duplicates)}`")

    if args.duplicates_only:
        print("\n## Duplicate Keys")
        if not duplicates:
            print("- none")
            return
        for key, entries in duplicates.items():
            print(f"- `{key}`")
            for entry in entries:
                state = "claimed" if entry.claimed else "unclaimed"
                print(f"  - `{entry.path}` category=`{entry.category}` state=`{state}`")
        return

    if args.unclaimed_only:
        print("\n## Unclaimed Stubs")
        print_entries("", unclaimed)
        return

    print("\n## Unclaimed Stubs")
    print_entries("", unclaimed)
    print("\n## Duplicate Keys")
    if not duplicates:
        print("- none")
        return
    for key, entries in duplicates.items():
        print(f"- `{key}`")
        for entry in entries:
            state = "claimed" if entry.claimed else "unclaimed"
            print(f"  - `{entry.path}` category=`{entry.category}` state=`{state}`")


if __name__ == "__main__":
    main()
