/*
 * Auto-generated by tools/ghidra_unmanaged_homes.py.
 *
 * This file is intentionally not wired into the build yet.
 * It exists so every raw Ghidra function mapped to an unmanaged live owner
 * still has a concrete .c home for iteration/reference work.
 *
 * Live owner: dolphin/mtx/mtx44.c
 * Text span: 0x80247D2C-0x80247E94
 * Imported Ghidra functions: 2
 * Verbatim-safe functions: 1
 * Auto-stubbed functions: 1
 */
/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: dolphin/mtx/mtx44.c
 * Text span: 0x80247D2C-0x80247E94
 * Imported Ghidra functions: 2
 * Verbatim-safe functions: 1
 * Auto-stubbed functions: 1
 */

#include "ghidra_import.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern double FUN_80294f2c();

/* Raw global references kept as loose externs for later cleanup. */
extern f32 FLOAT_803e82c8;
extern f32 FLOAT_803e82cc;
extern f32 FLOAT_803e82d0;
extern f32 FLOAT_803e82d4;
extern f32 FLOAT_803e82d8;
extern f32 FLOAT_803e82dc;

/* Local declarations keep imported functions visible within the TU. */
void FUN_80247d2c(double param_1,double param_2,double param_3,double param_4,float *param_5);
void FUN_80247dfc();

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80247D2C
 * EN v1.0 Size: 208b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80247d2c(double param_1,double param_2,double param_3,double param_4,float *param_5)
{
  float fVar1;
  float fVar2;
  double dVar3;
  double dVar4;
  
  dVar3 = FUN_80294f2c((double)(FLOAT_803e82dc * (float)((double)FLOAT_803e82d8 * param_1)));
  dVar4 = (double)FLOAT_803e82c8;
  fVar1 = (float)(dVar4 / dVar3);
  *param_5 = (float)((double)fVar1 / param_2);
  fVar2 = FLOAT_803e82d0;
  dVar3 = (double)(float)(dVar4 / (double)(float)(param_4 - param_3));
  param_5[1] = FLOAT_803e82d0;
  param_5[2] = fVar2;
  param_5[3] = fVar2;
  param_5[4] = fVar2;
  param_5[5] = fVar1;
  param_5[6] = fVar2;
  param_5[7] = fVar2;
  param_5[8] = fVar2;
  param_5[9] = fVar2;
  param_5[10] = (float)(-param_3 * dVar3);
  param_5[0xb] = (float)(dVar3 * -(double)(float)(param_4 * param_3));
  param_5[0xc] = fVar2;
  param_5[0xd] = fVar2;
  param_5[0xe] = FLOAT_803e82d4;
  param_5[0xf] = fVar2;
  return;
}

/*
 * --INFO--
 *
 * EN v1.0 Address: 0x80247DFC
 * EN v1.0 Size: 152b
 * EN v1.1 Address: TODO
 * EN v1.1 Size: TODO
 * JP Address: TODO
 * JP Size: TODO
 * PAL Address: TODO
 * PAL Size: TODO
 */
void FUN_80247dfc()
{
}
