/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/CF/CFcrystal.c
 * Text span: 0x80186BA4-0x80187608
 * Imported Ghidra functions: 7
 * Verbatim-safe functions: 0
 * Auto-stubbed functions: 7
 */

#include "ghidra_import.h"
#include "main/dll/CF/CFcrystal.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_8000da78();
extern double FUN_80010f00();
extern undefined4 FUN_8001dbb4();
extern undefined4 FUN_8001dbd8();
extern undefined4 FUN_8001dbf0();
extern undefined4 FUN_8001dcfc();
extern undefined4 FUN_8001de04();
extern undefined4 FUN_8001f448();
extern int* FUN_8001f58c();
extern undefined4 FUN_8001ffac();
extern undefined4 FUN_80020000();
extern uint FUN_80020078();
extern undefined4 FUN_800217c8();
extern undefined4 FUN_80021b8c();
extern uint FUN_80022264();
extern int FUN_8002bac4();
extern undefined4 FUN_8002cc9c();
extern undefined4 FUN_8003709c();
extern undefined4 FUN_8003b9ec();
extern undefined4 FUN_80063000();
extern double FUN_80293900();
extern undefined4 FUN_802945e0();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4 DAT_803dc070;
extern undefined4* DAT_803dd6f8;
extern undefined4* DAT_803dd708;
extern undefined4 DAT_803de758;
extern f64 DOUBLE_803e4748;
extern f32 FLOAT_803dc074;
extern f32 FLOAT_803dca40;
extern f32 FLOAT_803e4724;
extern f32 FLOAT_803e4728;
extern f32 FLOAT_803e4730;
extern f32 FLOAT_803e4734;
extern f32 FLOAT_803e4738;
extern f32 FLOAT_803e473c;
extern f32 FLOAT_803e4740;
extern f32 FLOAT_803e4750;
extern f32 FLOAT_803e4754;
extern f32 FLOAT_803e4758;
extern f32 FLOAT_803e475c;
extern f32 FLOAT_803e4760;
extern f32 FLOAT_803e476c;

/* Local declarations keep imported functions visible within the TU. */
void FUN_80186ba4(undefined2 *param_1,int param_2);
void FUN_80186c70(short *param_1);
void FUN_80186e28(int param_1);
void FUN_80186f34(int param_1);
void FUN_80187044(int param_1,int param_2);
void FUN_801870ec(int param_1);
void FUN_80187120(uint param_1);

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_80186ba4(undefined2 *param_1,int param_2)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_80186c70(short *param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_80186e28(int param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_80186f34(int param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_80187044(int param_1,int param_2)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_801870ec(int param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

/* Auto-stubbed for compileability: forced full-owner stub for compile-first import. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_80187120(uint param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}
