/*
 * Auto-generated by tools/ghidra_bulk_import.py.
 *
 * Owner: main/dll/CF/CFcrystal.c
 * Text span: 0x80186BA4-0x80187608
 * Imported Ghidra functions: 7
 * Verbatim-safe functions: 5
 * Auto-stubbed functions: 2
 */

#include "ghidra_import.h"
#include "main/dll/CF/CFcrystal.h"

/* Cross-file calls lifted from the raw Ghidra output. */
extern undefined4 FUN_8000da78();
extern double FUN_80010f00();
extern undefined4 FUN_8001dbb4();
extern undefined4 FUN_8001dbd8();
extern undefined4 FUN_8001dbf0();
extern undefined4 FUN_8001dcfc();
extern undefined4 FUN_8001de04();
extern undefined4 FUN_8001f448();
extern int* FUN_8001f58c();
extern undefined4 FUN_8001ffac();
extern undefined4 FUN_80020000();
extern uint FUN_80020078();
extern undefined4 FUN_800217c8();
extern undefined4 FUN_80021b8c();
extern uint FUN_80022264();
extern int FUN_8002bac4();
extern undefined4 FUN_8002cc9c();
extern undefined4 FUN_8003709c();
extern undefined4 FUN_8003b9ec();
extern undefined4 FUN_80063000();
extern double FUN_80293900();
extern undefined4 FUN_802945e0();

/* Raw global references kept as loose externs for later cleanup. */
extern undefined4 DAT_803dc070;
extern undefined4* DAT_803dd6f8;
extern undefined4* DAT_803dd708;
extern undefined4 DAT_803de758;
extern f64 DOUBLE_803e4748;
extern f32 FLOAT_803dc074;
extern f32 FLOAT_803dca40;
extern f32 FLOAT_803e4724;
extern f32 FLOAT_803e4728;
extern f32 FLOAT_803e4730;
extern f32 FLOAT_803e4734;
extern f32 FLOAT_803e4738;
extern f32 FLOAT_803e473c;
extern f32 FLOAT_803e4740;
extern f32 FLOAT_803e4750;
extern f32 FLOAT_803e4754;
extern f32 FLOAT_803e4758;
extern f32 FLOAT_803e475c;
extern f32 FLOAT_803e4760;
extern f32 FLOAT_803e476c;

/* Local declarations keep imported functions visible within the TU. */
void FUN_80186ba4(undefined2 *param_1,int param_2);
void FUN_80186c70(short *param_1);
void FUN_80186e28(int param_1);
void FUN_80186f34(int param_1);
void FUN_80187044(int param_1,int param_2);
void FUN_801870ec(int param_1);
void FUN_80187120(uint param_1);

// Function: FUN_80186ba4
// Entry: 80186ba4
// Size: 176 bytes

void FUN_80186ba4(undefined2 *param_1,int param_2)

{
  uint uVar1;
  int iVar2;
  
  iVar2 = *(int *)(param_1 + 0x5c);
  *param_1 = (short)((int)*(char *)(param_2 + 0x18) << 8);
  param_1[1] = (short)((int)*(short *)(param_2 + 0x1c) << 8);
  *(float *)(param_1 + 4) = FLOAT_803e4724;
  *(float *)(iVar2 + 4) = *(float *)(param_1 + 0x54) * *(float *)(param_1 + 4) * FLOAT_803e4728;
  uVar1 = FUN_80020078((int)*(short *)(param_2 + 0x1e));
  if (uVar1 != 0) {
    param_1[3] = param_1[3] | 0x4000;
    param_1[0x58] = param_1[0x58] | 0xe000;
  }
  *(undefined4 *)(iVar2 + 8) = 0xffffffff;
  return;
}

// Function: FUN_80186c70
// Entry: 80186c70
// Size: 352 bytes

void FUN_80186c70(short *param_1)

{
  float fVar1;
  float fVar2;
  float fVar3;
  float fVar4;
  int iVar5;
  int iVar6;
  int iVar7;
  
  iVar7 = *(int *)(param_1 + 0x5c);
  iVar6 = *(int *)(param_1 + 0x26);
  *(short *)(iVar7 + 0x68) = (short)*(char *)(iVar6 + 0x18);
  *(undefined *)(iVar7 + 0x6a) = *(undefined *)(iVar6 + 0x19);
  *(float *)(iVar7 + 0x4c) = FLOAT_803e4738;
  *(float *)(iVar7 + 0x50) =
       (float)((double)CONCAT44(0x43300000,(int)*(short *)(iVar6 + 0x1c) ^ 0x80000000) -
              DOUBLE_803e4748);
  *(undefined *)(iVar7 + 0x6f) = 0;
  FUN_80063000(param_1,(short *)0x0,1);
  iVar5 = FUN_8002bac4();
  fVar1 = *(float *)(iVar5 + 0x18);
  fVar2 = *(float *)(iVar5 + 0x20);
  fVar3 = *(float *)(iVar5 + 0x1c) + FLOAT_803e473c;
  fVar4 = FLOAT_803e4740 + *(float *)(iVar5 + 0x1c);
  iVar5 = *(int *)(param_1 + 0x5c);
  *(float *)(iVar5 + 0x54) = fVar1;
  *(float *)(iVar5 + 0x58) = fVar4;
  *(float *)(iVar5 + 0x5c) = fVar2;
  iVar5 = *(int *)(param_1 + 0x5c);
  *(float *)(iVar5 + 0x34) = fVar1 - *(float *)(iVar5 + 0x54);
  *(float *)(iVar5 + 0x38) = fVar3 - *(float *)(iVar5 + 0x58);
  *(float *)(iVar5 + 0x3c) = fVar2 - *(float *)(iVar5 + 0x5c);
  *(undefined *)(iVar5 + 0x6c) = 4;
  FUN_80186f34((int)param_1);
  FUN_80186f34((int)param_1);
  FUN_80186f34((int)param_1);
  FUN_80186f34((int)param_1);
  FUN_80186f34((int)param_1);
  FUN_80186f34((int)param_1);
  *(byte *)(iVar7 + 0x70) = *(byte *)(iVar7 + 0x70) & 0x3f | 0x40;
  *(int *)(iVar7 + 0x60) = (int)*(short *)(iVar6 + 0x1a);
  FUN_80020000(0x698);
  return;
}

// Function: FUN_80186e28
// Entry: 80186e28
// Size: 268 bytes

void FUN_80186e28(int param_1)

{
  int iVar1;
  uint uVar2;
  int iVar3;
  ushort local_38 [4];
  float local_30;
  float local_2c;
  float local_28;
  float local_24;
  undefined8 local_20;
  undefined4 local_18;
  uint uStack_14;
  
  iVar3 = *(int *)(param_1 + 0xb8);
  *(float *)(iVar3 + 0x34) = FLOAT_803e4750;
  uVar2 = FUN_80022264(-(int)*(short *)(iVar3 + 0x68),(int)*(short *)(iVar3 + 0x68));
  local_20 = (double)CONCAT44(0x43300000,uVar2 ^ 0x80000000);
  *(float *)(iVar3 + 0x38) = (float)(local_20 - DOUBLE_803e4748);
  if (FLOAT_803e4754 <= *(float *)(iVar3 + 0x50)) {
    iVar1 = (int)*(float *)(iVar3 + 0x50);
    local_20 = (double)(longlong)iVar1;
    uStack_14 = FUN_80022264(0x14,(int)(short)iVar1);
    uStack_14 = uStack_14 ^ 0x80000000;
    local_18 = 0x43300000;
    *(float *)(iVar3 + 0x3c) =
         *(float *)(iVar3 + 0x50) -
         (float)((double)CONCAT44(0x43300000,uStack_14) - DOUBLE_803e4748);
  }
  else {
    *(float *)(iVar3 + 0x3c) = FLOAT_803e4750;
  }
  uVar2 = FUN_80022264(3000,5000);
  *(short *)(iVar3 + 100) = *(short *)(iVar3 + 100) + (short)uVar2;
  local_2c = FLOAT_803e4750;
  local_28 = FLOAT_803e4750;
  local_24 = FLOAT_803e4750;
  local_30 = FLOAT_803e4738;
  local_38[2] = 0;
  local_38[1] = 0;
  local_38[0] = *(ushort *)(iVar3 + 100);
  FUN_80021b8c(local_38,(float *)(iVar3 + 0x34));
  return;
}

// Function: FUN_80186f34
// Entry: 80186f34
// Size: 256 bytes

void FUN_80186f34(int param_1)

{
  int iVar1;
  uint uVar2;
  int iVar3;
  double dVar4;
  
  iVar3 = *(int *)(param_1 + 0xb8);
  *(undefined4 *)(iVar3 + 4) = *(undefined4 *)(iVar3 + 8);
  *(undefined4 *)(iVar3 + 0x14) = *(undefined4 *)(iVar3 + 0x18);
  *(undefined4 *)(iVar3 + 0x24) = *(undefined4 *)(iVar3 + 0x28);
  *(undefined4 *)(iVar3 + 8) = *(undefined4 *)(iVar3 + 0xc);
  *(undefined4 *)(iVar3 + 0x18) = *(undefined4 *)(iVar3 + 0x1c);
  *(undefined4 *)(iVar3 + 0x28) = *(undefined4 *)(iVar3 + 0x2c);
  *(undefined4 *)(iVar3 + 0xc) = *(undefined4 *)(iVar3 + 0x10);
  *(undefined4 *)(iVar3 + 0x1c) = *(undefined4 *)(iVar3 + 0x20);
  *(undefined4 *)(iVar3 + 0x2c) = *(undefined4 *)(iVar3 + 0x30);
  if (*(byte *)(iVar3 + 0x70) >> 6 == 1) {
    iVar1 = FUN_8002bac4();
    dVar4 = (double)FUN_800217c8((float *)(param_1 + 0x18),(float *)(iVar1 + 0x18));
    *(float *)(iVar3 + 0x44) = (float)((double)FLOAT_803e475c * dVar4 + (double)FLOAT_803e4758);
  }
  else {
    uVar2 = FUN_80022264(0x3c,0x5a);
    *(float *)(iVar3 + 0x44) =
         FLOAT_803e475c * (float)((double)CONCAT44(0x43300000,uVar2 ^ 0x80000000) - DOUBLE_803e4748)
    ;
  }
  *(undefined4 *)(iVar3 + 0x10) = *(undefined4 *)(iVar3 + 0x34);
  *(undefined4 *)(iVar3 + 0x20) = *(undefined4 *)(iVar3 + 0x38);
  *(undefined4 *)(iVar3 + 0x30) = *(undefined4 *)(iVar3 + 0x3c);
  return;
}

/* Auto-stubbed for compileability: function-pointer stores need manual cleanup. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_80187044(int param_1,int param_2)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}

// Function: FUN_801870ec
// Entry: 801870ec
// Size: 48 bytes

void FUN_801870ec(int param_1)

{
  char in_r8;
  
  if (in_r8 != '\0') {
    FUN_8003b9ec(param_1);
  }
  return;
}

/* Auto-stubbed for compileability: function-pointer stores need manual cleanup. */
/* Original raw Ghidra body omitted for compile-first stubbing. */

void FUN_80187120(uint param_1)
{
    /* TODO: replace this stub with a cleaned-up Ghidra body. */
}
